### ISSUE TITLE
OSGB files and paths are hardcoded

### ISSUE THREAD

**Issue by matthewcoyle-cpc** [esmini/esmini#10]
Current behaviour:
"../models" is a hardcoded directory for containing osgb files
carModelsFiles_ has a hardcoded list of files which must be present even if the target scenario doesn't require them [EDIT Must be present only if external control is enabled]

Expected behaviour:
osgb files should be referenced from open scenario files and loaded from the specified relative directory

**Comment by eknabevcc** [comment]
Totally agree, thanks for pointing out. We have now removed dependency to hardcoded model files from the viewer class. (Though a few applications still make use of hardcoded vehicles). 

It should be fixed in commit [1b150a2](https://github.com/esmini/esmini/commit/1b150a2eb2a0993bd41007dac76ff22123aa722b) and [latest release](https://github.com/esmini/esmini/releases/latest).

Please check it out and see if it works as expected.

**Comment by matthewcoyle-cpc** [comment]
Hi Emil,
it seems that line 345 of viewer.cpp:
`filePath.append("/../models/" + modelFilepath);`
still requires that files be located under a 'models' directory, was this an oversight or intentional?
Also you said that the model paths are relative the OpenDRIVE file, while this isn't a big problem for us, I wonder why they're not relative to the OpenScenario file since that's the file which contains the models references?

**Comment by eknabevcc** [comment]
Thanks for feedback. 
That remaining hardcoded filepath was for an optional special-purpose semi-transparent polygon (shadow_face.osgb) used for fake shadow under vehicles. It's a generic shape that's being scaled to whatever vehicle bounding box. However, we now changed so it will look in the same location as the scenegraph/environment model.

One of the applications, OpenDriveViewer, is used with OpenDRIVE only. So, OpenDRIVE being the single common asset was a reason to use it as pivot for relative paths. But I agree that it makes more sense to use the OpenSCENARIO location. So we changed the strategy to use OpenSCENARIO in first place, and OpenDRIVE location as fallback - in case the scenario is missing.

So all in all, we tried to get rid of hard coded relative pahts. But we still have some relative dependencies: 1. Relative model paths relates to the OpenSCENARIO file location. 2. Optional shadow file is assumed to be located in the same folder as the environment model (applications will work without).

Maybe we should make use of an environment variable or registry entry for resolving relative paths, but so far we wanted to avoid that - keeping it as "portable" as possible. 

Please check out lastest code or [release](https://github.com/esmini/esmini/releases/latest), hopefully it works better now.

**Comment by matthewcoyle-cpc** [comment]
Looking a lot better!
Still two small issues:
- odr references in osc files are treated as relative to the console's working directory unless the path starts with '.', this seems un-intuitive, I think the odr references should be treated as relative to the osc file by default, similarly to the osgb files
- when executing from the same directory as the xosc files, the following behaviour is observed `Scenario file directory, , is used as pivot for model relative file paths` and because of this line `std::string absFilepath = getScenarioDir().append("/" + modelFilepath);` if the scenarioDir is an empty string, filepaths start with a slash. Perhaps the scenarioDir should be defaulted to '.' if it's empty?

**Comment by eknabevcc** [comment]
This was a tougher challenge than expected :)

We've made some more adjustements to support flexible directory structures. Also created a centralized function for concatenating directory and file paths; CommonMini.cpp: CombineDirectoryPathAndFilepath() - that way it will hopefully make further fixes easier.

I dare not generating a new release, but please check out latest code ([60817d2](https://github.com/esmini/esmini/commit/60817d2f18c808716f08bce354550729d799c26b)) and try on your directory structure!

**Comment by matthewcoyle-cpc** [comment]
Filepaths are always a pain! I've done some testing and it seems to be working perfectly, I'm satisfied that this is now resolved
Thanks a lot for the effort and quick response on this one

**Comment by eknabevcc** [comment]
That's excellent news! Thanks for testing and providing feedback. I will close this issue. We can re-open if needed.
