### ISSUE TITLE
Get the states of detected objects

### ISSUE THREAD

**Issue by ZhangZongshi-Catarc** [esmini/esmini#101]
Hi,

Could you please provide me some advice about the 'IdealSensor'?
After i add some sensors on the object vehicle, how can i get the state of the detected objects? Such as speed, X,Y,Z values in the vehicle local coordinates and so on? Can you provide me an simple example?
Till this moment, i can only get the No. of detected object according to 'SE_FetchSensorObjectList'.

### IdealSensor

Best Regard
Zongshi

**Comment by sterres** [comment]
Hi,

the method 'SE_FetchSensorObjectList(int sensor_id, int *list)' reports a list of IDs for detected objects.

The state of each object can be fetched like described in this example:
https://github.com/esmini/esmini/tree/master/Hello-World_coding-example#fetch-state-of-scenario-objects

Of course, now you just loop over the ID list.

Hope that helps

Best regards
Simon

**Comment by eknabevcc** [comment]
Thanks Simon for answer! :)
I actually thought in the same direction. And also added an explicit code-example.
See here:
https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/code-examples/ideal-sensors/ideal-sensors.cpp

**Comment by eknabevcc** [comment]
Question answered, examples provided. Closing issue.
