### ISSUE TITLE
Is it possible to change the view of esmini player

### ISSUE THREAD

**Issue by S1201149** [esmini/esmini#104]
Hello,
Is it possible to change the view of esmini player. 
I have created a scenario file using python script(with the help of scenario geneerator). 
While executing the scenario with esmini the scenario view is based on ego rear camera. 
Is it possible to change the view of the player to front of the ego vehicle or bird eye view of the road network?
Is there any help document available for esmini?

**Comment by eknabevcc** [comment]
Short answer: 

- 'TAB' to jump to next vehicle, shift-TAB to previous
- 'k' switches between some modes
- '4' to disconnect camera. You can then zoom out (right mouse drag) and pan (middle mouse drag) and rotate (left mouse drag). Go back to esmini mode (where you can switch sub modes on 'k') on '1'.

Long answer:

There are a few options provided, some you can specify with launch arguments and some only while running esmini.

Arguments setting camera mode:
>   --camera_mode <mode>
>       Initial camera mode ("orbit" (default), "fixed", "flex", "flex-orbit", "top")

Some key shortcuts affecting camera:

>   k: Switch between the following sub models:
>            - Orbit        (camera facing vehicle, rotating around it)
>            - Fixed        (fix rotation, always straight behind vehicle)
>            - Flex         (imagine the camera attached to vehicle via an elastic string)
>            - Flex - orbit (Like flex but allows for roatation around vehicle)
>            - Top          (top view, fixed rotation, always straight above vehicle)
>     TAB:         Move camera to next vehicle

Mouse control:

>     Left:   Rotate
>     Right:  Zoom
>     Middle: Pan

There are also other models, e.g. '4' terrain mode which will disconnect camera from vehicle and you can move the camera independently. You can switch back to esmini default camera model with button '1'.


Full lists here:
Launch arguments: https://github.com/esmini/esmini/blob/master/docs/commands.txt
Runtime key shortcut commands: https://github.com/esmini/esmini/blob/master/docs/readme.txt

**Comment by S1201149** [comment]
Hello @eknabe ,
Thanks for the answer!
Still have few questions. 
1) I have tried to use trajectory catalog in my code. While executing I got warning saying Trajectory catalog is not supported and my script fails executing. Will there be a update for this.
2)As of now esmini supports OpenScenario v1.0, recently a new version of it has released (v1.1). Will esmini tool and Scenariogenerator(python package) be updated to support v1.1

**Comment by eknabevcc** [comment]
esmini DO support v1.1 already, since v2.7.0. Sorry, that was unclear. I have now updated the [readme](https://github.com/esmini/esmini/blob/master/README.md). Thanks for reminding me :)
But be aware that coverage is limited. See details [here](https://github.com/esmini/esmini/blob/master/osc_coverage.txt).

scenariogeneration tool will be updated as well, but there is no time plan. (a secret is that the v1.1 attribute initialDistanceOffset of FollowTrajectoryAction is already supported). 

Regarding Trajectory catalogs. It is supported since 2.7.0. So, please update your esmini to [latest version](https://github.com/esmini/esmini/releases/latest) and try again. Don't hesitate to report back if it doesn't work after all. I'm interested in finding such issues.

**Comment by S1201149** [comment]
Hi,
Thanks for the support. The new ASAM trajectory example works fine with this esmini version.
one more request. 
While updating scenariogeneration is it possible to provide few more python examples with new functions.
As I am new to this it will be helpful if there are more python examples like the xosc examples provided under esmini examples folder. 
Still feels like there are many things to explore with esmini tool. If there is any detailed documentation available on this tool?

**Comment by eknabevcc** [comment]
Thanks for reporting result of your test! Good to hear that it works.

I think that any scenariogeneration examples should be included with that framework. The examples provided with esmini is pure OpenSCENARIO/OpenDRIVE. I'm sure there will be some more examples when 1.1 supported is released, but it's up to the main developers of scenariogeneration. I'm mostly a hang-around in that project :)

Regarding documentation of esmini. Unfortunately there's way to little documentation. Wish we could spend more time on that. What we have, so far, is basically:
- main [readme](https://github.com/esmini/esmini/blob/master/README.md) (which you obviously already found 👍)
- Coding tutorial [Hello-World_coding-example](https://github.com/esmini/esmini/tree/master/Hello-World_coding-example)
- Some technical info [Inner Workings of esmini](https://github.com/esmini/esmini/blob/master/docs/InnerWorkings.md)
- The example run scripts [under this folder](https://github.com/esmini/esmini/tree/master/run) - which shows quite some various use cases
- esmini [docs/commands.txt](https://github.com/esmini/esmini/blob/master/docs/commands.txt)readme.txt and [docs/readme.txt](https://github.com/esmini/esmini/blob/master/docs/readme.txt)
- [odrviewer/readme.txt](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Applications/odrviewer/readme.txt)
- [replayer/readme.txt](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Applications/replayer/readme.txt)

I hope you still can find it useful to experiment with and learn about OpenSCENARIO and OpenDRIVE.

**Comment by eknabevcc** [comment]
Initial issue resolved/explained. 
Links to available examples documentation provided. 
Closing issue for now.

**Comment by S1201149** [comment]
Hi,
Is it possible to get a view of the driver (i.e view from inside the car) in esmini player?

**Comment by eknabevcc** [comment]
Good suggestion, would be useful. I re-open the issue and we'll see what we can do.

**Comment by eknabevcc** [comment]
Driver view added in commit bc536e7f67a6f8c700140393817389e3ade04fb6.
Can be activated either by toggle view on 'k' (press a few times to reach driver view) or specifying launch argument `--camera_mode driver`. See example script [run/esmini/run_lane_change_crest_driver-view.bat](https://github.com/esmini/esmini/blob/master/run/esmini/run_lane_change_crest_driver-view.bat).
Will be part of next release. 
Please try when possible and let us know if it works as expected.

![image](https://user-images.githubusercontent.com/29146839/118362575-40ae1280-b590-11eb-9c2b-1c24bf3a2433.png)

**Comment by S1201149** [comment]
Hi @eknabe,
Thanks for the update!!! 
The view is working fine as expected.

**Comment by eknabevcc** [comment]
Thanks for feedback, and thanks for a useful proposal. 👍
BTW, the 2.8.2 release unfortunately included a bug. Please switch to [2.8.3](https://github.com/esmini/esmini/releases/tag/v2.8.3) if possible.
I close the issue now.
