### ISSUE TITLE
Mouse wheel zoom direction inverted

### ISSUE THREAD

**Issue by johschmitz** [esmini/esmini#105]
I would like to report that the zoom direction when pressing 4 and then using the mouse wheel to zoom is inverted compared to most other software. Some examples among so many others: maps.google.com, www.bing.com/maps, Firefox, Chrome, GIMP, Blender

Would it be possible to invert the direction to make the tool more intuitive for the majority of users?

**Comment by eknabevcc** [comment]
Excellent suggestion! Thanks. I wasn't even aware of the scroll wheel zoom function. That one is part of OSG Viewer default behavior. 
But I like it. Luckily, it was possible to inverse the wheel scaling by function calls, not having to patch OSG code. 👍
And I also added same behavior to the esmini custom camera models.
These fixes part of commit [fb72d55](https://github.com/esmini/esmini/commit/fb72d55f34d2f7dad6bb2c39f463948868094ef3)
And [release 2.7.4](https://github.com/esmini/esmini/releases/tag/v2.7.4).
Please try and see if it works as expected.

**Comment by johschmitz** [comment]
@eknabevcc  I hope you fix this for odrviewer too?

**Comment by eknabevcc** [comment]
Yes of course, should be the same camera handling for all esmini apps. 👍
I keep the issue open until you get the chance to test and see if we got it right.

**Comment by johschmitz** [comment]
I tried the new release and it works much better than before! Very nice, closing the issue.

**Comment by eknabevcc** [comment]
Good to hear! Thanks for suggestion 👍
