### ISSUE TITLE
Respawn vehicles in odrviewer only at open lane ends

### ISSUE THREAD

**Issue by johschmitz** [esmini/esmini#106]
I would recommend to change the odrviewer tool in a way such that vehicles are only respawned at open road ends. Respawning at any arbitrary road in the middle of the map makes checking for incorrect connected roads very difficult to impossible.
For the initial spawn points the user should be able to select between "open ends" and something like "random normal distribution".

**Comment by eknabevcc** [comment]
The "re-spawn at open ends" is a very good suggestion. It makes it simpler to follow vehicles. It is now implemented in commit [3295c10](https://github.com/esmini/esmini/commit/3295c10590d649252d963bbba110330b7f9eb67b).

The traffic will still initially be spawned by random distribution over roads and lanes. I think this is the most useful case for this application. If you want a more specific analysis, e.g. for a specific road id or junction, then I recommend to use esmini with a "dummy" scenario where you just define the road network, initial position and speed. Something like this: 
[dummy_drive.xosc.txt](https://github.com/esmini/esmini/files/6392616/dummy_drive.xosc.txt).  

By the way, we updated the odrplot tool, now showing road starting points, direction and ID's. Potentially it can be helpful for road analysis... 

![image](https://user-images.githubusercontent.com/29146839/116423620-24e10780-a841-11eb-9b34-338f01bd4827.png)

**Comment by johschmitz** [comment]
Woaa, this is super useful! I am wondering if it would make sense to also
somehow annotate the lane IDs and the lane linking to see if something is
wrong on that level? You could draw a little circle at the beginning and
end of each lane and a connecting line between these circles. See the
Traffic Manager add-on of the game Cities: Skylines for some inspiration on
that.

**Comment by eknabevcc** [comment]
Good ideas. And yes, I know, there are endless of potential improvements for this app :) 

However I think we'll stop here for now, simply due to prioritizations. I also think that the approach of this tool (writing limited info from OpenDRIVE to a separate file for later plotting), will not scale in terms of functionality and features. For example, no connectivity info is currently exported. 

A better approach for detailed OpenDRIVE viewing would be to populate the data model in esmini RoadManager and from there visualize in a 2D view with nice GUI text and widget support. I mean, the RoadManager is aware of all logics and can report errors or shortcomings directly. It would be awesome to try implement such a tool (if only time for it existed).

So I'll close this issue for now, and we'll keep the good ideas in mind for potential future works.

**Comment by johschmitz** [comment]
Thanks for the improvement though. One last question before closing, do you
also annotate junction connecting road IDs? Building junctions is one of
the biggest issues with OpenDRIVE and it would help tremendously!

Emil Knabe ***@***.***> schrieb am Mi., 28. Apr. 2021, 18:24:

**Comment by eknabevcc** [comment]
Yes, connecting road IDs are also annotated. The ID is always placed midway along first lane section, and 2m under reference line (ID 0). But under might mean actually above, if it's heading is 180 degree, or to the right if heading is 90 deg. - you get it.

So for example, in the image below (from [multi_intersections.xodr](https://github.com/esmini/esmini/blob/master/resources/xodr/multi_intersections.xodr)) a best guess would be:

- 271 and 273 is on either side of the north-west connection
- 272 and 274 is on either side of the north-east connection
- 276 and 277 is on either side of the east-west connection

![image](https://user-images.githubusercontent.com/29146839/116457725-0a6c5580-a864-11eb-8be6-c960e75cbd2e.png)

**Comment by johschmitz** [comment]
This is cool. Without having tested it, it seems to me though that it would be easier and less confusing to read if the numbers would be very close to each reference line in positive t direction and close to the start of the road. I am having a really hard time distinguishing the three numbers in the middle.

In this example do you have a case of double junction connection roads? 6 instead of 3?

**Comment by eknabevcc** [comment]
I agree. However putting the number closer to starting point can result in overlap, like this:

![image](https://user-images.githubusercontent.com/29146839/116531439-74761080-a8df-11eb-966b-8011bd941358.png)

So I made a compromise solution (commit [22a5a13](https://github.com/esmini/esmini/commit/22a5a13192e2a0039eedbef515d81d67a8de54f4) and release [2.8.0](https://github.com/esmini/esmini/releases/tag/v2.8.0)) putting it at 1/3 of s-distance. And as you suggested at positive T, also closer at 0.7m.
Looks like this:
![image](https://user-images.githubusercontent.com/29146839/116531720-c3bc4100-a8df-11eb-95fc-17459a46ad2e.png)

I think it's at least a small improvement. It can easily be changed if we find better ideas later.
