### ISSUE TITLE
Problem with FollowTrajectoryAction

### ISSUE THREAD

**Issue by aktasalifurkan** [esmini/esmini#107]
I have a crossing pedestrian scenario and I wrote the action of the pedestrian as FollowTrajectoryAction starting from one offset value to another. However for some reason pedestrian always finishes the action with a ≈-0.5 offset. Is this issue regarding the scenario or Esmini. I also added the code below.

                    <FollowTrajectoryAction>
                      <Trajectory name="CrossTrajectory" closed="false">
                        <Shape>
                          <Polyline>
                            <Vertex time="0">
                              <Position>
                                <LanePosition roadId="$Initial_RoadId" s="$Initial_Spline" laneId="$Initial_Lane" offset="$Initial_Offset">
                                  <Orientation h="$Initial_Orientation_h" p="0.0" r="0.0" type="relative"/>
                                </LanePosition>
                              </Position>
                            </Vertex>
                            <Vertex time="$TTC">
                              <Position>
                                <LanePosition roadId="$Initial_RoadId" s="$Initial_Spline" laneId="$Initial_Lane" offset="$Final_Offset">
                                  <Orientation h="$Initial_Orientation_h" p="0.0" r="0.0" type="relative"/>
                                </LanePosition>
                              </Position>
                            </Vertex>
                          </Polyline>
                        </Shape>
                      </Trajectory>
                      <TimeReference>
                        <Timing domainAbsoluteRelative="relative" scale="1.0" offset="0.0" />
                      </TimeReference>
                      <TrajectoryFollowingMode followingMode="position" />
                    </FollowTrajectoryAction>

**Comment by eknabevcc** [comment]
Very good finding! You're totally right. The code had exactly 0.5m (s-value) tolerance for the action's end criteria ([here](https://github.com/esmini/esmini/blob/c0d5ea840316db6b285605777f5b1c34de5731d2/EnvironmentSimulator/Modules/ScenarioEngine/OSCTypeDefs/OSCPrivateAction.cpp#L154)). 
I don't even remember why. Anyway, it has now been removed, in commit [69ad5d0](https://github.com/esmini/esmini/commit/69ad5d055737408d5423da2b8bd11ef4cb02615c).
Will be part of next release.

Here is a test scenario that I used for my own testing. The pedestrian should now follow left edge perfectly (which was not the case previously): [dummy_traj.xosc.txt](https://github.com/esmini/esmini/files/6392533/dummy_traj.xosc.txt)

Please test your scenario again and let me know if it works better now. BTW, can you pull and build yourself or do you need to wait for a release?

**Comment by eknabevcc** [comment]
FYI: The fix is now part of [release v2.8.0](https://github.com/esmini/esmini/releases/tag/v2.8.0).

**Comment by eknabevcc** [comment]
Good to hear! Thank you for reporting 👍
