### ISSUE TITLE
Build broken [Ubu 6.04]

### ISSUE THREAD

**Issue by theoutsider24** [esmini/esmini#11]
Build error when building in an Ubuntu 16.04 docker container using the build on Linux instructions:
/urs/bin/ld: cannot find -lWs_32.lib

Seems to be caused by the CMakeLists.txt modifications in commit "Added UDP server for external simulator integration"
Possibly the change required an update to the build documentation?

**Comment by eknabevcc** [comment]
Thanks for pointing out! The problem was trying to link with a Windows network library on Linux. It should hopefully be fixed now.

**Comment by eknabevcc** [comment]
I close this for now. On wishlist is to find out how to apply anti-alias in a Linux docker container...
