### ISSUE TITLE
Will esmini support Signals in the near future?

### ISSUE THREAD

**Issue by zn845639326** [esmini/esmini#112]
In the [osc_coverage.txt](https://github.com/esmini/esmini/blob/v2.8.1/osc_coverage.txt#L38) of v2.8.1, the `Signals` is not supported.
```
 RoadNetwork                                  
    Logics                                   Yes
    SceneGraph                               Yes
    Signals                                  No
```

The traffic lights are  very important at junctions. Will esmini support `Signals` in the near  future?

**Comment by eknabevcc** [comment]
Actually it is being discussed and it's in the backlog. We also see the need coming ahead. However it should not be expected in near time. 
Current best guess is within two months. But please note that it's a guess - can be earlier or later.

**Comment by zn845639326** [comment]
> Actually it is being discussed and it's in the backlog. We also see the need coming ahead. However it should not be expected in near time.
> Current best guess is within two months. But please note that it's a guess - can be earlier or later.

It's tremendous work, and I am looking forward to the day. :smile:

**Comment by eknabevcc** [comment]
The dynamic signal support has been delayed. Basically we had a change in backlog prioritization. And unfortunately no target date set. Sorry for broken expectations. 
I'll keep issue open to log whenever support is released.

**Comment by eknabevcc** [comment]
Unfortunately signals has been pushed down again in the backlog. 

Instead of keeping story open until implemented I choose to close it with simple but sad conclusion that signals is not currently supported.

Whenever it's implemented and released It will be posted in release notes.

**Comment by zn845639326** [comment]
> Unfortunately signals has been pushed down again in the backlog.
> 
> Instead of keeping story open until implemented I choose to close it with simple but sad conclusion that signals is not currently supported.
> 
> Whenever it's implemented and released It will be posted in release notes.

OK!
