### ISSUE TITLE
Cannot compile the master version now

### ISSUE THREAD

**Issue by dalishi** [esmini/esmini#115]
Hi guys, I pull the master and encounter compilation problem. im on Ubuntu 16.04 with cmake-3.20.0. Need change all to std:;isnan? i found a bunch in the code without std.

/esmini/EnvironmentSimulator/Modules/ScenarioEngine/OSCTypeDefs/OSCPosition.cpp:19:14: error: ‘isnan’ was not declared in this scope
  if (!isnan(z) || !isnan(p) || !isnan(r))

**Comment by eknabevcc** [comment]
Thanks for reporting. I've added std:: to all locations I found and committed on branch [nan](https://github.com/esmini/esmini/tree/nan). Will check back in a while for [build and test results](https://ci.appveyor.com/project/esmini/esmini/builds/39182559). 

Meanwhile it would be great if you also could try to build this branch on your 16.04 system (I don't have access to such). 

Then, if all is green (from your side and appveyour) then I'll just merge into master.

**Comment by dalishi** [comment]
Hi @eknabevcc I have tested the branch [nan](https://github.com/esmini/esmini/tree/nan) on my Ubuntu 16.04. It works now. Successfully built. Thanks for the prompt response.

-- Ubuntu 16.04
-- CMake version: 3.20.0
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0

**Comment by eknabevcc** [comment]
Excellent. I've just merged to master. Closing the issue. Thanks again for reporting problem and testing solution. 👍
