### ISSUE TITLE
External Controller Help

### ISSUE THREAD

**Issue by aktasalifurkan** [esmini/esmini#118]
How can I implement a Simulink module for an external controller? It would be helpful if you give any instructions.

**Comment by eknabe** [comment]
There is ways to put shared libraries into Simulink, e.g. in terms of a S-function (wrapping the DLL/.so). Actually complete esminiLib can be integrated that way for Simulink use cases. However, there's no easy way to put a controller in a separate shared library. The controller concept in esmini simply is not that flexible, as of now.

That said, perhaps you can solve your use case without actually implementing a custom controller. One potential approach would be to use the ExternalController, which will prevent DefaultController to update the vehicle instead allowing for external app/system to update the vehicle state using the  `SE_ReportObject...` functions.

See Hello World tutorial examples how to get and set object states:
* [Fetch state of scenario objects](https://github.com/esmini/esmini/tree/master/Hello-World_coding-example#fetch-state-of-scenario-objects) 
* [External control of Ego](https://github.com/esmini/esmini/tree/master/Hello-World_coding-example#external-control-of-ego) 

Also there is a bit more complex example involving a simple [driver model](https://github.com/esmini/esmini/tree/master/Hello-World_coding-example#driver-model). This example also shows how to assign and activate a controller.

**Comment by aktasalifurkan** [comment]
Yes, thank you for your response, I will try to implement it in the way you described it. Continue good work :)

**Comment by eknabevcc** [comment]
Thanks :)
I hope it works out. I close this issue for now. Just open again or a new one if you run into related issues.
