### ISSUE TITLE
Catalog 'Directory' tags need to reference specific catalog files

### ISSUE THREAD

**Issue by matthewcoyle-cpc** [esmini/esmini#12]
As the name suggests, they should point to the directory containing the catalog files rather than a specific catalog file

**Comment by eknabevcc** [comment]
How to handle catalogs was a bit unclear at time of first implemented. But I now totally agree that directory should point to a folder containing the actual catalogs. Catalog handling has been updated accordingly. Please see [release_notes.txt](https://github.com/esmini/esmini/blob/master/release_notes.txt) and example scenario [synchronize.xosc](https://github.com/esmini/esmini/blob/master/resources/xosc/synchronize.xosc) for more info on updated naming and usage info.
