### ISSUE TITLE
Errors related <Waypoint> in the same lane

### ISSUE THREAD

**Issue by bleach31** [esmini/esmini#121]
Thank you for this very useful tool. 
I want to simulate the behavior of a vehicle wavering from side to side in same lane.
I am trying to realize it by using `Waypoint` for the following two reasons. 

* If using `Trajectory`, it is trouble to calculate trajectory according to the vehicle speed.
* If using `laneOffsetAction`,  A lot of action definition is needed. (left -> right -> left -> right ...)

And I created a `Waypoint` definition that offsets in the same lane as shown below.

```xml
<Route name="HostStraightRouteFor500m" closed="false">
    <Waypoint routeStrategy="shortest">
        <Position>
            <LanePosition roadId="0" laneId="1" offset="0" s="0"/>
        </Position>
    </Waypoint>
    <Waypoint routeStrategy="shortest">
        <Position>
            <LanePosition roadId="0" laneId="1" offset="1" s="5"/>
        </Position>
    </Waypoint>
    <Waypoint routeStrategy="shortest">
        <Position>
            <LanePosition roadId="0" laneId="1" offset="-1" s="10"/>
        </Position>
    </Waypoint>
</Route>
```

An error occurred.
```bash
Route::AddWaypoint Added waypoint 0: 1, -1, 0.00
Error: waypoint (1, -1) is not connected to the previous one (1, -1)

Error: waypoint (1, -1) is not connected to the previous one (1, -1)
```

Is `Waypoint` designed only for connecting different lane as OSC standard? 
Or, Esmini doesn't yet support `Waypoint`in the same lane?

(My env. is esmini v 2.8.4  windows10.)

**Comment by pyoscx** [comment]
Hi
Routes are usually made to create a path through a road network, like finding the correct way through a junction (so it will go the same way each time), so for your use case I don't think the Route is the correct way to go. 

If you use trajectory and polyline as the shape you technically don't have to specify the "time" attribute, hence the speed will not be the same throughout the trajectory (or can be set through separate SpeedActions). It will not be a nice continuous movement then at the points though. 

If you want a continuous form, you either have to go through the NURBS (tricky mathematically though), or as you said some LaneChangeAction/LaneOffsetActions (that will be a couple of them then).

**Comment by mander76** [comment]
Hi
Routes are usually used to make an object find it's way through a road-network not to define a path within a lane. 
So for your use case I would say that Route is not the best choice.

I would suggest as you said, Trajector (with polyline), and if you don't wanna mess with time, just don't set the time attribute, then the speed will be kept.  However this will cause discontinuities at each point (and the yaw will abruptly change). And if you want to change the speed you can just use SpeedActions whenever. 

If you want smooth changes you can either use Trajectory with Nurbs (more complicated mathematically), or as you said use a series of LaneChangeActions or LaneOffsetActions.

**Comment by bleach31** [comment]
thank you for the advice.

I understood that I'm using `Waypoint` incorrectly. thank you very much.

> If you use trajectory and polyline as the shape you technically don't have to specify the "time" attribute, 

as you said, the `time` attribute of `Vertex` is optional, so I tried like this:

```xml
<Trajectory closed="false" name="">
    <ParameterDeclarations/>
    <Shape>
        <Polyline>
            <Vertex >
                    <Position>
                    <RelativeLanePosition entityRef="Host" dLane="0" ds="0" offset="0"></RelativeLanePosition>
                    </Position>
            </Vertex>
            <Vertex >
                    <Position>
                    <RelativeLanePosition entityRef="Host" dLane="0" ds="5" offset="1.0"></RelativeLanePosition>
                    </Position>
            </Vertex>
            <Vertex >
                    <Position>
                    <RelativeLanePosition entityRef="Host" dLane="0" ds="10" offset="-1.0"></RelativeLanePosition>
                    </Position>
            </Vertex>
        </Polyline>
        </Shape>
</Trajectory>
```

But, The result is not the behavior I expected. It looks like only the last Position is enabled.

![image](https://user-images.githubusercontent.com/5919566/120642677-26d95e80-c4b0-11eb-89d3-618b77055376.png)

Regarding this problem, I think  Esmini doesn't yet support `Vertex` without `time`.

And also thanks for the advice about  smooth changing.
Indeed, this was also problem.

So, I will try 2 way:
1. `Nurbs` without `time` 　( At this moment, I think it will fail as above, but I will try.)
2.  a series of LaneOffsetActions

**Comment by eknabevcc** [comment]
Regarding Vertex and no time:
esmini should support PolyLine trajectory with and without time reference.

I can't tell from your code snippet, but you need to specify Time reference None in order to ignore vertex/control point timings (which by the way defaults to 0 if not specified). Like this:
```
<TimeReference>
    <None/>
</TimeReference>

```
Complete action would look something like:
```
<FollowTrajectoryAction>
    <Trajectory closed="false" name="">
        <ParameterDeclarations/>
        <Shape>
            <Polyline>
                <Vertex >
                    <Position>
                        <RelativeLanePosition entityRef="Ego" dLane="0" ds="0" offset="0"></RelativeLanePosition>
                    </Position>
                </Vertex>
                <Vertex >
                    <Position>
                        <RelativeLanePosition entityRef="Ego" dLane="0" ds="5" offset="1.0"></RelativeLanePosition>
                    </Position>
                </Vertex>
                <Vertex >
                    <Position>
                        <RelativeLanePosition entityRef="Ego" dLane="0" ds="10" offset="-1.0"></RelativeLanePosition>
                    </Position>
                </Vertex>
            </Polyline>
        </Shape>
    </Trajectory>
    <TimeReference>
        <None/>
    </TimeReference>
    <TrajectoryFollowingMode followingMode="position"/>
</FollowTrajectoryAction>

```
Please try this and report back if it works better. Otherwise we need to investigate further 👍

**Comment by bleach31** [comment]
Thank you very much! 

In this way , I have confirmed :
* The speed before the `FollowTrajectoryAction` is kept.
* `SpeedAction` can be work during `FollowTrajectoryAction`

It worked perfectly.
My understanding of OSC was not enough. Thank you very much.

finally, the XML looks like this:
```xml
<FollowTrajectoryAction>
    <Trajectory closed="false" name="">
    <ParameterDeclarations />
    <Shape>
        <Nurbs order="3">
            <ControlPoint  weight="1">
                <Position>
                <RelativeLanePosition dLane="0" ds="0" entityRef="Host" offset="0.0" />
                </Position>
            </ControlPoint>
            <ControlPoint  weight="1">
                <Position>
                <RelativeLanePosition dLane="0" ds="20" entityRef="Host" offset="0.0" />
                </Position>
            </ControlPoint>
            <ControlPoint  weight="1">
                <Position>
                <RelativeLanePosition dLane="0" ds="40" entityRef="Host" offset="-1.0" />
                </Position>
            </ControlPoint>
            <ControlPoint  weight="1">
                <Position>
                <RelativeLanePosition dLane="0" ds="60" entityRef="Host" offset="1.0" />
                </Position>
            </ControlPoint>
            <ControlPoint  weight="1">
                <Position>
                <RelativeLanePosition dLane="0" ds="80" entityRef="Host" offset="-1.0" />
                </Position>
            </ControlPoint>
            <ControlPoint  weight="1">
                <Position>
                <RelativeLanePosition dLane="0" ds="100" entityRef="Host" offset="0.0" />
                </Position>
            </ControlPoint>
            <ControlPoint  weight="1">
                <Position>
                <RelativeLanePosition dLane="0" ds="120" entityRef="Host" offset="0.0" />
                </Position>
            </ControlPoint>
            <Knot value="0.0" />
            <Knot value="0.0" />
            <Knot value="0.0" />
            <Knot value="0.333" />
            <Knot value="0.4444" />
            <Knot value="0.556" />
            <Knot value="0.667" />
            <Knot value="1.0" />
            <Knot value="1.0" />
            <Knot value="1.0" />
        </Nurbs>
    </Shape>
    </Trajectory>
    <TimeReference>
    <!-- <Timing domainAbsoluteRelative="relative" offset="0" scale="1" />-->
    <None />
    </TimeReference>
    <TrajectoryFollowingMode followingMode="position" />
</FollowTrajectoryAction>
```

![image](https://user-images.githubusercontent.com/5919566/120762578-5b512700-c551-11eb-879d-2f9e0f10777a.png)

**Comment by eknabevcc** [comment]
Excellent! Thanks for letting us know 👍
