### ISSUE TITLE
The files "osg、osi、sumo、googletest" can not be downloaded and extracted correctly. 

### ISSUE THREAD

**Issue by JinxBIGBIG** [esmini/esmini#122]
The terminal shows the downloading and extracting process,but there are no files under their corresponding directories when it finished.
_CMake version: 3.20.3
-- downloading osg.7z ...
-- extracting osg.7z ... 
-- downloading osi.7z ...
-- extracting osi.7z ... 
-- downloading sumo.7z ...
-- extracting sumo.7z ... 
-- downloading googletest.7z ...
-- extracting googletest.7z ... 
-- Configuring done
-- Generating done
_

**Comment by eknabevcc** [comment]
Not good. Let's investigate.
What platform (Win, Linux, Mac) are you on?
Make sure you run the following sequence from esmini root folder:
```
mkdir build
cd build
cmake ..
```
The there should appear files under esmini/externals/OSI, OSG...

Can you then please double check e.g. if you have
```esmini/externals/OSI/v10/lib/libprotobuf.lib``` (this should be the case in Windows, it's similar but different on Linux and Mac)
or not.

Then we think about next step.

**Comment by JinxBIGBIG** [comment]
Thanks.The problem has been solved .I checked the osi,osg,,files's source address in the "cmakelist" txt and find that i can not download the source file on linux. I downloaded the corresponding files by myself  and then it works well.

**Comment by eknabevcc** [comment]
It is strange that it didn't work for you. It should work on Linux and I see that your cmake is up to date.
But I guess you solved the issue for now. 
I close the issue for now. Please re-open if the issue persists and cause trouble again.
