### ISSUE TITLE
Esmini inside virtualbox

### ISSUE THREAD

**Issue by ebadi** [esmini/esmini#125]
In Windows 10 inside **virtualbox** (with & without 3D accelerator), esmini throws the following error messages.
I tried some of the commands that were suggested #64 (adding `--window 50 50 800 400  --screen Y --samples  X`) with no success. 

```
C:\Users\ABC\Downloads\esmini-demo_win\esmini-demo\bin> esmini --osc ..\resources\xosc\pedestrian.xosc
esmini GIT REV: 159852b
esmini GIT TAG: v2.9.0
esmini GIT BRANCH: tags/v2.9.0^0
esmini BUILD VERSION: 2.9.0.build.1491
Loading pedestrian.xosc (v1.1)
OpenDRIVE: ../xodr/fabriksgatan.xodr
Scenegraph: ../models/fabriksgatan.osgb
Route::AddWaypoint Added waypoint 0: 0, 1, 63.00
Route::AddWaypoint Added intermediate waypoint 1 roadId 9 laneId -1
Route::AddWaypoint Added waypoint 2: 2, 1, 0.00
Route::AddWaypoint Added waypoint 0: 0, 1, 63.00
Route::AddWaypoint Added intermediate waypoint 1 roadId 9 laneId -1
Route::AddWaypoint Added waypoint 2: 2, 1, 0.00
0.000: Init Ego RoutingAction standbyState -> startTransition -> runningState
0.000: Ego New position:
0.000: Pos(42.98, -71.25, 0.00) Rot(1.78, 0.00, 0.00) roadId 0 laneId 1 offset 0.00 t 1.75
0.000: Init Ego TeleportAction standbyState -> startTransition -> runningState
0.000: Init Ego LongitudinalAction standbyState -> endTransition -> completeState
0.000: pedestrian_adult New position:
0.000: Pos(35.69, -23.63, 0.00) Rot(1.80, 0.00, 0.00) roadId 0 laneId 3 offset 0.50 t 5.30
0.000: Init pedestrian_adult TeleportAction standbyState -> startTransition -> runningState
0.000: Init Ego RoutingAction runningState -> endTransition -> completeState
0.000: Init Ego TeleportAction runningState -> endTransition -> completeState
0.000: Init pedestrian_adult TeleportAction runningState -> endTransition -> completeState
0.000: Viewer failure. Probably requested level of Anti Aliasing (4 multisamples) is not supported - try a lower number. Making another attempt without Anti-Alias and single screen.
Windows Error #127: [Screen #0] ChooseMatchingPixelFormat() - wglChoosePixelFormatARB extension not found, trying GDI. Reason: The specified procedure could not be found.

Rendering in software: pixelFormatIndex 3
Warning:: Mipmapped osg::Image not a power of two, cannot apply to texture.
Warning:: Mipmapped osg::Image not a power of two, cannot apply to texture.
Warning:: Mipmapped osg::Image not a power of two, cannot apply to texture.
Warning:: Mipmapped osg::Image not a power of two, cannot apply to texture.
```

**Comment by eknabevcc** [comment]
Interesting. Just to understand the setup: Do you run Windows within VirtualBox on a Linux host?
Does it crash after throwing the warnings or it keeps going?

The Anti Alias warning is common in virtual machines. But esmini normally makes another attempt to open graphics context with no subsampling (anti-alias). 

But the last warning I don't recall I've seen before. It indicates that at least one texture image is of size not a power of two (128, 256, 512, 1024...). Old graphics HW typically had this requirement. I guess that there is some objects in the fabriksgatan.osgb file that make use of such texture. 

Can you test run_lane_change_crest.bat? That is not making use of any .osgb file, and hence there's no risk for non power-2-size textures. Does it run correctly?

This is good input. Future model files should obey this power 2 rule to be as compatible as possible - if that is the issue...

**Comment by ebadi** [comment]
Thanks. Yes, I am running Windows guest machine within VirtualBox on a Ubuntu host.

Yes, it crashes immediately even when I run the run_lane_change_crest.bat script :
```
C:\Users\ABC\Downloads\esmini-demo_win\esmini-demo\run\esmini>run_lane_change_crest.bat

C:\Users\ABC\Downloads\esmini-demo_win\esmini-demo\run\esmini>"../../bin/esmini" --window 60 60 1024 576  --osc ../../resources/xosc/lane_change_crest.xosc --camera_mode flex-orbit
esmini GIT REV: 159852b
esmini GIT TAG: v2.9.0
esmini GIT BRANCH: tags/v2.9.0^0
esmini BUILD VERSION: 2.9.0.build.1491
Loading lane_change_crest.xosc (v1.0)
OpenDRIVE: ../xodr/crest-curve.xodr
Scenegraph: None
0.000: Ego New position:
0.000: Pos(164.65, -4.63, 0.00) Rot(6.14, 0.00, 0.00) roadId 0 laneId -1 offset 0.00 t -1.60
0.000: Init Ego TeleportAction standbyState -> startTransition -> runningState
0.000: Init Ego LongitudinalAction standbyState -> endTransition -> completeState
0.000: Target1 New position:
0.000: Pos(262.63, -127.47, 0.00) Rot(1.06, 0.00, 0.00) roadId 0 laneId 1 offset 0.00 t 1.60
0.000: Init Target1 TeleportAction standbyState -> startTransition -> runningState
0.000: Init Target1 LongitudinalAction standbyState -> endTransition -> completeState
0.000: Target2 New position:
0.000: Pos(247.62, -140.90, 0.00) Rot(0.71, 0.00, 0.00) roadId 0 laneId -1 offset 0.00 t -1.60
0.000: Init Target2 TeleportAction standbyState -> startTransition -> runningState
0.000: Init Target2 LongitudinalAction standbyState -> startTransition -> runningState
0.000: Init Ego TeleportAction runningState -> endTransition -> completeState
0.000: Init Target1 TeleportAction runningState -> endTransition -> completeState
0.000: Init Target2 TeleportAction runningState -> endTransition -> completeState
Windows Error #127: [Screen #0] ChooseMatchingPixelFormat() - wglChoosePixelFormatARB extension not found, trying GDI. Reason: The specified procedure could not be found.

Rendering in software: pixelFormatIndex 3
0.000: No scenegraph 3D model loaded. Generating a simplistic one...
0.000: Created outline geometry for object Building1.
0.000:   if it looks strange, e.g.faces too dark or light color,
0.000:   check that corners are defined counter-clockwise (as OpenGL default).
0.000: Created outline geometry for object Building2.
0.000:   if it looks strange, e.g.faces too dark or light color,
0.000:   check that corners are defined counter-clockwise (as OpenGL default).

C:\Users\ABC\Downloads\esmini-demo_win\esmini-demo\run\esmini>
```

**Comment by eknabevcc** [comment]
Ok, thanks for reporting back. The good news then is that it wasn't the 2-power thing that caused the crash. Bad news is that then I don't have a clue.
To confirm that it is related to graphics window handling, please try to run: run_cut-in_cr_headless.bat
It will run the cut-in_cr scenario without graphics. 

If that seems to work then it will be possible to run scenarios and create recordings like this:
`.\bin\esmini --headless --fixed_timestep 0.01 --record sim.dat --osc .\resources\xosc\cut-in.xosc`

The resulting .dat file can then be replayed (and plotted and analyzed) on any other system. Play it like this:
`.\bin\replayer.exe --res_path .\resources --window 60 60 800 400 --file sim.dat`

I think that's the best we can do for now. 

I had a similar issue trying to run esmini on a virtual Mac. It simply seems like virtual machines has some issues with OpenGL (which OpenSceneGraph is based on) support. Probably due to OpenGL pretty connected to graphics HW features, and SW implementations of same features are not perfect. But that is me guessing...

**Comment by ebadi** [comment]
I downloaded `run_cut-in_cr_headless.bat` and `cut-in_cr.xosc` separately and added to the prebuilt package:
```
Windows Error #127: [Screen #0] ChooseMatchingPixelFormat() - wglChoosePixelFormatARB extension not found, trying GDI. Reason: The specified procedure could not be found.

Rendering in software: pixelFormatIndex 3
Warning:: Mipmapped osg::Image not a power of two, cannot apply to texture.
```
So the previous command didn't work.

The following command works successfully:
`.\bin\esmini --headless --fixed_timestep 0.01 --record sim.dat --osc .\resources\xosc\cut-in.xosc`

but running the second command causes the usual error: 
```
C:\Users\bilin\Downloads\esmini-demo_win\esmini-demo>.\bin\replayer.exe --res_path .\resources --window 60 60 800 400 --file sim.dat
esmini GIT REV: 159852b
esmini GIT TAG: v2.9.0
esmini GIT BRANCH: tags/v2.9.0^0
esmini BUILD VERSION: 2.9.0.build.1491
Recording sim.dat opened. odr: e6mini.xodr model: e6mini.osgb
Windows Error #127: [Screen #0] ChooseMatchingPixelFormat() - wglChoosePixelFormatARB extension not found, trying GDI. Reason: The specified procedure could not be found.

Rendering in software: pixelFormatIndex 3
Creating object 0 - got state from gateway
Creating object 1 - got state from gateway
Warning:: Mipmapped osg::Image not a power of two, cannot apply to texture.
```

Thanks. Yes, I think there is a fundamental issue with OpenGL inside virtualbox.  I close this issue for now and try other virtualization solution (e.g. vmware).

**Comment by eknabevcc** [comment]
Make sure you run the second command on another system (not the one causing crash):
`.\bin\replayer.exe --res_path .\resources --window 60 60 800 400 --file sim.dat`

One use case is to run many scenarios in batch mode (skipping graphics greatly increase throughput of scenarios/minute).
Then you can pick up the .dat files and review selected runs. That's the basic idea with --record and replayer.
