### ISSUE TITLE
Questions about SE_GetObjectState

### ISSUE THREAD

**Issue by omy5123** [esmini/esmini#126]
Hello, I'm trying esmini in unity. I wonder where the algorithm is to update the vehicle's location information (SE_GetObjectState) by receiving open-drive and open-scenarios files.

With the map information of the open drive, I wonder how it is calculated!

Thank you so much.

**Comment by eknabevcc** [comment]
Hi! Did you check out the example found [here](https://www.dropbox.com/s/sj53hz0zesxa681/esmini-player.unitypackage?dl=0)?

In the module "esminiUnityExample.cs" you have (line ~153) an example of retrieving the state of all available objects/vehicles:
```
        for (int i = 0; i < ESMiniLib.SE_GetNumberOfObjects(); i++)
        {
            ESMiniLib.SE_GetObjectState(i, ref state);

```
Then around line ~172 the state (position and rotation) is applied to the Unity objects:
```
            // Adapt to Unity coordinate system
            cars[i].transform.position = RH2Unity(new Vector3(state.x, state.y, state.z));
            cars[i].transform.rotation = Quaternion.Euler(RHHPR2UnityXYZ(new Vector3(state.h, state.p, state.r)));
```
I hope this is somewhat answer to your question. Otherwise just get back.

**Comment by omy5123** [comment]
I checked. Thank you for your reply! In addition, as far as I understand, is it right to parse the values of s, x, and y in the open drive file and update the position value of the state of the vehicle?

I'm confused about the calculation process between scenario and open drive.

Thank you for reading!

**Comment by eknabevcc** [comment]
I'll try to answer:
You connect the scenario to a road network in the `<RoadNetwork>`/`<LogicFile>` element of the OpenSCENARIO file. Example [here](https://github.com/esmini/esmini/blob/4918437c81ee9ca00e1130f1b7a41a3404f5a921/resources/xosc/cut-in.xosc#L27).

Then you need to position scenario objects somewhere. Either you can do this with Cartesian coordinates X, Y (and heading) using WorldPosition, e.g:
`<WorldPosition x="10.0" y="5.0" h="3.14" />`
But a simpler way is usually to look up the ID of the desired road, and then specify a lane-ID and s-value (how far along the road). E.g:
`<LanePosition roadId="5" laneId="-1" offset="0" s="120"/>`
This will put the object at Road with ID 5, in lane -1 (which is first lane on right side of center), no offset from lane center and 120m from the start of the road.
This is typically done within the `<Init>` section of the Storyboard.

Then, if you set a speed for the object, esmini will update the position for each timestep - making sure it follows the lane at specified speed. 

You can see any of the [example xosc files](https://github.com/esmini/esmini/tree/master/resources/xosc).

**RoadID**
And yes, it might be tricky to identify a the road ID. If you don't have any road/OpenDRIVE tool, I can recommend odrplot. Use it like this, from esmini root folder:
```
.\bin\odrplot.exe .\resources\xodr\fabriksgatan.xodr
.\EnvironmentSimulator\Applications\odrplot\xodr.py .\track.csv
```
Note that this requires Python and Matplotlib package (pip install matplotlib).

Press the button:
![image](https://user-images.githubusercontent.com/29146839/121707182-9bc31e80-cad6-11eb-9e05-58e778884038.png)
Then right click to zoom and left click to panorate in the image. 

![image](https://user-images.githubusercontent.com/29146839/121706768-3a9b4b00-cad6-11eb-892b-6edd8c73cdd4.png)

**Comment by eknabevcc** [comment]
I hope the connection of OpenDRIVE to a scenario and how positioning works has been somewhat clarified by our answer. 
Closing the issue. Please re-open for further questions on the topic.
