### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by BolinZhou** [esmini/esmini#13]
While following the procedure to the last step:

> make -j4

It returns the following error

`Building CXX object EnvironmentSimulator/ViewerBase/CMakeFiles/ViewerBase.dir/viewer.cpp.o
In file included from /home/bolin/esmini/EnvironmentSimulator/ViewerBase/viewer.cpp:13:0:
/home/bolin/esmini/EnvironmentSimulator/ViewerBase/viewer.hpp:133:3: error: extra qualification ‘viewer::CarModel::’ on member ‘CarModel’ [-fpermissive]
   CarModel::CarModel(osgViewer::Viewer *viewer, osg::ref_ptr<osg::LOD> lod, osg::ref_ptr<osg::Group> parent, osg::ref_ptr<osg::Group> trail_parent, osg::ref_ptr<osg::Node> dot_node, osg::Vec3 trail_color);
   ^~~~~~~~
In file included from /home/bolin/esmini/EnvironmentSimulator/ViewerBase/viewer.cpp:13:0:
/home/bolin/esmini/EnvironmentSimulator/ViewerBase/viewer.hpp:138:8: error: extra qualification ‘viewer::CarModel::’ on member ‘UpdateWheelsDelta’ [-fpermissive]
   void CarModel::UpdateWheelsDelta(double wheel_angle, double wheel_rotation_delta);
        ^~~~~~~~
EnvironmentSimulator/ViewerBase/CMakeFiles/ViewerBase.dir/build.make:62: recipe for target 'EnvironmentSimulator/ViewerBase/CMakeFiles/ViewerBase.dir/viewer.cpp.o' failed
make[2]: *** [EnvironmentSimulator/ViewerBase/CMakeFiles/ViewerBase.dir/viewer.cpp.o] Error 1
CMakeFiles/Makefile2:758: recipe for target 'EnvironmentSimulator/ViewerBase/CMakeFiles/ViewerBase.dir/all' failed
make[1]: *** [EnvironmentSimulator/ViewerBase/CMakeFiles/ViewerBase.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

Not too sure where went wrong.

The environment is Ubuntu 18.04

Thanks

**Comment by eknabevcc** [comment]
Thanks for feedback! I think it is fixed now. But I have only checked on my virtual Ubuntu, so please verify and get back if it still fails in your environment.

**Comment by eknabevcc** [comment]
Actually I found another similar error in vehicle.hpp, now fixed as well (commit c93d7b5).

**Comment by eknabevcc** [comment]
Does it compile in your environment now and we can close the issue? Otherwise I will investigate further,

**Comment by eknabevcc** [comment]
Assuming fixed. Closing issue.
