### ISSUE TITLE
Controller explanation for OSCPrivateAction

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#132]
Hi,
can someone explain a little bit more the so called ALKS controller in the OSC ALKS scenarios
```
<PrivateAction>
    <ActivateControllerAction lateral="true" longitudinal="true"/>
</PrivateAction>
```
I think here the ego vehicle brakes, if there is an object on lane. But, when this braking is activated (target vehicle enters the lane or target vehicle starts the lane change but is still on its lane, target vehicle crosses ego waypoints, ....), is also an emergency braking possible (always full brake, if collision is not avoidable or if remaining distance would be close to zero after braking)?

My plan would be to check with esmini whether a scenario can be physically handled or not, this means, if the ego vehicle would directly detect the lane change in front of it and would directly execute a full braking, if a collision would happen or not. The collision calculation on the basis of esmini trajectories and bounding boxes I've already implemented, thus no worry about it.

And yes for sure, however this will be finally implemented, it is always a rough estimation, because full braking of real cars behave always different to simplified vehicle models (also difference in braking controller, wheather conditions, tyres, friction, ...) and the real shape of cars looks never than a simple bounding box, but as first shot this would be sufficient for me.

**Comment by eknabevcc** [comment]
I think the ALKS scenarios are designed to make it easy to hook up an ALKS function (by means of a controller) to the simulation for testing or development.
esmini does not include an ALKS controller by default. And I'm not the right person to say what exactly should be expected from an ALKS system. 
Anyway, when no explicit controller is activated the default controller will handle the vehicle, moving it forward at current speed and current lateral lane offset (typically lane center if not explicitly changed by an action). And does not see/care about other vehicles.
Maybe your plan is to implement an ALKS controller in esmini? That would be very interesting. And nice if it could be shared eventually. Or do you plan to run the simulation and analysis in a post (esmini) processing step?

**Comment by tmIdiada** [comment]
Hi,

so you mean, that the OSC ALKS scenarios added to esmini (git hyperlink) are not fully compatible with esmini, that there is some kind of controller integrated, that does not exist in esmini (but can be integrated like any kind of external controller). Has esmini any kind of aeb controller integrated per default? If not, then I have a simple workaround for my use-case. Instead of this defined ALKS controller (that does not exist and where the default controller is used), I can add one additional braking action to ego with full braking at the same moment, when any action is executed by the target vehicle in front (braking, cut-in). Only, when I need this information if a collision would happen (additional braking action to ego) and also the full trajectory of ego vehicle (without this new additional braking action), then one would need here two scenario files and two simulations with esmini.

For me I see here only the need for an aeb-controller, because the lane is already kept by the default controller. But the design of such a controller is complicated with many parameters, that all people would be happy with it, like reaction time, sensor range, width of the sensors' field of view (per distance), minimal and maximal bounding box width in ego lane that would raise a reaction (braking), maybe some parameters more (for example statistical parameters for sensor errors or more realistic sensors instead of ideal sensors).

Thank you a lot for the explanation so far, I know now a solution for my use-case and yes instead of maybe one additional file and simulation a simple alks (kept by default controller)/aeb controller (do a full-brake and try to avoid a collsiion) would be very nice in future. Unfortunately, my knowledge in C/C++ is not the best (more pythonic world), thus for the moment I must solve my issue by such quick & dirty solutions.


Kind regards,

Thaddäus
