### ISSUE TITLE
Update OSC 1.1 for ActivateControllerAction

### ISSUE THREAD

**Issue by arauschert** [esmini/esmini#133]
When running one of the ALKS scenarios there's an error message:

"Unexpected ControllerAction subelement: ActivateControllerAction"

Probably esmini needs a small update for the new domain model of OpenSCENARIO 1.1, where the ActivateControllerAction was moved below the ControllerActions.

**Comment by eknabevcc** [comment]
You're absolutely right. We missed that change. Now fixed in commit https://github.com/esmini/esmini/commit/0c3ed3b5ff2c673100b422ef4db43d7389b5de9c
Should we make a release asap?

**Comment by arauschert** [comment]
Thanks for the quick reply! It's not urgent.

**Comment by eknabevcc** [comment]
Ok. Good to know. It's now on master and then it'll simply be part of next upcoming release.
