### ISSUE TITLE
Displacement not yet considered in LongitudinalDistanceAction

### ISSUE THREAD

**Issue by arauschert** [esmini/esmini#136]
Hi,
when using the LongitudinalDistanceAction, then the new attribute "displacement" (leading/trailing) is not considered yet. Instead the sign of the distance/timegap attribute is still used to determine, if the entity should be in front or behind the reference entity. To achieve backward compatibility to 1.0, you could only consider the sign of the distance attribute, if no displacement is given and if a displacement is given, then the distance/timegap must be positive / only the absolute value is used.

I will shortly post a link to an example in the XOSC ALKS scenarios, where I use this action to set up the initial headway time.

**Comment by arauschert** [comment]
The example scenario for testing can be found here:
https://github.com/asam-oss/OSC-ALKS-scenarios/blob/create_distribution_files/Scenarios/ALKS_Scenario_4.1_2_SwervingLeadVehicle_TEMPLATE.xosc

If you change the timeGap in line 107 from 2.0 to -2.0 it works as expected.

**Comment by eknabevcc** [comment]
Thanks a lot for reporting this issue and providing the example scenario.
It should now be fixed accordingly in commit c73c96e356c9ec5ca012458ed9bf75ca33ed4b82 and release [v2.12.2](https://github.com/esmini/esmini/releases/tag/v2.12.2).

**Comment by arauschert** [comment]
Great thanks! I tested it and it works.
I write a comment in the commit for the case when distType::Distance is used:
https://github.com/esmini/esmini/commit/c73c96e356c9ec5ca012458ed9bf75ca33ed4b82#r53982340

**Comment by eknabevcc** [comment]
Thanks for the observation/found bug. It should be fixed in commit c2e8978 and release [v2.12.3](https://github.com/esmini/esmini/releases/tag/v2.12.3).

**Comment by arauschert** [comment]
Looks good! I think we can close this issue then.
