### ISSUE TITLE
Is there API to read Lane Validity Record?

### ISSUE THREAD

**Issue by dalishi** [esmini/esmini#143]
Hi,
there is "Lane Validity Record" for objects in OpenDrive xodr, e.g. for a signal:
`<validity fromLane="1" toLane="1"/>` means it is valid for lane 1.

Is there an API in RoadManager to read this tag? I didnt find any. Thanks.

**Comment by eknabevcc** [comment]
Thanks for reporting this missing feature. It's now added in commit 89efe7e7190794dbbfd0eebd4bafff1da0d6c2b9 and [release 2.12.5](https://github.com/esmini/esmini/releases).
Please check code example in [rm-basic.cpp](https://github.com/esmini/esmini/blob/7aeb578dd72caa650806bc0d1f6eecac05cfef19/EnvironmentSimulator/code-examples/rm-basic/rm-basic.cpp#L24).
Hopefully this is what you need.
