### ISSUE TITLE
Missing datas in CSV log file 

### ISSUE THREAD

**Issue by fatihmms** [esmini/esmini#145]
Hello,

I am working on getting some data from scenarios. To do that, I used csv_logger functionality. However, in the output file there are some missing data such acceleration Y and X values etc. How can I fix it or is there any way to get detailed csv file?

Thank you.

**Comment by eknabevcc** [comment]
The CSV logger and .dat file logging are both limited and include only most important values. Unfortunately, to end users, there's no simple way of modifying what's logged.

But if you can compile esmini yourself, I can see two solutions:

**1. Extend existing CSV logger**

- First add parameters to headers in [constructor](https://github.com/esmini/esmini/blob/25fb3cbbf9c45032de2d5f6a9ca90f74aea72e68/EnvironmentSimulator/Modules/CommonMini/CommonMini.cpp#L807), 
- then add values in [log method](https://github.com/esmini/esmini/blob/25fb3cbbf9c45032de2d5f6a9ca90f74aea72e68/EnvironmentSimulator/Modules/CommonMini/CommonMini.cpp#L875).
- Finally you need to add the parameter values to the [method call](https://github.com/esmini/esmini/blob/25fb3cbbf9c45032de2d5f6a9ca90f74aea72e68/EnvironmentSimulator/Modules/PlayerBase/playerbase.cpp#L943). E.g. add acceleration entries, something like: pos.GetAccX(), pos.GetAccY(), pos.GetAccZ().

**2. Use OSI framework**
Most ground-truth information is packed into OSI format and made available in different ways: 
- Get it by function calls
- As UDP messages
- As OSI trace file (*.osi)

You can check the [OSI code example](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/code-examples/osi-groundtruth/osi-groundtruth.cpp) (which demonstrate how to fetch some OSI data by function call). I just updated it to include acceleration.
Another way could be to save OSI trace file (esmini argument `--osi_file` will result in a "ground_truth.osi" file) for post processing/conversion into other file format. [Here's a starting point](https://github.com/OpenSimulationInterface/open-simulation-interface/tree/master/format) for reading OSI trace files. (But I agree this option may be a bit tricky, however powerful).

**Comment by fatihmms** [comment]
I changed EnvironmentSimulator code according your instructions for option 1 (extend existing CSV logger). Then I builded the solution and get the .csv file. But, still I got same datas and file. Is there anything that I do wrongly?

**Comment by eknabevcc** [comment]
I made a quick example in branch [extend_csv](https://github.com/esmini/esmini/tree/extend_csv)
more specifically in commit dbf30c9878b6a246797f05d946424f28c3b6e9b8 (Example how to extend CSV logger)

**Comment by eknabevcc** [comment]
BTW. Don't forget to activate the CSV logger with argument --csv_logger, e.g: `--csv_logger myfilename.csv`

**Comment by fatihmms** [comment]
I solved it thanks your help. Thank you very much. Last question about it. Is there any way to get yaw velocity of vehicles in esmini source code or do I need to write a special function for that?

**Comment by eknabevcc** [comment]
I think Yaw velocity is the same as what we call "heading rate" in esmini. 

I've updated the code example with heading rate, and also fixed a bug (missing entries in the long list of "i"s which provide index to the entries in the log). And another bug which inserted acceleration values before posZ for Ego (first) vehicle. 
I think it's more correct now.

Please check commit 61ada8091194587257021b89eda2ee42320bc77c, still in branch [extend_csv](https://github.com/esmini/esmini/commits/extend_csv).

**Comment by fatihmms** [comment]
Thank you very much for your help, I solved all problems in my configuration.

**Comment by eknabevcc** [comment]
Good to hear! 
Actually I merged the branch to master, so the added CSV entries is included in new release [v2.13.0](https://github.com/esmini/esmini/releases/tag/v2.13.0).
I close this issue now. Please re-open for further questions on the topic.
