### ISSUE TITLE
Where to find documentation about the esmini network interfaces

### ISSUE THREAD

**Issue by johschmitz** [esmini/esmini#152]
It seems there is not much documentation about the network interfaces of esmini and their features. Maybe I just did not find it? Or will there be more in the future. I am wondering for example if I can do things like triggering a simulation step from outside using UDP communication.

**Comment by eknabevcc** [comment]
Short answer no, there's no UDP interface to esminiLib. But I must admit it's an interesting idea (although TCP might be preferred for command-like messages).

There are unfortunately no explicit documentation. On the other hand there are scenario files and code examples to demonstrate what's supported and inspire to develop similar things. For example:
- [esmini-dyn](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Applications/esmini-dyn/main.cpp)
- [osi_receiver](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Applications/replayer/osi_receiver.cpp)
- and this [collection of code examples](https://github.com/esmini/esmini/tree/master/EnvironmentSimulator/code-examples)
- and [Hello World tutorial](https://github.com/esmini/esmini/tree/master/Hello-World_coding-example)

In the Hello World page there's [some info](https://github.com/esmini/esmini/tree/master/Hello-World_coding-example#python-binding) on how to integrate with Python. 

Another example that might be relevant is [Server.cpp](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Modules/ScenarioEngine/SourceFiles/Server.cpp) which receives Ego state from an external simulator (over UDP) and feed it to esmini.

So if I was to do it, which I will not be able to right now, I would go for either:
1. Writing a small application that listens to UDP messages (see server for some code snippets) and steps esmini, like one of the hello world-examples. or
2. Do it in Python, i.e. write a Python script that receives UDP messages and translates them into esmini calls.

This is what currently comes to my mind.

**Comment by sterres** [comment]
Sorry to hijack this issue... but I keep getting errors when trying to use esmini as OSI sender

I start esmini with this command:  `esmini.exe --osc e6mini.xosc --window 100 100 600 400 --osi_receiver_ip 127.0.0.1`

And get this error for every timestep
`OSIReporter.cpp / 292 / OSIReporter::UpdateOSIGroundTruth(): Failed send osi package over UDP`

Do you know if this is a esmini configuration issue?
I made sure to add a firewall exception for all ports for esmini.


Also it took a bit of searching to find that the port is actually hardcoded:
https://github.com/esmini/esmini/blob/52f50df64d193468a9da84fa344e960f3f13f132/EnvironmentSimulator/Modules/ScenarioEngine/SourceFiles/OSIReporter.cpp#L28

**Comment by eknabevcc** [comment]
The following should work (tested on ubuntu and win10), from esmini root folder:

terminal 1: `./bin/osireceiver`
terminal 2: `./bin/esmini --osc ./resources/xosc/cut-in.xosc --window 100 100 600 400 --osi_receiver_ip 127.0.0.1`

Terminal 1 outputs something like:
```
Socket open. Waiting for OSI messages on port 48198. Press Ctrl-C to quit.
timestamp: 0.01
 obj id 0 pos (8.18, 51.67, -0.04) orientation (1.57, 0.00, 0.00) velocity (0.11, 30.00, 0.00)
 obj id 1 pos (4.51, 26.43, -0.01) orientation (1.57, 0.00, 0.00) velocity (0.00, 0.00, 0.00)
timestamp: 0.11
 obj id 0 pos (8.19, 54.67, -0.05) orientation (1.57, 0.00, 0.00) velocity (0.11, 30.00, 0.00)
 obj id 1 pos (4.53, 30.03, -0.01) orientation (1.57, 0.00, 0.00) velocity (0.12, 36.00, 0.00)
...
```

If it fails, maybe it's because the port seems to be in use and not released correctly by a previous esmini session. Last resort, try restart the computer. In a custom application you could make the port configurable, e.g. via argument.

**Comment by sterres** [comment]
My bad...I used an outdated version of esmini. Works fine with the newest release.

Do you happen to have an example of how to treat the buffer with a Python receiver? Do we need ctypes to "reconstruct" the buffer you use in the C++ example?

**Comment by eknabevcc** [comment]
Not 100% sure about the use case, but perhaps have a look at this example:

https://github.com/esmini/esmini/blob/master/scripts/udp_driver/testUDPDriver-minimalistic-example-osi.py

You can skip the UDP stuff, but look how OSI is received using the [OSIReceiver](https://github.com/esmini/esmini/blob/master/scripts/udp_driver/udp_osi_common.py) class.

**Comment by sterres** [comment]
I was looking for exactly this one: 
https://github.com/esmini/esmini/blob/master/scripts/udp_driver/udp_osi_common.py

Thanks for your fast support!
