### ISSUE TITLE
support for ubuntu 16.04  

### ISSUE THREAD

**Issue by zwkcoding** [esmini/esmini#153]
when I download the pre-built binary , then run `./odrviewer`, get error as below:

```
./odrviewer: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./odrviewer)
```

After I searched on google, I  found   `GLIBC_2.27`  is not supported for  ubuntu 16.04   system, Must I upgrade system to 18.04  ?

**Comment by zwkcoding** [comment]
One more build error as below: 

```bash
[  1%] Generating ../../../../EnvironmentSimulator/Modules/CommonMini/_version.cpp, ../../../../EnvironmentSimulator/Modules/CommonMini/version.cpp
Consolidate compiler generated dependencies of target PlayerBase
Consolidate compiler generated dependencies of target Controllers
Consolidate compiler generated dependencies of target ScenarioEngine
[  4%] Built target PlayerBase
[  5%] Building CXX object EnvironmentSimulator/Modules/ScenarioEngine/CMakeFiles/ScenarioEngine.dir/SourceFiles/Entities.cpp.o
[ 18%] Built target Controllers
[ 19%] Building CXX object EnvironmentSimulator/Applications/replayer/CMakeFiles/osireceiver.dir/osi_receiver.cpp.o
[ 20%] Building CXX object EnvironmentSimulator/Unittest/CMakeFiles/OperatingSystem_test.dir/OperatingSystem_test.cpp.o
Consolidate compiler generated dependencies of target CommonMini
[ 20%] Generating ../../../../EnvironmentSimulator/Modules/CommonMini/_version.cpp, ../../../../EnvironmentSimulator/Modules/CommonMini/version.cpp
[ 22%] Building CXX object EnvironmentSimulator/Modules/CommonMini/CMakeFiles/CommonMini.dir/version.cpp.o
[ 23%] Linking CXX static library libCommonMini.a
/usr/bin/ar qc libCommonMini.a CMakeFiles/CommonMini.dir/CommonMini.cpp.o CMakeFiles/CommonMini.dir/version.cpp.o CMakeFiles/CommonMini.dir/buildnr.cpp.o
/usr/bin/ranlib libCommonMini.a
[ 26%] Built target CommonMini
[ 27%] Building CXX object EnvironmentSimulator/Modules/ScenarioEngine/CMakeFiles/ScenarioEngine.dir/SourceFiles/IdealSensor.cpp.o
/home/zwk/Downloads/xodr/software/esmini/EnvironmentSimulator/Modules/ScenarioEngine/SourceFiles/Entities.cpp: In member function ‘void scenarioengine::Object::SetJunctionSelectorAngle(double)’:
/home/zwk/Downloads/xodr/software/esmini/EnvironmentSimulator/Modules/ScenarioEngine/SourceFiles/Entities.cpp:199:17: error: ‘isnan’ was not declared in this scope
  if (isnan(angle))

```

I solved this by add std namespace prefix according this link :  https://stackoverflow.com/a/18128988/8691463

**Comment by eknabevcc** [comment]
To the original question: I'm not sure actually. There was another user with similar issue on CentOS. 
In that case not all dependencies ware needed, only OpenSceneGraph (for visualizing). So the solution was to compile OSG for the older GLIBC and provide those libs, and then he could (re)compile esmini himself. 

If you think you could (and want to) compile esmini yourself, you might look into [this guideline](https://github.com/esmini/esmini/blob/master/docs/BuildInstructions.md#centos-7-linux).
The OSG libraries within osg_centos.7z might work on Ubuntu 16 as well...

**Comment by zwkcoding** [comment]
> To the original question: I'm not sure actually. There was another user with similar issue on CentOS.
> In that case not all dependencies ware needed, only OpenSceneGraph (for visualizing). So the solution was to compile OSG for the older GLIBC and provide those libs, and then he could (re)compile esmini himself.
> 
> If you think you could (and want to) compile esmini yourself, you might look into [this guideline](https://github.com/esmini/esmini/blob/master/docs/BuildInstructions.md#centos-7-linux).
> The OSG libraries within osg_centos.7z might work on Ubuntu 16 as well...

Yes， I compiled it by the guideline. Once I fix the little compile error caused by `isnan`, I successed.

**Comment by eknabevcc** [comment]
Great. Thanks for the compile error fix. It's now added on master branch. 

By the way, I understand you managed to compile on Ubuntu 16.04, but was it including the visualization (OSG) so that you can view the scenario running? In that case I should add that info to the guideline and then close the issue.

**Comment by zwkcoding** [comment]
> Great. Thanks for the compile error fix. It's now added on master branch.
> 
> By the way, I understand you managed to compile on Ubuntu 16.04, but was it including the visualization (OSG) so that you can view the scenario running? In that case I should add that info to the guideline and then close the issue.

YES, I compile it with OSG : `cmake  -D USE_SUMO=False ..`
BTW,  the build instruction is Excellent !
