### ISSUE TITLE
Difference between defined trajectory with vertex and simulated data coming from esmini

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#158]
Hi,

I have a trajectory defined in xosc via vertex for ego vehicle is a world position of around 115m in x for last time value 48sec. But when I'm simulating this xosc with esmini, I'm getting as last x-position 138m. I have uploaded the xosc, xodr, dat and csv coming from dat.

Please help here to find the error.
[CutOut011.zip](https://github.com/esmini/esmini/files/7175837/CutOut011.zip)

one additional question: Why do I see real shapes of cars when I build esmini by myself and why do I see only cuboids when I use the released binaries of windows?

**Comment by tmIdiada** [comment]
Sorry, I've seen now, that the TimeReference was None, something was wrong in the usage of scenariogeneration.

**Comment by eknabevcc** [comment]
I don't think it's possible to delete. But it's totally OK - and it's closed. Actually I'd like to look into the cuboid part of the issue.

The binary zip-package includes (almost) only binaries (all executables and libraries). But you don't get content like scenarios and models. The demo zip-package on the other hand includes some scenarios plus binaries and models typically referred to by scenarios. 

My typical recommendation is to grab demo package first. 

If you already have models and perhaps own scenarios you can grab binary package to get the latest versions. Then just replace binaries in the demo bin folder.

Another way to get models is to grab the model pack from here: https://www.dropbox.com/s/5gk8bvgzqiaaoco/models.7z?dl=1
(the same link as in [this section](https://github.com/esmini/esmini#binaries-and-demos))

I hope it makes sense and that it solves the cuboid issue.

**Comment by tmIdiada** [comment]
The models issue is now solved. Thanks, seems that I was too lazy to read the whole docu or too tired in that moment to understand all its content.
