### ISSUE TITLE
Animation from replayer and data from dat/xosc do not match

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#159]
Hi,

When I execute the replayer with the added dat file, then the white ego cuboid or car shape seems to start later then the first point of trajectory, so I think here the x-position of center of gravity is correctly used. But the red trajectory of the second vehicle ends near the point, where the rear surface of the cuboid or car shape is at last timestep. So, it seems, that the center of gravity of the second vehicle is the same like of ego vehicle = 1m instead of defined mid of the vehicle = 2.35m. This must be the reason why I see no collision in the replayer animation, but there must be a collision between 12.2 and 12.3 sec, if one looks at the x-positions of the dat or csv file.

I think here is a bug.

Could you check it?

Kind regards,

Thaddäus
[Deceleration001.zip](https://github.com/esmini/esmini/files/7178419/Deceleration001.zip)

**Comment by eknabevcc** [comment]
You're right that bounding-box center affects time of collision. To see more clearly you can press ',' (comma) key to visualize the bounding boxes and hide 3D model. This will also clearly show ref point relative bounding box (BB). Or you can start esmini with flag `--view_mode boundingbox`

When specifying center of bounding box it is relative reference point (and this is what the positions in dat file will track). So, for example, x=1 would put the BB center one meter ahead of ref point, or in other words, put the reference point 1m behind center of BB. According to OpenSCENARIO the vehicle reference point should be at rear axis. So, how we interpret this is to choose BB center x-value as distance between rear axis and geometrical center of the vehicle/BB. 

In your example (BB x=2.35) the reference point is coinciding with bounding box rear end, in effect moving car forward - which means that collision will happen later than e.g. BB x=1.0.

In first screenshot I run your settings:
![image](https://user-images.githubusercontent.com/29146839/133728047-383af422-e598-4b82-880e-c080de53589b.png)
In second image I adjusted lead BB x = 0:
![image](https://user-images.githubusercontent.com/29146839/133728096-b157c0e2-8daf-4fec-8190-e50f57d3826c.png)

To avoid confusion (or maybe add confusion): The BB specification is independent of the 3D model, which should have reference point hardcoded at rear axis. So, with your settings we get:
![image](https://user-images.githubusercontent.com/29146839/133730002-a5e5a18a-a3f3-4eaa-8097-7d64eae27da1.png)
Hence, the BB settings should match the 3D model, if one is used. And of course, you can skip 3D model in which case esmini will generate a solid cuboid with dimensions of the BB.

Let us know if this helps getting your scenario right. 
This is tricky, so it could be that we got something wrong in esmini.

**Comment by tmIdiada** [comment]
Hi,

thanks for the answer. So, when I understand it correctly one should define x position of rear axle always to zero, or if one has more than one rear axle, then maybe it is possible to define several rear axles, so that the sum of all the negative and positive x-values is zero and the 'resulting' rear axle is in the mid of all those axles. A little bit confusing, that this value must be chosen always to zero, if there is only one rear axle, maybe here should be a check and an error if there exist is only one rear axle or if the mid point of all rear axles is not zero.

Accordingly the x position of bounding box must be chosen in the following way: length of bounding box divided by two minus rear overhang. All my vehicles are 4.7m long, this would mean rear axle always at x=0 and bb center x= 1.35m (4.7m / 2 - 1m rear overhang).

Only in that way the data of esmini and the visualization would match, right?

So, what are now my possibilities? I need for my simulation the reference point, that is tracked for all other objects except of ego in the mid of the bounding box not at the rear axle and this is what I've tried to do (For sure for simulations it is very nice to have the mid point of rear axle as reference point, but in real world from testing point of view, when I have another vehicle directly in front, I don't know where the rear axle is and the bounding box has a length close to zero). In that case I must translate all coordinates from esmini from rear axle to bounding box center, feed with those trajectories coming from esmini my simulation (that cannot handle xosc directly) and then transform back from simulation the data from bbox center to rear axle for esmini to have esmini as postprocessing, right? There is no possibility to force esmini to use another reference point than the rear axle?
And yes I know, that the reference point is always on the ground with z=0, to keep it simple I say always mid of rear axle ;-).

Another question, even I define all x=0 and all bbox center x to 1.35, then I see, that the bbox and the 3d model do not match perfectly
![image](https://user-images.githubusercontent.com/78544110/133742553-8a4eb5d2-99ae-413b-a50f-41982cf59e70.png)

Is there a possibility to stretch the 3d-models in any dimensions, that they fit perfectly the defined bounding box with their corners?

Thanks for your support Emil

**Comment by eknabevcc** [comment]
Yes, regarding multiple rear axis I agree its not clear how to deal with reference point. 
Here is what's stated in the OpenSCENARIO 1.1 (under 3.3.4. Vehicle coordinate system):
https://www.asam.net/index.php?eID=dumpFile&t=f&f=4092&token=d3b6a55e911b22179e3c0895fe2caae8f5492467#_coordinate_systems
For (special) cases that falls outside the explicit boundaries of the standard; as long as the scenario author/generator and simulation tool agree I think it's any approach is OK.

And yes, I think your math for reference point is correct. 

And yes, the specified bounding boxes in xosc files do not fit the 3D models perfectly. But for your info, the 3D model is not part of any calculations, e.g. collision or distance. So any mismatching geometry is "just" a visual flaw. The default models are mainly proxies to provide slightly better understanding of the scenario than just bounding boxes. Users can replace the 3D models quite easily. 

That said, my suggestion for visual inspection of collisions is to simply skip the default models and go for bounding boxes only. This will also allow for flexible configuration of reference point. 

So, as you are thinking, try to set all BB x = 0, and start esmini with argument `--view_mode boundingbox`. That should put the reference point (and saved coordinates) in center of bounding box. This is decoupled from any axles. Actually esmini is not aware of any such think as axles :) (except the simple vehicle model used for interactive driving). 

A final comment on reference point. It's nice to have reference point at rear axle since that's a good rotation point - looks more natural than rotating cars around geometrical center e.g. when turning in intersections.

**Comment by tmIdiada** [comment]
Hi, again thank you for the help and comment.
Especially I have not seen that esmini don't cares about positions of axles and if one defines all positions and distances dependent on the center point and sets bbox x=0, that this automatically is leading to reference point in center point in esmini. This is tricky.

To be compliant with xosc standard and to be prepared for any kinematics in esmini in future releases I decided to implement the transformations from rear axle to center of bbox and vice versa, only this way it should be possible to simulate all xosc-files (e.g. from a real drive scene database, if and only if they are xosc compliant regarding the reference point), not only the self created ones (scenariogeneration).

Some last questions here regarding the 3D models (answers no must have): Is the size of one 3d model always the same (bbox sizes do never influence the size of the 3d model)? If I wanted to implement, that the 3d models should be stretched and get an offset until it matches perfectly the bbox corners, any idea where it should be implemented into esmini, are there any sizes of the 3d models available in esmini as variables, that they could be modified, like corner coordinates of polygons?

I'm no member of ASAM or have ever participated on any OpenScenario standard, but from real sensors' point of view I had not decided to use the rear axle as reference point, because the location is often or always unknown (until today I have never seen an AI showing me the location of the rear axle of a detected bounding box), here I would prefer the center point. Such transformation to rear axle for the visualization and the kinematics should be done by the solver. But ok, I have now to live with it like it is.

Could be interesting here how real drive scene databases are working like PEGASUS, there should be the possibility to export exactly that driving maneuver from real scene into xosc. If so, they can for sure not detect the rear axle positions, so then they must use default values for rear overhang (too unexact) or work with xosc files which are not standard compliant and work for example the same way you have proposed it with bbox x=0 and center point as reference point.

Kind regards,

Thaddäus

**Comment by eknabevcc** [comment]
Regarding axles, you're right that OpenSCENARIO Vehicle class contains axle definitions. And esmini is parsing them into the data model. But after that they are not really used in any calculations. So in that sense esmini is not aware of specified axles. But if/when we add vehicle dynamics option I think axle definitions will be really useful.

Them I must admit that your input regarding scaling models and/or bounding boxes inspired me to do some updates in the code. This is actually something that I think will be useful.

There is now, from commit 74166066c9463c52f76062776c8401394bc0ae21, an optional property, `scaleMode`, for ScenarioObjects (vehicle, pedestrian, miscobject) with the folowing possible values:
`None` (default) = Don't scale 3D model or bounding box
`BBToModel` = Scale bounding box to fit loaded 3D model
`ModelToBB` = Scale model to fit specified bounding box

Would you mind testing this new feature? It doesn't address the axle issue. But you can have the 3D model scaled exactly to fit the specified bounding box. Or the other way around, you can have the bounding box perfectly adapt to the specified 3D model (regardless of what's specified).

You can see available vehicles in the [VehicleCatalog](https://github.com/esmini/esmini/blob/master/resources/xosc/Catalogs/Vehicles/VehicleCatalog.xosc), and also how the property is used.

**Comment by tmIdiada** [comment]
Hi,
I've tested it and at least ModelToBB seems to work very well, but maybe too good. This means I added this scaleMode only as property to ego vehicle and the other vehicle was also scaled. Is this a feature, that it only must be defined once or is it a bug here?

Kind regards,

Thaddäus

**Comment by eknabevcc** [comment]
Thanks for testing!
You're right. I totally forgot about replayer and dat files. The scaleMode was not propagated correctly to dat.
It should now been fixed, commit 54023031f784bc422eb44b2547c800aeb9d7e643.
Would be great if you could do another test.

**Comment by tmIdiada** [comment]
It works very well. Great work Emil! I've also tested the direct esmini simulation without replayer with same result.

**Comment by eknabevcc** [comment]
Thanks for super fast feedback! 👍
we'll now release this feature.
