### ISSUE TITLE
road info depends on OpenDRIVE XODR road direction and not vehicle perspective

### ISSUE THREAD

**Issue by sterres** [esmini/esmini#161]
Hi,

while testing a simple lane keep assist with esmini, I found a problematic behavior using SE_GetRoadInfoAtDistance().

I'll use the "multi_intersections.xodr" example map from esmini to explain the problem. As you can see in the screenshot, the lane ids would change from 1 to -1 for a vehicle that drives from west to east. This is due to the road directions in the OpenDRIVE map being opposed.

![image](https://user-images.githubusercontent.com/30345042/134659065-03feda31-4c5b-4d2f-ab21-40874b03d149.png)

The problem is, that the road information that esminiLib gives, depend on the ODR road direction and not the vehicle direction.

This means, many values switch direction or sign (lane_offset, heading, s, t, curvature, ...) when driving from an "upstream" road on a "downstream" road.

In my use-case, the LKA algorithm would go nuts, because suddenly the input error signal (lane offset) switched the sign.

I'm using a simple fix for my use case to get uniform signals from esmini. But I didn't explore all consequences for all signals yet.

```cpp
// fix road heading offset sign
if (roadInfo.laneId > 0) {
    roadInfo.laneOffset *= -1;
    roadInfo.curvature *= -1;
}
```

The parameter "inRoadDrivingDirection" seems to not have the expected effect as it only alters the look ahead distance. But maybe here the fix could be implemented.
https://github.com/esmini/esmini/blob/f723817ffce9c64305d11c039e8db5a66011f1bf/EnvironmentSimulator/Libraries/esminiLib/esminiLib.cpp#L1411

Best regards
Simon

**Comment by eknabevcc** [comment]
Yes, the function will move forward specified distance from current position and collect road information at that destination position. As you noticed, the information is reflecting the OpenDRIVE description. So, for example, the laneId will always be the "true" laneId. Sign of laneOffset and curvature correlating to sign of laneId, all aligned with the OpenDRIVE standard.

That said, I totally understand your problem. Actually I guess that in most cases, like yours, it would be convenient to adjust laneOffset and curvature to the current driving direction. 

However, I think there might be situations where user needs more control. For example left hand traffic or temporary moving in opposite direction during a country-road overtake maneuver. And as you found out, it's fairly simple to adjust the result for road direction on user side. I think your code snippet is a perfect solution (applied on your side, after the esmini function call).

By returning "true" OpenDRIVE info we don't have to make any assumptions about use cases. Instead, the user can correlate the information to driving- and road direction as needed.

So, while it's not a very easy decision, I lean towards keeping existing function as is. But perhaps we could add another function better suited for driver-model use cases...? 

By the way, the flag inRoadDrivingDirection controls whether the look-ahead should be in road driving direction (true) according to current landId OR according to current actual driving direction regardless of laneId (false).

Another useful function is SE_SetLockOnLane(id, mode) which makes object keep current laneId, even if position (temporarily) might be closer to another lane. It's not easy to explain, hopefully the following videos helps to understand:

SE_SetLockOnLane(0, true);
https://user-images.githubusercontent.com/29146839/135215673-7888dfa1-0bad-451b-940b-1a91364dcf21.mp4

SE_SetLockOnLane(0, false);
inRoadDrivingDirection = false
https://user-images.githubusercontent.com/29146839/135215758-134775d0-5d73-4ff9-9c37-3b09de68c0ac.mp4

SE_SetLockOnLane(0, false);
inRoadDrivingDirection = true
https://user-images.githubusercontent.com/29146839/135215895-c149a64e-adcf-47f4-8e06-839b83bfd4eb.mp4

**Comment by sterres** [comment]
Thanks for another detailed explanation.

I think my main point of confusion is that there is an OpenDRIVE road direction and not only lane directions.

I totally get your point and then the esmini implementation also makes sense to me. Sometimes it's just difficult to see where the standard ends and the implementation begins :)

**Comment by eknabevcc** [comment]
I agree, it's always a balance what to do where. Sometimes convenience has to step aside for flexibility...  I admit esmini is not very consistent, some functions are high-level for convenience and some are lower and closer to the standard. 

I close the issue for now. Please re-open if needed. 👍
