### ISSUE TITLE
false parameter declarations?

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#182]
https://github.com/esmini/esmini/blob/52e6e0f9144fd9e87e887c59f86ffbeec11b2ad5/resources/xosc/Catalogs/Controllers/ControllerCatalog.xosc#L129

ECE ALKS driver model has only debug prints, all other parameters are fix

**Comment by eknabevcc** [comment]
Good finding, the parameters are clearly wrong, probably bad copy-paste. The one and only parameter should be Logging, what I understand. 
It should now be fixed by commit 2e624a3404afa1ff42308fef07813019acabdd70 and will be included in next release.
If you agree you can close the issue.
