### ISSUE TITLE
RelativeTargetLaneOffset does not consider the reference entity.

### ISSUE THREAD

**Issue by bleach31** [esmini/esmini#183]
I think that `RelativeTargetLaneOffset`  does not consider the reference entity.
I would like to have your comments on whether my usage is wrong, or, wrong interpretation of OSC, or a bug in Esmini.

**Detail**

Here's a simple scenario based on cut-in_sample.xosc

[cut-in_simple.xosc.txt](https://github.com/esmini/esmini/files/7480891/cut-in_simple.xosc.txt)

### initial position
* Ego(White)
  * Lane: -1
  * Lane offset(t): 0.00
* OverTaker(Red) 
  * Lane: 1
  * Lane offset(t): 0.03
![screen_shot_0_0](https://user-images.githubusercontent.com/5919566/140464571-d4f7b86a-02e3-4154-98c2-989e89a8379b.jpg)
![screen_shot_0_1](https://user-images.githubusercontent.com/5919566/140464578-f71cdd78-cb21-48ea-b4f0-11cf65ec6850.jpg)

Then, Overtaker acts below `RelativeTargetLaneOffset`
```xml
<PrivateAction>
   <LateralAction>
      <LaneOffsetAction continuous="false">
         <LaneOffsetActionDynamics maxLateralAcc="0" dynamicsShape="step" />
         <LaneOffsetTarget>
            <RelativeTargetLaneOffset value="0" entityRef="Ego" />
         </LaneOffsetTarget>
      </LaneOffsetAction>
   </LateralAction>
</PrivateAction>
```

### final position
In my expect, Overtaker should be 0 offsets and lane -1 same at ego

* Overtaker (Red) 
  * Lane: -1
  * Lane offset(t): 0.0

Or, Overtaker keeps his own lanes, But By offsetting the road width, the result is same.

* OverTaker(Red) 
  * Lane: 1
  * Lane offset(t):  ~~- 3.5~~ -3.07

But, Actually,  Overtaker is still in his own lane.
 OverTaker(Red) 
  * Lane: 1
  * Lane offset(t): 0.00

![screen_shot_0_2](https://user-images.githubusercontent.com/5919566/140464874-2049b488-ea9b-4a42-b872-25f564eba580.jpg)

**Comment by eknabevcc** [comment]
Many thanks for this report! The detailed explanation and scenario file is appreciated 👍
You certainly found a bug. Hopefully it's fixed by commit 8b9ad8fbf931ab5c8f4c4612b4f584954fcbc3eb.
Will be part of next release.
If and when possible, please test and report if it works as expected.

**Comment by bleach31** [comment]
thank you for your quick response!
I will test it on Monday.

**Comment by bleach31** [comment]
This worked as expected!
The Overtaker keeps his lane and is in the same t-position as the reference entity.
thank you again.

![screen_shot_0_0](https://user-images.githubusercontent.com/5919566/140693372-d5e8dc94-e8d1-429d-a26c-d5bbb9efafe6.jpg)
