### ISSUE TITLE
How does Esmini define the rear axle(reference point)?

### ISSUE THREAD

**Issue by bleach31** [esmini/esmini#185]
The OSC specifies that the rear axle is the reference point.

https://www.asam.net/index.php?eID=dumpFile&t=f&f=4092&token=d3b6a55e911b22179e3c0895fe2caae8f5492467#_coordinate_systems

How do I define the rear axle of car in Esmini?

I did some experiment about this.
### Experiment 1
*  Change `Center` of `BoundingBox` and `TeleportAction(x=0,y=-10)`. 
  ```xml
  <BoundingBox>
     <Center x="10" y="0.0" z="0.9" />
     <Dimensions width="2.0" length="5.0" height="1.8" />
  </BoundingBox>
  ```
*  Result: The vehicle's reference point (white dot) appears to be offset as per the change.
![image](https://user-images.githubusercontent.com/5919566/141730315-07988bf9-07b8-43c8-b4f4-faffdbe3e0df.png)

### Experiment 2
 Change `positionX` of `RearAxle ` and `TeleportAction(x=0,y=-10)`. 
  ```xml
<Axles>
   <FrontAxle maxSteering="30" wheelDiameter="0.8" trackWidth="1.68" positionX="2.98" positionZ="0.4" />
   <RearAxle maxSteering="30" wheelDiameter="0.8" trackWidth="1.68" positionX="1000" positionZ="0.4" />
</Axles>
  ```
* Result: It didn't change anything.

**My understanding**

In Esmini, the reference point(White dot) is defined by `Center`.
So, In order to comply with the OSC standard, we have to correctly defined that `Center` should be offset to the rear axle.

Is my understanding correct?
If I set the `Center`  incorrectly(like experiment1), will the behavior of Esmini be correct as per the OSC standard?

**Comment by eknabevcc** [comment]
Your understanding is correct. esmini does not take Axles/RearAxle element into account, yet. Instead reference point (for position and rotations) will be according to -BoundingBox/Center/x.
So to align with OpenSCENARIO the ref point should be defined as bounding box center offset from rear axle (typically along positive x-axis, if the rear axle is behind BB center).

Probably we'll at some point add handling of axles as well. At least if vehicle dynamics option is added. For curiosity, what is your use case where axles comes into play?

**Comment by bleach31** [comment]
Thanks for the quick response.

Another simulator use the center of gravity point as a reference point. So, I was looking for a way to get the same result in esmini.

I was convinced that I could easily achieve this by shifting BoundingBox/Center/x. thank you again.

> For curiosity, what is your use case where axles comes into play?

I am thinking of using to test sub-applications such as pre-crash brake, lane keeping assist, etc., rather than the entire ADA system. I think this needs to specify more rigorous test cases than what OSC was originally intended for.

I can't explain in detail here, but my colleague in germany will  provide feedback via ASAM!

**Comment by eknabevcc** [comment]
I see. Thanks for information. 
I also think axle definitions will be necessary eventually, e.g. to achieve more specific motion according to vehicle configuration and dynamics.
