### ISSUE TITLE
Set scenario parameters for initialization phase via C#

### ISSUE THREAD

**Issue by mpfist-no** [esmini/esmini#190]
Hello,

I would like to set scenario parameters that are used in the initialization phase (e.g. initial speed of the ego vehicle) using the C# wrapper.

I noticed that esmini supports setting a parameter declaration callback natively in C++ since version 2.17.0 (https://github.com/esmini/esmini/commit/bdda0f2df389ad175ffc4be490279ca988a1a01f). This addresses my exact use case. However, this function can not (yet?) be used using the C# wrapper.

Do you plan on adding this feature? And do you have an idea how I could circumvent this problem of setting initialization parameters?

Thank you for your help.

**Comment by eknabevcc** [comment]
Thanks for pointing out this gap. The callback API is now added by commit c85298e092145bc914cafa369335043e4ad372f6.

Please see example usage in [esminiLib/esminiUnityExample.cs](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Libraries/esminiLib/esminiUnityExample.cs).

**Comment by eknabevcc** [comment]
Part of [release](https://github.com/esmini/esmini/releases) 2.17.4

**Comment by mpfist-no** [comment]
Thank you very much for your quick response and implementation! I already tested the feature with release 2.17.4 and it works as expected.

**Comment by eknabevcc** [comment]
Good to hear! Closing the issue.

**Comment by vjjraman** [comment]
Hi, trying to use the python wrapper se.SE_SetParameterDouble(), it turns out it does update the parameter as observed by the se.SE_GetParameterDouble() method. But the parameter actually doesn't update as observed from the data logged. Just for more context, I'm trying to update the 'TargetSpeedFactor' Parameter. Am I missing something?
