### ISSUE TITLE
NotEqualTo' don't work when the data type is Interger.

### ISSUE THREAD

**Issue by jurriya** [esmini/esmini#191]
Some comparison operators dont't work when data type is not double.
Could you verify them. Thank you very muck.

![image](https://user-images.githubusercontent.com/53253020/143156533-fb85c8bf-0d85-41dc-9970-13f19a1fdd5e.png)

**Comment by eknabevcc** [comment]
Oops. Thanks for reporting this gap!

It should now be fixed by commit 228ac5ebdfee6ba095b848b104ed1a44b9ecdbf4. And will be part of next release. Let us know if you need a release immediately.

**Comment by jurriya** [comment]
Thank you for your reply, not urgent need the next realease。

**Comment by eknabevcc** [comment]
Included in [release](https://github.com/esmini/esmini/releases) 2.17.5 (and onward)
