### ISSUE TITLE
Access vehicle name using C#

### ISSUE THREAD

**Issue by mpfist-no** [esmini/esmini#193]
Hello,

is there a way to access the "name"-attribute of a vehicle in the scenario using the C# API? 
I would like to use this property to store the model (i.e., brand and exact model) and to be able to process this in C#.

Thanks again for your assistance.

**Comment by eknabevcc** [comment]
Good suggestion!
Let's call that property "type name", to distinguish from the ordinary object name and to make it applicable to pedestrians and misc objects as well. To the existing SE_GetObjectName() we now added (commit https://github.com/esmini/esmini/commit/3ceb4b34a05f0fcc2fd0cdb3f92691655fbcfdbf):
`SE_GetObjectTypeName()`
`SE_GetObjectModelFileName`

See example usage in C# script [esminiUnityExample.cs](https://github.com/esmini/esmini/blob/3ceb4b34a05f0fcc2fd0cdb3f92691655fbcfdbf/EnvironmentSimulator/Libraries/esminiLib/esminiUnityExample.cs#L148).

It will be included in next release. Let us know if urgent.

**Comment by mpfist-no** [comment]
The applicability to other scenario object types is great! Looking forward to the release.

**Comment by eknabevcc** [comment]
Release [2.18.1](https://github.com/esmini/esmini/releases/tag/2.18.1) available.
Please report if works as expected or not.

**Comment by mpfist-no** [comment]
Hi and a happy new year! 
I have finally tested the feature in version 2.18.2 and everything works as expected. Thanks for implementing that.
