### ISSUE TITLE
OpenScenario Trajectory Support

### ISSUE THREAD

**Issue by Vincentklw** [esmini/esmini#20]
As indicated in your [OSC Coverage](https://github.com/esmini/esmini/blob/master/osc_coverage.txt), Trajectories are not being supported currently. Are there any plans regarding a trajectory feature in the near future?

**Comment by eknabevcc** [comment]
Yes, it's in upper part of the backlog. Actually today's [commit ](ce24052cb5c00691593020e473bb9229659bfb0b)(major update to support OSC 1.0) includes some initial and limited Trajectory support. So far only PolyLine (not Clothoid and Nurbs yet). And very limited tests performed. 
If PolyLine based trajectory might be useful for your use case, please give it a try and report any problems.
There are some other priorities right now, and I can't make any commitments. But Clothoids and Nurbs is hopefully done within a month.
And, perhaps a longshot, but if you would like to implement something on your own, don't hesitate to post a pull request.

BTW, with support for 1.0 we cut ropes to 0.9.1. So if this means a problem for you, please consider to automatically update your scenarios. There are tools, e.g. Saxononica, that can do this based on the migration scheme migration0_9_1to1_0.xslt bundled with OpenSCENARIO 1.0 release.
