### ISSUE TITLE
maxLateralAcc is not respected in both domains scenario

### ISSUE THREAD

**Issue by DNMotoShiba** [esmini/esmini#201]
In scenarios that longitudinal and lateral domains occur simultaneously, the `maxLateralAcc` is not respected.

I'm using esmini v2.18.2.

[both-domains.xosc.txt](https://github.com/esmini/esmini/files/7767089/both-domains.xosc.txt)

In this scenario, the following will occur simultaneously
* Spoeed 10m/s@0sec -> 30m/s@7sec
* LanePosition 0m@0sec -> 5m @ maxLateralAcc="0.25"

Plotting Esmini's CSV, the Acc-Y exceeds 0.25 

![image](https://user-images.githubusercontent.com/23490530/147197757-d0b7e2c8-b21c-44f9-a0ab-5752717f2d18.png)

[log.csv](https://github.com/esmini/esmini/files/7767085/log.csv)

(FYI)
comment out SpeedAction the attached OSC, the `maxLateralAcc` is respected.
![image](https://user-images.githubusercontent.com/23490530/147197803-536b0b7a-b974-4ef1-b493-9ef0b2517bfe.png)

**Comment by eknabevcc** [comment]
Thanks for clear report. 
Good timing. The equations for action dynamics has been kind of ad-hoc. This report and some ongoing discussions regarding the equations inspired to some rework of the esmini action dynamics implementation altogether. Primary commit 18359d28df9573e8617f72e5590a8961f3330d8f but with b5101f438b51cebe735bdf9436e8060e5137a1e8 also vehicle performance specification is taking into account. These changes are now merged on master and will be part of next release.

Now running your scenario gives the following output, which I think looks more correct:
![acc_both](https://user-images.githubusercontent.com/29146839/147755553-3855f17a-b7d9-44f2-89f2-182596c7e1ec.png)
![acc_y](https://user-images.githubusercontent.com/29146839/147755560-3bd2b7a9-5ea2-4016-93e0-533577003baa.png)

Please test when possible and report back whether you get expected result or not.

**Comment by eknabevcc** [comment]
Included in release [2.19.0](https://github.com/esmini/esmini/releases/tag/v2.19.0).

**Comment by DNMotoShiba** [comment]
Thank you very much.
I tested with v2.19.1.
I got the results I expected.
It is excellent! 🙇

**Comment by eknabevcc** [comment]
Good to hear. Thanks for reporting back test result!
