### ISSUE TITLE
No top level esmini directory in "non-demo" releases

### ISSUE THREAD

**Issue by johschmitz** [esmini/esmini#204]
Would it be possible to add a top level directory "esmini/" in the non-demo release archives as it is good practice? Similar to the -demo release archives.
I often would like to download the smaller release whenever I don't need all the example files but it is a bit cumbersome to extract them..

See also definition of "tarbomb" as a reference:
http://www.linfo.org/tarbomb.html
https://en.wikipedia.org/wiki/Tar_(computing)#Tarbomb

**Comment by eknabevcc** [comment]
Excellent suggestion, thanks. 
Included in release [2.19.0](https://github.com/esmini/esmini/releases/tag/v2.19.0).

**Comment by johschmitz** [comment]
I am closing this since it is working fine now.
