### ISSUE TITLE
Support for AddEntityAction and DeleteEntityAction

### ISSUE THREAD

**Issue by jackokaiser** [esmini/esmini#208]
Hello,

Thanks for all the work put into esmini! 

I have a use case for entities which are only defined in a given time interval within an OpenSCENARIO act. The ASAM documentation mentions two EntityAction (AddEntityAction and DeleteEntityAction) which can be used for spawning and deleting entities on demand at runtime, although no example is provided in the documentation. 

Is there a plan to support these actions in esmini? I have tried teleporting the entities far away instead of a proper spawn/delete mechanism but this is not reliable.

Cheers,
Jacques

**Comment by eknabevcc** [comment]
Thanks for reminder! We almost forgot about those global actions.

Looking into it a few questions arises. What are the expectations in following cases:
1. The entity has a TeleportAction defined in Init section. And then, in a story maneuver, there is an AddEntityAction. Should it not be present from start of scenario?
2. Similar to above, but the entity is not referred to in Init section. There is a AddEntityAction later in a story. Still there is a TeleportAction defined in a story with trigger potentially prior to the AddEntityAction, e.g. simulationTime>=2. Should it be present in the scenario at start of scenario, at trigger of the TeleportAction, or not until added?
3. The storyboard has both AddEntityAction and DeleteEntityAction defined for the same entity, but with different triggers. It's not possible on beforehand to decide what will happen first. Should the entity be added automatically at start of scenario?
4. If the AddEntityAction is applied twice for the same entityRef. Should it add a clone or just ignore additional Add actions? If it adds a clone, how to treat DeleteEntityAction, should it remove all clones or just the latest?

I don't expect you to deliver all answers. I just wanted to put them down. I will think more about it and also try to discuss with OpenSCENARIO work group. Either I miss something obvious or there is a need for clarifications how it should work.

But for you, meanwhile, maybe you can have use of the [VisibilityAction](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.1.1_Model_Documentation/modelDocumentation/content/VisibilityAction.html), which I think should achieve similar result as Add/DeleteEntityAction. But I realize that esmini do not completely respect the settings. E.g. traffic="false" is not respected by controllers and sensors="false" will still put the entity into OSI stream. We have some homework to on that end. But at least the graphics="false" should be respected by both esmini and replayer.

Add: 
```
<PrivateAction>
    <VisibilityAction sensors="true" graphics="true" traffic="true" />
</PrivateAction>
```

Delete:
```
<PrivateAction>
    <VisibilityAction sensors="false" graphics="false" traffic="false" />
</PrivateAction>
```

There is an example scenario exercising the VisibilityAction: [cut-in_visibility.xosc](https://github.com/esmini/esmini/blob/master/resources/xosc/cut-in_visibility.xosc). You can launch it simply with [run/esmini-dyn/run_cut-in_visibility.bat](https://github.com/esmini/esmini/blob/master/run/esmini-dyn/run_cut-in_visibility.bat).

**Comment by jackokaiser** [comment]
Hi Emil, thanks for your reply!

These are excellent questions. I'm also wondering how these actions would work in practice; the documentation just mentions them and I wasn't able to find an example anywhere. I could provide opinionated answers, but as a modest OpenSCENARIO user it wouldn't be very valuable.

In the meantime the visibility trick will do the job, cheers!

**Comment by mschneider1711** [comment]
Hi, I would like to share my experience with this topic with you. Like the Author, I would like to add entities later on in an act instead of in the init. Right now as it is explained above I am using the VisibilityAction to add/remove vehicles from the scene for given timestamps. However, when the vehicles are removed from the scene so that they are not visible their behavior is not defined by me because I do not have any more position data for these vehicles. With that being said I am encountering multiple collisions detected by esmini. It would be very nice for this workaround that esmini does not use the global collision detection for vehicles that are removed from the scene with the VisibilityAction.

**Comment by eknabevcc** [comment]
Just in time. [v2.20.0](https://github.com/esmini/esmini/releases/tag/v2.20.0) just released which brings support for EnityActions. See [release notes](https://github.com/esmini/esmini/blob/master/release_notes.md#2022-01-19-version-2200) for some more info.

To run the example scenario ([Unittest/xosc/add_delete_entity.xosc](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Unittest/xosc/add_delete_entity.xosc)) go to folder `EnvironmentSimulator/Unittest/xosc` and run:
`../../../bin/esmini --window 60 60 800 400 --osc ./add_delete_entity.xosc`

Please test and play around with the feature and report any issues you encounter.

**Comment by mschneider1711** [comment]
I am encountering an error with my scenarios but with your scenario "add_delete_entity.xosc" as well .
The log.txt looks like this:

> esmini GIT REV: b8dc3c5
esmini GIT TAG: v2.20.0
esmini GIT BRANCH: tags/v2.20.0^0
esmini BUILD VERSION: 2.20.0.build.2110
Generated seed 3979447291
Loading add_delete_entities.xosc (v1.0)
OpenDRIVE: ../xodr/straight_500m.xodr
Scenegraph: ../models/straight_500m.osgb
Unsupported geo reference attr: +no_defs
Expr ${250/3.6} = 250/3.6 = 69.444443
Failed to find object Car1
Exception: Failed to find object: Car1

**Comment by jackokaiser** [comment]
I've pulled the v2.20.0 release, the example scenario works as expected on my side. Thanks for implementing the feature, and so quickly ;-)

**Comment by eknabevcc** [comment]
@jackokaiser Good to hear, thanks for quick feedback!

@mschneider1711 Hopefully it's just a path issue. The scenario is normally executed as part of unit test suite. If you grabbed the demo package the following should work:
1. Make a new folder under xosc, e.g: esmini-demo/resources/xosc/tmp
2. Put the scenario file in that tmp-folder.
3. Open a terminal in that folder, and run:
4. `../../../bin/esmini --window 60 60 800 400 --osc ./add_delete_entity.xosc`

Please report back if it still doesn't work, I would like to understand and solve.

**Comment by mschneider1711** [comment]
Yes, I somehow messed up the paths. Now it works. Thank you very much for the quick help provided. :)

**Comment by mschneider1711** [comment]
Hi,
it is not really an issue but deals with the usage of these two actions. It would be really nice for visualization reasons if the trajectory is removed from the scene after a vehicle is removed by the DeleteEntityAction. Right now the trajectory remains on the OpenDrive map. However, exactly this is done if you use the VisibilityAction and it would be nice to add this for the DeleteEntityAction as well.
Thank you as always for your amazing work!

**Comment by eknabevcc** [comment]
I agree that's how it should work. We'll have a look at it. 
I reopen the issue until fixed.

**Comment by eknabevcc** [comment]
Should be fixed by commit 8dd16d873b6de17d81ceb2afded70b69f24213e2.
Will be included in next release. 
When possible, please test and report how it works.
Keeping issue open until then.

**Comment by eknabevcc** [comment]
Forgot to mention, the fix is included in [releases](https://github.com/esmini/esmini/releases) from v2.20.5.

Please test and report whether it works as expected or not.

**Comment by mschneider1711** [comment]
Hi Emil,

I forgot to reply to this commit but I can tell you it works as expected and intended.

Thank you very much!

**Comment by eknabevcc** [comment]
Thanks for feedback. Good to hear! Closing the issue.
