### ISSUE TITLE
LaneOffsetAction with huge maxLateralAcc

### ISSUE THREAD

**Issue by bleach31** [esmini/esmini#213]
If given a huge maxLateralAcc, the LaneOffsetAction action will not reach the target value of the lateral position.
I'm using esmini v2.19.1.

I understand that giving a huge maxLateralAcc is a strange usage.
However, if possible, I'd like you to fix the Esmini so that reaches to the target value. 🙇 

sample code

```xml
<LateralAction>
   <LaneOffsetAction continuous="true">
      <LaneOffsetActionDynamics dynamicsShape="cubic" maxLateralAcc="10000" />
      <LaneOffsetTarget>
         <AbsoluteTargetLaneOffset value="-2" />
      </LaneOffsetTarget>
   </LaneOffsetAction>
</LateralAction>
```

## sample scenario

[laneOffsetAction.xosc.txt](https://github.com/esmini/esmini/files/7911465/laneOffsetAction.xosc.txt)

### simulation result (--fixed_timestep 0.01)

[maxLateralAcc=10000.csv](https://github.com/esmini/esmini/files/7911461/maxLateralAcc.10000.csv)
![image](https://user-images.githubusercontent.com/5919566/150491153-13bb526c-6d97-4901-b336-5abebe1f4fa0.png)

[maxLateralAcc=1000000.csv](https://github.com/esmini/esmini/files/7911462/maxLateralAcc.1000000.csv)
![image](https://user-images.githubusercontent.com/5919566/150492114-05b72407-a37b-4f92-ba62-5b44b25742d7.png)

**Comment by eknabevcc** [comment]
Thanks for reporting this issue! Yes, it's clearly a bug. There is no truncation of overshooting target value. Hopefully fixed now by commit b16b27920b85be53e5227d6eb31f2f341128bcbf.

Merged on master and will be included in next release. 

Please test when possible and report back how it works.

**Comment by bleach31** [comment]
Thank you so much. 

I've confirmed the correct behaviour in a locally built environment.

![image](https://user-images.githubusercontent.com/5919566/150708260-5210c669-d722-4874-8cd6-83df9289b0a4.png)

**Comment by eknabevcc** [comment]
Thanks for quick test & feedback 👍
