### ISSUE TITLE
Double road marks not shown

### ISSUE THREAD

**Issue by johschmitz** [esmini/esmini#215]
It seems esmini is having an issue with double roadmarks when using the "simple" definition. Here is an example that is not working:
[example.zip](https://github.com/esmini/esmini/files/7920533/example.zip)

I also noticed that the shortcuts <kbd>U</kbd>, <kbd>I</kbd>, <kbd>O</kbd>, <kbd>P</kbd> are not explained in the <kbd>H</kbd> help menu.

**Comment by johschmitz** [comment]
Showing the double line with the "default" distance of one line width between the two lines would be a sensible default in the case that no extra line information is supplied I believe.

**Comment by johschmitz** [comment]
While at it I also noticed that the color of the road mark is always displayed as `white` instead of the specified color. Maybe that could also be supported. Especially support for `yellow` is quite important but maybe all colors from the standard could be supported.

**Comment by eknabevcc** [comment]
Thanks for the report! Commit 5887baa08de6b1155352ef795187e5433a0b0240 adds support for:
- solid_solid
- broken_broken

as a starter. There are more types, e.g. broken_solid and solid_broken, but they require some more work and are still unsupported.

Regarding help menu ('H' = shift 'h'). In odrviewer and esmini u, i, o, p are mentioned. However, 'i' was missing in odrviewer. That was added in the same commit. What app (esmini or odrviewer) and version is u, i, o, p missing? (maybe it's an old version...)

Yes, definitely yellow should be supported 👍 (commit 63340df62b3c52df270197eda45930a93116af44). Lazy as we are, the rest of colors will fall into white category, until needed. 

These fixes are merged on master and will be included in next release.
Please test when possible and report if it works as expected or not.

**Comment by johschmitz** [comment]
I feel you! I received a pull request and it was similarly only for solid_solid because the rendering for the solid_broken is a bit tricky. So don't worry, you will probably arrive there first :-D

Support for `yellow` is highly appreciated! May I ask which RGB color you are using? I settled on (0.85, 0.63, 0.0) or (217, 161, 0) which I found somewhere on the internet. Did not find a perfect source so far.

Maybe it depends on the resolution of the esmini window if all shortcuts are visible in the help menu? I need to check that.

**Comment by johschmitz** [comment]
Found another little detail:
It should be possible to distinguish between `standard` and `bold` road mark weight in the visualization. Maybe just draw the line 2 pixels instead of 1 pixels or something like that.

**Comment by eknabevcc** [comment]
> I feel you! I received a pull request and it was similarly only for solid_solid because the rendering for the solid_broken is a bit tricky. So don't worry, you will probably arrive there first :-D
> 
> Support for `yellow` is highly appreciated! May I ask which RGB color you are using? I settled on (0.85, 0.63, 0.0) or (217, 161, 0) which I found somewhere on the Internet. Did not find a perfect source so far.
> 
> Maybe it depends on the resolution of the esmini window if all shortcuts are visible in the help menu? I need to check that.

Good question about color. I just tested, and settled for the second try which was 0.9f, 0.9f, 0.25f. Probably unrealistic, but esmini visualization is mostly for understanding and do not claim photo realism anyway. However, it's easy to change if you or someone else would prefer a different nuance. 

Thanks for reminding about the roadmark width. Weight was never used so far and width has been hardcoded to 15 cm. Now, by commit d17a472b7f57b839d321b56143833293c9b6c5e4 width should be applied if specified (optional), else the weight will end up in 15 cm (standard) or 20 cm (bold) for now - easy to change. 
Also the OSI lines ('u') are affected with double width for bold ones.

By the way: The esmini help is on key 'H' not 'h', and ends up in the console. Yes, I know it's confusing, but OSG features is by default on 'h' and I didn't want to change that, yet.

**Comment by johschmitz** [comment]
I was talking about the onscreen help menu. Are you talking about the command line help option? We were probably talking about different things.

What do you mean with 15 cm and 20 cm being the default, is that Swedish? We have 12 cm and 25 cm default in Germany (15/30 on Autobahn) as far as I can tell.

**Comment by eknabevcc** [comment]
If you press 'H' you will see the esmini help text in the console. If you press 'h' you see OSG (graphics system) help on screen. It's just different things. Additionally you can always find esmini launch and runtime features in the [readme.txt](https://github.com/esmini/esmini/blob/master/docs/readme.txt).

Regarding width. I just mean that IF you don't specify width esmini will now look at the weight and simply set 0.15 for standard and 0.2 for bold. Please note: This is not claimed to relate to any standard, just a simple default setting. If a specific with is needed then just set the width attribute (which now is not only parsed but also applied).

**Comment by johschmitz** [comment]
If we find out that European roadmarks are similar in that regard I would prefer to settle for those width and either make European highway or European normal roads the default. At least default bold should be 2x default standard width in my opinion.

**Comment by eknabevcc** [comment]
If you find such info, please let us know and we can align. 

Until then, I don't agree/think that bold should be double size. For the more schematic OSI lines I think that's perfectly OK (and that's how it's implemented right now), but not for the actual geometry. 

So, let's keep as is in esmini for now, and if you find more information on this we can change easily. 👍

**Comment by johschmitz** [comment]
I think we need to do the research work somewhat together since a lot of the literature about the road marking is in the native languages. If we could at least compare the German and Swedish standard that would already be good.
A starting point is the German Wikipedia page:
https://de.m.wikipedia.org/wiki/Stra%C3%9Fenmarkierung
Then in "Markierungszeichen" there is a table about the line width. "Schmalstrich" is equivalent to OpenDRIVE "standard" weight and "Breitstrich" is equivalent to OpenDRIVE "bold" weight.
There seems to also exist a Swedish version of the article but I was unable to find any information on the topic of line width. When OpenDRIVE was initially modeled that was apparently the reason behind the two specified weights.

The more official German literature is from FGSV Verlag.
There is a series of documents about this topic like these:
https://www.fgsv-verlag.de/raa-richtlinien-fur-die-anlage-von-autobahnen
https://www.fgsv-verlag.de/ral

You can also use this summary document and see page 29 (pdf page) for the line widths:
https://dsgs.de/data/CMM_Contents/files/Publikationen/Leitfaden-Fahrbahnmarkierung-DVR-DSGS-1.pdf

So I would say as long as we don't have any other conflicting information why not use that as a baseline? At least that would increase backwards compatibility with existing simulation engines.

**Comment by eknabevcc** [comment]
Thanks for this extensive document collection. Seems like great sources for anyone authoring OpenDRIVE files, at least German roads. Unfortunately I can't prioritize doing the research. But let's keep the issue open for some days in case someone else can compare with info for other countries. 

I think that OpenDRIVE concept is good. The designer/author of a road can specify in detail the exact line width using the <roadMark/type/line> element. Now even esmini is respecting <roadMark> width attribute. 
But if line width is not known or of no significance he/she can just make use of the simpler <roadMark> definition, perhaps even skipping the optional width attribute, falling back on just weight. In those cases I would assume that the exact width is of less importance. 

So I see no problem of keeping it as is until either we find out that there is a wide standardization of line width (covering multiple countries) or some other good reason...

**Comment by johschmitz** [comment]
A good reason for me would be to be able to overlay the 3D model supplied in the .osgb with the 3D model generated by esmini itself to check for consistency and 100% exact alignment. Right now I am always just roughly eyeballing. I don't think such a feature is available right now though? Until then this is a low priority issue for me at the moment.

**Comment by eknabevcc** [comment]
That's a good idea! esmini can save the generated model (launch flag `--save_generated_model`). And then it would be possible to check consistency by overlay inspection in osgviewer, especially in wireframe mode ('w').
Doing this with e6mini.xodr / osgb looks like this:

![image](https://user-images.githubusercontent.com/29146839/150941752-5d4efe8f-5934-4b75-b653-4dae0a24521a.png)

Same procedure for straight_500m, looks like this in wireframe:
![image](https://user-images.githubusercontent.com/29146839/150942462-096089c2-e38d-4a13-840c-f7208789ebea.png)

Here it's possible to see any lane marking differences. In this case it looks perfect, one being slightly elevated (along z).

With this I close the issue. Let's re-open or create another one when/if there is a high priority need. 👍
