### ISSUE TITLE
Unity rendering

### ISSUE THREAD

**Issue by jxzzhang** [esmini/esmini#219]
Hi, thanks for great work! This is not an issue but more of general questions. 

When using the esmini individually, if we do not provide osgb file, the player will still render the basic texture based on the information within the resource folder (e.g., asphalt.jpg). However, when I use the esmini shared library with Unity, if I do not specify an osgb file for the road, the popped-out esmini player window (outside Unity) will not show the texture and only displays lines as per opendrive file. Is this the expected behaviour? 

Additionally, is there any way we could share the textures rendered within esmini over to Unity? (like a live export of the rendered scene from esmini to an osgb file)

Sorry if the questions are too obvious or basic, I am just getting started with the Unity extension of esmini, thanks.

**Comment by eknabevcc** [comment]
Please find updated demo package [here](https://www.dropbox.com/s/sj53hz0zesxa681/esmini-player.unitypackage?dl=1).
It now includes the road textures.  It also includes a scenario, lane_change_creset, which make use of a road which was
1. generated by esmini 
2. converted to FBX
3. imported into Unity

Here's a brief guide about how to get osgb models into Unity, via FBX:
https://github.com/esmini/esmini/blob/master/docs/BuildOSG.md#on-osgb-and-unity

**Comment by jxzzhang** [comment]
> Please find updated demo package [here](https://www.dropbox.com/s/sj53hz0zesxa681/esmini-player.unitypackage?dl=1). It now includes the road textures. It also includes a scenario, lane_change_creset, which make use of a road which was
> 
> 1. generated by esmini
> 2. converted to FBX
> 3. imported into Unity
> 
> Here's a brief guide about how to get osgb models into Unity, via FBX: https://github.com/esmini/esmini/blob/master/docs/BuildOSG.md#on-osgb-and-unity

Thank you very much for the answer, I have a follow-up question regarding point 1 - getting the road texture generated by esmini. My understanding is that esmini can display the texture in two ways: 1) manually create and convert the it into osgb file which when written into .xosc file esmini can use it to display, 2) if the osgb path is not specificed in the .xosc file, esmini can display the road and objects written in .xodr file during runtime using their individual osgb file. Could you please comment on how we can get the generated scene in option 2 from esmini (as such complete osgb file does not exist as a whole, but rather the osgb files of some individual components exist such as poles, railing) ? Thank you again

**Comment by jxzzhang** [comment]
I might have found it, is it achieved by using the command '--save_generated_model'?

**Comment by eknabevcc** [comment]
Exactly! This flag should result in a file named "generated_road.osgb", in the folder esmini was launched from.

Please note that there are some limitations when converting the generated model, for example:

- Some texture formats not supported by the FBX conversion, e.g. .rgb[a]
- Road marks too close to road surface. Solution: In Unity, find the node and increase Z-value by 10 cm or so.

**Comment by jxzzhang** [comment]
> Exactly! This flag should result in a file named "generated_road.osgb", in the folder esmini was launched from.
> 
> Please note that there are some limitations when converting the generated model, for example:
> 
> * Some texture formats not supported by the FBX conversion, e.g. .rgb[a]
> * Road marks too close to road surface. Solution: In Unity, find the node and increase Z-value by 10 cm or so.

thank you very much Emil for your help, everything is very clear now. I will experiment a bit around this.
