### ISSUE TITLE
Using ActivateControllerAction leads to exit

### ISSUE THREAD

**Issue by arauschert** [esmini/esmini#22]
It seems the PrivateAction "Autonomous" still needs to be migrated to OSC 1.0, where it was renamed to "ActivateControllerAction". Using an ActivateControllerAction in the Storyboard leads to an error message "ActivateControllerAction not supported" and esmini exits.

In ScenarioEngine->ScenarioReader.cpp, line 1426

**Comment by eknabevcc** [comment]
Thanks for finding and pointing out! It was left out of migration by mistake. We'll fix that.

**Comment by arauschert** [comment]
Thank you and see you later in the OSC1.x Kick-Off!

Von: Emil Knabe <notifications@github.com>
Gesendet: Donnerstag, 25. Juni 2020 10:32
An: esmini/esmini <esmini@noreply.github.com>
Cc: Rauschert Andreas, EV-461 <Andreas.RB.Rauschert@bmw.de>; Author <author@noreply.github.com>
Betreff: Re: [esmini/esmini] Using ActivateControllerAction leads to exit (#22)


Thanks for finding and pointing out! It was left out of migration by mistake. We'll fix that.

**Comment by eknabevcc** [comment]
Now we fixed the specific issue with ActivateControllerAction (from commit [9839c86](https://github.com/esmini/esmini/commit/9839c8671e11db6b1b5d62b6cb30fb7a9e1cd602)). However I realize that there are unfortunately no further support for controllers in esmini yet, except for the default behavior for all entities to follow lane with current speed. 

We haven't had a use case for controllers yet. Would it be possible to share yours? At least give some hints regarding how you would use controllers?

Yes, see you soon at the 1.X kick off! :)

**Comment by arauschert** [comment]
Hi Emil,

great! Thanks!
I think the controllers are primarily meant to be used for driver requests to activate/deactivate the autonomous function of the car. At the moment in esmini the internal/external control parameter of the vehicle entity is used for that. Controllers have the advantage that they can be activated at any time during the scenario. Maybe it´s even necessary in a test to activate the autonomous function only after the driver (or the default controller in esmini) drove for a while.
Secondly, with controllers you can assign a different behavior to other cars/agents in the simulation, if the default controller is not sufficient for the test. Or you could assign a driver model to the ego vehicle.
I think since controllers mainly refer to other agents in the simulation, which are not standardized, a manual connection of the controller (actions) to a module in the simulation/agent/system under test is necessary. Therefore at the moment I don’t see how we could extend the OSC standard to support controller functionality. But for esmini maybe a second controller with more intelligence (drive on the right side, adjust speed to speed limits…) besides the default controller could be used and activated in an example to demonstrate how controllers should be used?

Best regards,
Andreas

Von: Emil Knabe <notifications@github.com>
Gesendet: Donnerstag, 25. Juni 2020 11:51
An: esmini/esmini <esmini@noreply.github.com>
Cc: Rauschert Andreas, EV-461 <Andreas.RB.Rauschert@bmw.de>; Author <author@noreply.github.com>
Betreff: Re: [esmini/esmini] Using ActivateControllerAction leads to exit (#22)


Now we fixed the specific issue with ActivateControllerAction (from commit 9839c86<https://github.com/esmini/esmini/commit/9839c8671e11db6b1b5d62b6cb30fb7a9e1cd602>). However I realize that there are unfortunately no further support for controllers in esmini yet, except for the default behavior for all entities to follow lane with current speed.

We haven't had a use case for controllers yet. Would it be possible to share yours? At least give some hints regarding how you would use controllers?

Yes, see you soon at the 1.X kick off! :)

**Comment by eknabevcc** [comment]
Thanks for sharing these thoughts and ideas! It totally makes sense to use controllers in that way - much more flexible than esmini current internal/external control (at any time, and any dimension - lat/long). And yes, it sounds like an excellent idea to introduce a simple driver model in esmini (perhaps just some noise or variation to lateral position and speed as a starter) to illustrate the concept and functionality of controllers. 
I will discuss this internally.

**Comment by arauschert** [comment]
Should we close this issue? The crash is fixed.

**Comment by eknabevcc** [comment]
No I think this represent an important discussion, and the resolution I think is the introduction of controllers in esmini (hopefully this or next week). So I think we can keep it for a while.

**Comment by eknabevcc** [comment]
esmini 2.0 has been released with an initial experimental implementation of controllers. It will probably evolve in near time, but at least we have something that replace the old external/internal/hybrid concept. And that can be used for external driver models.
Issue closed.
