### ISSUE TITLE
Vehicle Lane Initialization may be broken

### ISSUE THREAD

**Issue by antoniobruto** [esmini/esmini#222]
Hi Emil,
We're having issues with vehicle initialization. Not sure what's happened.

To summarize: the initial position of vehicles is not as expected. The initialization seems correct in v2.13.1, but seems broken in v2.15.1,v2.20.0 and v2.20.4. 
With absolute positions, and negative lane numbers, we see vehicles initialized in lanes one lane offset. For instance, if positions of <v1, v2> should be <-1,-2>, in simulation they are initialized on <0,-1>
With relative positions, they are initialized in incorrect lanes with a longitudinal separation. 
These scenario files work correctly (as intended) with v2.13.1. 

Any thoughts?

**Comment by eknabevcc** [comment]
Please provide an example scenario to simplify/speed up investigation on our side.

**Comment by eknabevcc** [comment]
"These scenario files" that you're referring to. Are those part of esmini examples, i.e. in esmini/resources/xosc?

We haven't seen this issue. Probably you have some interesting configuration (road network, actions) that triggers this error behavior. We'd really like to understand and fix the problem. But without more info it is really hard for us to analyze.

It would be appreciated if you could, as a minimum, paste a snippet of just the TeleportAction (I assume that's what goes wrong). I mean something like this:
```xml
<TeleportAction>
    <Position>
        <LanePosition roadId="0" laneId="-3" offset="0.3" s="50.0"/>
    </Position>
</TeleportAction>
```
and of course if you can provide the OpenDRIVE as well it would be great. But we can start checking with e6mini.xodr, which should be pretty standard highway configuration.

**Comment by eknabevcc** [comment]
I run some tests initializing a vehicle at some different (absolute) WorldPositions, and inspecting what lane it ended up "connecting" to. Here's a few results:

y=-13
![image](https://user-images.githubusercontent.com/29146839/153708867-49586c5a-0a36-4b02-8467-eede81825c47.png)

y=-10
![image](https://user-images.githubusercontent.com/29146839/153708891-afa6ef32-ab20-4138-8607-fd44b5ee0688.png)

y=-9
![image](https://user-images.githubusercontent.com/29146839/153708941-6104ce0c-6a02-4b11-b0c9-e2fffa5f8456.png)

To me it look correct. Perhaps the strange behavior in your use case was a result of some issue in the input data (e.g. OpenDRIVE or .xosc file). 

Not being able to reproduce the issue I now close the issue. If problem remains, please add more info and we'll re-open.
