### ISSUE TITLE
RelativeLane(Road)Position's orientation's relative option

### ISSUE THREAD

**Issue by t-nishi-24** [esmini/esmini#223]
Hello!    
If I performed the action changing angle of 90deg (1.57rad) four times, as shown in the example, I expected the action to be 90deg→180deg→270deg→360deg (=0deg)  
My understanding is correct?    

**example**  
```xml
<TeleportAction>
    <Position>
        <RelativeLanePosition entityRef="ID2" ds="0.0" offset="0.0" dLane="0">
            <Orientation h="1.57" type="relative" />
        </RelativeLanePosition>
    </Position>
</TeleportAction>
```
![image](https://user-images.githubusercontent.com/91576582/151903026-a83827a4-18fd-4732-921a-f5b1ddf8b636.png)  

## If correct 
[sample_xosc.zip](https://github.com/esmini/esmini/files/7975404/sample_xosc.zip)  

I created a sample scenario and tried it out, but only the first time it expanded in the 90deg direction, and nothing happened after the second time.      

I've seen it described like this.  
So, I also tried `RelativeRoadPosition`, but it still didn't work.   

![image](https://user-images.githubusercontent.com/91576582/151903461-1ae07005-ef2f-4925-85ab-f701acb5d845.png)
https://github.com/esmini/esmini/blob/master/osc_coverage.txt#L7

## If not correct
I'd like to know how it behaves when `orientation` is set to `relative`.

**Comment by eknabevcc** [comment]
For RelativeRoadPosition and RelativeLanePosition the relative orientation will refer to the road (see orientation annotation [here](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.1.1_Model_Documentation/modelDocumentation/content/RelativeRoadPosition.html)), not refered entity. So that's why you always get the same angle (pi/2), because it's 90 degree to the road direction. 

For comparison you could change the position type into [RelativeObjectPosition](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.1.1_Model_Documentation/modelDocumentation/content/RelativeObjectPosition.html). It will rotate additional pi/2 each time, refering to the orientation of itself.

Please see and try this modified variant of your scenario:
[sample-mod_xosc.zip](https://github.com/esmini/esmini/files/7979778/sample-mod_xosc.zip)

**Comment by t-nishi-24** [comment]
Thanks for the comment and the fix on the sample scenario!    
In this case, it turns out that I should use `RelativeObjectPosition`.  

Just for reference, are you saying that I can get the same results whether I set `RelativeRoadPosition` or `RelativeLanePosition` `Orientation` to` relative` or `absolute`?  
The same goes for referencing itself with `RelativeObjectPosition`?

**Comment by eknabevcc** [comment]
First to avoid confusion. The CoordinateSystem you're referring to in the [osc_coverage.txt](https://github.com/esmini/esmini/blob/master/osc_coverage.txt) this one: https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.1.1_Model_Documentation/modelDocumentation/content/CoordinateSystem.html
which is used in some other conditions and actions.

Then regarding relative/absolute orientation. The relative orientation will have different context depending on Position type. 

In these cases (RelativeRoadPosition and RelativeLanePosition) it's refering to the road. So for example, if the road has heading 0.5 and the relative heading is 0.2 the result will be 0.7 rad.
But if you set absolute, then the heading will be 0.2 independent of road direction.

If you for example use [RelativeWorldPosition](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.1.1_Model_Documentation/modelDocumentation/content/RelativeWorldPosition.html) or RelativeObjectPosition, then the relative heading will be added with the heading of the referenced object, which actually can be itself.

I hope it's a bit clearer, and not more confusing :) This is more about OpenSCENARIO. But it's not always clear how to interpret, so these are good questions.

**Comment by eknabevcc** [comment]
Release [v2.20.5](https://github.com/esmini/esmini/releases/tag/v2.20.5) available

**Comment by eknabevcc** [comment]
Sorry, previous comment was intended for another issue. Please ignore.

**Comment by t-nishi-24** [comment]
**My points that were not good**  
Because the OpenDRIVE file I was testing was a simple straight road, the relative/absolute behavior appeared to be the same.  

@eknabevcc   
Testing with other OpenDrive files has given me a complete understanding of relative/absolute orientation.  
Thank you for your detailed explanation.
