### ISSUE TITLE
Pedestrian's performance is limited

### ISSUE THREAD

**Issue by t-nishi-24** [esmini/esmini#224]
Hello!  
In OpenScenario, Performance cannot be specified for pedestrians.  

https://www.asam.net/static_downloads/modelDocumentation/content/Pedestrian.html  

![image](https://user-images.githubusercontent.com/91576582/152082330-95b485f8-0f4d-40ba-997d-7a8b291828ec.png)  

But in Esmini, it is set as follows.  

https://github.com/esmini/esmini/blob/b8dc3c50c2a10f4412423064fcfdf388d537338e/EnvironmentSimulator/Modules/ScenarioEngine/SourceFiles/Entities.hpp#L416  

![image](https://user-images.githubusercontent.com/91576582/152082405-93975388-7262-4f6f-b4ba-1236d60289a9.png)  

**Question**  
Why is 10.0 set for pedestrian performance in Esmini?  
Is it possible to remove this limitation or set it to such a huge number that it will not have any impact?

**Comment by eknabevcc** [comment]
Release [v2.20.5](https://github.com/esmini/esmini/releases/tag/v2.20.5) available

**Comment by t-nishi-24** [comment]
Thanks for the quick fix!  
I have checked with v2.20.5.  
So, I close this issue.
