### ISSUE TITLE
Should the orientation of RelativeRoadPosition be affected by the direction of the lane?

### ISSUE THREAD

**Issue by bleach31** [esmini/esmini#228]
I’ｍ trying an action to change only the orientation(with angle along the road) of the vehicle, as follows
```xml
 <TeleportAction>
    <Position>
       <RelativeRoadPosition entityRef="Ego" ds="0.0" dt="0.0">
          <Orientation h="1.57" type="relative" />
       </RelativeRoadPosition>
    </Position>
 </TeleportAction>
```
and also, I used `RelativeRoadPosition` instead of `RelativeLanePosition` because I didn't want to vehicle be affected  by the direction of the lane which the car belongs to.

However, the orientation of `RelativeRoadPosition` was affected by the direction of the lane which the car belongs to.
(you can see the sample at bottom)

In my understanding of ODR Spec, The Road has a start and end point but no both direction definition(only the lane changes direction on either side of the reference road)

**sample**

[orientation_road.xosc.txt](https://github.com/esmini/esmini/files/8021138/orientation_road.xosc.txt)

sample:　After the two initial positions, `RelativeRoadPosition(h=1.57)` is executed

**case1** Initial pos : `<LanePosition roadId="1" laneId="-1" offset="0" s="100" />`
![image](https://user-images.githubusercontent.com/5919566/152925368-fcd2983e-3674-4d4f-b502-bb1922e78f01.png)

**case2** IInitial pos : `<LanePosition roadId="1" laneId="1" offset="0" s="100" />`
![image](https://user-images.githubusercontent.com/5919566/152925483-373ceb04-cf54-4ed6-b9e8-83342e3de786.png)

**Comment by bleach31** [comment]
Thank you for your kindness comment.

Also thank you very much for the suggestions.
However, they do not work for my use case. :cry: 

* We cannot predict in advance the position where the orientation change event will occur (it will be determined during the simulation)
  *  Especially as trajectory actions need to be used, So vehicles be re-belonged to the nearest lane after trajectory actions have finished. If it finished in the opposite lane, the direction would be the opposite.
* I want to specify the orientation along the road, like a crosswalker, but, the road on which this orientation change event occurs may be a curve, clothoid, etc.
  * If using absolute orientation, the orientation is not what is expected.

**Comment by eknabevcc** [comment]
We've been looking into this. Conclusion is that you're right. According to the standards (osc, odr) lane direction should not affect orientation in RelativeRoadPosition. Actually neither in RelativeLanePosition. 

For most use cases it has been convenient to base relative heading on driving direction, which is the reason for current behavior in esmini.

However, in the strive to harmonize with the standards we have now changed interpretation for the RelativeRoadPosition. Orientation will be based only on road s and t coordinate system. 

Note: For now the RelativeLanePosition behavior will remain, relating to the driving direction. But that will also be updated as soon as 1. Lane coordinate system has been fully implemented and 2. another mechanism is established to find out the driving direction is available (e.g. something like OrientationCondition).

It would be appreciated if you could try out branch https://github.com/esmini/esmini/tree/fix_relative_road_pos
Would that be possible or do you need a release?

**Comment by bleach31** [comment]
Thank you so much for looking into this in deep.

> We've been looking into this. Conclusion is that you're right. According to the standards (osc, odr) lane direction should not affect orientation in RelativeRoadPosition. Actually neither in RelativeLanePosition.

I am very sorry, but please let me confirm the meaning of the this English sentence.

Are you meaning that not only `RelativeRoadPosition` but also `RelativeLanePosition` should not be affected by the lane direction?

And,  I'm confusing driving direction with lane direction.


Is my understanding correct?
* Orientation of `RelativeRoadPosition` :  not affected by lane direction which the vehicle belongs, not affected driving direction of vehicle.
* Orientation of  `RelativeLanePosition`:  affected by lane direction which the vehicle belongs, not affected driving direction of vehicle..

Anyway, https://github.com/esmini/esmini/tree/fix_relative_road_pos was excellent. The sample scenario changed direction as expected.

Thank you again.

**Comment by eknabevcc** [comment]
Your understanding is correct. But to clarify what we mean with driving direction of the lane: The direction in which the traffic normally moves given:
1. The sign of lane ID (minus to the right of s, and positive to the left)
2. The value of the OpenDRIVE road rule attribute (right hand or left hand traffic)

**Comment by bleach31** [comment]
Thank you

I thought it meant that the vehicles were going forward or backward. This was a mistake.

I now understand what the driving direction of the lane means.

**Comment by eknabevcc** [comment]
Thanks for quick test and feedback.
The change is now merged on master and will be included in next release.
