### ISSUE TITLE
OSI file much larger on the second record

### ISSUE THREAD

**Issue by cfschaller** [esmini/esmini#229]
Hi Emil,

hoping that I am not using the API incorrectly, I am back to report another issue related to OSI.
Using the same workflow as in issue #212 (i.e. SE_Init, SE_EnableOSIFile, loop with SE_UpdateGroundTruth/SE_StepDT, SE_DisableOSIFile, SE_Close), I do observe the following:
The OSI file is much larger (e.g. 269 MB instead of 1 MB) when I try to record the same scenario twice without closing the software inbetween. This is independent of the underlying scenario. The third (and all further) attempts will have the same size as the second one (e.g. 269 MB). 

I tried adding SE_ClearOSIGroundTruth before/after SE_Close but that did not change anything.

**Comment by eknabevcc** [comment]
Thanks for this report. It's clearly a bug that we haven't come across. 👍
A fix is included in release [v2.20.6](https://github.com/esmini/esmini/releases/tag/v2.20.6).
Please test and report how it works.

**Comment by cfschaller** [comment]
And last but not least, this one is resolved, too! Thanks!

**Comment by eknabevcc** [comment]
Thanks a lot for testing the fixes and providing feedback! 👍
