### ISSUE TITLE
Evaluation cycle of Condtion with delay in 2.20.6 

### ISSUE THREAD

**Issue by bleach31** [esmini/esmini#237]
The evaluation cycle for conditions with delay in 2.20.6 is dependent on the delay time.
Because of this, the trigger does not become active at the correct time.

**Sample**

This is a sample scenario of approaching a stopped target, and stop, and finally re-start again.

following  two conditions with delays must be satisfied in order to restart.
```xml
<StartTrigger>
   <ConditionGroup>
      <Condition name="DealyCond1" delay="5" conditionEdge="none">
         <ByEntityCondition>
            <TriggeringEntities triggeringEntitiesRule="all">
               <EntityRef entityRef="Ego" />
            </TriggeringEntities>
            <EntityCondition>
               <SpeedCondition value="1" rule="lessOrEqual" />
            </EntityCondition>
         </ByEntityCondition>
      </Condition>
      <Condition name="DealyCond2" delay="5" conditionEdge="none">
         <ByEntityCondition>
            <TriggeringEntities triggeringEntitiesRule="all">
               <EntityRef entityRef="Ego" />
            </TriggeringEntities>
            <EntityCondition>
               <RelativeDistanceCondition value="30.1" freespace="false" entityRef="Target" rule="lessOrEqual" relativeDistanceType="longitudinal" coordinateSystem="entity" />
            </EntityCondition>
         </ByEntityCondition>
      </Condition>
   </ConditionGroup>
</StartTrigger>
```
[delay-eval-timing.xosc.txt](https://github.com/esmini/esmini/files/8066423/delay-eval-timing.xosc.txt)

in 2.20.5,　two conditions are satisfied at 17.550sec , the vehicle will be restarted ( --fixed_timestep 0.01)

```ruby
11.270: DealyCond1 timer 5.00s started
12.550: DealyCond2 timer 5.00s started
14.000: Event1 complete after 1 execution
14.010: stop runningState -> endTransition -> completeState
14.010: Event1 runningState -> endTransition -> completeState
16.270: DealyCond1 timer expired at 5.00 seconds
17.550: DealyCond2 timer expired at 5.00 seconds
17.550: Trigger /------------------------------------------------
17.550: DealyCond1 == true, speed: 0.00 <= 1.00, edge: none
17.550: Triggering entity 0: Ego
17.550: DealyCond2 == true, rel_dist: 30.10 <= 30.10, edge: none
17.550: Triggering entity 0: Ego
17.550: Trigger  ------------------------------------------------/
17.550: reStart standbyState -> startTransition -> runningState
17.550: Trigger /------------------------------------------------
```
[log_2.20.5.txt](https://github.com/esmini/esmini/files/8066422/log_2.20.5.txt)

in 2.20.6, Every 5 seconds, which is the delay time, the timers will evaluate each other and the trigger will never be activated
```ruby
11.270: DealyCond1 timer 5.00s started
12.550: DealyCond2 timer 5.00s started
14.000: Event1 complete after 1 execution
14.010: stop runningState -> endTransition -> completeState
14.010: Event1 runningState -> endTransition -> completeState
16.270: DealyCond1 timer expired at 5.00 seconds
16.280: DealyCond1 timer 5.00s started
17.550: DealyCond2 timer expired at 5.00 seconds
17.560: DealyCond2 timer 5.00s started
21.280: DealyCond1 timer expired at 5.00 seconds
21.290: DealyCond1 timer 5.00s started
22.560: DealyCond2 timer expired at 5.00 seconds
22.570: DealyCond2 timer 5.00s started
26.290: DealyCond1 timer expired at 5.00 seconds
26.300: DealyCond1 timer 5.00s started
27.570: DealyCond2 timer expired at 5.00 seconds
27.580: DealyCond2 timer 5.00s started
```
[log_2.20.6.txt](https://github.com/esmini/esmini/files/8066424/log_2.20.6.txt)

I think esmini now supports re-evaluation of conditions with delays in this 2.20.6.
This is  (2) in [this picture](https://github.com/esmini/esmini/issues/202#issuecomment-1003723641
) I said.  This is very much appreciated.
However, I think that the evaluation cycle should not depend on the delay time, but should be evaluated at each simulator step.

**Comment by bleach31** [comment]
Thank you, I found your commit!
I tested it.

It now works as before, as shown below.

The only difference are Esmini version and the last condition is more correctly ">" evaluated.

![image](https://user-images.githubusercontent.com/5919566/154233158-4bcd09d0-bb10-49d9-a3fd-009266d72e22.png)

Thank you for your quick response.

**Comment by eknabevcc** [comment]
Excellent! Thanks for the confirmation, and for the quick finding and report of the bug!
