### ISSUE TITLE
FollowTrajectory

### ISSUE THREAD

**Issue by ReiDa8684** [esmini/esmini#24]
I have seen in [osc_coverage](https://github.com/esmini/esmini/blob/master/osc_coverage.txt) that recently activities started concerning Trajectories. I am very exited about this, because the missing "FollowTrajectory" feature is the main reason why I am not using esmini more often.
Is this "FollowTrajectory" functionality already on the internal roadmap or are there other reasons for activities concerning Trajectories?

If the FollowTrajectory functionality will be implemented, I would like to ask not to use some kind of "internal path following control", which always leads to deviations from the desired path. If possible, it would be of huge benefit to directly move the vehicles along the desired trajectory.

Thank you for this excellent tool!

**Comment by eknabevcc** [comment]
That's correct. We added some initial trajectory support a while ago. Then a lot of other stuff came in between (like OSI support), so there is still no full support yet.
However, basic trajectories with vertex type PolyLine hopefully work. I just added a very [simple example](https://github.com/esmini/esmini/blob/master/resources/xosc/trajectory_test.xosc) that you can check out and experiment with - to see if current Trajectory-support cover your needs.
And by the way, assigning a trajectory to a vehicle, it should follow the trajectory without deviation, however crazy the trajectory may be.
Please feed back any issues you find. Thanks!

**Comment by ReiDa8684** [comment]
Thank you so much for the quick respond and the very helpful example! I was playing around for 2 hours now and it looks perfect!

**Comment by eknabevcc** [comment]
Thanks for feedback, glad to hear it worked for you!
