### ISSUE TITLE
Opendrive version support

### ISSUE THREAD

**Issue by yumianhuli2** [esmini/esmini#241]
Hi! 
What is the version of Opendrive currently supported by Esmini? 1.5 1.6 Is it supported?
Thank U!

**Comment by eknabevcc** [comment]
It's mostly based on 1.5.
And just a subset, the coverage is far from complete.

But we added one highlight from 1.7: Virtual Junctions which we found useful. 
Our approach is to add stuff on need basis.

Thanks for asking. I realized that the [odr_coverage](https://github.com/esmini/esmini/blob/master/odr_coverage.txt) was not updated. It is now.
