### ISSUE TITLE
Speed Extraction Python

### ISSUE THREAD

**Issue by florianhuber99** [esmini/esmini#242]
Hi,

it seems that there is a problem with speed extraction in python.

for i in ( i for i in range(1000) if not se.SE_GetQuitFlag()):
____for j in range(se.SE_GetNumberOfObjects()):
________se.SE_GetObjectState(j, ctypes.byref(obj_state))
________ file.write('{:.2f},{},{:.2f},{:.2f},{:.2f}\n'.format(obj_state.timestamp, j, obj_state.x, obj_state.y, obj_state.speed))
____se.SE_Step()

When I run the python program and try to extract speed values, these are too high by far respectively should be 0 but are not.

When I run the same OpenScenario with the C program I get these values:
0.01,0,28004.8281,45446.6875,3.30
0.01,1,28013.3789,45427.5156,0.00
0.01,2,28004.0527,45430.0664,-0.00
0.01,3,28020.6738,45435.5820,5.46
0.02,0,28004.8535,45446.6680,3.30
0.02,1,28013.3789,45427.5156,0.00
0.02,2,28004.0527,45430.0664,-0.00
0.02,3,28020.6602,45435.5859,5.46
...

If I run the same OpenScenario with the Python program I get these values:
0.00,0,28004.80,45446.71,41.84
0.00,1,28013.38,45427.52,6.24
0.00,2,28004.05,45430.07,29.19
0.00,3,28020.69,45435.58,3.97
0.01,0,28004.83,45446.69,41.88
0.01,1,28013.38,45427.52,6.24
0.01,2,28004.05,45430.07,29.19
0.01,3,28020.67,45435.58,3.98
...

As you can see the x and y coordinates are correct but the speed is completly wrong.

In the Simulation the speed is correctly but the extracted values are wrong.
Do you already know about this defect?

Thank you very much in advance.

Florian

**Comment by eknabevcc** [comment]
Thanks for reporting this flaw. The root cause is probably (hopefully) an outdated struct. So values doesn't match the struct fetched from esmini.
See updated [example](https://github.com/esmini/esmini/tree/master/Hello-World_coding-example#example-get-object-states).
Please test and report result.

**Comment by florianhuber99** [comment]
Yes, now it also extracts the correct speed values with the Python program.

Thank you very much for the quick help.
