### ISSUE TITLE
Get collision state via DLL API

### ISSUE THREAD

**Issue by Violin9906** [esmini/esmini#243]
Hello,
It seems that the only function about collision detection in `esminiLib.hpp` is `void SE_CollisionDetection(bool)`. Can you add a function to get current collision state?e.g. return a vector which contains all collision entity ID pairs.
Thanks!

**Comment by eknabevcc** [comment]
Good idea.
Implemented by commit 896caffeefd3e66c9f3b125b59e9f8833c6ae5a3. I did it in a more basic way, following pattern of other similar functions. (Main reason for this pattern is to stick with C basic types for the portable shared library interface)

Here's the API in the header file: https://github.com/esmini/esmini/blob/896caffeefd3e66c9f3b125b59e9f8833c6ae5a3/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L714

And here's a minimalistic code example:

```c++
#include "esminiLib.hpp"
#include "stdio.h"

int main(int argc, char* argv[])
{
	SE_Init("../../../../EnvironmentSimulator/Unittest/xosc/test-collision-detection.xosc", 1, 1, 0, 0);
	SE_CollisionDetection(true);

	for (int i = 0; i < 500; i++)
	{
		SE_Step();

		for (int j = 0; j < SE_GetNumberOfObjects(); j++)
		{
			for (int k = 0; k < SE_GetObjectNumberOfCollisions(j); k++)
			{
				printf("Collision[%d]: %d\n", j, SE_GetObjectCollision(j, k));
			}
		}
	}

	return 0;
}
```

It's merged on master and will be included in next release. Let us know if you need a release asap.

**Comment by eknabevcc** [comment]
Included in [releases from v2.20.9](https://github.com/esmini/esmini/releases)
Please test and report if it works as expected.

**Comment by Violin9906** [comment]
Great! It works well for me. By the way, are there any method to be informed when a car hit any road objects (railing, etc.)?

**Comment by eknabevcc** [comment]
Thanks for feedback from test on your side.

Regarding road object collision detection: Unfortunately there is no such function implemented or even planned for yet. 
But I can imagine it will eventually. So I close this issue now, but I'll try to remember to update it if and when such feature is added.
