### ISSUE TITLE
Using absolute paths in xosc

### ISSUE THREAD

**Issue by GraLu1992** [esmini/esmini#25]
I am using the esmini demo version and I am starting esmini from another program. Therefore it is necessary to use absolute paths in the xosc-file, e.g., for VehicleCatalog or RoadNetwork. In a demo scenario I  just tried to replace the relative paths to absolute paths and it does not work

Original:
`<RoadNetwork>`
		`<Logics filepath="../xodr/straight_500m.xodr" />`
		`    <SceneGraph filepath="../models/straight_500m.osgb" />`
	`</RoadNetwork>`

Modified:
`	<RoadNetwork>`
		`<Logics filepath="D:\esmini\esmini-demo\resources\xodr\straight_500m.xodr" />`
		`<SceneGraph filepath="D:\esmini\esmini-demo\resources\models\straight_500m.osgb" />`
	`</RoadNetwork>`

The error message in console is 

`RoadManager.cpp / 1286 / roadmanager::OpenDrive::LoadOpenDriveFile(): Failed to load ../../resources/xosc/./D:\esmini\esmini-demo\resources\xodr\straight_500m.xodr - looking for file straight_500m.xodr in current folder`

Is there a way to use absolute paths in the xosc-file?

**Comment by eknabe** [comment]
Thanks for input. You're absolutely right, esmini should support absolute paths as well. Support added in commit [c052e5c](https://github.com/esmini/esmini/commit/c052e5cff37c47985fa8b135f4a42e011a7c4195). 
Please download the [latest release, v1.6.1](https://github.com/esmini/esmini/releases/latest) and give it a try.

**Comment by GraLu1992** [comment]
Thank you very much, that was fast. Esmini now perfectly works with absolute paths, which helps me a lot!

**Comment by eknabevcc** [comment]
Thanks for feedback. Good to hear that it works as expected.
