### ISSUE TITLE
Problem with RelativeRoadPosition

### ISSUE THREAD

**Issue by johschmitz** [esmini/esmini#253]
I am having some trouble with RelativeRoadPosition which I use for to initialize the vehicle positions. Depending on the heading of the road/vehicle it will work differently.
Attached are two examples.
I am trying to position the vehicles in s direction at the start of the road. And then let them drive along the road. Is this maybe a new bug or a change in behavior of esmini or did I just never discover this problem and have a bug on my end?

[examples.zip](https://github.com/esmini/esmini/files/8240012/examples.zip)

**Comment by eknabevcc** [comment]
What you see is most probably an effect of a recent change of the RelativeRoad behavior. Please see details in issue #228.
In brief:

- RelativeLane will consider lane driving direction
- RelativeRoad will consider road construction direction

I understand that this is not perfect and may be confusing. But there was a few use cases that was not possible until we introduced this new behavior of RelativeRoad. 

To conclude, in this case I think the RelativeLane variant is fitting the need perfectly. Please test modified scenarios:
[examples-mod.zip](https://github.com/esmini/esmini/files/8250889/examples-mod.zip)

**Comment by johschmitz** [comment]
What exactly do you mean with "will consider road construction direction"?
I found this:
"we have now changed interpretation for the RelativeRoadPosition. Orientation will be based only on road s and t coordinate system."
But that doesn't seem to be working. In both examples that I posted above I am trying to drive along the road in s direction (or am I not?) but in one case the vehicle just turns around. That can't be right in my eyes according to the definition. If I am understanding this wrong please explain a bit more where my mathematical error lies.

**Comment by eknabevcc** [comment]
Indeed you're right. When I tested same relative road heading for various road (with different heading) it sure does not work as expected:
 
![bad-rel-heading](https://user-images.githubusercontent.com/29146839/158760003-d7cfd509-cab8-4e9b-ba68-a251f4eeddd3.png)

I found the bug, and hopefully fixed it by commit ef6fd706bcba65fdfea83e8c7da1d45ef7e88dc3.
Also added a simple test (seen in images) based on scenario file [four_roads.xosc](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Unittest/xosc/four_roads.xosc)/[straight_20m.xodr](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Unittest/xodr/straight_20m.xodr) to prevent regression.

Now it looks better:
![good-rel-heading](https://user-images.githubusercontent.com/29146839/158761969-209cfdfd-0eb7-4633-b8d8-83b51acdd50d.png)

I tested the fix with your two examples, which now seem to work. Still it would be appreciated if you could test as well to confirm improved behavior.

Thanks for reporting and follow up on this issue!

**Comment by johschmitz** [comment]
Cool, thank you. You mean testing with the new release right? Will definitely do and tell if I find another problem 😊

**Comment by eknabevcc** [comment]
Ah, it's merged on master but not released yet. I'll let you know when next release is done.

**Comment by johschmitz** [comment]
So far I don't compile esmini myself on my personal computer. Could do if that helps but since releases are so frequent I did not see a big need for that so far. That is until I want to make a contribution.. I wonder if it is possible to manually trigger a GitHub action for a certain branch and upload the resulting tarball/zip into this issue instead of the release page. Then you could just trigger the build with a single click and I could just download and test the result super easily. Also the release page would stay clean.

**Comment by eknabevcc** [comment]
Actually we have such a hook. By adding "#store_bins" to the commit comment the CI will pick and store binary packages (not complete demo though). Just for cases like this :)
I could have done it from start, but I did it now anyway (another commit with modified message).

You can find the binaries [here](https://ci.appveyor.com/project/esmini/esmini/builds/42928199). 
Click on relevant job (matching your system), then you find the bin package under tab "Artifacts".

I'll try to remember to write here anyway when we have a proper release.

**Comment by johschmitz** [comment]
I have build another example for the test:
[example.zip](https://github.com/esmini/esmini/files/8309243/example.zip)
I works for the cars going from the center outwards but it does not seem to work correctly for the cars going towards the center. Maybe another little bug?

**Comment by johschmitz** [comment]
@eknabevcc I am still not sure how to solve my issue around this. OpenSCENARIO says that the lane ID is mandatory within RelativeLanePosition so I can not use it without knowing the lane ID which in my current implementation I don't know. 
https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.1.1_Model_Documentation/modelDocumentation/content/RelativeLanePosition.html
I just want to place a vehicle in the right driving direction and let it drive. Such a simple use-case should be possible before implementing more complicated stuff.
So I am not sure if your "good" example from above is valid. It can also not be generated using the scenariogeneration lib without the lane ID:
https://pyoscx.github.io/scenariogeneration/xosc/position.html#scenariogeneration.xosc.position.RelativeLanePosition
Also how can we model a scenario where a car is driving against the correct driving direction or starts in the middle of an overtaking maneuver?
Why can't the initial heading be taken into account when deciding in which direction to drive when using RelativeRoadPosition?
Or there should be some other solution which enables this.

**Comment by eknabevcc** [comment]
For RelativeLanePosition, I think it makes sense to involve relative lane ID. Else, (if you just want to specify a lateral offset) have you considered [RelativeRoadPosition](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.1.1_Model_Documentation/modelDocumentation/content/RelativeRoadPosition.html)?

**Comment by johschmitz** [comment]
@eknabevcc Yes I DO use RelativeRoadPosition, however then it just turns my vehicle around. How can I use RelativeRoadPosition and let the vehicle start driving in the direction that the user placed it? Did you just made that impossible with your recent changes?

**Comment by eknabevcc** [comment]
Well, if you really want to maintain both the position and heading you specified in the first TeleportAction, then why not just skip the RelativePosition action altogether?

But if you, for some reason, need the additional position action you could specify absolute heading (once again). Modifying your example, would be something like:
```
                    <PrivateAction>
                        <TeleportAction>
                            <Position>
                                <WorldPosition x="31.06049346923828" y="-99.47952270507812" z="0.0" h="1.94512939453125"/>
                            </Position>
                        </TeleportAction>
                    </PrivateAction>
                    <PrivateAction>
                        <TeleportAction>
                            <Position>
                                <RelativeRoadPosition entityRef="33_Car" ds="0.0" dt="0.0">
                                    <Orientation type="absolute" h="1.94512939453125"/>
                                </RelativeRoadPosition>
                            </Position>
                        </TeleportAction>
                    </PrivateAction>
```

**Comment by eknabevcc** [comment]
Wow, looks really nice and clean! Thanks for sharing.
I close the issue for now. Just add comment if you find more related issues. 👍

**Comment by johschmitz** [comment]
@eknabevcc  I am sorry but I forgot to test the new code with elevation and now I see that it does not work.
I found a fix for that though:

    # Teleport to initial position
    init.add_init_action(car_name,
        xosc.TeleportAction(
            xosc.WorldPosition(
                x=obj['position'][0], y=obj['position'][1], z=obj['position'][2])))
    # Get pitch and roll from road
    init.add_init_action(car_name,
        xosc.TeleportAction(
            xosc.RelativeRoadPosition(0, 0, car_name,
                xosc.Orientation(h=obj['hdg'], p=0, r=0, reference=xosc.ReferenceContext.relative))))

Note that the world position has no heading now and I am using `xosc.ReferenceContext.relative` again.

What seems a bit strange to me is how the vehicles move in the first few timesteps of the simulation. Is that correct?
See this example:
[bdsc.zip](https://github.com/esmini/esmini/files/8784856/bdsc.zip)

**Comment by johschmitz** [comment]
@eknabevcc Hm I noticed now that this solution depends on the heading of the road. Could this be a bug in esmini?
Here is an example. Both cars should be driving uphill:

[bdsc.zip](https://github.com/esmini/esmini/files/8785208/bdsc.zip)

**Comment by johschmitz** [comment]
Let me also summarize all requirements because it seems that after the change in esmini whatever I do always violates one of them:
- It shall be possible to place a car on a road using world coordinates.
- It shall be possible to let a car start driving using heading from placement independent of the correct driving direction of the lane below car's position.
- It shall be possible to let a car start driving using pitch and roll from road below car's position.
All of these shall be possible simultaneously.

**Comment by johschmitz** [comment]
@eknabevcc Will you reopen this or shall we continue the discussion in https://github.com/esmini/esmini/issues/205 ?

**Comment by eknabevcc** [comment]
I'll look into it when I find the time. It's good that you provided an example pinpointing the problem.

**Comment by eknabevcc** [comment]
[Release 2.23.3](https://github.com/esmini/esmini/releases/tag/v2.23.3) includes one or a few related fixes. For example, the strange roll angle during lane change should be fixed. Also the pitch is hopefully behaving better for relative position. 

Please check when possible and let us know how it works for your case.

**Comment by johschmitz** [comment]
Seems to be working fine now :+1:  Will close this ticket and create a new one if I discover any leftover issues.
