### ISSUE TITLE
Useless directories in CMakeLists.

### ISSUE THREAD

**Issue by zn845639326** [esmini/esmini#255]
https://github.com/esmini/esmini/blob/cdf04b15eb9197e413afc7f0730f2af1ade160d5/EnvironmentSimulator/CMakeLists.txt#L13-L14
The Actions and Conditions directories do not exist. 
So I suggest deleting L13-L14 from the CMakeLists.txt. :smile:

**Comment by eknabevcc** [comment]
:) Good finding. It must survived from an ancient time.
It's now fixed by commit e42c630f2b7078c65925f3dc117d7409821feb70.

**Comment by zn845639326** [comment]
Nice, I like your sense of humor. 
Thank you!
