### ISSUE TITLE
SE_ScenarioObjectState Information

### ISSUE THREAD

**Issue by Genco2** [esmini/esmini#256]
Hello Everyone,
I was wondering if there is a source where I can get information about the parts of SE_ScenarioObjectState construct, especially the ones without comments in esminiLib.hpp file like (float) h, p, r, t, and s?
Furthermore;

-  I was wondering, is it possible to get the acceleration value of an object? I guess there is "ACCELERATION_SCALE" that implies a value however I could not reach it via main.cpp. 
- Similarly, I was wondering if there is a way to obtain time to collision between two objects? 

I am aware answers to some of my questions can be obvious however I am new to this domain and looking forward to learning more.
Thanks a lot.
Genco Cosgun

**Comment by eknabevcc** [comment]
1. Information added to [SE_ScenarioObjectState ](https://github.com/esmini/esmini/blob/a03744e11bbfb0d9fb11e0543ed38e78f012b55f/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L23)in commit a03744e11bbfb0d9fb11e0543ed38e78f012b55f

2. There is no explicit method to fetch acceleration of an object. The main channel for the "groundtruth" (information about the road and all entities) is OSI ([Open Simulation Interface](https://www.asam.net/standards/detail/osi/)). That stream includes acceleration.
Maybe you can use that? Check code example: [osi-groundtruth.cpp](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/code-examples/osi-groundtruth/osi-groundtruth.cpp).
(It's also possible from Python. Here's a starting point: [testUDPDriver-minimalistic-example-osi.py](https://github.com/esmini/esmini/blob/master/scripts/udp_driver/testUDPDriver-minimalistic-example-osi.py))
3. There is currently no method to get TTC between objects. You can add TTC conditions in the scenario, but that will only log TTC value when trigger happens, so I understand that's limited use.

**Comment by Genco2** [comment]
Thanks a lot. This response helped a lot!
