### ISSUE TITLE
Is there any API to control or read data from ongoing simulation

### ISSUE THREAD

**Issue by xjsolid** [esmini/esmini#257]
In issue #231 mentioned:
Link and use the esmini lib (DLL, .so...). It provides a simplified (limited) API to control and read out data from ongoing simulation.

but I can't find any API in ESMiniWrapper.cs or esminiLib.cpp.
I'm using esminiLib in unity.
I want to know what happend or which condition has been triggered in runtime.
Any suggestions?

**Comment by eknabevcc** [comment]
Ok. Yes there is an API for the esminiLib.
There is also a C# wrapper: [EnvironmentSimulator/Libraries/esminiLib/ESMiniWrapper.cs](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Libraries/esminiLib/ESMiniWrapper.cs).

Then to your actual need, receiving notification about triggers and action. 
In the lib, there is a callback framework to receive such notifications, see [here](https://github.com/esmini/esmini/blob/a46da1a9012bda6cc052a2f7ef557a04837bcb19/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L834).

```
SE_DLL_API void SE_RegisterConditionCallback(void (*fnPtr)(const char* name, double timestamp));
SE_DLL_API void SE_RegisterEventCallback(void (*fnPtr)(const char* name, double timestamp, bool start));
```

Unfortunately this very functionality is not exposed in the C# wrapper.

What is available is the basic log.txt file, which contains log entries like triggers and events. 

You could try the Unity example package, see here:
https://github.com/esmini/esmini#unity-support

If it seems useful, maybe you could try to add the two callback functions to the C# wrapper. But it might be a bit of a challenge.

**Comment by xjsolid** [comment]
Thanks, works well, Great work!

**Comment by eknabevcc** [comment]
Cool! Thanks for feedback and the code contribution. 
I added it to the wrapper in commit 09158fab183382d4a183c69b3f59ba82b5c48c9c. Will be included in next release.
