### ISSUE TITLE
Usage of SE_ReportObjectSpeed Method

### ISSUE THREAD

**Issue by Genco2** [esmini/esmini#258]
Hello,
I am trying to use SE_ReportObjectSpeed function inside of the "[Driver model](https://github.com/esmini/esmini/tree/master/Hello-World_coding-example#driver-model)" example in "esmini Hello World Tutorial" .
For example, for once, 10 seconds  after the simulation started, I want to set the speed of the Ego car to a specific value lets say 10.0 .  I tried;

`		
                // Step vehicle model with driver input, but wait until time > 0

		if (SE_GetSimulationTime() > 0)
		{
			SE_SimpleVehicleControlAnalog(vehicleHandle, dt, throttle, steerAngle);
		}

		if ((cont == true) && (SE_GetSimulationTime() > 10))
		{
			SE_SimpleVehicleGetState(vehicleHandle, &vehicleState);
			printf("%.2f \n",vehicleState.speed);
			SE_ReportObjectSpeed(SE_GetId(0), 10.0);
			cont = false;
			SE_SimpleVehicleGetState(vehicleHandle, &vehicleState);
			printf("%.2f \n",vehicleState.speed);
		}
...
`
The rest of the code as it is in example.
However, I could not effect the speed of the car, my console output was "20.55" "20.55" . Does anyone have a idea what is wrong with my implementation ? 
Later on by assigning a negative value to "throttle" variable in each iteration, I was able to slow the car but if there is a way to work this directly with a single function call, I wonder how.  
Thanks a lot.
Genco Cosgun
[main.txt](https://github.com/esmini/esmini/files/8304555/main.txt)

**Comment by Genco2** [comment]
I realized that to obtain such report methods ( SE_ReportObjectSpeed  is one of them), the vehicle should be defined with the external controller of esmini, described [here](https://github.com/esmini/esmini/blob/master/docs/Controllers.md) .
Closing the issue since the question is solved. Moreover, this issue can be deleted.
Genco Cosgun

**Comment by esmini** [comment]
In the case of the [test-driver](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/code-examples/test-driver/test-driver.cpp) code example the (external) Ego vehicle is represented by the SE_SimpleVehicle class in the application. It is a simple "bicycle model" controlled by a few input methods, like throttle/brake and steer left/right. 

This is an example of how to control a vehicle from an external process or application, just like you found out this is typically done via a controller. In the test-driver scenario example, [test-driver.xosc](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/code-examples/test-driver/test-driver.xosc), the ExternalController is assigned to the Ego vehicle. What it basically do is preventing DefaultController from updating the Ego vehicle, hence reported speed has no effect. Instead it is assumed to be controlled from the application (test-driver.cpp in this case) which updates the explicit state every frame, e.g. using the SE_ReportObjectPosXYH() method.

But let's assume another use case: You want only to control the longitudinal speed of a vehicle.
Then you can 
1. setup a simple scenario
2. let DefaultController do most of the work and 
3. just report speed

Let's try with the first Hello World example:
```c++
#include "esminiLib.hpp"

int main(int argc, char* argv[])
{
	SE_Init("../../resources/xosc/cut-in.xosc", 0, 1, 0, 0);

	for (int i = 0; i < 500; i++)
	{
		if (i == 390)
		{
			SE_ReportObjectSpeed(0, 60.0);
		}

		SE_Step();
	}
	return 0;
}
```
You should see Ego vehicle suddenly accelerate to prevent being overtaken...

I don't know if this fits your use case, but I wanted to mention the option anyway.
