### ISSUE TITLE
Is it possible to combine ACCControler with External Controller ? 

### ISSUE THREAD

**Issue by Genco2** [esmini/esmini#259]
Hello,
I have another question about controllers.
Is there a mechanism to add 2 different controllers to a single vehicle? Hereby what I desire is, can we configure a mechanism like ; "follow the external controller unless there is an interruption from ACC controller". For example, ego vehicle can follow the calls from main.cpp(SE_SimpleVehicleControlAnalog, SE_ReportObjectPosXYH etc) however when the ego vehicle is about the crash another vehicle, ACC controller can take control and avoid the collision.
Thanks a lot.
Genco Cosgun

**Comment by mander76** [comment]
This is a feature that will come in OSC 1.2

**Comment by eknabevcc** [comment]
This is an interesting use case.

Even with OpenSCENARIO 1.2 supporting multiple controllers per entity, it seems that you want to enable/disable the ACC controller given some parameter e.g. HeadwayTime or TimeToCollision. In effect the controllers don't need to execute in parallel? I mean something like:

```
On TTC < threshold condition with edge=rising:
  Trig activate ACC controller
  Trig deactivate External controller
On TTC > threshold condition with edge=rising
  Trig deactivate ACC controller
  Trig activate External controller
```
Actually, maybe it would be possible already today. But I haven't thought it through completely...

**Comment by eknabevcc** [comment]
By the way, here's an example osc with triggering of some controller activation/deactivation:
https://github.com/esmini/esmini/blob/master/resources/xosc/controller_test.xosc

**Comment by Genco2** [comment]
> This is an interesting use case.
> 
> Even with OpenSCENARIO 1.2 supporting multiple controllers per entity, it seems that you want to enable/disable the ACC controller given some parameter e.g. HeadwayTime or TimeToCollision. In effect the controllers don't need to execute in parallel? I mean something like:
> 
> ```
> On TTC < threshold condition with edge=rising:
>   Trig activate ACC controller
>   Trig deactivate External controller
> On TTC > threshold condition with edge=rising
>   Trig deactivate ACC controller
>   Trig activate External controller
> ```
> 
> Actually, maybe it would be possible already today. But I haven't thought it through completely...

Yes, this is what I am exactly looking for. :)

Moreover, thanks for the example, as I understand this requires knowledge about OpenSCENARIO rather than esmini so I am closing with this comment.
Thanks a lot for both your explanatory answers.
Genco Cosgun

**Comment by eknabevcc** [comment]
I couldn't resist trying to implement a scenario like that.
Although two controllers can't operate in parallel, they can switch back and forth.
It was a good exercise, we found and fixed a bug in the process.

Anyway, the scenario is here: https://github.com/esmini/esmini/blob/master/resources/xosc/acc-toggle.xosc

Basically a target vehicle is driving ahead. Ego is controlled interactively with arrow keys. If/when coming near, the ACC controller will take over from Interactive controller. Then when target accelerates, headway time will increase and ACC will hand over to Interactive again. And so on...

It's not perfect. E.g. heading will "jump" to align with road as soon as ACC takes over. But I wanted to let you know anyway what's possible with current OpenSCENARIO 1.1 and esmini.

**Comment by Genco2** [comment]
Thanks a lot for the response. This is exactly what I am working on. 
Moreover, I also have an approach that I would like to share; this one more relies on the main code (main.cpp) rather than the OpenSCENARIO file. I declared a parameter "isACCon" in the scenario file(initial value as 0) and implemented the "ActivateACCEvent" depending on this variable with ;
`
                             <ByValueCondition>
								<ParameterCondition parameterRef="isACCOn" value = "1" rule="equalTo">
								</ParameterCondition>
                             </ByValueCondition>
`

Parallelly, I update the value of isACCOn variable from main.cpp with SE_SetParameter function. The call of this function may be decided with the user's implementation, it can be called depending on a relative distance, a value of state of any vehicle or simulation time etc.
This method may be inefficient in a general manner however I think it is also an acceptable solution for the problem. Thanks to esmini we can discuss different methods for a single problem.

Genco Cosgun

**Comment by eknabevcc** [comment]
Cool! Thanks for sharing this method.
I think that's an excellent and smart use of the Parameter/SetParameter functionality. - A good way to move control to application level 👍 (when you have the possibility to modify the application)
