### ISSUE TITLE
Reference to cite?

### ISSUE THREAD

**Issue by ReiDa8684** [esmini/esmini#26]
Dear authors of esmini. I am very happy about this tool and will mention it in a publication. 
Is there any paper to cite, e.g. from the previous swedish project? I was not able to find anything about esmini so far.

**Comment by eknabe** [comment]
We're glad that esmini and OpenSCENARIO is found useful and being mentioned!
An idea might be to provide a reference or link to the [GitHub repo page](https://github.com/esmini/esmini). And for the record mention that it initially was a result from the research project Simulation Scenarios. Here is the official site providing the public report from the project: https://www.vinnova.se/en/p/simulation-scenarios/
There is also [this site](https://sites.google.com/view/simulationscenarios) where you can find links to the public report and also some slides from the final seminar.

**Comment by ReiDa8684** [comment]
Thank you so much for the links. I studied the public report and will definetly get into contact with some of the people mentioned there.
Concerning the reference, I will use the link to GitHub, as you proposed.
