### ISSUE TITLE
Position::Delta sometimes return wrong dLaneId

### ISSUE THREAD

**Issue by brifsttar** [esmini/esmini#261]
Hi Emil,

I hope you're doing well. It's been a while since I found a bug in esmini, but it's not for lack of trying! We've been using RoadManager more and more recently, and I can't thank you enough for your work on this project.

Anyway, we recently encountered an issue with `Position::Delta`, which returned an incorrect `dLaneId`. As usual, I brought my A-game MSPaint skills to help illustrate the issue.

![image](https://user-images.githubusercontent.com/53508707/160681391-2f3d99b8-cf58-4ba9-aa13-9eb71dce3f85.png)

So the issue occurs when requesting the delta between points `A` and `B`. They are indeed connected via the junction `j1`, and their `dLanedId` should be either 2 or -2 (I can never remember which side is which). But `Position::Delta` returns a `dLanedId` of 0, which isn't what I expected.

I've tracked down the issue to the following lines, and I'll explain more about it below.

https://github.com/esmini/esmini/blob/45ef22ed04867f6e6630bb73461e5d4a3fcd7d93/EnvironmentSimulator/Modules/RoadManager/RoadManager.cpp#L8272-L8277

Basically, Dijkstra's algorithm works as expected, and correctly finds the connection between `r1` and `r2` via `j1`. However, when navigating the graph of connected roads from `r1`, it starts first by checking `j2`. Which is not an issue, as the algorithm properly backtracks to `j1` and finds the connection.

However... `j2` gets added to the `visited_` vector, which is where trouble starts. That, in itself, obviously isn't an issue, but it leads to one down the line.

https://github.com/esmini/esmini/blob/45ef22ed04867f6e6630bb73461e5d4a3fcd7d93/EnvironmentSimulator/Modules/RoadManager/RoadManager.cpp#L4494

Because if we go back to culprit lines above, we see that you check if start and end road are inverted to (rightfully) flip sides. However, the code assumes `visited_[0]` as the first `RoadLink` between the two points, but that's not always the case! And in my example, it's definitely not the case, as the first checked `RoadLink` happened to be the `j2` connection, which wasn't the correct one. The consequence is that the code thinks roads are in opposite directions, so it flips sides, which leads to a null `dLanedId` when I expected 2 (or -2, I still don't know :P ). If point `B` was on the other lane of `r2`, `dLanedId` would then be 2 instead of 0.

If my analysis is correct (and if I managed to make it understandable), one solution could be to add another attribute to `RoadPath` of type `std::vector<PathNode*>` which would store the actual solved path between the two points. You could then use that variable instead of `visited_` in the code above, and that would work. If you want, I could probably try to implement that and make a PR, but I still wanted to raise the issue to you first.

If you want, I can also send you the `.xodr` (it's a new one!) along with the actual coordinates leading to the erroneous `Position::Delta` call.

**Comment by brifsttar** [comment]
Hey, as mentioned in #265, the fix should be easy to implement, so I'll make a PR probably friday or this weekend.

**Comment by eknabevcc** [comment]
Yes, please do that. That would be appreciated!

**Comment by eknabevcc** [comment]
Thanks a lot for the thorough analysis. I agree that there seems to be an issue. I looked through the code change proposed in PR #266 and I also tested it for a few roads and scenarios. 
There is one detail I'd like to check (noted in the PR). 
So if offer still valid, please send the updated road and relevant coordinates.

**Comment by brifsttar** [comment]
The `.xodr` can be found [here](https://github.com/esmini/esmini/files/8411252/newmob.txt), though I had to change its extension to `.txt` for GitHub to accept it.

The coordinates are as follow, both T and H shouldn't matter and could be set at 0. `A` is closer than `j2` than in my drawing, otherwise `j1` gets visited first.
* A
  *  (X=222.83275391,Y=1580.19187500), (Yaw=-154.960068) (deg)
  * Road 63, lane 1, S=38.62212646, T=-0.22243349, H=-2,05533 (deg)
* B
  * (X=185.43298828,Y=1544.50843750), (Yaw=98.315598) (deg)
  * Road 56, lane -1, S=108.7249707, T=-0.62930916, H=0,173253 (deg)
