### ISSUE TITLE
Position update problem when the velocity updated in API

### ISSUE THREAD

**Issue by fatihmms** [esmini/esmini#271]
I am trying to utilize from API source code and I used SE_ReportObjectSpeed function to update velocity of actors. When I update the velocity with that function position of actor stays stable and does not change. Also, I tried to use SE_ReportObjectAcc and I cannot see the change on velocity and position. So, is there any way to update all variables in an implementation at the same time? 

Thank you!

**Comment by eknabevcc** [comment]
Try attached zip-file containing main.cpp and simple.xosc. [simple.zip](https://github.com/esmini/esmini/files/8484094/simple.zip)

Put simple.xosc in esmini/resources/xosc
Put main.cpp in Hello-World_coding-example

Build according to User guide [Hello World programming tutorial](https://esmini.github.io/#_hello_world_programming_tutorial)

The scenario (simple.xosc) just puts a car on a straight road with speed 1 m/s.

The application (main.cpp) will step the scenario 500 times. At 100:th iteration it will change speed of the car to 10 m/s.

Please test and report how it goes.

**Comment by aktasalifurkan** [comment]
If we use the case where actor speed increases 0.01 m/s for each step of simulation after 100th iteration, even though the speed of actor increases, it stays stable. You can find the mentioned .cpp in here [main.zip](https://github.com/esmini/esmini/files/8486452/main.zip). Please let us know if our approach is incorrect or anything that we can change.

**Comment by eknabevcc** [comment]
I think your code looks OK. I did slight modifications, just to make the speed change more obvious.

[main.cpp.txt](https://github.com/esmini/esmini/files/8490294/main.cpp.txt)

It looks like:

https://user-images.githubusercontent.com/29146839/163420541-d0ac532b-2ee1-41ee-929e-cc1d1724cca8.mp4

Please try and see if you get same result.

**Comment by fatihmms** [comment]
We tried to run same code but we got same error again. Our vehicle does not move but its velocity changes. Could it be related to the environment or the esmini version?

**Comment by eknabevcc** [comment]
Yes, you're right. My bad. I did a commit (dd89b32a2ba3093ca3f494a5a029e4fc787b7d19) the other day which I thought only affected dirty bits to enable interactive steering while application updating speed. But I now realize that the commit changes behavior of the SE_ReportObjectSpeed() function, locking the position.

Could you pull latest version from master branch and build yourself, or do you need a release?

**Comment by fatihmms** [comment]
In the last attempt, we solved the problem. Thanks a lot for your help.

**Comment by eknabevcc** [comment]
Good to hear. Closing issue.
