### ISSUE TITLE
bicycle demo & bicycle 3d model

### ISSUE THREAD

**Issue by qqkkwan** [esmini/esmini#272]
Hi,
    Are there any models and examples of bicycles. Now i have normal cars and pedestrian，i just need the bicycle . Thanks!

**Comment by eknabevcc** [comment]
Yes, we have one bicycle + rider: cyclist.osgb

![image](https://user-images.githubusercontent.com/29146839/163324586-0db8a35e-5796-408f-a0c7-31372bca56a4.png)

and one motorbike + rider: mc.osbg

![image](https://user-images.githubusercontent.com/29146839/163324693-0916389d-2f57-4077-ad22-13bb12b72f2d.png)

The models are included in the esmini model pack which can be found [here](https://dl.dropboxusercontent.com/s/5gk8bvgzqiaaoco/models.7z?dl=1).

This scenario includes a cyclist: [synch_with_steady_state.xosc](https://github.com/esmini/esmini/blob/master/resources/xosc/synch_with_steady_state.xosc)
See vehicle catalog for an [example how to specify a bike](https://github.com/esmini/esmini/blob/dd89b32a2ba3093ca3f494a5a029e4fc787b7d19/resources/xosc/Catalogs/Vehicles/VehicleCatalog.xosc#L144).

**Comment by qqkkwan** [comment]
good！
