### ISSUE TITLE
convert opendrive to osgb 

### ISSUE THREAD

**Issue by qqkkwan** [esmini/esmini#281]
Hi, 
    Is there any way to convert opendrive to osgb file and add some environmental elements along the road?

**Comment by eknabevcc** [comment]
Look at this OpenDRIVE example, it's includes a road definition with some objects:
[resources/xodr/crest-curve.xodr](https://github.com/esmini/esmini/blob/master/resources/xodr/crest-curve.xodr)
![image](https://user-images.githubusercontent.com/29146839/167440694-fd39bf05-e826-43b7-9094-6be2df1e45c1.png)

Another example with rails and guide-posts is:
[resources/xodr/e6mini.xodr](https://github.com/esmini/esmini/blob/master/resources/xodr/e6mini.xodr)
![image](https://user-images.githubusercontent.com/29146839/167441370-27f53943-2b79-497e-9f9b-c4da85490109.png)

You can save models generated by esmini, check User guide: 
https://esmini.github.io/#_road_network_visualization
