### ISSUE TITLE
esmini crashing

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#295]
Hi,

exact at below if condition esmini is crashing in my use case:

https://github.com/esmini/esmini/blob/3090bc5ca5c014e830f4c70a2794af8366a51453/EnvironmentSimulator/Modules/ScenarioEngine/OSCTypeDefs/OSCManeuver.cpp#L54

I've added the following if condition directly below the pa2 definition or before this if condition:
```
if (i == k || !pa2->IsActive())
{
    continue;
}
```
Hard to say what exactly the problem is, i == k solves the problem that pa == pa2. without my second condition esmini crashed directly after I tried to access pa2->object_->GetId(). Maybe a mutex lock is missing here? Any idea what the problem is?

Kind regards,

Thaddäus

**Comment by eknabevcc** [comment]
Can you share the scenario (or at least enough part of it to reproduce the issue)?

**Comment by tmIdiada** [comment]
Hi,
I think I've found the issue. I have an user defined action that I'm allowing for my V2X functionality. And this user defined action has normally no referenced object, because not needed, and this is the reason why esmini is crashing here. Good this is my problem, but there is also a problem with your code, first you are defining pa2 as PrivateAction and later you are checking if its base_type is PRIVATE. So, in my case the user defined action is declared as private action and and in the if condition the referenced object is checked before the base_type for private or before it is checked if the action is active. I think here some changes would be needed.

**Comment by eknabevcc** [comment]
I'm not totally following. Any private action is associated with an object. Any other action, that does not involve a specific object, is falling into the [global action](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.2.0_Model_Documentation/modelDocumentation/content/GlobalAction.html) category, or potentially user defined. (I'm not sure about user defined actions. Don't think we have done any such yet)

Is there any specific reason why you implement the user action as a private one in the first place? 

Your code is not wrong, but I don't see that the check is needed. The action that you check is fetched from the object's list of events - which by definition would be private. Or do you see a case where the action, associated with an object, could be of UserDefined type? - which I would not expect.

Focusing on the root problem, did you find a solution, e.g. changing action type? Or how did you solve it?

**Comment by tmIdiada** [comment]
Okay I defined a user defined action (specific V2X type) like your private action, so it belongs not to the global actions, the single difference is that it is also a direct child class of Action and it does not set the property for belonging object, because I don't need it, even it is read by scenario reader. So, the object looks a bit similar to your PrivateAction, but is of class UserDefeinedAction. I think the same or at least similar way if you would introduce in the future also an UserDefinedAction. This action has also only an init step, the other function are empty and unused, so I must not fear any conflicts with your private actions and this action must currently never stop. So I need only the check before you are declaring all event actions as private actions, that this action is really of type private and this something you are not doing, First you are defining pa2 as private action and then you check for type PrivateAction, which is too late for me. So you are translating my UserDefinedAction as PrivateAction and before you check if this action is of type Private you are checking its referenced object which is not there.
