### ISSUE TITLE
RelativeTargetLaneOffset does not consider the reference entity's current lane position.

### ISSUE THREAD

**Issue by HiroshiAndo23** [esmini/esmini#296]
I think that RelativeTargetLaneOffset (value=0) does not consider the reference entity's current lane position.
I would like to have your comments on whether my usage is wrong, or, wrong interpretation of OSC, or a bug in Esmini.

- Sample Scneario
  Here's a simple scenario based on cut-in_sample.xosc.
  [cut-in_try_goback.xosc.txt](https://github.com/esmini/esmini/files/8999077/cut-in_try_goback.xosc.txt)

- Expecting Behavior
　OverTaker tries to change lanes in the lane and offsets, but quits and returns on the original lane position.
　
- Current Behavior
  OverTaker tries to change lanes in the lane and offsets, but continues to drive on the offset lane position.
  I think the lateral position is based on the lateral position of the reference entity, not the center of reference entity's current lane position.

- Detail

**initial position**
![image](https://user-images.githubusercontent.com/108319364/176132162-d431ca1b-428a-496d-9768-d94a8cbc780d.png)
　Ego(White): Lane: -1, Lane offset(t): 0.00
　OverTaker(Red): Lane: 1, Lane offset(t): 0.03

**Then, OverTaker tries to change lanes in the lane and offsets.**
![image](https://user-images.githubusercontent.com/108319364/176132463-8ae2239c-2d96-44a4-83f4-c57619232d21.png)
　OverTaker(Red): Lane: 1, Lane offset(t): 0.53 (0.03 + 0.5)

**Finally, Overtaker acts below RelativeTargetLaneOffset**
```
　<LaneOffsetAction continuous="ture">
        <LaneOffsetActionDynamics maxLateralAcc="2" dynamicsShape="sinusoidal" />
        <LaneOffsetTarget>
            <RelativeTargetLaneOffset value="0" entityRef="$owner" />
        </LaneOffsetTarget>
    </LaneOffsetAction>
```

**But the OverTaker does not return to the original lane position and drive on the offset lane position.**
![image](https://user-images.githubusercontent.com/108319364/176133471-546da416-4d84-4362-9cb2-91fbcada7407.png)
　Expecte position
　　OverTaker(Red): Lane: 1, Lane offset(t): 0.0

　Current position
　　OverTaker(Red): Lane: 1, Lane offset(t): 0.53 (0.03 + 0.5)

**Comment by mander76** [comment]
I would say this is the exact behavior according to the standard.
from the user guide:
For RelativeTargetLaneOffset:

value | double | 1..1 | XSDattribute | Lane offset with respect to the reference entity's current lane position. Unit: m.

So a 0 should actually not move the car laterally 

If you want it to return to the center of the lane, I would instead suggest the AbsoluteTargetLaneOffset
(from the userguide)


value | double | 1..1 | XSDattribute | Signed number in meters the vehicle should respect as an offset from the center of the current lane.

**Comment by HiroshiAndo23** [comment]
Thank you for your response and suggestions.

However, I understand the specification differently than your response.

As you said, RelativeTargetLaneOffset is defined as the reference entity's current lane position (not the reference entity's current position).
Also, the lane position is defined as The s coordinate of the current position, but the definition of the lane position does not include the t coordinate. (from the userguide)

From this I think So a 0 should actually move the car laterally, what do you think?

Also, since AbsoluteTargetLaneOffset cannot specify a reference entity, I am having trouble offsetting a target on a different lane than the Host with respect to the Host lane center.

**Comment by mander76** [comment]
Well, there I don't agree, there is a t coordinate (in actions referred to as offset for lanes) (in 1.1 userguide 3.3.3, in 1.2 userguide 6.3.3).

And if you want to move the car to another lane, I would suggest a LaneChangeAction instead of an offset action

**Comment by HiroshiAndo23** [comment]
Thank you for your quick reply, I understand the interpretation of the specifications on the ESMINI side.
I will try another way. Thank you very much.

**Comment by eknabevcc** [comment]
I understand the expectation. But I agree with Mikael. 
Using `RelativeTargetLaneOffset` will relate to the **current** lane offset of the reference vehicle (target in this case), whatever it is... 

I think that for this use case the AbsoluteTargetLaneOffset is perfect. Just put value = "0.0" and it will move to lane center.

For reference I attach a modified version of your scenario that will complete the GoBackEvent.
[cut-in_try_goback-mod.xosc.txt](https://github.com/esmini/esmini/files/9597109/cut-in_try_goback-mod.xosc.txt)

Let me know if I you still don't agree or if you find a different behavior in another tool.
