### ISSUE TITLE
RoadManager doesn't connecting road link to another junction

### ISSUE THREAD

**Issue by mljack** [esmini/esmini#298]
When open opendrive files with 2 junction next to each other.
The function CheckJunctionConnection() complains with this error msg: "Expected element type ROAD, found JUNCTION". 
https://github.com/esmini/esmini/blob/05192a6db265e9b2a323cabe9372966f756e44e7/EnvironmentSimulator/Modules/RoadManager/RoadManager.cpp#L5021

The junction is next to another junction, so a connecting road connects to another connecting road of another junction. Although it's a bit complex, but I think it's a valid case.

**Comment by brifsttar** [comment]
Hey,

I don't think that's a valid OpenDRIVE case, as per [section 10.2 rules](https://www.asam.net/index.php?eID=dumpFile&t=f&f=4422&token=e590561f3c39aa2260e5442e29e93f6693d1cccd#top-c0d5f9a9-a73a-4bcc-9a8c-393f357a559c):

> Connecting roads shall not be incoming roads.

Adding a super short road between the junctions should work.

**Comment by mljack** [comment]
Thanks for your kind suggestion~ I'm trying to merge these junctions into a bigger junction and generate new connecting roads from all kinds of routes in original junctions.
