### ISSUE TITLE
Sure you chose the if-condition the best way?

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#307]
Hi,

only to make sure the condition is behaving like you are expecting it:
False && True || True = False || True = True, so the last condition is very powerful without any brackets

Normally I would expect such a more complicated condition than your simple one:

```
(!obj->IsGhost() || (obj->IsGhost() && (ghost_mode_ != GhostMode::RESTART || ghost_mode_ != GhostMode::RESTARTING)))
```

At least for my use-cases your condition is working like expected to take here the default controller, but maybe there are use-cases or could be use-cases the default controller is not used when it should be (ghost_mode_ restarting even if the current object is no ghost).

https://github.com/esmini/esmini/blob/3d1abcd6b3e3855707dc424f7c25477bbf136078/EnvironmentSimulator/Modules/ScenarioEngine/SourceFiles/ScenarioEngine.cpp#L555

**Comment by eknabevcc** [comment]
The design of the statement is not trying to be smart, but rather straight forward. The idea is to let through all:
* non ghosts
* ghosts that are not in RESTART or RESTARTING phase

Probably the expression could be written better/differently. For example I guess the following is a re-write:

`!(obj->IsGhost && (ghost_mode_ == GhostMode::RESTART || ghost_mode_ == GhostMode::RESTARTING))`

However I tend to prefer avoiding the NOT operator in front of (negating) huge logical expressions. But now when I look at it I'm not so sure, maybe this latter one is better... 

Anyway. I don't think the current one is wrong, so let's keep it. Unless you actually find it giving the wrong/unexpected behavior. Also, there is no point evaluating ghost_mode for non ghost objects.

**Comment by tmIdiada** [comment]
Hi,
your last posted solution looks best to me. From my point of view your wanted behaviour will be not achieved by the current implementation and the ghosts are moved at restarting phase due to the missing brackets . Maybe you know a scenario you have at least one ghost where the other conditions are fulfilled for it and the ghost is in restarting phase.

Kind regards

Thaddaeus

**Comment by eknabevcc** [comment]
My bad. Revisiting our comments I found that my own interpretation of current code (and rewrite proposal) was not as I first expected. 

The purpose of the filter is NOT to always let through non ghosts. On the other hand always let through ghosts, but prevent non ghosts updates during any ghost restart phase.

So actually the original statement:
`(obj->IsGhost() && ghost_mode_ != GhostMode::RESTART || ghost_mode_ != GhostMode::RESTARTING)`

can be (and [has been](https://github.com/esmini/esmini/commit/8be51cc09fd44af3dcef3e3dcc7dbffa18dfbca5)) simplified into:
`!(!obj->IsGhost() && ghost_mode_ == GhostMode::RESTARTING) `

( I guess the unnecessary complexity of the original was remains from some experimenting...)

Thanks for your careful review.
