### ISSUE TITLE
DistanceCondition with freespace="true" produces incorrect results

### ISSUE THREAD

**Issue by aG-MathWorks** [esmini/esmini#309]
In the attached scenario, a vehicle is intended to follow a trajectory and stop 2 meters from a WorldPosition (coinciding with the end of the trajectory).  However, the condition is satisfied when the entity is far from the point.

The condition evaluates correctly when freespace="false". 

Tested in 2.25.1.

[StopBeforeTrajectoryEnd.zip](https://github.com/esmini/esmini/files/9155945/StopBeforeTrajectoryEnd.zip)

**Comment by eknabevcc** [comment]
Thanks for good finding. Yes it sure is a bug. 
Fixed by commit 4f81f66d88d4bb3c983f8a7633dfbe42d32b4de0.

Please test and report if it works as expected. Let us know if you need a release.

**Comment by aG-MathWorks** [comment]
I have tested latest master and can confirm that this issue is resolved. Thanks for the quick turnaround!
(and thanks for the simple build process - it was a piece of cake). 

A release would certainly be appreciated (by the end of August would be ideal)

**Comment by eknabevcc** [comment]
Thanks for feedback! 
Yes, there will for sure be a release before then.

**Comment by eknabevcc** [comment]
[v2.26.0](https://github.com/esmini/esmini/releases/tag/v2.26.0) released
