### ISSUE TITLE
LaneChangeAction/RelativeTargetLane do not act correctly

### ISSUE THREAD

**Issue by wxtshr001** [esmini/esmini#31]
I have a two car lane change scenario. The scenario acts as following:

```
|  1  |  2  |  3  |  4  |  5  |
|     |     |     |     |     |
|     |     |  ^  |  ^  |     |
|     |     |  E  |  O  |     |
|     |     |     |     |     |
```

Ego car runs on lane 3, object car runs in lane 4. The ^ symbol indicates the forward direction. At some time, the ego car act LaneChangeAction with RelativeTargetLane value -1, and object car act LaneChangeAction with RelativeTargetLane value as 1. In VTD, this scenario simulation result is, ego car changes to lane 4, and object car changes to lane 3. But in esmini, ego car changes to lane 2 and object car changes to lane 5.

I examined the esmini RelativeTargetLane implementation, found it was a simple lane id calculation depends on OpenDrive lane id:
`target_lane_id_ = ((TargetRelative*)target_)->object_->pos_.GetLaneId() + target_->value_;`

But in ASAM OpenScenario userguide, the relative LaneChangeAction is set as this:

>  For the LaneChangeAction, relative target referencing works differently than absolute referencing. Here, the Vehicles' Xv-axis serves as reference direction. Lane changes are evaluated positive if they’re aligned with the vehicles' positive Yv -axis. Thus, a positive lane change moves the corresponding vehicle to the next actual lane in its positive Yv-axis direction.

I suppose the esmini RelativeTargetLane need a more precise implementation.

**Comment by eknabevcc** [comment]
This is a good question! 
Just to clarify: Relative lane reference only apply to the RelativeTargetLane option. And the typical use case for this option is when you want a vehicle X to end up in a specific lane relative to vehicle Y.
But of course the reference entity in the RelativeTargetLane can of course refer to itself, i.e. the same vehicle that is performing the action. Which is useful when you just want to switch lane one step left or right. I assume this is the use case you have in mind.
Now, I totally agree with your interpretation of the user guide. I was actually not aware of this information. Thanks for pointing it out! esmini should be aligned. I'll look into this tomorrow.

**Comment by eknabevcc** [comment]
Fixed in commit [6960bb1](https://github.com/esmini/esmini/commit/6960bb1634881268595ac8b9baae0fa7b2213d5b).
Please check and see if behavior is aligned with VTD.

**Comment by wxtshr001** [comment]
@eknabevcc Thanks for your efforts! Got right result.

**Comment by eknabevcc** [comment]
Good news! Thanks for feedback.
