### ISSUE TITLE
esmini runs slow with high cpu usage at some road

### ISSUE THREAD

**Issue by yonhdee** [esmini/esmini#317]
hi, i'm using `esmini-bin_ubuntu` binary file from release page
i'm using a converted .xodr file of rome city, and i created some traffic flow around my ego car
i noticed my esmini runs slower and slower when a car passes through the "turnaround" road(or "u-turn" road), and when they do, they begin to slide laterally
which is weird

**screenshots**
![Screenshot from 2022-08-25 14-42-56](https://user-images.githubusercontent.com/12524685/186595709-af8c8287-5ef8-4257-807f-7d0904b72450.png)
![Screenshot from 2022-08-25 14-43-51](https://user-images.githubusercontent.com/12524685/186596298-3ed6978b-5097-40ed-9055-6a46d4b44705.png)

---

i got the small area map of rome from openstreetmap.org, and convert it into xodr using sumo's netconvert
```bash
netconvert --osm-files roma.osm --opendrive-output roma.osm.sumo.xodr
```
i also tried converting with no turnaround road
```bash
netconvert --osm-files roma.osm --opendrive-output roma.osm.sumo.no.turnarounds.xodr -v --no-turnarounds
```
and the vehicles drive normally, here is my command to run esmini
```bash
./bin/esmini --window 60 60 800 400 --osc ./resources/xosc/roma.xosc
```
the files i'm using can be found here https://github.com/yonhdee/esmini/commit/cc56ee219534fd4aafc3c8f298d9b9031dc7ae4f
including:
- resources/xodr/roma.osm
- resources/xodr/roma.osm.sumo.no.turnarounds.xodr
- resources/xodr/roma.osm.sumo.xodr
- resources/xosc/roma.xosc

**Comment by eknabevcc** [comment]
Excellent. Thanks for the advice!

Actually I had some recollection about a similar finding. And I found this note:
https://github.com/esmini/esmini/blob/master/resources/sumo_inputs/readme.txt
with this, similar, command (going the other way from odr to sumo):
`netconvert --opendrive multi_intersections.xodr -o multi_intersections.net.xml  --junctions.scurve-stretch 1.0 --no-turnarounds.except-deadend`

I tested both variants `--no-turnarounds`/`--no-turnarounds.except-deadend` on your file and got this limited difference:

![image](https://user-images.githubusercontent.com/29146839/188176561-0b1b1c0b-241b-4401-80fd-bbf36201d7ce.png)

![image](https://user-images.githubusercontent.com/29146839/188176611-4c01004a-a203-4787-898e-80c6f3f115de.png)

So it seems that `.except-deadend` will add a loop when there is an adjacent lane of opposite direction. But that probably lead to more confusion than value. 

Anyway, I added your tip to the User guide:
https://esmini.github.io/#_openstreetmap_osm_roads_in_esmini
