### ISSUE TITLE
can not get right  value using RM_GetPositionData in python

### ISSUE THREAD

**Issue by diff8911** [esmini/esmini#318]
I want a tool to parse opendrive files and find the excellent esmini.
When I try the example code in esmini/EnvironmentSimulator/code-examples/hello_world/use_roadmanager.py according to the [user guide 12.3. Python binding](https://esmini.github.io/#_python_binding), I found that I can not get the same road position after setting the same x,y value from a road position input. This may be not clear, the code is like this:
`
#test a few positions
**x = 19
y = 1.34**
rm.RM_SetWorldPosition(rm_pos, x, y, 0.0, 0.0, 0.0, 0.0)
rm.RM_GetPositionData(rm_pos, ct.byref(rm_pos_data))
print('road_id {} lane_id {} lane_offset {:.2f} s {:.2f}'.format(
    rm_pos_data.road_id, rm_pos_data.lane_id, rm_pos_data.lane_offset, rm_pos_data.s))
**_--expect road_id=1,lane_id=1,offset=-0.2,s=40, but get road_id=1,lane_id=-1,offset=0,s=-0.19_**

road_id = 1
lane_id = 1
lane_offset = -0.2
s = 40
rm.RM_SetLanePosition(rm_pos, road_id, lane_id, lane_offset, s)
rm.RM_GetPositionData(rm_pos, ct.byref(rm_pos_data))
print('x {:.2f} y {:.2f} h (yaw) {:.2f}'.format(
    rm_pos_data.x, rm_pos_data.y, rm_pos_data.h)) 
**--will out put x=40,y=1.34**
`
Then I found the RM_PositionData class was not the same as esminiRMLib.hpp，it lost the "junctionId", after I add it ,the positon value it  right.

**Comment by eknabevcc** [comment]
Thanks a lot for reporting this good finding. 
We simply forgot about updating this example after adding the `junctionId` field to the C-code struct.
Now it's done by commit [71311c7](https://github.com/esmini/esmini/commit/71311c7d9b7e25247e040afe4730a07830d3d4d7) and the [User guide](https://esmini.github.io/#_example_use_of_esminirmlib_roadmanager) is updated as well.
