### ISSUE TITLE
Adding CSV data logging

### ISSUE THREAD

**Issue by CPettit-LCM** [esmini/esmini#32]
Hi ESMINI Dev's,

I am interested in adding an option to generate a vehicle data log in text/csv format for post-processing of the simulation. I have already implemented a working version that generates the desired output inside of CommonMini, however I am unsure if this is the correct location for such a feature. Should the logger be located within CommonMini alongside the main logging class, or somewhere else such as within the Replayer? 

I also noticed that dat2ascii exists already, with close to desired functionality. However, there are additional values that I would like to store. Is expanding the range of values stored by the Replayer and extending dat2ascii an optimal solution?

My end goal is to merge my branch so it could be accessed by my colleagues.

Any advice is greatly appreciated!

(Here is a picture of the desired output format I am working towards)
![Desired Output](https://user-images.githubusercontent.com/69789709/90398059-1844c680-e099-11ea-9cdf-f5738c09289d.JPG)

**Comment by eknabevcc** [comment]
Great! This looks like a nice feature. 

There is a similar functionality, the application dat2ascii, which takes a .dat output file and converts into CSV ASCII format. However that does not include all good stuff that you seem to have. And I think it's more complicated to modify. 
I have been thinking about converting osi output data to CSV ASCII as well, but that would also be limited by the data included in the OSI file. 

So, the conclusion is that I think it makes sense to add a csv logger like this. Perhaps the ASCII format will be a bottleneck w.r.t performance and file size when running long scenarios with many entities. But hey, we can solve that if and when it happens, e.g. output a binary format that can be transformed into a CSV ASCII in a post processing step.

My spontaneous suggestion would be that you please add your code in the most straight forward way, what makes sense for you. Then we can refactor it if and as desired, keeping the functionality untouched. E.g. putting it into a separate module, which could be nice but requires some fiddling with cmake files.

**Comment by CPettit-LCM** [comment]
This sounds great! I’m very excited to collaborate on such a well-developed project. My company (Linz Center of Mechatronics) is very motivated to incorporate ESMINI into our toolchain and expand on its support of OpenScenario.

Recently I have been working on cleaning my code and pushing my repo to Github.

Before I make any pull requests I would like to add a command line argument for enabling/disabling the logger, as well as solve a startup crash related to the output CSV file being open already.

Good point regarding performance, I'll set up a batch file for stress testing and keep an eye on performance as I move forward.

I was also curious if a help file containing a list of existing launch arguments already exists? If not, I have already begun working on one that I will include in my repo.

**Comment by CPettit-LCM** [comment]
Hi Emil,
I have finished adding my launch argument and everything is running well.

However, I am a bit stuck on handling the launch error. If the output .csv log is open and another simulation is attempted an abort code is called. The abort does not happen when the log is open in a text editor, only when it’s open in Excel. Is there a common coding practice here? A try-catch wrapper which displays a message? 

In regards to the readme, I was wondering what the usage() method was for, I had only seen the calls in PlayerBase and hadn’t looked into them. Very useful.

From what I’ve read, embedding other text sources into a MarkDown document is not a built-in feature and requires something else such as MarkdownPreprocessor (https://github.com/jreese/markdown-pp). But I wasn't sure if you were referring to only hyperlinking another document.

Another strategy I know is to run a command line copy automatically at the end of every build. This would append the main readme.md with readme.txt (the runtime command readme) and usage.txt. I’m definitely interested in this dynamic documentation idea. If you have any examples in mind or more thoughts on how it could be executed, I’d be more than happy to continue investigating.

**Comment by eknabevcc** [comment]
I think your proposal looks really good. 
The only concern I have, with moving text from separate files into the READMe.md, is when distributing esmini, e.g. the demo package. It's nice to include information e.g. runtime key and mouse commands. So far I have been thinking that separate small text files is good. Keeping those text files and also putting stuff in the MD file would mean double sources (if not automated, which seems a bit tricky).
But now I'm thinking that perhaps the README.md could be distributed as a single source of info. Maybe that would be simpler. It could include, as your example, launch and runtime commands, OpenSCENARIO coverage, and so on. Skipping those separate text files.
Let me think a bit more and discuss internally. Meanwhile I added links to the separate text files. Better than nothing. Let me get back in a few days.

Regarding the file lock. A try-catch could be a good thing if a user explicitly wants to log. But we could add that later if we see the problem. esmini is not bullet proof anyway :)

**Comment by CPettit-LCM** [comment]
I agree, double sources would be doing more harm than good. Looking forward to hearing what your team comes up with!

In the meantime I submitted my pull-request (I'll resubmit if it was done improperly). I also created an ESMINI application logo on LucidChart (something like web-based MS Visio) and figured it might be of some use to your team as well! If there is anything you would like changed I can make improvements or provide the source.

![ESMINI_Logo_with_car_export(4)](https://user-images.githubusercontent.com/69789709/91187309-5329a880-e6f0-11ea-8ca0-be231487f181.png)

**Comment by eknabevcc** [comment]
Excellent, the [pull request](https://github.com/esmini/esmini/pull/36) is now merged! Code looked good and it worked right out of the box. Did just minor a minor merge adjustment. Thanks for the contribution.
The logo looks nice, good work! We had something similar in-house. I'll keep in mind if we'll change.

**Comment by CPettit-LCM** [comment]
Great news, I'm pleased the merge was smooth! 

Should I close this Issue and begin a new one related to the automatically generated ReadMe file?

**Comment by eknabevcc** [comment]
Yes that's a good idea. From now the csv logger is an integrated part of esmini, so the issue is "solved". 
But to track ideas and any development regarding the ReadMe, please file a separate Issue for that and close this one.

**Comment by CPettit-LCM** [comment]
Will do. CSV logger implemented / Issue closed and ReadMe discussion moved to new topic.
