### ISSUE TITLE
Get wheel angle via esminiLib.hpp.

### ISSUE THREAD

**Issue by mickmack1213** [esmini/esmini#322]
I'd like to retrieve the `ObjectInfoStruct::wheel_angle` through the c++ interface.

I'm willing to take over the implemenation part myself.

For me the best fitting place would be to enlarge the `SE_ScenarioObjectState` struct and set it inside `copyStateFromScenarioGateway` in esminiLib.cpp, but this will not only break the public API but also might cause some very ugly side effects when the user of the lib overrides a larger memory area than previously.

**Comment by eknabevcc** [comment]
I think it's a good idea to add wheel info. I'd suggest to add both wheel_rot and wheel_angle, just for consistence.

Also the [C# wrapper](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Libraries/esminiLib/ESMiniWrapper.cs) needs to be updated accordingly.

You're right in that the API will change. But as long as we point it out in a new release it should be OK.

Please go ahead and propose implementation in a pull request 👍
