### ISSUE TITLE
About Trajectory Planning

### ISSUE THREAD

**Issue by qqkkwan** [esmini/esmini#324]
Hi,
   if I have an opendrive map , and i give 2 points A,B. Is there a way to give a route from A to B, which does not necessarily require an optimal route

**Comment by mander76** [comment]
There are two ways (maybe more?) one is to add more waypoints that it should take, somewhere off the optimal route. The other is to use the routing-strategy "random"

**Comment by eknabevcc** [comment]
There are a few related ways in esmini:

1. [AssignRouteAction](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.2.0_Model_Documentation/modelDocumentation/content/AssignRouteAction.html) which finds a route between provided waypoints, if a path can be found without lane changes. Only shortest path is currently supported. Additional waypoints are inserted automatically for each intermediate road between provided waypoints.
Example: [routing-test-route.xosc.txt](https://github.com/esmini/esmini/files/9613306/routing-test-route.xosc.txt)

2. [AcquirePositionAction](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.2.0_Model_Documentation/modelDocumentation/content/AcquirePositionAction.html) is like a short version of AssignRouteAction which takes you from current position (A) to a target position (B), if a path can be found without lane changes. Only shortest path is currently supported. A route is created with inserted waypoints for each intermediate road.
Example: [routing-test-acquire.xosc.txt](https://github.com/esmini/esmini/files/9613288/routing-test-acquire.xosc.txt)

3. The FollowRouteController adds capabilities, inserting lane changes if needed to reach destination and also fully supports the different routing strategies:
    - shortest 
    - fastest (wrt speed limits)
    - leastIntersections

Note: Contrary to Mikael's comment above random strategy is not yet supported.

Example: [follow_route_with_lane_change.xosc](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Unittest/xosc/follow_route_with_lane_change.xosc)
Run as: `./bin/esmini --window 60 60 800 400 --osc ./EnvironmentSimulator/Unittest/xosc/follow_route_with_lane_change.xosc`

But I suspect none of these is what you actually want. To me it seems like you ask for the [TrafficAction](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.2.0_Model_Documentation/modelDocumentation/content/TrafficAction.html) with Sink and Source, spawning random traffic at Source which then are deleted when (eventually) reaching Sink. However, that feature is not yet implemented, unfortunately.

Or did you have something else in mind? In that case, could you elaborate briefly on your use case?

**Comment by eknabevcc** [comment]
BTW: Default routing is random. So if you launch a few vehicles from positions at or close to A they will drive randomly throughout the road network. And you could have a [DeleteEntityAction](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.2.0_Model_Documentation/modelDocumentation/content/DeleteEntityAction.html) lurking at B position - if you want to remove vehicles reaching the goal, for example.

**Comment by qqkkwan** [comment]
Thank you , I can describe the requirements specifically，We have a big opendrive map, we want the car to go from the start point A to the end point B, we want to find a route that satisfies it, the route records a lot of opendrive elements such as road information and so on, we need to capture them down, that's what we need.
But it seems that if the initial position needs to go through a lane change to the target position isn't that impossible to achieve?

**Comment by eknabevcc** [comment]
I see. My suggestion is to make use of the [https://esmini.github.io/#_followroute](FollowRoute controller). 

Have a look at this example scenario: [follow_route_with_lane_change.xosc](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Unittest/xosc/follow_route_with_lane_change.xosc). It has two waypoints, and need to insert a few lane-changes in order to find a path in between.

You can run it from esmini root as follows:
`./bin/esmini --window 60 60 800 400 --osc ./EnvironmentSimulator/Unittest/xosc/follow_route_with_lane_change.xosc`

I'm not sure if you can get/extract needed information, but at least you can see waypoints in the log file, like:

> Route::AddWaypoint Added waypoint 0: 0, -1, 10.00
> Route::AddWaypoint Added waypoint 1: 2, -1, 20.00

The numbers are: waypoint index, `roadId`, `laneId` and `s`

**Comment by eknabevcc** [comment]
And to clarify: Waypoints will be inserted automatically for each intermediate road if needed.

**Comment by qqkkwan** [comment]
good！
