### ISSUE TITLE
How to disabled track lines display

### ISSUE THREAD

**Issue by qqkkwan** [esmini/esmini#325]
Hi,
I would like to know how to disable track line display when I use FollowTrajectoryAction？

**Comment by eknabevcc** [comment]
launch argument = `--hide_trajectories`
key shortcut = `n`

Example: `.\bin\esmini.exe --window 60 60 800 400 --osc .\resources\xosc\lane-change_clothoid_based_trajectory.xosc --hide_trajectories`

Full commands reference here: https://esmini.github.io/#_esmini

**Comment by qqkkwan** [comment]
Thanks
