### ISSUE TITLE
Problem with junction lane links

### ISSUE THREAD

**Issue by johschmitz** [esmini/esmini#328]
It seems that esmini has some problems with junction lane links when they are not redundantly defined in the connecting roads again.

Here is an example: 
[example.zip](https://github.com/esmini/esmini/files/9693084/example.zip)

When running this I am getting errors like:

    No connection from rid 6 lid -1 -> rid 2 eltype 1 - try moving to closest lane

Is this a bug or am I doing something wrong with the OpenDRIVE?

**Comment by eknabevcc** [comment]
My thinking is that the OpenDRIVE is incomplete since lane links are missing for all connecting roads. Here's a modified version with those links added: [bdsc_export_mod.xodr.txt](https://github.com/esmini/esmini/files/9762767/bdsc_export_mod.xodr.txt)

I understand your assumption that these links are not needed since they are implicitly defined by the junction connections. In that regard the linkage in my version is "over defined", but I think its the correct way nonetheless. 

I also checked examples from OpenDRIVE 1.7 (connecting road lane links are defined) and also checked it in the excellent online tool https://odrviewer.io (can't resolve route without connecting road lane links). Conclusion is that esmini interpretation is aligned with those, at least.

So my suggestion is simply that you add the lane links in the connecting roads.

**Comment by johschmitz** [comment]
First of all I already I did add the redundant links and it does work, so I can live with it for my use case. 👍 See version 0.14.1 of my Blender addon to try out a simple first version of the generic junction tool.

Second, nevertheless, I am not sure either if leaving the links in the road out is compliant or not. I can maybe ask about this during one of the next standardization meetings. I think it would be good if esmini could support it since it is well defined logically. Also, if it can not support this, I would strongly recommend for esmini at least to fail more clearly when driving onto this kind of junction. Maybe also throw a clear error message such as "junction lane links missing in road definition" or so. It is quite confusing that right now it works "sometimes a bit" and sometimes the vehicles make weird jumps onto another road.

**Comment by eknabevcc** [comment]
I think that esmini behaves as expected. If there are no links in the road definition there simply aren't any. 

So we will not prioritize to implement additional checking as for now. But of course, if you have a good idea, please make a pull request and we'll definitely consider it. Or close the issue.

I agree with you, I think any further discussion regarding interpretation is good to have in the OpenDRIVE standardization context 👍

**Comment by johschmitz** [comment]
Yeah I think you are right about the low priority of this. I just don't understand the expected behavior thing because if I run the simulation without the redundant links it sometimes can cross some junction links and sometimes not. This confuses me..

**Comment by eknabevcc** [comment]
If there is no link, no car will pass. My assumption is that you run odrviewer and observe the random traffic. And by coincidence cars may appear (when re-spawned) at a connecting road start or end point. So no need to be confused :)
Closing the issue.

**Comment by eknabevcc** [comment]
Actually I run your OpenDRIVE again. And I must admit that some cars DO continue into the intersection, your observation was correct - which is confusing I agree.

Looking closer to why this happens sometimes only, I think the explanation is that when a car moves from an ordinary road into a junction the lane level connection is resolved via the junction laneLink elements. But when moving into another ordinary road it is the lane link element that is consulted. Maybe this is not optimal, and I agree it would be nice to harmonize this handling. We'll keep this in mind for future work.

Thanks for reporting the issue and sorry for dismissing it on wrong grounds!

**Comment by johschmitz** [comment]
Perfect, now we are on the same page 😅. Thanks for the discussion and explanation. I think you also have some code in esmini which automatically resolves missing lane links with some kind of heuristic. I remember thinking that this might be related (don't remember the exact log output). I think it would be good if this kind of "magic" could be enabled/disabled (preferably disabled by default) via a command line switch in order to be able to more easily spot such errors when loading novel OpenDRIVE files for the first time. Maybe you can keep this related topic also in mind when working on this next time.

**Comment by eknabevcc** [comment]
I agree, optional "magic" would be the best of both worlds. Will keep it in mind 👍

**Comment by johschmitz** [comment]
I shortly discussed this in the meeting and have to admit that my thinking regarding this issue was "partially" wrong since the lane linking information in the connecting road is only partially redundant. I think there is no information regarding "outgoing" roads in the junction element. Since it is partially needed anyway I think it makes more sense to always fully supply it.

**Comment by eknabevcc** [comment]
Ah, very good that you already discussed it. Thanks for the info, it seems to make sense as you describe it - junction only keeping record of incoming and connecting roads 👍
