### ISSUE TITLE
Control Ego Vehicle (lane change) via python script

### ISSUE THREAD

**Issue by Abhiram-R** [esmini/esmini#331]
Hello,
I wanted to know if there is any way to perform a lane change maneuver using the esminilib. I couldn't find much in documentation under 'python binding' regarding control over Ego Vehicle.

Any idea on ego vehicle control for changing lanes would be really appreciated as I prefer using esmini very much for my project work. 

Edit: The whole idea is to fetch the current ego vehicle position data every 'x' seconds from the simulator and find available lanes and then perform the lanechange maneuver.

**Comment by eknabevcc** [comment]
Interesting use case. Regarding finding a good opportunity for a lane change I think you need to ask esmini about other road users, e.g. using [SE_GetNumberOfObjects()](https://github.com/esmini/esmini/blob/3d2600dab0f7aab20b9a45fa4f14deb42a1148c8/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L702) and [SE_GetObjectState()](https://github.com/esmini/esmini/blob/3d2600dab0f7aab20b9a45fa4f14deb42a1148c8/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L717). See example [get_states.py](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/code-examples/hello_world/get_states.py). 

Then the actual lane change. One way of doing it is to define the lane change maneuvers in a scenario file (OpenSCENARIO) and then just trig the events from the Python script. I made a simple example, see here: [code-examples/trig_lane_change](https://github.com/esmini/esmini/tree/master/EnvironmentSimulator/code-examples/trig_lane_change). 

Video clip: https://youtu.be/5N3JH4n4T7o

**Comment by Abhiram-R** [comment]
I know only a few features from the OpenSCENARIO model documentation. The example code and xosc [code-examples/trig_lane_change](https://github.com/esmini/esmini/tree/master/EnvironmentSimulator/code-examples/trig_lane_change) gave me new ideas to use SE_SetParameterBool() and the 'ParameterCondition'. I think my doubts regarding lane change is solved. Thanks a lot! [eknabevcc](https://github.com/eknabevcc).
