### ISSUE TITLE
run with python script

### ISSUE THREAD

**Issue by kikiQuentin** [esmini/esmini#333]
Hello,
I want to call the callback function in the esmini-player.py from object_callback.py. But because both python files initialize the same cut-in. xosc scenario, an error was reported. The error is 'The core has been dumped' .
I tried to solve the problem but the effect was not good. Is there any other way to solve it? I would appreciate it if there is a way to solve this problem.

The callback function file path is as follows:/esmini/EnvironmentSimulator/code_examples/hello_world/object_callback.py

**Comment by eknabevcc** [comment]
You're right. The search path gets wrong. I added a path in the script so hopefully it's possible to run now (commit [098bba4](https://github.com/esmini/esmini/commit/098bba4e3655287c9d67a2407609a0bf5f0b2335)) - merged on master branch.

Get the updated script:
`git pull`

Example how to run from `Hello-World_coding-example` folder:
`..\EnvironmentSimulator\code-examples\hello_world\object_callback.py`

Please try and let us know if it works better.

**Comment by kikiQuentin** [comment]
Thank you. It works better with your help. In addition, I would like to ask what the callback function parameters state_ptr and b mean in the object_callback.py file. I still don't know how they are defined.

The callback function in the object_callback.py file is defined as follows：
def callback(state_ptr, b):
    state = state_ptr.contents
    print("callback for obj {}: x={:.2f} y={:.2f} h={:.2f}".format(state.id, state.x, state.y, state.h))
    se.SE_ReportObjectPosXYH(ct.c_int(state.id), ct. c_float(state.timestamp), ct.c_float(state.x + 0.02), ct.c_float(state.y), ct.c_float(state.h + 0.001))

**Comment by eknabevcc** [comment]
This is a bit tricky, but I'll try to explain:

The object callback function must be with the following type:
`void (*fnPtr)(SE_ScenarioObjectState *, void *)`
Which means: 
A function taking two parameters: 
  1. pointer/reference to a SE_ScenarioObjectState struct and 
  2. a pointer/reference to undefined data (this is a common way to allow user to pass any data he/she needs in the callback)

and returning nothing/void.

Simple example of such a function header in C:
[void objectCallback(SE_ScenarioObjectState* state, void* my_data)](https://github.com/esmini/esmini/blob/50144bf71894a542c86eb560feec1664029d2295/EnvironmentSimulator/Unittest/ScenarioEngineDll_test.cpp#L2185)

In the Python case we have this header:
`def callback(state_ptr, b)`

state_ptr is a pointer/reference to a SEScenarioObjectState struct. To access the content we use:
`state = state_ptr.contents`
then we can easily read the various fields of the struct, e.g. `state.x`.

The 'b' parameter is a dummy placeholder carrying the pointer/reference to any passed user data - in this case nothing - (see `ct.c_void_p` below).

The following two lines will create a typed reference to the callback function (here you see how to represent a void parameter):
`callback_type = ct.CFUNCTYPE(None, ct.POINTER(SEScenarioObjectState), ct.c_void_p)`
`callback_func = callback_type(callback)`
to be used when register the callback.

Finally it's time to register the callback. The C header for that function is:
[`void SE_RegisterObjectCallback(int object_id, void (*fnPtr)(SE_ScenarioObjectState *, void *), void *user_data)`](https://github.com/esmini/esmini/blob/50144bf71894a542c86eb560feec1664029d2295/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L857)

First integer is the object_id which will be represented in the SEScenarioObjectState struct passed in the callback. Second argument is the reference to the callback function as created above. The third and final argument is the optional user data - which most often is not needed.

In Python code the call looks like:
`se.SE_RegisterObjectCallback(0, callback_func, 0)`
First 0 is the object_id, then we have the callback function reference and the final zero says we don't need to pass any user data.

I hope it's a bit clearer - but maybe I caused even more confusion :)

All that said: This feature, object_callback, I would assume is VERY rarely needed. I think for most use cases it's good enough to call `SE_GetObjectState()` and potentially the `SE_ReportObject*` functions in between each call to `SE_Step*`. So maybe you can reconsider whether you really need to use the callback method.

**Comment by kikiQuentin** [comment]
Thank you for your patient explanation. I complicated the problem.

**Comment by eknabevcc** [comment]
It was good for me to look through and "document" the callback procedure anyway 👍

Yes, I hope you find a simpler solution. I close the issue now. Please re-open for further related questions.
