### ISSUE TITLE
lane error

### ISSUE THREAD

**Issue by csawp** [esmini/esmini#337]
Vehicles in the right lane run in the left lane
![image](https://user-images.githubusercontent.com/114643211/197327967-5329e220-ddf9-4f0e-bcb7-5c81c37c1f74.png)
[lane.zip](https://github.com/esmini/esmini/files/9843840/lane.zip)

**Comment by csawp** [comment]
https://github.com/esmini/esmini/commit/ba3c7d2168213f71bd36a35eeac923d9b0f9edbc
There are still problems that have not been resolved

**Comment by csawp** [comment]
![image](https://user-images.githubusercontent.com/114643211/197926177-4a25f0bb-c748-45d7-a884-b615a435f358.png)
int Road::GetLaneInfoByS(double s, int start_lane_section_idx, int start_lane_id, LaneInfo& lane_info, int laneTypeMask)
{
	lane_info.lane_section_idx_ = start_lane_section_idx;
	lane_info.lane_id_ = start_lane_id;

	if (lane_info.lane_section_idx_ >= (int)lane_section_.size() || lane_info.lane_section_idx_ < 0)
	{
		LOG("Error idx %d > n_lane_sections %d\n", lane_info.lane_section_idx_, (int)lane_section_.size());
	}
	else
	{
		LaneSection *lane_section = lane_section_[lane_info.lane_section_idx_];
		double width = lane_section->GetCenterOffset(s, lane_info.lane_id_);
		if (width < SMALL_NUMBER)
		{
			LOG("The coordinates need to be reset when the road lane width is 0");
			return -1;
		}
		// check if we passed current section
		if (s > lane_section->GetS() + lane_section->GetLength() || s < lane_section->GetS())
		{
			if (s > lane_section->GetS() + lane_section->GetLength())
			{
				while (s > lane_section->GetS() + lane_section->GetLength() && lane_info.lane_section_idx_ + 1 < GetNumberOfLaneSections())
				{
					// Find out connecting lane, then move to next lane section
					lane_info.lane_id_ = lane_section->GetConnectingLaneId(lane_info.lane_id_, SUCCESSOR);
					lane_section = GetLaneSectionByIdx(++lane_info.lane_section_idx_);
				}
			}
			else if (s < lane_section->GetS())
			{
				while (s < lane_section->GetS() && lane_info.lane_section_idx_ > 0)
				{
					// Move to previous lane section
					lane_info.lane_id_ = lane_section->GetConnectingLaneId(lane_info.lane_id_, PREDECESSOR);
					lane_section = GetLaneSectionByIdx(--lane_info.lane_section_idx_);
				}
			}

			// If new lane is not of snapping type, try to move into a close valid lane
			Lane* lane = lane_section->GetLaneById(lane_info.lane_id_);
			if (lane == 0 || !(laneTypeMask & lane_section->GetLaneById(lane_info.lane_id_)->GetLaneType()))
			{
				double offset = 0;

				if (lane == 0)
				{
					LOG("No valid connecting lane (s: %.2f lane_id %d) - looking for closest valid lane", s, lane_info.lane_id_);
				}
				double t = SIGN(lane_info.lane_id_) * width;
				lane_info.lane_id_ = lane_section->GetLaneByIdx(lane_section->GetClosestLaneIdx(s, t, offset, true, laneTypeMask))->GetId();
				if (lane_info.lane_id_ == 0 || SIGN(lane_info.lane_id_) != SIGN(start_lane_id))
				{
					LOG("Failed to find a closest snapping lane");
					return -1;
				}
			}
		}
	}

	return 0;
}
To solve the problem that the road lane width is 0, you need to reset the coordinates

**Comment by csawp** [comment]
It seems that the route with lane width of 0 is also included
AddWaypoint and MoveRouteDS It is unknown which of the two functions has a problem

**Comment by eknabevcc** [comment]
Yes, you're right. The fix only handles when lane cease to exist. I forgot to check the case where lane-width becomes zero. 
I will look into it.

**Comment by csawp** [comment]
AddWaypoint(1，-1, 0);
AddWaypoint(1，-1, 250);
Or enter the reverse lane

**Comment by csawp** [comment]
https://github.com/esmini/esmini/commit/931e00443b3794a5c75810e3c6c755e042a2d269
There is still a problem. I don't know where my settings are incorrect

**Comment by csawp** [comment]
https://github.com/esmini/esmini/commit/931e00443b3794a5c75810e3c6c755e042a2d269
There is still a problem. I don't know where my settings are incorrect

**Comment by eknabevcc** [comment]
Some experimental refactorization on the lane type handling ongoing, not complete. Maybe we will redo it. 
I will let you know when its ready for next test.

**Comment by csawp** [comment]
nice, I will look forward to your reconstruction land version.

**Comment by eknabevcc** [comment]
You can test new commit (new branch as well).
It should handle 1. Lane cease to exist and 2. Lane width becoming zero.
Please report how it works for your use case. If still issues, can you share the scenario or some application code (or at least snippet enough to reproduce the issue).

**Comment by csawp** [comment]
Finally solved, but there was a small problem, redefining variables
![image](https://user-images.githubusercontent.com/114643211/198559620-9ce5d432-2a03-46a0-a23e-2a7f9933651f.png)

**Comment by eknabevcc** [comment]
Good finding. It's now fixed as well. 
Thanks for quick test. The branch is now merged to master.
Closing the issue.
