### ISSUE TITLE
FollowRouteController shows double the velocity in one time step before a lane change

### ISSUE THREAD

**Issue by MichaelHarth** [esmini/esmini#338]
Hello,

I noticed that the FollowRouteController shows double the velocity in one time step before a lane change. I used the following command with the files already uploaded in [issue #355](https://github.com/esmini/esmini/issues/335#issuecomment-1290392747):

esmini --headless --osc generic_city.xosc --fixed_timestep 0.001 --csv_logger generic_city.csv

At time step 2.951 in the csv file, I recognized double the velocity, which is also associated with double the traveled distance and very high acceleration in this time step:

![follow_route_controller_velocity_increase](https://user-images.githubusercontent.com/82376333/198521320-94ec3719-256e-4669-96a7-3993f86850db.PNG)

I could also replicate the issue with follow_route_with_lane_change.xosc from the examples.

**Comment by MichaelHarth** [comment]
Thank you for fixing the issue.

**Comment by eknabevcc** [comment]
Ah, I forgot to mention here that release [v2.26.8](https://github.com/esmini/esmini/releases/tag/v2.26.8) includes the fix.
I close the issue now. Let us know if issue remains or you see some (unwanted) side effects.

**Comment by eknabevcc** [comment]
And by the way, thanks a lot for reporting this bug!
