### ISSUE TITLE
External ALKS Controller as FMU

### ISSUE THREAD

**Issue by jdsika** [esmini/esmini#341]
Hi all,

would it be possible to integrate an external controller (model) as [OSMP Traffic Participant FMU](https://opensimulationinterface.github.io/osi-documentation/#_osmp_specification). We are evaluating if the [autoware](https://github.com/autowarefoundation/autoware.universe) ALSK ROS wrapped controller could be packaged as as FMU.
Alternative: Take the contoller here.

Question: Do we even need the input/output signals of the controller?

Involved parties: @pmai @martinboehmtt

**Comment by eknabevcc** [comment]
Unfortunately I'm noob when it comes to FMU. But it sounds like an interesting idea.

I think we would need signals from FMU to update the corresponding traffic participant in esmini. At least in cases where other entities depends on it, e.g. relative distance action or condition.

Probably it would be possible, but hard to estimate effort. Currently we have no similar work planned. But I'll keep this in mind.

BTW: What do you mean with "Alternative: Take the controller here"? (maybe implement as C++ controller with no FMU interface?)

**Comment by jdsika** [comment]
Here is an example for a sensor model which uses an OSI FMU [here](https://github.com/openMSL/object_based_generic_perception_object_model). Maybe this is a good example to get aquainted with FMI?

I meant that we wrap a controller here as FMU in order to demonstrate that esmini can integrate OSI FMUs

**Comment by eknabevcc** [comment]
If I try to summarize I see the follow two main approaches:

![image](https://user-images.githubusercontent.com/29146839/216824115-64c019f5-7f3d-4af5-8e36-53bd7a3b7dd8.png)

I find this very interesting, and for each week I wish there would be more time for looking into this topic. But just looking at todo list I realize I will not be able to do anything substantial in near time, since it's still low prio from internal users.

So any external help/contributions would be highly appreciated. I think the only way to make this happen is as collaboration with following three roles:
1. User/stakeholder (providing the use case and test the implementation)
2. Implementer (doing most of the implementation)
3. esmini technical support (e.g. knows esmini API and can extend/adapt it)

Of course 1 and 2 can be the same person/organization.

I can of course volunteer as the esmini technical support. @jdsika: Do you think @ClemensLinnhoff's approach would work with the use case you had in mind? 

@MartinBoehmTT: Do you see a preferred approach, maybe even interested in contributing/helping with implementation?

**Comment by jdsika** [comment]
Hi Emil,

I would like to represent the user/stakeholder side of things and the application would be the OSI sensor model testing architecture we are drafting in [OpenMSL](https://github.com/openMSL/sensor_model_testing/blob/main/doc/test_architecture.md). 
I will talk to Clemens but my first impule what be to opt for **Alt 2**?

Best regards
Carlo

**Comment by jdsika** [comment]
Modify the build pipeline for every release to include e.g. the `esmini_win10_x64.fmu` into the corresponding .zip package

**Comment by MartinBoehmTT** [comment]
Hi Emil,

thanks for the summarizing both approaches. 
To be honest, when talking about this topic I always had option 1 in mind, so integrating a custom FMU directly with esmini. But option 2 could make sense as well of course. 
Unfortunately, right now it is not completely clear for me what option 2 would mean technically. Therefore, I would be happy if we could maybe clarify the necessary steps in a joint discussion.
 
@ClemensLinnhoff : Would you be willing in giving us an overview of your proposed solution as well as a discussion of necessary steps for implementing something like this?

Thanks and regards
Martin

**Comment by ClemensLinnhoff** [comment]
I am going to look into what the necessary steps would be and come back to you.

**Comment by eknabevcc** [comment]
> Hi Emil,
> 
> thanks for the summarizing both approaches. To be honest, when talking about this topic I always had option 1 in mind, so integrating a custom FMU directly with esmini. But option 2 could make sense as well of course. Unfortunately, right now it is not completely clear for me what option 2 would mean technically. Therefore, I would be happy if we could maybe clarify the necessary steps in a joint discussion.
> 
> @ClemensLinnhoff : Would you be willing in giving us an overview of your proposed solution as well as a discussion of necessary steps for implementing something like this?
> 
> Thanks and regards Martin

Naively I think option 2 would be simpler to implement. Roughly, I think it means that the FMU will link needed esmini modules, either picking individual modules for static linking OR link the esminiLib dynamically. Maybe when I learn more about FMU it will be clearer which of the two approaches (static or dynamic linking) is best in this case. I imagine that the FMU internally will call esmini SE_Init() and SE_Step*() functions and fetching groundtruth from esmini OSI output (which is also done via function call).

**Comment by ClemensLinnhoff** [comment]
I just pushed a [first draft](https://github.com/esmini/esmini/pull/409) with an example using the esmini API in an OSMP FMU. Feel free to check it out.

**Comment by ClemensLinnhoff** [comment]
For now this only outputs the OSI ground truth in a SensorView message. This enables connecting a sensor model FMU. It does not yet contain a backchannel for controlling a traffic participant via OSI. I see this as a subsequent step in a secondary pull request.

**Comment by eknabevcc** [comment]
Great! Thanks @ClemensLinnhoff for implementing this feature.
https://github.com/esmini/esmini/tree/master/OSMP_FMU

I close the issue now. We can open new ones for potential add-ons later 👍
