### ISSUE TITLE
Is there a function to get ScenarioObject names? 

### ISSUE THREAD

**Issue by rwisi** [esmini/esmini#345]
Currently, the esminiLib.hpp header file contains a struct SE_ScenarioObjectState which has an "automatically generated ID". Can you please also add the string ScenarioObject name as well?

Or maybe there is another implementation I have missed and any guidance on this is greatly appreciated :)

Thanks.

**Comment by eknabevcc** [comment]
You're right. The SE_ScenarioObjectState struct does not contain the name string. Reason is to keep struct as lean as possible. For example, this content is stored for each timestep and entity into .dat file for later replay of the scenario.

There are two functions: 
[SE_GetObjectTypeName()](https://github.com/esmini/esmini/blob/0767118341eb6aac480cb19c7fccc643bab32ebc/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L732) and
[SE_GetObjectName()](https://github.com/esmini/esmini/blob/0767118341eb6aac480cb19c7fccc643bab32ebc/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L739)
that you can use to find out the type and name, based on object ID.

Would that be sufficient for your use case?

**Comment by rwisi** [comment]
Is there a function to get Object ID from ScenarioObject name?

**Comment by eknabevcc** [comment]
No there is :)
[SE_GetIdByName()](https://github.com/esmini/esmini/blob/cd476a77a2888f7a65208fe37beb06d7e1dd322e/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L711)
It makes sense to have a function like that.
See example in test case: [TestGetIdByName](https://github.com/esmini/esmini/blob/cd476a77a2888f7a65208fe37beb06d7e1dd322e/EnvironmentSimulator/Unittest/ScenarioEngineDll_test.cpp#L2540)

**Comment by rwisi** [comment]
That's great. Thank you :)

I will close the issue after testing it in my implementation.

**Comment by eknabevcc** [comment]
Included in release [v2.26.9](https://github.com/esmini/esmini/releases/tag/v2.26.9)

**Comment by rwisi** [comment]
Issue resolved. Thank you.
