### ISSUE TITLE
Errors when building esmini under Windows

### ISSUE THREAD

**Issue by TilmanBuente** [esmini/esmini#349]
Hello esmini team,

thanks for developing esmini!

Building esmini under Ubuntu 22.04 works fine but under Windows 10 I run into problems.
So far I have followed these instructions: https://esmini.github.io/#_build_guide

I feel the simplest is to paste the contents of my cmd shell, see below.
Can you help? Thank you very much.

Kind regards
Tilman

D:\users\buente\Git\esmini\build>cmake ..
-- Building for: Visual Studio 15 2017
-- CMake version: 3.25.0-rc4
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.16.27045.0
-- The CXX compiler identification is MSVC 19.16.27045.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at cmake/cache.cmake:27 (message):
  ccache is enabled but was not found.  Not using it
Call Stack (most recent call first):
  cmake/project_options.cmake:6 (enable_cache)
  CMakeLists.txt:84 (include)

Unsupported Windows configuration
Add version file
-- downloading osg.7z ...
-- extracting osg.7z ...
-- downloading osi.7z ...
-- extracting osi.7z ...
-- downloading sumo.7z ...
-- extracting sumo.7z ...
-- downloading googletest.7z ...
-- extracting googletest.7z ...
-- downloading models.7z ...
-- extracting models.7z ...
Submodule 'test/OSC-ALKS-scenarios' (https://github.com/arauschert/OSC-ALKS-scenarios.git) registered for path 'test/OSC-ALKS-scenarios'
Cloning into 'D:/users/buente/Git/esmini/test/OSC-ALKS-scenarios'...
Submodule path 'test/OSC-ALKS-scenarios': checked out '289f12bfdcf716e9fa035a3348ebf920c408ec9c'
-- Configuring done
-- Generating done
-- Build files have been written to: D:/users/buente/Git/esmini/build

D:\users\buente\Git\esmini\build>cmake --build . --config Release --target install
Microsoft (R)-Build-Engine, Version 15.9.21+g9802d43bc3 für .NET Framework
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

  Checking Build System
  Generating D:/users/buente/Git/esmini/EnvironmentSimulator/Modules/CommonMini/_version.cpp, D:/users/buente/Git/esmini/EnvironmentSimulator/Modules/CommonMini/version.cpp
  Building Custom Rule D:/users/buente/Git/esmini/EnvironmentSimulator/Modules/CommonMini/CMakeLists.txt
  Microsoft (R) C/C++-Optimierungscompiler Version 19.16.27045 für x86
  Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

  CommonMini.cpp
  cl /c /ID:\users\buente\Git\esmini\externals\pugixml /ID:\users\buente\Git\esmini\externals\expr /W4 /WX- /diagnostics:classic /O2 /Ob2 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D NOMINMAX /D NDEBUG /D _USE_OSG /D _USE_OSI /D _USE_SUMO /D _USE_GTEST /D _CRT_SEC
  URE_NO_WARNINGS /D "CMAKE_INTDIR=\"Release\"" /Gm- /EHsc /MD /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++14 /Fo"CommonMini.dir\Release\\" /Fd"CommonMini.dir\Release\CommonMini.pdb" /Gd /TP /wd4127 /wd4100 /analyze- /errorR
  eport:queue D:\users\buente\Git\esmini\EnvironmentSimulator\Modules\CommonMini\CommonMini.cpp D:\users\buente\Git\esmini\EnvironmentSimulator\Modules\CommonMini\UDP.cpp D:\users\buente\Git\esmini\EnvironmentSimulator\Modules\CommonMini\version.cpp D:\user
  s\buente\Git\esmini\EnvironmentSimulator\Modules\CommonMini\buildnr.cpp

D:\users\buente\Git\esmini\EnvironmentSimulator\Modules\CommonMini\CommonMini.cpp(132): warning C4018: "<": Konflikt zwischen "signed" und "unsigned" [D:\users\buente\Git\esmini\build\EnvironmentSimulator\Modules\CommonMini\CommonMini.vcxproj]
D:\users\buente\Git\esmini\EnvironmentSimulator\Modules\CommonMini\CommonMini.cpp(1375): warning C4018: "<": Konflikt zwischen "signed" und "unsigned" [D:\users\buente\Git\esmini\build\EnvironmentSimulator\Modules\CommonMini\CommonMini.vcxproj]
D:\users\buente\Git\esmini\EnvironmentSimulator\Modules\CommonMini\CommonMini.cpp(1406): warning C4018: "<": Konflikt zwischen "signed" und "unsigned" [D:\users\buente\Git\esmini\build\EnvironmentSimulator\Modules\CommonMini\CommonMini.vcxproj]
D:\users\buente\Git\esmini\EnvironmentSimulator\Modules\CommonMini\CommonMini.cpp(1411): warning C4018: "<": Konflikt zwischen "signed" und "unsigned" [D:\users\buente\Git\esmini\build\EnvironmentSimulator\Modules\CommonMini\CommonMini.vcxproj]
D:\users\buente\Git\esmini\EnvironmentSimulator\Modules\CommonMini\CommonMini.cpp(1428): warning C4018: "<": Konflikt zwischen "signed" und "unsigned" [D:\users\buente\Git\esmini\build\EnvironmentSimulator\Modules\CommonMini\CommonMini.vcxproj]
  UDP.cpp
  version.cpp
  buildnr.cpp
  Code wird generiert...
  CommonMini.vcxproj -> D:\users\buente\Git\esmini\build\EnvironmentSimulator\Modules\CommonMini\Release\CommonMini.lib
  Building Custom Rule D:/users/buente/Git/esmini/EnvironmentSimulator/Unittest/CMakeLists.txt
  Microsoft (R) C/C++-Optimierungscompiler Version 19.16.27045 für x86
  Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

  CommonMini_test.cpp
  cl /c /ID:\users\buente\Git\esmini\externals\pugixml /ID:\users\buente\Git\esmini\externals\expr /ID:\users\buente\Git\esmini\EnvironmentSimulator\Modules\ScenarioEngine\SourceFiles /ID:\users\buente\Git\esmini\EnvironmentSimulator\Modules\ScenarioEngine\
  OSCTypeDefs /ID:\users\buente\Git\esmini\EnvironmentSimulator\Libraries\esminiLib /ID:\users\buente\Git\esmini\EnvironmentSimulator\Libraries\esminiRMLib /ID:\users\buente\Git\esmini\EnvironmentSimulator\Modules\CommonMini /ID:\users\buente\Git\esmini\Env
  ironmentSimulator\Modules\RoadManager /ID:\users\buente\Git\esmini\EnvironmentSimulator\Modules\ViewerBase /ID:\users\buente\Git\esmini\EnvironmentSimulator\Modules\PlayerBase /ID:\users\buente\Git\esmini\EnvironmentSimulator\Modules\Controllers /ID:\user
  s\buente\Git\esmini\EnvironmentSimulator\Applications\replayer /ID:\users\buente\Git\esmini\EnvironmentSimulator\..\externals\googletest\include /ID:\users\buente\Git\esmini\EnvironmentSimulator\..\externals\OSI\include /ID:\users\buente\Git\esmini\Enviro
  nmentSimulator\..\externals\OpenSceneGraph\build\include /ID:\users\buente\Git\esmini\EnvironmentSimulator\..\externals\OpenSceneGraph\include /ID:\users\buente\Git\esmini\externals\dirent\win /W4 /WX- /diagnostics:classic /O2 /Ob2 /Oy- /D _MBCS /D WIN32
  /D _WINDOWS /D NOMINMAX /D NDEBUG /D _USE_OSG /D _USE_OSI /D _USE_SUMO /D _USE_GTEST /D _CRT_SECURE_NO_WARNINGS /D OSG_LIBRARY_STATIC /D "CMAKE_INTDIR=\"Release\"" /Gm- /EHsc /MD /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c+
  +14 /Fo"CommonMini_test.dir\Release\\" /Fd"CommonMini_test.dir\Release\vc141.pdb" /Gd /TP /wd4127 /wd4100 /analyze- /errorReport:queue D:\users\buente\Git\esmini\EnvironmentSimulator\Unittest\CommonMini_test.cpp

D:\users\buente\Git\esmini\EnvironmentSimulator\Unittest\CommonMini_test.cpp(1): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "gtest/gtest.h": No such file or directory [D:\users\buente\Git\esmini\build\EnvironmentSimulator\Unittest\Common
Mini_test.vcxproj]

#  AND SOME MORE ERRORS OF THE SAME KIND APPEAR:  

d:\users\buente\git\esmini\environmentsimulator\modules\scenarioengine\sourcefiles\OSIReporter.hpp(17): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "osi_sensordata.pb.h": No such file or directory [D:\users\buente\Git\esmini\build\Environ
mentSimulator\Modules\ScenarioEngine\ScenarioEngine.vcxproj]
  Parameters.cpp

D:\users\buente\Git\esmini\EnvironmentSimulator\Modules\Controllers\ControllerSumo.cpp(19): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "utils/geom/PositionVector.h": No such file or directory [D:\users\buente\Git\esmini\build\Environment
Simulator\Modules\Controllers\Controllers.vcxproj]
  ControllerUDPDriver.cpp

D:\users\buente\Git\esmini\EnvironmentSimulator\Applications\replayer\osi_receiver.cpp(17): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "osi_common.pb.h": No such file or directory [D:\users\buente\Git\esmini\build\EnvironmentSimulator\Ap
plications\replayer\osireceiver.vcxproj]

D:\users\buente\Git\esmini\EnvironmentSimulator\Unittest\RoadManager_test.cpp(2): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "gtest/gtest.h": No such file or directory [D:\users\buente\Git\esmini\build\EnvironmentSimulator\Unittest\RoadM
anager_test.vcxproj]

D:\users\buente\Git\esmini\EnvironmentSimulator\Unittest\RoadManagerDll_test.cpp(1): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "gtest/gtest.h": No such file or directory [D:\users\buente\Git\esmini\build\EnvironmentSimulator\Unittest\Ro
adManagerDll_test.vcxproj]

D:\users\buente\Git\esmini\EnvironmentSimulator\Modules\ScenarioEngine\SourceFiles\OSIReporter.hpp(17): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "osi_sensordata.pb.h": No such file or directory [D:\users\buente\Git\esmini\build\Environ
mentSimulator\Modules\PlayerBase\PlayerBase.vcxproj]

**Comment by eknabevcc** [comment]
I think the root cause is that you build for win32 (32 bit). I realize it's not obvious from the User guide, actually it appears to be possible to build for win32. 

The guide has now been updated with some additional information about Windows 32 bit limitations. See [User guide - Build configurations](https://esmini.github.io/#_build_configurations).

In summary, try the following:

`cmake .. -A x64`

or more explicitly: `cmake .. -G "Visual Studio 15 2017" -A x64`

maybe you need to first to delete the file `CMakeCache.txt` to clean the old settings.

See more info here: [cmake and Visual Studio 15 2017](https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2015%202017.html)

Please report how it goes.

**Comment by TilmanBuente** [comment]
Thank you, Emil, for your prompt, valuable, and appropriate hint.
Now it builds smoothly :-)
