### ISSUE TITLE
SE_AddObjectSensor issue

### ISSUE THREAD

**Issue by echod-wmg** [esmini/esmini#351]
Hello,

I am trying to create a sensor model and attach it to the vehicle.
I use Python so I applied ctypes to insert inputs within SE_AddObjectSensor from the esmini API.

The simulation can't go through the sensor line when I run the code. It does not generate any errors, but esmini player is not responding.
Has anyone experienced a similar issue?

Many thanks.

**Comment by eknabevcc** [comment]
ctypes do not recognize float types, so for functions returning or having arguments of non int types it seems that specifications are needed. The trick is to define arguments for the function, like for this function:
``` c++
int SE_AddObjectSensor(int object_id, float x, float y, float z, float h, float rangeNear, float rangeFar, float fovH, int maxObj);
```
It should be:
``` c++
se.SE_AddObjectSensor.argtypes = [
    ctypes.c_int,
    ctypes.c_float,
    ctypes.c_float,
    ctypes.c_float,
    ctypes.c_float,
    ctypes.c_float,
    ctypes.c_float,
    ctypes.c_float,
    ctypes.c_int
]

```
(It could probably even be possible to define a "wrapper" for complete API, but then it needs to be updated. BTW maybe there are tools that could generate such wrapper from a C++ header file...)

Anyway, I added an example showing how it can be done for sensors:
[code-example/hello_world/add_sensor.py](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/code-examples/hello_world/add_sensor.py)

**Comment by hcLime** [comment]
Many thanks for that.
I can confirm that it works flawlessly now.

Now, I'm wondering how I can read/process the SensorData generated by the added sensor.
I'm feeding the OSI Groundtruth data through the UDP. Can I do something similar with SensorData?
How I can process the output of SE_GetOSISensorDataRaw() within Python?

**Comment by eknabevcc** [comment]
Maybe I should have mentioned before, that esmini do not populate OSI sensor data. The idea, or how we use it, is to output the complete ground truth and hand over sensor modeling to the external vehicle (under test) simulator. 

So the esmini sensors are not directly related to OSI, but they can be used in combination with esmini API calls to fetch states of objects in the simulation. 

Assume you have a lot of vehicles in the scenario and you're only interested in the ones close to the ego vehicle, or even in front of it. Then the esmini sensors can be used to filter out vehicles of interest, and then retrieve detailed status only for those ones. 

Like in the "Ideal sensors" example in the [User guide - Hello world section](https://esmini.github.io/#_ideal_sensors). 

But all this is making use of the high level API, not UDP. Would that be feasible for you, or you need UDP link?

**Comment by hcLime** [comment]
Okay, so the sensor only detects entities within the given zone and then states of objects are obtained from esmini API, is that correct?
Is it feasible to detect other types of objects like stationary objects with a sensor?

Many thanks.

**Comment by eknabevcc** [comment]
Yes you're right. These simple "cull" sensors detects entities within the view frustum of the sensor. You can get the IDs of detected objects. With that info you can then retrieve further details of the objects by using the `SE_GetObjectState()` function.

Unfortunately only [scenario entity objects](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.2.0_Model_Documentation/modelDocumentation/content/EntityObject.html) are considered by the simple sensors, not stationary objects defined in the OpenDRIVE. The OSI stream contains both though.

However, stationary (misc) objects defined in OpenSCENARIO are still considered. Like the box in example scenario [drop-bike.xosc](https://github.com/esmini/esmini/blob/master/resources/xosc/drop-bike.xosc).

![drop_bike](https://user-images.githubusercontent.com/29146839/202733866-17fec624-ed65-48e1-beff-829dfd0f8ea6.jpg)
