### ISSUE TITLE
Timestep in generated OSI file

### ISSUE THREAD

**Issue by msalmirim** [esmini/esmini#352]
Hi,

Is there a way to control the sampletime for the generation of the OSI groundtruth data through esmini i.e setting an identical timestep between the frames ?

Thanks in advance.
Rim

**Comment by eknabevcc** [comment]
To control the overall scenario time step:
Command line: Add launch argument `--fixed_timestep 0.05` (or your preferred step size)
API: `SE_StepDT(0.05f);`

If you need higher frequency on simulation than OSI, you can for example set `--osi_freq 5`. Then OSI is saved only every 5:th simulation step.

Example:
`./bin/esmini --headless --fixed_timestep 0.01 --osc ./resources/xosc/cut-in.xosc --osi_file gt.osi --osi_freq 5`
will run simulation in 100 Hz while OSI in 20 Hz (time step 0.05).

**Comment by msalmirim** [comment]
Thanks a lot Emil. I have missed the --osi-freq option.
