### ISSUE TITLE
Question : Position of the center of the bounding box when road network is defined 

### ISSUE THREAD

**Issue by msalmirim** [esmini/esmini#355]
Hi,

When running the cut-in scenario and generating corresponding OSI data I noticed that the z coordinates for the moving objects (two vehicles) is set to 0.
As I understand it the reference point should be the center of the bounding box and in that case x, y, x should correspond to the coordinates of the center of the bounding box in world coordinate. So I expected z to be non-zero even with the presence of a road network.

Any explanation for why the z coordinate of the center of the bounding box is set to zero when a road network is defined ? Or is it probably a bug ?

Thanks in advance for your support.
Rim

**Comment by eknabevcc** [comment]
Thanks for pointing out. I agree, it seems to be wrongly calculated in esmini (bug, neglection or misundersting...).

To my understanding the line [749](https://github.com/esmini/esmini/blob/99b7f2aef94bee3533a57c103cc91ee40a268ecb/EnvironmentSimulator/Modules/ScenarioEngine/SourceFiles/OSIReporter.cpp#L749) should be:
`obj_osi_internal.mobj->mutable_base()->mutable_position()->set_z(objectState->state_.pos.GetZ() + objectState->state_.info.boundingbox.dimensions_.height_ / 2.0);`

Would you agree @mguldogu and @mander76?

**Comment by mguldogu** [comment]
@eknabevcc Yes I agree that it should be updated as you suggested. As you have said, I think **z-coordinate** has been neglected in the osi parts mainly as we have initially focussed on 2D calculations from sensors point of view.

@msalmirim Thanks for pointing it out..

**Comment by eknabevcc** [comment]
Good, I fix tomorrow 👍

**Comment by eknabevcc** [comment]
Should be fixed on master branch now. Will be included in next release.
