### ISSUE TITLE
can't use shortcuts while playing esmini

### ISSUE THREAD

**Issue by tgjht2022** [esmini/esmini#359]
Hi, there. I'm new to esmini and met some problems while running the scenario using esmini.
When esmini is playing in the window, I can't receieve any responce pressing the keyboard. The esmini window still stays the same and keeps playing itself. I'm wondering if there's something wrong with my operation. 
I've tried both on my laptop and desktop, but that did not make any difference.
My windows version is win10 and the repo  I downloaded is of the lastest version f151ea1.

**Comment by eknabevcc** [comment]
The following is what is expected:
esmini window catch the focus, so any key and mouse events goes to esmini application. To verify this behavior, press “esc” key and esmini should quit. 
To hand over key and mouse events to any other window, just click on that window, for example a terminal/console.

Let us know if your esmini is not working as above and we will investigate further together.

**Comment by eknabevcc** [comment]
BTW: Also make sure that Caps-Lock is not active (esmini does not recognize 'R' as 'r', for example).

**Comment by tgjht2022** [comment]
Thanks for your reply.
`esmini window catch the focus, so any key and mouse events goes to esmini application. To verify this behavior, press “esc” key and esmini should quit.`
Yeah, that's what I expected. But as I started from the powershell and clicked on the esmini window, pressing "esc" didn't work, which means my esmini failed to catch the keyboard focus. Btw, if I don't press any key and hold left mouse to rotate the camera, it works. But as long as I press a single key, the esmini window stucks and it's impossible for me to rotote the camera or close the window. The only way is to wait until the program ends.

`BTW: Also make sure that Caps-Lock is not active (esmini does not recognize 'R' as 'r', for example).`
I've checked this, but the problem still exists.

**Comment by eknabevcc** [comment]
Ah, I see. Thanks for clarification. Also the scenario "freezes" and cars do not move? 
I think this is the same problem as reported in #348. 

Unfortunately this seems to be a bug that I can't reproduce, hence is hard to catch and fix. Let's hope that canberkkurtulmus (#348 reporter) can find what commit caused this bad behavior.

**Comment by tgjht2022** [comment]
Yes, I've seen issue #348, which is similar to mine.
Due to the file size limitation in github, I can't upload my esmini zip.
Please forgive that  I searched your volvo email address on Google, and sent the files by email.
I'd apprecitate it very much if you can check that and reproduce the problem.
Thanks for the quick reply.

**Comment by tgjht2022** [comment]
Sorry, it take some time to upload. Maybe you can check that later.
With sincere thanks.

**Comment by eknabevcc** [comment]
Good idea to post your compiled executable. No hurry. I'll check later.

**Comment by tgjht2022** [comment]
Thanks for your support and patience. :)

**Comment by tgjht2022** [comment]
Failed to sent the exe package via email. I've uploaded the esmini.exe here.
Hope you can see that!
[esmini_exe.zip](https://github.com/esmini/esmini/files/10124380/esmini_exe.zip)

**Comment by eknabevcc** [comment]
I've tested both esmini from your large zip and the standalone one. "Unfortunately" they run perfectly on my HP laptop running Windows 10.

Could it be something with the graphics system? 
I run [dxdiag](https://support.microsoft.com/sv-se/windows/%C3%B6ppna-och-k%C3%B6ra-dxdiag-exe-dad7792c-2ad5-f6cd-5a37-bf92228dfd85)  and get:
![image](https://user-images.githubusercontent.com/29146839/204862097-7f18eced-2ca3-4028-857d-e029927746c6.png)

Can you run the same tool?

I'm not sure how to progress. One way could be if you try the https://github.com/esmini/esmini/commit/9951aa6172e72a4939cb40acd5dd5bfda4ee955f version of esmini. It seemed to work for canberkkurtulmus. Would be interesting to see if it works for you as well. Then we could go forward from there...

**Comment by tgjht2022** [comment]
I just solved the problem by changing my keyboard method to English input.
After that, the esmini windows worked perfectly.
Thanks for your support and patience. :)

**Comment by eknabevcc** [comment]
Ah, thank you for the info! That was a nice solution - I didn't even think about that :) 

Just a last question: Did the graphics freeze (cars stops moving, time stops updating) when you pressed a key with Chinese layout? That might be a bug that we should look into. I mean, if a key is not recognized it should just be ignored, it should not make esmini freeze.

**Comment by tgjht2022** [comment]
`Just a last question: Did the graphics freeze (cars stops moving, time stops updating) when you pressed a key with Chinese layout?`
Actually the esmini window still plays (the car is moving until the program finishes) when I press the key in Chinese layout. But it doesn't response with my keyboard input :)

**Comment by eknabevcc** [comment]
I see, thanks for clarification! Very good for us to be aware of this 👍
