### ISSUE TITLE
GhostDriver determinism and Action support

### ISSUE THREAD

**Issue by Lunarix** [esmini/esmini#362]
Hello :)
Really appreciate the work and love esmini for scenario running!

I got 2 questions.

### Determinism

I am currently getting in touch with the GhostDriver and want to use my own driver and vehicle dynamics. Is the GhostDriver deterministic? This is some of my output log that I got:
1st run 
ESMINI State -- Time 32.36 x: 74.5909 y: 13.5958 z: 431 h: 0.394369r: 0 p: 0 speed: 1.63493 t: -7.02117 s: 55.3983
Distance: 0.64143 Target x : 75.1841 y : 13.8398 z: 431

2nd run
ESMINI State -- Time 32.36 x: 74.5909 y: 13.5958 z: 431 h: 0.394369r: 0 p: 0 speed: 1.63493 t: -7.02117 s: 55.3983	
Distance: 0.64143 Target x : 75.1823 y : 13.8438 z: 431

I am printing the current esmini state in the first line and in the second line the information that I use for the ghost driver. 0.64143 is the distance that I want to look ahead of the current position. But then I get different target x values back. Is this intended? In my scenario, which I sadly can't really share, this happens at the crossing section of multiple lanes.  

### FollowTrajectoryAction

I am not able to get the GhostDriver work with FollowTrajectoryAction's that work with the regular esmini driver. It's not returning a speed that would be used received from another action (FollowTrajectoryAction for trajectory and SpeedAction for speed changes). Any idea's how to make it work?

Thank you! :)

**Comment by eknabevcc** [comment]
Determinism: With fixed timestep it should give repeatable/deterministic result. If there is any random ingredients, e.g. as in swarm traffic or way selection in intersection (which is random as long as not route is assigned) then you also need to re-use the same seed for repeated runs.

FollowTrajectoryAction: Don't understand fully. Usually it saves time if we can reproduce the issue. Perhaps you could prepare and share a snippet of application/scenario?

**Comment by Lunarix** [comment]
Hello eknabevcc,

your totally right. It was an issue on my side only. I was not have a look at the seed. Is is possible to reconfigure the seed once the simulation is running, or is that only possible when initializing the scenario runner?

FollowTrajectoryAction: The issue was on my side that the calculated throttle value was not high enough to get out of the standstill.

Thank you!

**Comment by eknabevcc** [comment]
Good to hear that you found the "standstill" root cause.

Regarding seed: From command line you can only set seed at launch time. But via the API (`SE_SetSeed()`) you can actually change the seed at any time during an ongoing simulation (although I never thought about a use case where it's being changed during ongoing simulation :))
