### ISSUE TITLE
SE_InitWithArgs whitespace bug

### ISSUE THREAD

**Issue by Lunarix** [esmini/esmini#370]
Hello,

there seems to be a bug within `SE_DLL_API int SE_InitWithArgs(int argc, const char *argv[]); `
(https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L352). The description tells you about 3 param's but the "@param oscFilename Path to the OpenSCENARIO file" does not exist. 
I tried passing the --osc XOSC_PATH within the arguments, which works but only when there is no whitespace within the xosc path (i.e. `--osc D:\test\test.xosc` works, while `--osc D:\test 2\test.xosc` does not work). I was having a look at the parsing function and found that esmini is spliting the arguments on whitespaces (https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Libraries/esminiLib/esminiLib.cpp#L97). Internally esmini is spliting the `--osc D:\test 2\test.xosc` to `--osc`, `D:\test` and `2\test.xosc`, which can not be loaded anymore.

**Comment by eknabevcc** [comment]
Thanks for reporting this issue. Indeed it's a drawback not allowing spaces in filenames (although I personally try to avoid them, inserting underscores '_' instead).

I tried to update the behavior of the parsing. It should support spaces in filenames, hopefully without introducing unwanted side-effects. (commit 0f129b8ead239e0f0c754510aaf66efa032acfcc)

It's on master branch and will be included in next release.

Please test and report back how it works.

**Comment by eknabevcc** [comment]
Fix included in release [v2.27.5](https://github.com/esmini/esmini/releases/tag/v2.27.5)
