### ISSUE TITLE
Failed to display correct relative position in the map which has mult-roads

### ISSUE THREAD

**Issue by StephenHU-sh** [esmini/esmini#372]
The map (.xodr file ) has several road. Ego is on the road 6. TV（Target Vehicle） is 100 meters in front of Ego.  I define the position of TV by "RelativeLanePosition" style .  it look like this:  <RelativeLanePosition entityRef="Ego" dLane="0" ds="100" offset="0.0"/>.  All car has no speed, speed =0 m/s.

But in the animation of esmini， the TV stands in the wrong pisition （see figure1）. It  always stands the position(s=56.33) when the ds in <RelativeLanePosition> greater than 56.33 .

After analysis, I find that the s value of the end of road 6 is 56.33 . So , it mean that the TV just stay in the current road , can't stay in the next road.  But this only affects init position, if the vehicle is moving, there is no such problem.

![figure1](https://user-images.githubusercontent.com/65988728/211765297-61cfee3d-2902-4b2a-bbb2-3ce60adfa13b.png)
![figure2](https://user-images.githubusercontent.com/65988728/211765319-aa966ce8-14dd-4c45-873c-4898ec290874.png)

[xodr file.zip](https://github.com/esmini/esmini/files/10390601/xodr.file.zip)

**Comment by eknabevcc** [comment]
Excellent finding. Thanks for reporting!

Yes, it was a lazy assumption in esmini that the relative position would be at the same road, which is unacceptable.

This bug has now been fixed in commit 1b0a1fa1dc2d62ca86b72f499b56853f917a4331 and will be included in next release.

**Comment by StephenHU-sh** [comment]
Dear all , Thank you very much !

**Comment by eknabevcc** [comment]
The fix is included in release [v2.28.0](https://github.com/esmini/esmini/releases/tag/v2.28.0).

Please test and report if it works as expected.

**Comment by StephenHU-sh** [comment]
Greate!
The problem has been fixed.
