### ISSUE TITLE
Bus is going to following trajectory but motion is not natural.

### ISSUE THREAD

**Issue by victor0777** [esmini/esmini#373]
![image](https://user-images.githubusercontent.com/111849721/212445571-48ee5953-d533-4d23-b2d8-1d4db4bf56c9.png)

The bus heading direction needs to be adjusted to the defined trajectory. Do you know how I can fix it? Is it a program bug or am I missing something in the scenario?
[source.zip](https://github.com/esmini/esmini/files/10416341/source.zip)

**Comment by eknabevcc** [comment]
Yes, even though it's cool with the sliding bus:

In followingMode = "position" esmini totally use the provided or (or if missing, the default =0.0) for heading. This mode is useful if you want to explicit control the heading.

In followingMode = "follow" esmini will align heading to the segments. Which is what you want in this case (and most cases I think).

So, change following mode as follows:
<TrajectoryFollowingMode followingMode="follow"/>

**Comment by eknabevcc** [comment]
The XML snippet became invisible, here it is:
\<TrajectoryFollowingMode followingMode="follow"/>

Or check attached modified scenario:
[17410_SEQ_S_F_D_1_O_1_2_t_esmini-mod.xosc.txt](https://github.com/esmini/esmini/files/10416834/17410_SEQ_S_F_D_1_O_1_2_t_esmini-mod.xosc.txt)

**Comment by victor0777** [comment]
It works. Thanks.
