### ISSUE TITLE
A pedestrian is supposed to cross the road in my scenario, but in the esmini play he is moving along the road

### ISSUE THREAD

**Issue by victor0777** [esmini/esmini#374]
Hi,

I have a question. 

Three cars(Car 1, Car 2, Car 3) are moving and a pedestrian is crossing the road. Car1 and Car 2 decrease while Car3 is going steadily. Car 1 and Car 2 move again when the pedestrian crosses the road.

![image](https://user-images.githubusercontent.com/111849721/212574761-e7fc21d4-9fa2-4b84-8eb9-fe4ac5c3bcce.png)

But the pedestrian in the esmini is walking along the road

![image](https://user-images.githubusercontent.com/111849721/212574811-3ec8bff1-1388-4bdd-a920-e5c4b3e33afb.png)

in the section of (Private entityRef="Pedestrian 1"), I changed the value to 12.2222222222222223 like below
`<AbsoluteTargetSpeed value="12.2222222222222223"/>`

![image](https://user-images.githubusercontent.com/111849721/212574895-d8992469-babf-4b9c-8e47-5de2945ca910.png)

it played as I intended excluding pedestrian speed.

What am I missing?

[example.zip](https://github.com/esmini/esmini/files/10421627/example.zip)

**Comment by eknabevcc** [comment]
This week I’m AFK (no access to PC), but quick review of the scenario I have one potential lead: The pedestrian trajectory start condition is simtime == 0.2. That should be OK if you have control of timestep, e.g. run with launch flag: —fixed_timestep 0.1 or via API SE_StepDT(0.1). Then you will hit exactly 0.2. But “free” running esmini will choose dt based on actual elapsed time, which might miss 0.2.

So a general recommendation is to rather use > or >= in conditions involving time.

Can you try to replace “equalTo” with “ greaterOrEqual” and see if it has any effect?

**Comment by victor0777** [comment]
It works! Thank you very much.
