### ISSUE TITLE
Run Car

### ISSUE THREAD

**Issue by csawp** [esmini/esmini#388]
I didn't read all the data in the OSC file, which was dynamically added during operation. Can I add vehicles dynamically during operation

**Comment by csawp** [comment]
resolved！

**Comment by eknabevcc** [comment]
I see that you already found a solution. I was about to answer "Yes" :)

For reference I put some notes here:

If you use esminiLib integrated with your application, check this code example:
https://github.com/esmini/esmini/tree/master/EnvironmentSimulator/code-examples/ad_hoc_traffic
(I actually found an issue now resolved by commit 706ddfc0633f126afdb0f30af4a8778d57987195)

That example shows how you can add and delete any vehicle on the fly. They don't need to be represented in the OpenSCENARIO file.

If the objects should be part of the scenario (for example perform actions, be related to by other object's actions or used in trigger conditions) then this example might be useful to look at:
https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Unittest/xosc/add_delete_entity.xosc

Run it from esmini root as:
`./bin/esmini --window 60 60 800 400 --osc ./EnvironmentSimulator/Unittest/xosc/add_delete_entity.xosc`
