### ISSUE TITLE
FollowTrajectoryAction while driving backward

### ISSUE THREAD

**Issue by Lunarix** [esmini/esmini#389]
Hello,

I am facing an issue with the FollowTrajectoryAction and driving backwards. It works driving forwards but when having negative speed and triggering the FollowTrajectoryAction the vehicle is placed to the starting node in a forward direction and not moving.

[FollowTrajectoryAction.zip](https://github.com/esmini/esmini/files/10695976/FollowTrajectoryAction.zip)

There are 2 scenarios within: 
**forward_followTrajectoryAction.xosc** works as expected. The vehicle will accelerate and then follows the trajectory nodes described within the FollowTrajectoryAction.

**backward_followTrajectoryAction.xosc** does not work. The vehicle will accelerate backwards but when the FollowTrajectoryActions is triggered it will look in the same direction as it did within the forward_followTrajectoryAction.xosc (wrong direction) and not move. 

Is there a mistake in my xosc description or is esmini not able to drive backwards on a FollowTrajectoryAction? 

Thank you! :)

**Comment by eknabevcc** [comment]
Yes, you're right. I think we overlooked this use case of going reverse along a trajectory. Thanks for pointing out this shortcoming.

Commit 754f6d4caf3e02a41ebc2000d39d1464aa35719a (merged on master) should hopefully support these use cases:
1. Changing direction while driving along trajectory
2. Starting action with negative speed

The sign of speed at start of the FollowTrajectoryAction will decide the orientation of the vehicle. So for example, if it is reversing at start but then acceleration to positive speed, it will retain heading.

Please test and see if it works as expected.

**Comment by Lunarix** [comment]
I've tested the latest mater and it seems to work. Thank you!
