### ISSUE TITLE
`DeterministicMultiParameterDistribution` not working as expected

### ISSUE THREAD

**Issue by jiixyj** [esmini/esmini#390]
I've been playing around with the new parameter distribution feature a little bit, trying the `DeterministicMultiParameterDistribution` tag similar to the following example:

```xml
<?xml version="1.0" encoding="utf-8"?>
<OpenSCENARIO>
  <FileHeader revMajor="1" revMinor="2" date="2022-10-31T12:00:00" description="Parameter values for scenario" author="esmini-team" />
  <ParameterValueDistribution>
    <ScenarioFile filepath="cut-in.xosc" />
    <Deterministic>
      <DeterministicMultiParameterDistribution>
        <ValueSetDistribution>
          <ParameterValueSet>
            <ParameterAssignment parameterRef="HostVehicle" value="car_blue" />
            <ParameterAssignment parameterRef="TargetVehicle" value="car_yellow" />
          </ParameterValueSet>
          <ParameterValueSet>
            <ParameterAssignment parameterRef="HostVehicle" value="car_yellow" />
            <ParameterAssignment parameterRef="TargetVehicle" value="car_blue" />
          </ParameterValueSet>
        </ValueSetDistribution>
      </DeterministicMultiParameterDistribution>
      <DeterministicSingleParameterDistribution parameterName="EgoSpeed">
        <DistributionSet>
          <Element value="70.0" />
          <Element value="110.0" />
        </DistributionSet>
      </DeterministicSingleParameterDistribution>
      <DeterministicSingleParameterDistribution parameterName="TargetSpeedFactor">
        <DistributionRange stepWidth="0.2">
          <Range lowerLimit="1.1" upperLimit="1.5" />
        </DistributionRange>
      </DeterministicSingleParameterDistribution>
    </Deterministic>
  </ParameterValueDistribution>
</OpenSCENARIO>
```

...so a slightly modified `cut-in_parameter_set.xosc` example, with two instead of one `ParameterValueSet` inside the `ValueSetDistribution`. I would have expected 12 concrete scenarios from that, but I'm getting only 6. I expected:

- { { "HostVehicle": "car_blue", "TargetVehicle": "car_yellow" }, "EgoSpeed": "70.0", "TargetSpeedFactor": "1.1" }
- { { "HostVehicle": "car_blue", "TargetVehicle": "car_yellow" }, "EgoSpeed": "70.0", "TargetSpeedFactor": "1.3" }
- { { "HostVehicle": "car_blue", "TargetVehicle": "car_yellow" }, "EgoSpeed": "70.0", "TargetSpeedFactor": "1.5" }
- { { "HostVehicle": "car_blue", "TargetVehicle": "car_yellow" }, "EgoSpeed": "110.0", "TargetSpeedFactor": "1.1" }
- { { "HostVehicle": "car_blue", "TargetVehicle": "car_yellow" }, "EgoSpeed": "110.0", "TargetSpeedFactor": "1.3" }
- { { "HostVehicle": "car_blue", "TargetVehicle": "car_yellow" }, "EgoSpeed": "110.0", "TargetSpeedFactor": "1.5" }
- { { "HostVehicle": "car_yellow", "TargetVehicle": "car_blue" }, "EgoSpeed": "70.0", "TargetSpeedFactor": "1.1" }
- { { "HostVehicle": "car_yellow", "TargetVehicle": "car_blue" }, "EgoSpeed": "70.0", "TargetSpeedFactor": "1.3" }
- { { "HostVehicle": "car_yellow", "TargetVehicle": "car_blue" }, "EgoSpeed": "70.0", "TargetSpeedFactor": "1.5" }
- { { "HostVehicle": "car_yellow", "TargetVehicle": "car_blue" }, "EgoSpeed": "110.0", "TargetSpeedFactor": "1.1" }
- { { "HostVehicle": "car_yellow", "TargetVehicle": "car_blue" }, "EgoSpeed": "110.0", "TargetSpeedFactor": "1.3" }
- { { "HostVehicle": "car_yellow", "TargetVehicle": "car_blue" }, "EgoSpeed": "110.0", "TargetSpeedFactor": "1.5" }

That would treat one `ParameterValueSet` of a `ValueSetDistribution` similar to an `Element` of a `DistributionSet` when calculating all possibilities.

Of course, I might be on the wrong track here... Does anyone know more about this? The OSC use guide has this to say in section 9.3.1:

> *Multi-parameter distribution*
> `ValueSetDistribution`: Complete sets of parameter values may be given. For each concrete scenario, one set is used and all parameter values given within this set are changed.

**Comment by eknabevcc** [comment]
Indeed I agree with your interpretation! We simply overlooked this. 
Should be fixed by commit 41ef845985bfcb6f3544af085e4d354bda3bb85b (merged on master).

Example scenario used for test cases [(cut-in_parameter_set.xosc)](https://github.com/esmini/esmini/blob/master/resources/xosc/cut-in_parameter_set.xosc) updated inspired by your example. 

Thanks a lot for the report!

**Comment by eknabevcc** [comment]
Please test the fix when possible and close issue if it works as expected. Otherwise we look further 👍

**Comment by jiixyj** [comment]
I built and tested the fix, works as expected now. Thanks again!

**Comment by eknabevcc** [comment]
Great, thanks for quick feedback!
