### ISSUE TITLE
Is there a way to move the camera position in odrviewer?

### ISSUE THREAD

**Issue by smhase** [esmini/esmini#398]
I am able to 
1. Move the camera along with the car.
2. Move the angle at which I am viewing the car.
3. Detach from car and point at one place.
4. Zoom in/ Zoom out.

The functionality I am missing is being able to move the camera freely.

**Comment by smhase** [comment]
I could see the following options available. But they do not seem to be targeting my usecase

    1 - 9: Camera models acording to :
        1: Custom camera model
        2: Flight
        3: Drive
        4: Terrain
        5: Orbit
        6: FirstPerson
        7: Spherical
        8: NodeTracker
        9: Trackball

    When custom camera model(1) is activated
        k: Switch between the following sub models:
           - Orbit        (camera facing vehicle, rotating around it)
           - Fixed        (fix rotation, always straight behind vehicle)
           - Flex         (imagine the camera attached to vehicle via an elastic string)
           - Flex - orbit (Like flex but allows for roatation around vehicle)
           - Top          (top view, fixed rotation, always straight above vehicle)
           - Driver       ("driver" view, fixed at center of vehicle)

**Comment by eknabevcc** [comment]
There is no camera model that will zoom into a point specified by a click. But maybe something similar. Try:
1. Press '4' to detach and change into "terrain" camera model
2. Now you should be able to rotate, zoom and pan (mouse middle button) from here

Do you think this will be useful enough for your use case?

**Comment by smhase** [comment]
PERFECT! That is what I was looking for! Thanks @eknabevcc

**Comment by tmIdiada** [comment]
Hi,

this is really great since it works in esmini replayer and esmini. But, please add this documenttation to user-guide (not seen so far) and maybe you have an idea how to get back to the default camera positions like ego?

BR

**Comment by eknabevcc** [comment]
It's a bit tricky. But yes you're right, '1' will take you back to esmini camera models, where you can toggle between esmini models with 'k'. Mode 2-9 is OSG predefined camera models. 

Brief info: [User guide - Runtime key shortcut commands](https://esmini.github.io/#_runtime_key_shortcut_commands)

Hint: This help can also be printer to console with 'H' (Shift-'h').

**Comment by tmIdiada** [comment]
Many thanks, is there also an option to see in terrain mode ('4') the position of the mouse cursor in coordinates, maybe also velocities, but especially the position would be very nice. Very useful could be also a kind of grid. Also 2 options could be thought here, one in global coordinates and one in relative to road, also for the mouse position, like nearest roadID with s and offset. Maybe you can think about it if it would make sense to you, for me from postprocessing point of view I could directly check what I'm doing wrong in the positioning and what is the error of my scenario to the expected positions.

**Comment by eknabevcc** [comment]
Many good ideas :) unfortunately we can't currently prioritize . I'll keep the cursor position in mind. I agree that could be helpful. 

BTW: At least you can always check camera pose by 'K' (Shift-'k')

**Comment by tmIdiada** [comment]
> BTW: At least you can always check camera pose by 'K' (Shift-'k')

Already very helpful, only to shift between the windows. Could be maybe added to the help https://esmini.github.io/#_runtime_key_shortcut_commands

**Comment by eknabevcc** [comment]
Ah, thanks for discovering that flaw. Now it's added to the help ('H' and [User guide - command reference](https://esmini.github.io/#_command_reference)).
