### ISSUE TITLE
Problems with catalog path and subdirectories

### ISSUE THREAD

**Issue by johschmitz** [esmini/esmini#399]
Today I encountered this weird behavior when running a scenario in a subdirectory where it would complain about
```
Failed to look up entry car_1 in catalog VehicleCatalog
```
Then when I started the simulation directly from the directory containing the .xosc file and it worked. 
Then I stayed in that subdirectory and started esmini with the inital call including the subdirectory like
```
$ esmini --osc xosc/example.xosc --window 100 100 1000 600
```
and it still worked.

I am really having a hard time explaining this behavior. I am currently trying to implement pedestrians so I had to work on the catalog stuff.

Are you always making sure that the catalog path is relativ to the .xosc location and it has nothing to do with the working directory? Or are you doing some magic there? How can it work for both `--osc example.xosc` as well as `--osc xosc/example.xosc` from the same working directory?

[example.zip](https://github.com/esmini/esmini/files/10834676/example.zip)

Bonus Question: How to initialize pedestrians in a way that they walk straight in their initial heading direction?

**Comment by johschmitz** [comment]
It seems the scenarios included with esmini are also doing it a bit strange.
the Catalog folder is next to the scenario files but the path is something like `../xosc/Catalogs/Vehicles` which is not wrong but why not just put `Catalogs/Vehicles` or `./Catalogs/Vehicles`?

**Comment by johschmitz** [comment]
I found out if I go one directory up from where the problem occurs it also works. I am getting more confused with this..

**Comment by eknabevcc** [comment]
Bonus question first:
With no active esmini will move entities according to default behavior which is: Move along current lane offset with current speed and with current relative orientation, which is normally, but not necessarily, zero. It you want to follow another path, just assign a trajectory, which can be really simple, e.g. just a straight line between start and end points.

Regarding catalogs: In addition to just specified path (relative current/launch directory), esmini will look in additional locations based on:
- from the scenario file directory (i.e. where the .xosc file is located)
- from the directory where the esmini executable is located

If this is not enough, you can simply specify any number of additional search paths with the "--path" launch argument, e.g: `--path /my/absolute/scenario_path` or `--path ../my/relative/scenario_path`

If you still have a problem, provide details and we'll sort it out.

(the ../xosc pattern that you see in some example is not mandatory at all. It's just based on some file structure we had where xosc folder was reserved for original scenarios, including catalogs while custom scenarios typically where kept in parallel folders. You don't need to adapt that pattern of course)

**Comment by johschmitz** [comment]
I think the inability to specify an arbitrary moving direction without a trajectory is a big gap in OpenSCENARIO. I am probably going to address that in an ASAM standardization issue.

Regarding the catalog, my understanding is that the path needs to be specified relative to the OpenSCENARIO file itself in order to make everything portable and independent of the working directory. This should be the first priority when searching. Otherwise, if something else with "magic" is the first priority, you run into problems like I am right now. Can you say what the search priorities are? I am also not sure if it is clearly stated in the standard that paths need to be relative to the .xosc location.

Also I still don't understand it why it doesn't work for my case with the example since you say that you are also searching "from the scenario file directory (i.e. where the .xosc file is located)" but that doesn't seem to always work. Would be cool if we could have a command line switch to disable all search magic for easier debugging and for the case that we know everything is relative to the main xosc file.
What additional information do you need to debug this or how can I debug it?

**Comment by eknabevcc** [comment]
Regarding moving without trajectory. Yes, discussions like that is better to have within ASAM projects. 

Catalog search priority:
1. absolute path or relative to current directory
2. relative path to scenario directory
3. relative path to executable location
4. additional specified locations

I hope this clarifies. If you still have problem, yes, try debug yourself - usually most efficient avoiding misunderstandings. As last resort, if still not resolved, we can support of course. Then just provide all details, e.g. your scenario assets with the same folder structure. Plus info on how and from where you launch esmini.

**Comment by johschmitz** [comment]
May I ask what the reasoning is for "relative to current [working] directory" being higher priority than "relative path to scenario directory"? That means, as I understand, that I can get different results depending on from where I call esmini even if inside the OpenSCENARIO "project" the directory structure and the links are correct/consistent. Like just by putting a file with the accidentally same name somewhere relative to the working directory very strange things may happen. Do you know what I mean? Are you sure this is intentional? I am a bit shocked about this to be honest. Would it be a problem with legacy to at least invert these two so that it at least takes the file from the project folder if available before searching somewhere outside?

**Comment by johschmitz** [comment]
Note: I would be willing to work on a patch for this myself in my spare time in case developer time is the only blocker for improving this. I will also post a more detailed example including the exact commands later to better explain what happens and make it reproducible.

**Comment by johschmitz** [comment]
Okay I will have a look then. Question for my understanding before I come up with a pull request: Is the search relative to the working directory essential for you or could it even also be removed? 
I am asking because my idea would be to to disable this (or only enable via a switch or provide it via your option 4) and instead provide the user more feedback about the search process and which path has been scanned via information and error messages. Also an update of the documentation of course makes a lot of sense for this, I agree.

**Comment by johschmitz** [comment]
@eknabevcc Also another question, will it be okay to bump the C++ standard to 17 so that I can use std::filesystem without going to experimental (in 14)? I tried this and it seems to compile without issues.
I would like to use things like std::filesystem::current_path() so it would be very helpful to move to 17.

**Comment by johschmitz** [comment]
I have added a preliminary pull request to show how it can work with C++ 17
https://github.com/esmini/esmini/pull/403
I will have to do the same for the other file types and also need to study how the user documentation works in order to add it there.

**Comment by eknabevcc** [comment]
Ah, I looked into the [PR #403](https://github.com/esmini/esmini/pull/403) first. Now I see that you commented on C++ 17 here! I appreciate your proposal, and the code itself looks very good. See my thoughts in the [PR #403](https://github.com/esmini/esmini/pull/403).

I basically agree with you, a clearer/stricter search path strategy is good to prevent wrong files being used. But there is some legacy here which we need to consider. Back in the days we didn't have the --path argument. Instead esmini accepted some various file structures to support different user preferences and use cases. With the introduction of --path argument we perhaps should have restricted the auto-search paths, e.g. not look in/from the current folder. 

So, after all I come to the conclusion to do this in steps, as outlined in the PR.

**Comment by johschmitz** [comment]
I have now completed a first version for C++17. Did not like to leave a half baked PR there.
Please check if you really can not switch to C++17 because this is in my experience not a big problem also for enterprise projects. Compatibility with C++14 is really good. I think there was some trouble when switching to C++11 and also C++20 seems to be a bit more tricky but C++14 to C++17 should not be a big deal.
If it is absolutely not possible within the next few month I can maybe work on another legacy pull request.
Also maybe it would make sense to reopen this issue until it is merged?

**Comment by eknabevcc** [comment]
Let's keep the communication regarding the proposed changes in the PR itself, to simplify and avoid confusion. I actually added some feedback yesterday, see https://github.com/esmini/esmini/pull/403#issuecomment-1455108569.
