### ISSUE TITLE
Instructions for building OSG

### ISSUE THREAD

**Issue by davidhesselbomvcc** [esmini/esmini#4]
The instructions for Windows contain links to OSG binaies (e.g. https://drive.google.com/uc?export=download&id=1a0HxilPJq2bZrat2le2x-Cscs5JeVAXP).

What if those links go dead, and I have to build OSG myself? Instructions for how to do this need to be added. Even better, a script.

**Comment by eknabevcc** [comment]
Fixed: https://github.com/esmini/esmini/blob/master/BuildOSG.md
Linked to from [Windows build instruction](https://github.com/esmini/esmini/blob/master/BuildOSG.md)
