### ISSUE TITLE
Reverse control

### ISSUE THREAD

**Issue by chenjian88888** [esmini/esmini#400]
I am using DRIVER_ INPUT to control the car in the esmini, but I can't find the interface to control the gear. So I can't control the vehicle reversing. Is it supported now?

**Comment by eknabevcc** [comment]
I assume you're using [this message](https://github.com/esmini/esmini/blob/1866e4115e1d78f807bad2a355f7675c310a936b/EnvironmentSimulator/Modules/Controllers/ControllerUDPDriver.hpp#L89)

Yes, you're right. There is no gear selection. The vehicle model is extremely simple. Just throttle and brake. However, there is a way to reverse. I just added an example show how it can be done:

https://github.com/esmini/esmini/blob/master/scripts/udp_driver/testUDPDriver-forward-reverse.py

Please try it out (instructions in the head comment in the file). Is that enough for your use case?

**Comment by chenjian88888** [comment]
Yes, I tried. This can meet my needs.
