### ISSUE TITLE
Error in build process

### ISSUE THREAD

**Issue by Dan-A22** [esmini/esmini#401]
Hi. I was installing esmini according to [this link](https://esmini.github.io/#_build_esmini_quick_guide). I successfully cloned the project into my windows10 system and after that, I started running the commands shown in the above link in cmd. However when I try to run the last command which is:
`cmake --build . --config Release --target install`
an error will encounter which says: "Error: could not load cache".
Does anybody have ideas for this?
any help is much appreciated!

**Comment by Dan-A22** [comment]
The problem is completely explained in #349 and my problem is also solved.

**Comment by eknabevcc** [comment]
Glad that you found the solution!
