### ISSUE TITLE
Catch simulation error

### ISSUE THREAD

**Issue by johannesWen** [esmini/esmini#413]
Hi,

one short question. Is it possible to catch a simulation error? For example, if "Failed to find OpenDRIVE file ..." occurred.
It seems that esmini writes all the output in stdout and stderr is empty.
Do you have any idea to check if the simulation was successful?

BR

**Comment by eknabevcc** [comment]
The return code SHOULD be != 0 if the simulation failed. Can you check it? Let me know if it's 0 in spite of failed scenario, in which case I think it's a bug.

**Comment by eknabevcc** [comment]
Ah, my bad. I now understand that you run the application, not library. I think there might be a flaw when it comes to return value. 

We'll look into it and get back.

**Comment by johannesWen** [comment]
Yes, I call esmini in a subprocess and I want to check if the simulation was successful. Currently, I have a workaround to check if the csv-logfile exists, but this is not a nice way ;)

**Comment by eknabevcc** [comment]
Attempt to solve it included in release [v2.30.1](https://github.com/esmini/esmini/releases/tag/v2.30.1)

Please test and see how it works

**Comment by johannesWen** [comment]
Thank you. Now I get an exit code if the simulation fails 👍
