### ISSUE TITLE
Parameters cannot be defined without prefix $

### ISSUE THREAD

**Issue by arauschert** [esmini/esmini#42]
When a parameter is defined within the ParameterDeclarations, its name should be defined without prefix $ according to the User Guide:
"Parameters are declared within ParameterDeclaration by their individual names (without any prefix)....Parameters can be referenced from within the scenario, e.g. for obtaining their values. In this case, a "$" prefix is used to indicate the referencing."

But if doing this, then the parameters cannot be referenced anymore. When executing the scenario an error is thrown:
`
ScenarioReader.cpp / 64 / scenarioengine::ScenarioReader::getParameter(): Resolve parameter $Ego_InitSpeed_Ve0
ScenarioReader.cpp / 75 / scenarioengine::ScenarioReader::getParameter(): Failed to resolve parameter $Ego_InitSpeed_Ve0
main.cpp / 253 / main(): Failed to resolve parameter
`

**Comment by eknabevcc** [comment]
Totally correct. Thanks for pointing out this issue which I had missed. Of course esmini should support correct parameter naming, it also looks better and more aligned to good practice of parameter naming. 

Code has been updated (commit https://github.com/esmini/esmini/commit/4c938d293992ade8acbe987e519af8f781dfbdd9) to support parameter names without the prefix. All example scenarios has been updated accordingly. Old naming, including prefix, still being supported as well.

Please check if it works as expected.

**Comment by arauschert** [comment]
Thanks a lot for the quick fix! I will test with the next release and give an update.

**Comment by eknabevcc** [comment]
There is now a new [release](https://github.com/esmini/esmini/releases/tag/v1.7.9) including the fix.

**Comment by arauschert** [comment]
Thanks for the update. I tried it but now I get a different error when loading the scenario, which I didn´t get with esmini 1.6.1:
ScenarioReader.cpp / 894 / scenarioengine::ScenarioReader::parseEntities(): Failed to load SUMO config file , also tried ././

and as a consequence:
ScenarioReader.cpp / 1785 / scenarioengine::ScenarioReader::FindObjectByName(): Failed to find object Ego
main.cpp / 298 / main(): Failed to find object Ego

Can you help me what this SUMO config file is and why I need this now?

**Comment by arauschert** [comment]
After checking the User Guide and the UML model I assume it´s not mandatory to pass a config file for a controller. Users may not need to pass configurations to the controller or pass them in a different way (e.g. via the test case). Is it possible to make the Scenario Reader only check for a config file, if ctrl->config_filepath_ != ""?

**Comment by arauschert** [comment]
Since this is a separate issue I will close this issue and create a new one.
