### ISSUE TITLE
Appearance of unwanted blocks in esmini & the unexpected behavior of the prebuilt ACC controller

### ISSUE THREAD

**Issue by Iqbalparvi** [esmini/esmini#427]
Hello.
We are conducting experiments on Esmini to assess the effectiveness of the prebuilt ACC controller. In our simulation, several cars are performing lane-changing actions in front of the ego car while following predefined trajectories. 
For further reference, we have provided the .xosc file for our scenario.
[ACCTestScenario.zip](https://github.com/esmini/esmini/files/11358247/ACCTestScenario.zip)
During our observation, we noticed two issues. 

1. First, unwanted black blocks appear in the OSC window for each actor in the surrounding when we run the simulation without activating the controller. 

![Unwanted boxes](https://user-images.githubusercontent.com/47267894/235281219-c00146ae-0b00-424d-b34b-adbbdd6df5ed.png)

2.  Second, even though the front car (lane changing) was not very close to the ego car, the ACC controller successfully activated during the simulation and reduced the ego car's speed from 60km/h to 21 km/h around 14 seconds into the simulation. The speed remained the same for the rest of the simulation.

We would appreciate it if someone could investigate the simulation to determine why the unexpected black objects appear in the environment and whether there are any limitations with the prebuilt ACC controller's ability to handle trajectory-following objects, or if something is missing in the scenario itself. To run the simulation with the controller, please uncomment code lines 88 to 90.
`<PrivateAction>
     <ActivateControllerAction longitudinal="true" lateral="false" />
</PrivateAction>
`
I am attaching the two videos of our LabScreen for further understanding.
[vedios.zip](https://github.com/esmini/esmini/files/11358274/vedios.zip)

Regards.

**Comment by eknabevcc** [comment]
Can you add the ACCTestScenario_OpenDRIVE.xodr as well?

**Comment by Iqbalparvi** [comment]
Ahh, sorry, have missed the file.
I am attaching the .xodr file here. 
[ACCTestScenario_OpenDRIVE.zip](https://github.com/esmini/esmini/files/11370450/ACCTestScenario_OpenDRIVE.zip)

**Comment by eknabevcc** [comment]
**1. Unexpected objects**

I think what you refer to are the road objects specified in the OpenDRIVE file, e.g:

`<objects>
      <object hdg="5.7051395628393564e-03" height="1.3999999999999999e+00" id="1" length="4.7000000000000002e+00" name="Ego_Car" orientation="none" pitch="-0.0000000000000000e+00" radius="0.0000000000000000e+00" roll="0.0000000000000000e+00" s="5.6490768150544443e+02" t="1.6973366133216283e+00" type="car" validLength="0.0000000000000000e+00" width="1.8000000000000000e+00" zOffset="0.0000000000000000e+00"/> 
...`

That element is typically used for stationary/static objects part of the road network such like railings, but can also represent static buildings, obstacles or whatever. In you OpenDRIVE the objects are named like vehicles, e.g. "Ego_Car" so maybe it has some relevance to the cars participating in the scenario?

Anyway, if you want to get rid of them either:
- add launch argument `--generate_no_road_objects` - esmini will skip all road objects, or
- simply remove them the OpenDRIVE file

Finally, I don't see how activation of the controller would affect the static objects. Can you elaborate on what is the difference when you activate the controller?

**2. ACC unexpected slow down**

What happens is that it finds a target vehicle in the same lane within 5 lateral meters (the yellow car). I see that the road has a wide lane (7.2m) which normally would be two different ones. Anyway, I find your case interesting and useful. At least I think that the lateral threshold should be tunable. 

Hence, I [added](https://github.com/esmini/esmini/commit/d86bb43c0181e5ae8509b238a21b1a9142c4369f) a parameter, `LateralDistance`, to the [ACC-controller](https://github.com/esmini/esmini/blob/d86bb43c0181e5ae8509b238a21b1a9142c4369f/resources/xosc/Catalogs/Controllers/ControllerCatalog.xosc#L138). Setting that to 3.0 at least resolves the issue in your scenario.

The change is so far only merged to dev branch. It will be included in next release (no date yet). If you want to try it out:
- checkout the `dev` branch
- build according to [Build esmini - quick guide](https://esmini.github.io/#_build_esmini_quick_guide)
- try the attached modified scenario: [ACCTestScenario-mod.zip](https://github.com/esmini/esmini/files/11428234/ACCTestScenario-mod.zip)

A tip: Activate road feature visualization and you'll see what target ACC has found

- toggle on 'o' key, or
- add launch argument `--road_features on`, e.g:
  `./bin/esmini --window 60 60 800 400 --osc ACCTestScenario-mod.xosc  --path ./resources/xosc/Catalogs/Vehicles --generate_no_road_objects --fixed_timestep 0.05 --road_features on`


![img](https://user-images.githubusercontent.com/29146839/237018830-06127363-ac37-4499-afe7-e4d1995eb140.jpg)

**Comment by Iqbalparvi** [comment]
Many thanks for the investigation response.
I agree with you that all the unwanted objects are relevant to the cars (i.e., ego_car, car1, car2, car3, and car4) participating in the scenario but not to any stationary/static objects. 
We revised the simulation with the argument ` --generate_no_road_objects – esmini` to skip the road objects and observe the behaviors.
**Ø. Can you elaborate on what is the difference when you activate the controller?**
In the current use case, we only have concerns with the moving cars; a few of them creates a situation where the ACC controller needs to take action to maintain a safe distance to avoid a collision.
However, in this platform, the placement/position of these unwanted objects in the OpenDrive file itself is also something beyond the user’s expectation, which does not affect the simulation results but may confuse the user.
For example, suppose each object represents the actor’s cars or stationery/static objects. In this scenario, these objects must be placed initially in the same position as the actor rather than scattered in various locations.
While esmini provides a way to remove these unwanted objects using available features, it is important to consider that when simulating the driving scenarios to testing the ACC or any other ADAS/AD functionality with other driving platforms. The appearance of these objects in different places can confuse the systems and hinder their ability to take appropriate actions.
**ACC controller performance:**
As the ego car moves in one lane throughout the simulation, we wonder whether we can set the system's target trajectory (the green line) to target the Lead car, which comes in front of the Ego car in the same lane (As in the pink line) rather than the other lane.
![response](https://github.com/esmini/esmini/assets/47267894/5946279d-a973-44a0-ab70-82667fb9b9a2)
I am attaching a video to help you understand this further. In this short video frame, the Blue car is the Ego car, and the Purple car is one of the moving actors who perform some maneuvers to test the ACC.  
[ACC_behavior.zip](https://github.com/esmini/esmini/files/11503738/ACC_behavior.zip)

**Comment by eknabevcc** [comment]
It's true that the simple ACC Controller do not react to stationary objects defined in the OpenDRIVE file. The reason why I suggested to remove the ones in your case was simply because it seemed to be duplicates of the cars created by the OpenSCENARIO file anyway. But yes, in general, I agree that also stationary objects defined in the OpenDRIVE file could be considered by the ACC. It might lead to some detailed questions, like should all such stationary objects be included, e.g. even sign poles? So far use cases has been focusing on objects and vehicles defined in the OpenSCENARIO file - which includes stationary MiscObjects. We don't have any immediate plan to extend the ACC Controller to consider OpenDRIVE objects. Feel free to propose extensions in a pull request (targeting dev branch).

Regarding setting system target trajectory. My recommendation is to actually define two lanes in the road description. To me it looks like the road is meant to have two lanes. Then automatically Ego will target vehicles in it's own lane.

![img](https://github.com/esmini/esmini/assets/29146839/a54e8ea2-4034-41c4-8c23-ea80d3086ccb)

See attached modified OpenDRIVE and OpenSCENARIO files: [ACCTestScenario-mod2.zip](https://github.com/esmini/esmini/files/11524016/ACCTestScenario-mod2.zip)

**Comment by Iqbalparvi** [comment]
Many thanks for your time and consideration.
So far, so good; now we can see the exact behavior as expected.
All the recommendations are helpful in inspecting the driving behaviors in terms of user expectation and increasing the ACC controller's robustness.
Looking forward to exploring the new version with the recommended/added changes in the ACC Controller.
We will also continue to explore esmini and other Virtual platforms with more critical Open Scenarios to inspect the driving behavior from different perspectives.
