### ISSUE TITLE
Setting the osi_receiver_ip using esmini_lib interface

### ISSUE THREAD

**Issue by yuanfei-lin** [esmini/esmini#433]
Dear esmini developers,

I would like to load the c lib of esmini_lib using CDLL in Python and use something like "esmini_lib.SE_SetOSIReceiverIP" to set up the OSIReceiverIP (similarly as `SE_SetLogFilePath`). But I didn't find this in the existing code, is it possible to do it or work it around?

Many thanks for your help in advance!

best regards,
Yuanfei

**Comment by eknabevcc** [comment]
Maybe this is what you're looking for:
[SE_DLL_API int SE_OpenOSISocket(const char *ipaddr);](https://github.com/esmini/esmini/blob/ee22196c054af7c0c07f8b4fdce95e481599e03b/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L1083)

**Comment by yuanfei-lin** [comment]
Dear Emil,

many thanks! This is exactly what I'm looking for!

Best regards,
Yuanfei
