### ISSUE TITLE
Triggering scenario action using python

### ISSUE THREAD

**Issue by bkrztrk** [esmini/esmini#435]
Hi everyone,

I want to trigger scenario action using python API. When I check from the esmini frame sequence in [InnerWorkings](https://github.com/esmini/esmini/blob/master/docs/InnerWorkings.md), It looks like we can only control/manipulate the player.  Do you have any suggestion for triggering scenario action from API?

![image](https://github.com/esmini/esmini/assets/64632779/08005b6e-806c-4f55-a8ee-5ae60831d998).

**Comment by eknabevcc** [comment]
There is no API for explicit triggering of actions. However, the method I first come to think of is to define a trigger based on [VariableCondition](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.2.0_Model_Documentation/modelDocumentation/content/VariableCondition.html). Then, by controlling the value of the variable via the API, you can in effect trigger actions.

If that could be a solution, see related issue: #331

which refer to code example: [code-examples/trig_lane_change](https://github.com/esmini/esmini/tree/master/EnvironmentSimulator/code-examples/trig_lane_change)
and this video clip: https://www.youtube.com/watch?v=5N3JH4n4T7o

**Comment by bkrztrk** [comment]
Thanks for the suggestion. I've found exactly what I needed. :)
