### ISSUE TITLE
Esmini window "not responding" error when using se_step() function

### ISSUE THREAD

**Issue by ufukbolat1** [esmini/esmini#440]
Hello, 

I would like to control my vehicle externally. To realize that I am using UDP driver. 

I am sending the information from another tool to Esmini using the UDP Driver and controlling the vehicle through a Python API.

However, when I run the script and also execute the other tool, I get a "not responding" error even though Esmini's window opens. However, I can still see the information being received and sent in the python terminal. This means that Esmini and the other tools are functioning correctly in the background, but I cannot observe the movements of the vehicles.

- 
![esmini_issue4](https://github.com/esmini/esmini/assets/41818980/c7fe24cd-c289-4abe-a454-456254e4aebf)

I am using the se.SE_Step() function to trigger and control the steps. When I remove this function, I don't get the "not responding" error, but I encounter synchronization issues with the tool. Therefore, I need to use this function.

Is there a solution to this problem that I can implement? 

Thanks

**Comment by ufukbolat1** [comment]
```
step_event = threading.Event()
def esmini_runner():
    for i in range(500):
        step_event.wait()  # Wait for the event
        step_event.clear()  # Reset the event
        se.SE_Step()
        time.sleep(0.1)

x = threading.Thread(target=esmini_runner, daemon=True)
x.start()
```

This section is the main problem. 

thanks a lot

**Comment by eknabevcc** [comment]
Interesting. I think the root cause is esmini being initialized and stepped in different threads. However, I don't know why it matters. 

Suggestion is to do ALL esmini operations in the same thread. I hope that is feasible for your use case.

The following code seems to work

``` python
import sys
import ctypes
import threading
import time


if sys.platform == "linux" or sys.platform == "linux2":
    se = ctypes.CDLL("../../../bin/libesminiLib.so")
elif sys.platform == "darwin":
    se = ctypes.CDLL("../../../bin/libesminiLib.dylib")
elif sys.platform == "win32":
    se = ctypes.CDLL("../../../bin/esminiLib.dll")
else:
    print("Unsupported platform: {}".format(sys.platform))
    quit()

se.SE_GetSimulationTime.restype = ctypes.c_float

step_event = threading.Event()

def esmini_runner():

    if se.SE_Init(b"../../../resources/xosc/slow-lead-vehicle.xosc", 0, 1, 0, 0) != 0:
        exit(-1)

    for i in range(10):
        step_event.wait(1.0)  # Wait for the event
        step_event.clear()  # Reset the event
        print("step esmini")
        se.SE_Step()
        time.sleep(0.1)

    print("close esmini")
    se.SE_Close()

x = threading.Thread(target=esmini_runner, daemon=True)
x.start()

for i in range(50):
    print("set event")
    step_event.set()
    time.sleep(0.1)

x.join()

print("quit")
```

**Comment by ufukbolat1** [comment]
Hello again,

Firstly I would like to thank you. I tried to change time sleep to really small values and it worked perfectly according to your code. 

However, my issue is kinda different. my step time is really varible. sometimes it might be high but sometimes it might be low. So, if I got even one "not responding" error, then other important information on other steps are also skipped. 

I also tried it on different computers below code. But you'll se what I meant when you run the code. 

```
import sys
import ctypes
import threading
import time
import random


if sys.platform == "linux" or sys.platform == "linux2":
    se = ctypes.CDLL("../../../bin/libesminiLib.so")
elif sys.platform == "darwin":
    se = ctypes.CDLL("../../../bin/libesminiLib.dylib")
elif sys.platform == "win32":
    se = ctypes.CDLL("C:/Users/../../Desktop/esmini-demo/bin/esminiLib.dll")
else:
    print("Unsupported platform: {}".format(sys.platform))
    quit()

se.SE_GetSimulationTime.restype = ctypes.c_float

step_event = threading.Event()

def esmini_runner():

    if se.SE_Init(b"C:/Users/../../Desktop/esmini-dev/esmini-dev/resources/xosc/slow-lead-vehicle.xosc", 0, 1, 0, 0) != 0:
        exit(-1)

    for i in range(10000):
        step_event.wait()  # Wait for the event
        step_event.clear()  # Reset the event
        print("step esmini")
        se.SE_Step()
        #time.sleep(0.1)

    print("close esmini")
    se.SE_Close()

x = threading.Thread(target=esmini_runner, daemon=True)
x.start()

for i in range(10000):
    print("set event")
    step_event.set()
    
    sleep_time = random.uniform(1, 10)
    if sleep_time > 5:
        sleep_time = sleep_time
    else:
        sleep_time = sleep_time/100
    print("s_T:", sleep_time)
    time.sleep(sleep_time)


x.join()

print("quit")
```


- ![esmini_issue5](https://github.com/esmini/esmini/assets/41818980/1107a007-d72f-4f47-96bb-cb3f72ebcdae)


Thanks again.
Ufuk

**Comment by ufukbolat1** [comment]
I changed the relevant line as you mentioned and it works now! Thank you so much.
