### ISSUE TITLE
GeoReference.axis_ should be a std::string

### ISSUE THREAD

**Issue by dakoehntopp** [esmini/esmini#442]
Hi,

I was trying to read an odr file with esmini but it would crash immediately. I was able to narrow it down to a small bug in the RoadManager.cpp which is also present in the master version

https://github.com/esmini/esmini/blob/aa5037c489610e5cb1c8bdc170634cb491a47dd8/EnvironmentSimulator/Modules/RoadManager/RoadManager.cpp#L5544-L5547

In my odr it says `+axis=nwu` which is according to the [PROJ documentation](https://proj.org/en/9.2/usage/projections.html#axis-orientation) correct. The function `OpenDrive::ParseGeoLocalization` on the other hand expects a double since it tries to read the value with `std::stod` which then throws an exception.

Could be fixed by making the `axis_` field in the `GeoReference` struct a `std::string`

https://github.com/esmini/esmini/blob/aa5037c489610e5cb1c8bdc170634cb491a47dd8/EnvironmentSimulator/Modules/RoadManager/RoadManager.hpp#L2472

and removing the `std::stod` call in the lines above.

Regards,
Daniel

**Comment by dakoehntopp** [comment]
That was quick. Awesome and thank you :)

**Comment by eknabevcc** [comment]
Included in release [v2.31.7](https://github.com/esmini/esmini/releases/tag/v2.31.7)

Please test and report how it works (maybe there are additional similar issues...)

**Comment by dakoehntopp** [comment]
Tested it. The axis case seems to be fixed. Unfortunately, there seem to be still later issues.

First of all, under ubuntu 20.04 it seems that fullscreen does not work.
```bash
 ./odrviewer --odr test_width_old.xodr
esmini GIT REV: 5782c88
esmini GIT TAG: v2.31.7
esmini GIT BRANCH: tags/v2.31.7
esmini BUILD VERSION: 3315
Generated seed 460633855
density: 1.00
global speed factor: 1.00
Unsupported geo reference attr: +h
Unsupported geo reference attr: +nodefs
Unsupported geo reference attr: +north
Invalid MIT-MAGIC-COOKIE-1 keyNo scenegraph 3D model loaded. Generating a simplistic one...
osi_features: lines off points off
0 cars added
libGL error: failed to create drawable
libGL error: failed to create drawable
Error: OpenGL version test failed, requires valid graphics context.
Segmentation fault (core dumped)

```
With --window it opens the viewer.

But the viewer shows just blue. I guess it draws the lanes but not in view, but that is just a guess.

Also, because we honestly did not expect such a quick reply and new release a colleague of mine had a look at the [odr standard 1.7](https://www.asam.net/index.php?eID=dumpFile&t=f&f=4422&token=e590561f3c39aa2260e5442e29e93f6693d1cccd#top-3535a746-e0af-4020-b71c-3a94e7a855a1) and rewrote how the geoReference in the xodr is written. Basically, the orientation and lat lon offsets are now given via the offset tag. In this case, also just a blue screen but also an additional
```bash
Unsupported geo reference attr: +no_defs
Unsupported geo reference attr: +type
[esmini_bug_files.zip](https://github.com/esmini/esmini/files/11721264/esmini_bug_files.zip)

cannot parse georeference: '+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs +type=crs'. Using default values.
```

This time I do not already know where the issue could be in the esmini code :)

**Comment by eknabevcc** [comment]
The camera focusing has been updated in [v2.31.8](https://github.com/esmini/esmini/releases/tag/v2.31.8). 

Now the focus is center of the object instead of reference point. One side effect is that roads far away from origin will be visible - at least that's the intention.

Please check if it works better for your roads.

**Comment by dakoehntopp** [comment]
v2.31.8 works with our maps. Thank you :)
