### ISSUE TITLE
GPS sensor location of ego based on georeference in xodr

### ISSUE THREAD

**Issue by pandaritrl** [esmini/esmini#443]
Hi,
I am trying to extract the global pose of the vehicle (Lat, Long, Alt or ECEF x,y,z position) based on the georeference string in xodr. Is it possible to access it from offline logs or online while the simulation is running?

**Comment by eknabevcc** [comment]
No, unfortunately esmini is not yet calculating geo reference coordinates. 

However, the location can be specified in the OpenDRIVE geoReference element of the header. OSI [map_reference](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/current/gen/structosi3_1_1GroundTruth.html#sec_14) will be populated accordingly. 

You can find `<geoReference>` example in [e6mini.xodr](https://github.com/esmini/esmini/blob/master/resources/xodr/e6mini.xodr), which will result in OSI map_reference:
`map_reference: "+proj=utm +lat_0=37.3542934123933 +lon_0=-122.0859797650754"`

That way it's possible for an external process to calculate a geo position (based on map_reference + local x, y coordinates).

**Comment by pandaritrl** [comment]
Sounds good. That works. Thanks.
