### ISSUE TITLE
LaneChange in wrong direction

### ISSUE THREAD

**Issue by ClemensLinnhoff** [esmini/esmini#444]
According to the OpenScenario user guide, relative lane changes are defined with respect to the vehicle entity:

> For the LaneChangeAction, relative target referencing works differently than absolute referencing. Here, the Vehicles' Xv-axis serves as reference direction. Lane changes are evaluated positive if they’re aligned with the vehicles' positive Yv -axis. Thus, a positive lane change moves the corresponding vehicle to the next actual lane in its positive Yv-axis direction. 

In esmini however, the relative target lane seems to be relative to the direction of the lane. Here are two examples I modified from the lane_change_simple scenario in the esmini resources folder.

[lane_change_simple.xosc.zip](https://github.com/esmini/esmini/files/11849084/lane_change_simple.xosc.zip):
In this example a positive relative lane change is performed. The ego vehicle correctly moves into the left lane.

[lane_change_simple_reverse.xosc.zip](https://github.com/esmini/esmini/files/11849096/lane_change_simple_reverse.xosc.zip):
In this example, the ego vehicle starts on the left lane driving in the reverse direction. It also performs a positive lane change. However, it is driving to the right from the point of view of the ego vehicle. But positive relative lane changes should always be to the left looking from the ego forward.

**Comment by eknabevcc** [comment]
Should be fixed in release [v2.31.8](https://github.com/esmini/esmini/releases/tag/v2.31.8)

Please check if it works as expected. 

FYI: Current implementation will calculate left/right based on the vehicle performing the action, not the referenced one, which happens to be the same in your case.

**Comment by ClemensLinnhoff** [comment]
Now it works. Thanks for the quick fix!
