### ISSUE TITLE
OpenDRIVE lane connectivity issue

### ISSUE THREAD

**Issue by johschmitz** [esmini/esmini#447]
I am having some trouble with cars getting stuck between road 33 and 34 in this example:

[example.zip](https://github.com/esmini/esmini/files/11886095/example.zip)

I checked the XML code but so far did not discover an error. Could it be a bug?

**Comment by johschmitz** [comment]
Alright I simplified it to the bare minimum to make the debugging easier:

[example.zip](https://github.com/esmini/esmini/files/11886124/example.zip)

![image](https://github.com/esmini/esmini/assets/771979/2258393d-c54e-43be-8b93-5d8fa1c80a25)

**Comment by eknabevcc** [comment]
I guess it can be argued, but to my understanding all links, both ways, needs to be explicitly defined. In provided files for the specific road link, the lane linkage is only specified one way. So the solution in this case is to add the missing ones. 

See modified xodrs: [modified-xodrs.zip](https://github.com/esmini/esmini/files/11891930/modified-xodrs.zip)

The modified ones looks OK also in https://odrviewer.io/

**Comment by johschmitz** [comment]
Ah alright thanks, I am going to check!

**Comment by johschmitz** [comment]
Okay I went through this and I believe this is a bug in the scenariogeneration lib which only occurs for some edge cases like this. Will open an issue in the other repo.

**Comment by johschmitz** [comment]
Here the related issue: https://github.com/pyoscx/scenariogeneration/issues/169

**Comment by eknabevcc** [comment]
Excellent that you found the root cause! And provided a fix proposal as well. 👍
