### ISSUE TITLE
Proposal: Integrate ALKS OpenScenario files in CI

### ISSUE THREAD

**Issue by jdsika** [esmini/esmini#45]
We have released the "BMW interpretation" of the ALKS regulation as openScenario/openDrive bundle. We advertise esmini in the project and you could consider integrating a release tag into your CI in order to see if your changes break any of the scenarios?

https://github.com/arauschert/OSC-ALKS-scenarios

Best regards
Carlo

**Comment by eknabevcc** [comment]
What a great initiative releasing that bundle of scenarios! Let see if we (later) can improve the visual experience, maybe with road-marks and make use of the simple 3D models for cars and pedestrian. 
Good idea! We will check into how we could include these set of scenarios as acceptance tests. There are some good work started and ongoing regarding unit/function test framework, and hopefully we can connect it to the CI and include your scenarios. 
Do you have any thoughts on how to verdict a scenario run? E.g. looking at vehicle positions in log file? Or maybe as a first step just check that the scenario is parsed correctly by scanning standard output for errors?

**Comment by jdsika** [comment]
I think the "evaluation of a scenario" involves some conceptual work from the ground up. How to define a test including a DUT (even if it is a dummy DUT) and some KPIs. What are the ongoing discussions in OSC1.X around that? @arauschert 

I think there was an ideation workshop around test specification at ASAM already?

We should start with "is the scenario parsed correctly" and extend the testing along with the development of the test specification. I think it is a great minimal test environment. I wouldn't care too much about the optical stuff. Only if it is relevant for the debugging :)

**Comment by eknabevcc** [comment]
Makes sense. Let's keep this open and we'll figure out, over next coming weeks, what and how we can do a first step.

**Comment by arauschert** [comment]
I agree to start with "is the scenario parsed correctly?", i.e. "can it be executed?" with esmini.
Acceptance tests for the DUT behaviour can only be done, when a controller different from the OSC default controller is used. So something similar to an ALKS. Maybe simplified Keep Lane/keep distance control algorithms are available open source for integration?
There was an initial discussion about test&scenario in the ASAM Coordination group with the result that there will be a Test specification study group project end of this year at ASAM. The proposal is: [here](https://code.asam.net/simulation/proposal/study-group/test-specification/-/jobs/artifacts/master/raw/P2020_SBT_Study_Project_Proposal.html?job=html)

In OSC 1.x we focus mainly on the scenario. There is one extension planned so it will be possible to reference from your proprietary test case description to a standardized parameter value distributions file, which is compatible with OSC1 scenarios. This enables for definition of logical scenarios with variation.

**Comment by eknabevcc** [comment]
ALKS scenarios added to esmini CI test suite, as a submodule. The [test cases](https://github.com/esmini/esmini/blob/master/test/alks_suite.py) simply runs each scenario, then do some checks for scenario events (e.g. scenario being loaded and triggers looking in the log file) and some state checks (e.g. time correlated vehicle position and speed looking in .csv file). 
I think this is a good start. Like another smoke test making sure esmini can still run the ALKS scenarios, and actually contributing to regression test of esmini itself.

This is how it looks like this in the [CI log](https://ci.appveyor.com/project/esmini/esmini/build/job/w0uln4bgrygc9q6k#L1520):

```
C:/Python38/python alks_suite.py
test_ALKS_Scenario_4_1_1_FreeDriving (__main__.TestSuite) ... ok
test_ALKS_Scenario_4_1_2_SwervingLeadVehicle (__main__.TestSuite) ... ok
test_ALKS_Scenario_4_1_3_SwervingSideVehicle (__main__.TestSuite) ... ok
test_ALKS_Scenario_4_2_1_FullyBlockingTarget (__main__.TestSuite) ... ok
test_ALKS_Scenario_4_2_2_PartiallyBlockingTarget (__main__.TestSuite) ... ok
test_ALKS_Scenario_4_2_3_CrossingPedestrian (__main__.TestSuite) ... ok
test_ALKS_Scenario_4_2_4_MultipleBlockingTargets (__main__.TestSuite) ... ok
test_ALKS_Scenario_4_3_1_FollowLeadVehicleComfortable (__main__.TestSuite) ... ok
test_ALKS_Scenario_4_3_2_FollowLeadVehicleEmergencyBrake (__main__.TestSuite) ... ok
test_ALKS_Scenario_4_4_1_CutInNoCollision (__main__.TestSuite) ... ok
test_ALKS_Scenario_4_4_2_CutInUnavoidableCollision (__main__.TestSuite) ... ok
test_ALKS_Scenario_4_5_1_CutOutFullyBlocking (__main__.TestSuite) ... ok
test_ALKS_Scenario_4_5_2_CutOutMultipleBlockingTargets (__main__.TestSuite) ... ok
test_ALKS_Scenario_4_6_1_ForwardDetectionRange (__main__.TestSuite) ... ok
test_ALKS_Scenario_4_6_2_LateralDetectionRange (__main__.TestSuite) ... ok
----------------------------------------------------------------------
Ran 15 tests in 32.086s

```
First release including this test solution is [v2.3.2](https://github.com/esmini/esmini/releases/latest).
