### ISSUE TITLE
Player arguments always set record true no matter what the configuration is in se.SE_Init

### ISSUE THREAD

**Issue by ChengWang2018** [esmini/esmini#457]
Hi,

I encounter a error after I set the record in se.SE_Init as 1. Data .dat can be recorded successfully. However, when i set the record as 0, it never changes back. It always record the data. The following command is shown in terminal:

Player arguments:  esmini(lib) --osc D:/Work/esmini/EnvironmentSimulator/code-examples/ad_hoc_traffic/empty_scenario.xosc --record empty_scenario.dat --headless

I have not set the --record and also --headless in se.SE_Init. I have no idea how it was configued.

This is what I wrote in my script:
        self.se.SE_Init(
            (esmini_path + "/EnvironmentSimulator/code-examples/ad_hoc_traffic/empty_scenario.xosc").encode(),
            disable_ctrls=0, use_viewer=1,
            threads=1, record=0)

Record is 0. but player argument always has --record, as shown above.

**Comment by eknabevcc** [comment]
Named parameters does not work by default with ctypes wrapper. Try to just remove the parameter names, like this:

```self.se.SE_Init((esmini_path + "/EnvironmentSimulator/code-examples/ad_hoc_traffic/empty_scenario.xosc").encode(), 0, 1, 1, 0)```

**Comment by ChengWang2018** [comment]
That works. Thanks a lot!
