### ISSUE TITLE
Marking issues

### ISSUE THREAD

**Issue by csawp** [esmini/esmini#458]
Hello, RM doesn't seem to support SOLID_ BROKEN and BROKEN_ Can SOLID markings enable it to support
![image](https://github.com/esmini/esmini/assets/114643211/f0ea181c-869c-4840-9f80-9182695413ea)
[mark.zip](https://github.com/esmini/esmini/files/12143058/mark.zip)

**Comment by eknabevcc** [comment]
Complex road marks like "solid broken" and "broken solid" can be specified explicitly. See attached example: [complex_roadmarks.zip](https://github.com/esmini/esmini/files/12206822/complex_roadmarks.zip)

![roadmark](https://github.com/esmini/esmini/assets/29146839/5c6dbb6e-224d-4e93-8cee-b5f47434560c)

**Comment by csawp** [comment]
Thanks for your reply
