### ISSUE TITLE
TrafficSwarmAction - parse for <centralObject> and not <CentralSwarmObject>

### ISSUE THREAD

**Issue by sterres** [esmini/esmini#459]
Hi,

the traffic swarm example uses a tag **<CentralSwarmObject>**
https://github.com/esmini/esmini/blob/371e593c133894538ba0f86443e72bdf0832fa35/resources/xosc/swarm.xosc#L65C24-L65C42

In OpenSCENARIO specification it is specified as  **<centralObject>**

https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.2.0_Model_Documentation/modelDocumentation/content/TrafficSwarmAction.html

Is this a bug or per design?  :-)

Best regards
Simon

**Comment by eknabevcc** [comment]
Good finding! Checking the XSD representation I see that the element name should be "CentralObject" instead of "CentralSwarmObject". 

So, the parser should look for "CentralObject" (and not "centralObject"). Is that also according to your understanding?

**Comment by sterres** [comment]
Yes, "CentralObject" - exactly...good that you double checked :-)

**Comment by eknabevcc** [comment]
👍
Fixed by commit c67595fc23769d0c8cb9aae24a0ac3a891ee1214 in dev branch. Will be merged to master by next release.

**Comment by sterres** [comment]
Thank you for this super fast fix  :-)

**Comment by eknabevcc** [comment]
Included in release [v2.31.10](https://github.com/esmini/esmini/releases/tag/v2.31.10).
