### ISSUE TITLE
Feature request for LaneChangeAction with transition dynamics dimension "rate"

### ISSUE THREAD

**Issue by arauschert** [esmini/esmini#46]
The ALKS regulation UN R157 parametrizes the LaneChangeAction in a Cut-In and Cut-Out maneuver with the maximum lateral velocity of the lead vehicle. This would correspond to the transition dynamics dimension "rate" (change of lateral position by time, m/s). At the moment esmini only provides "time" and "distance" as transition dynamics dimension. Would it be possible to also provide "rate"?
I could provide a formula for sinusoidal shapes to calculate the distance from the maximum lateral velocity. Then it would be the same case as "distance".

**Comment by eknabevcc** [comment]
Yes please share the calculation. That would be appreciated and I can hopefully add it quickly. 👍

**Comment by arauschert** [comment]
Here you are. Hope it´s correct. :)
[Calculation longitudinal distance from lateral velocity.docx](https://github.com/esmini/esmini/files/5348848/Calculation.longitudinal.distance.from.lateral.velocity.docx)

**Comment by eknabevcc** [comment]
Great. Thanks for the formula with excellent explanation!

I don't dare to say whether it's right or not, but I've implemented it and tried to get it right (and it looks OK I think) :)
commit [6b80331](https://github.com/esmini/esmini/commit/6b80331571511f3d8e88b9f927c7c3cbb2fb9d18)

Binaries should be available here: 
https://ci.appveyor.com/project/esmini/esmini/builds/35642488/job/s08q4bsvwwvac3pi/artifacts

Please check. You need a release asap, or should we just put it in the pile of fixes for next release?

**Comment by arauschert** [comment]
I´ve tested it and it looks like the execution of the lane change takes too long for linear and for sinusoidal shapes. 
Here´s my example data:
dimension: rate
shape: linear
vy: 1 m/s
With a lane width of 3.5 m, the lane change should take 3.5 s. But when executing the scenario, the lane change takes around 11s.
I´ll keep testing.

**Comment by arauschert** [comment]
In OSCPrivateAction.cpp, line 169:
		double lat_distance = object_->pos_.GetT() - target_->value_;

target_->value_ is the absolute of relative target lane ID. Should this be the target offset in t instead (like local variable target_t in LatLaneChangeAction::Step())?

**Comment by eknabevcc** [comment]
Yes, you're right. It's a bug. The target_->value_ holds the target lane ID, not distance. Now I just [committed an update](https://github.com/esmini/esmini/commit/9880761fe60030265573920578f543b8e0e7113a) calculating the lateral distance and hopefully solves the issue. 
The binaries should be found here: https://ci.appveyor.com/project/esmini/esmini/builds/35658551/job/ef7wj64d9frinnfu/artifacts

**Comment by arauschert** [comment]
I tested the new version and now it looks good! A release would be great because then we can kick out the scenarios, which are adapted for executability in esmini and have only the scenarios, which are compliant with the ALKS regulation.

**Comment by eknabevcc** [comment]
Thanks a lot for testing and providing feedback! 
A new release (1.7.13) available:
https://github.com/esmini/esmini/releases/tag/v1.7.13

**Comment by arauschert** [comment]
Thanks a lot!

**Comment by eknabevcc** [comment]
Let's close this now. We can open new ones if we discover further issues.
