### ISSUE TITLE
Visualize objects with bounding box instead of .osgb meshes

### ISSUE THREAD

**Issue by zzhuolun** [esmini/esmini#478]
Hi,

I'm curently using esmini to replay some `.xosc` OpenSCENARIO scenes. While esmini displays all the objects using their respective `.osgb` meshes, I'd like to visualize the objects based on their dimensions (width, length, and height) which I have on hand. Is there a way to achieve this?

Here is a snippet of one object from the .xosc file:
```
</ScenarioObject>                                                                                                                                                            
        <ScenarioObject name="29">                                                                                                                                                   
            <Vehicle name="vehicle_29" vehicleCategory="car" model3d="car_red.osgb">                                                                                                 
                <Performance maxSpeed="70" maxAcceleration="200" maxDeceleration="10"/>                                                                                              
                <Axles>                                                                                                                                                              
                    <FrontAxle maxSteering="0" wheelDiameter="0" trackWidth="0" positionX="0" positionZ="0"/>                                                                        
                    <RearAxle maxSteering="0" wheelDiameter="0" trackWidth="0" positionX="0" positionZ="0"/>                                                                         
                </Axles>                                                                                                                                                             
                <BoundingBox>                                                                                                                                                        
                    <Center x="0.0" y="0.0" z="0.767"/>                                                                                                                              
                    <Dimensions length="2.73" width="1.815" height="1.533"/>                                                                                                         
                </BoundingBox>                                                                     
<img width="283" alt="esmini-bbx" src="https://github.com/esmini/esmini/assets/23330740/63189477-2c6c-4a88-bba4-f3bfd01e68bf">
                                                                                  
                <Properties>                                                                                                                                                         
                    <Property name="type" value="simulation"/>                                                                                                                       
                </Properties>                                                                                                                                                       
            </Vehicle>                                                                                                                                                               
        </ScenarioObject>
```

**Comment by eknabevcc** [comment]
I assume you use esmini standalone application. Then you can pre-select bounding box mode. Start esmini with launch flag `--bounding_boxes`, for example:

./bin/esmini --window 60 60 800 400 --osc ./resources/xosc/cut-in.xosc --bounding_boxes

Regarding dimension of bounding boxes (BB) vs 3D model, esmini offer three options:
1. Keep bounding box and 3D model dimensions independently, i.e. they can actually differ. (None)
2. Scale BB to whatever dimension of the 3D model (BBToModel)
3. Scale 3D model to whatever dimension of the BB (ModelToBB)

Option 1 (None) may look like this when BB and 3D model scale is not aligned:

![none](https://github.com/esmini/esmini/assets/29146839/efda3241-b915-40b9-92fc-cdc8d25eb29c)

Option 2 and 3 will ensure perfect fitting:

![model2bb](https://github.com/esmini/esmini/assets/29146839/0cfd4b37-8e96-4f62-9d16-59d825ca4e79)

This is controlled by the object property `scaleMode`, which is non-standard and specific to the esmini tool. See examples in [VehicleCatalog.xosc](https://github.com/esmini/esmini/blob/6c252273c5aa2422d5629a59febeee436fa74ee2/resources/xosc/Catalogs/Vehicles/VehicleCatalog.xosc#L34)

**Comment by zzhuolun** [comment]
Thank you so much for the quick reply! Now I can visualize the bounding box(BB) and car models (Model) together.

I looked into my local `esmini-demo/resources/xosc/Catalogs/Vehicles/VehicleCatalog.xosc` file, and the car_red has scaleMode `BBToModel`, which means BB is resized to match the Model size. However, at the esmini replay, I found the red cars actually having different BB sizes:
![Screenshot from 2023-09-28 18-13-04](https://github.com/esmini/esmini/assets/23330740/7d24ef82-afa6-4fe9-b3ef-ad8c13e1f07d)

Also, the center of the Model seems to be at the rear axis of the cars, do you perhaps have any idea to solve this?

This is my esmini version:
```
esmini GIT REV: 1d32c34
esmini GIT TAG: v2.31.10
esmini GIT BRANCH: tags/v2.31.10
esmini BUILD VERSION: 3350
```

**Comment by zzhuolun** [comment]
Thank you so much!

I recreated the openscenario .xosc file with `scaleMode`=`ModelToBB`. Now the bounding box and model meshes are aligned and models are rescaled to match the bounding box size. Also, the offset between the model and the bounding box disappears:
![image](https://github.com/esmini/esmini/assets/23330740/e2cf8daf-70ee-49bf-baea-cc9abc6bff6e)


But now I'm not sure if the bounding box is correctly centered. I'd like to display the bounding box center at the actual vehicle center. You mentioned the reference point is at the mid rear axle projected on ground. Should I make changes to my vehicle definition to center the bounding box? Or it is already centered?

Here is a snippet of one vehicle definition from my .xosc file.
```
     </ScenarioObject>
      <ScenarioObject name="162">
          <Vehicle name="vehicle_162" vehicleCategory="car" model3d="car_red.osgb">
              <Performance maxSpeed="70" maxAcceleration="200" maxDeceleration="10"/>
              <Axles>
                  <FrontAxle maxSteering="0" wheelDiameter="0" trackWidth="0" positionX="0" positionZ="0"/>
                  <RearAxle maxSteering="0" wheelDiameter="0" trackWidth="0" positionX="0" positionZ="0"/>
              </Axles>
              <BoundingBox>
                  <Center x="0.0" y="0.0" z="0.772"/>
                  <Dimensions length="2.915" width="1.854" height="1.543"/>
              </BoundingBox>
              <Properties>
                  <Property name="type" value="simulation"/>
                  <Property name="scaleMode" value="ModelToBB"/>
              </Properties>
          </Vehicle>
      </ScenarioObject>
```

**Comment by eknabevcc** [comment]
Good to hear, looks perfect! 👍

I don't know if it's very important for your use case. But according to the (OpenSCENARIO 1.X) standard vehicles should have reference point at rear axle, while other objects in geometric center, both projected on ground (at "neutral load conditions").

See [here](https://www.asam.net/index.php?eID=dumpFile&t=f&f=4908&token=ae9d9b44ab9257e817072a653b5d5e98ee0babf8#_coordinate_systems) under _6.3.4. Vehicle coordinate system_ and _6.3.5. Pedestrian / MiscObject coordinate system_.

This is a typical center definition from an esmini car:
`<Center x="1.4" y="0.0" z="0.75"/>`

But if a geometrical center also for vehicles fits your use case, I guess that's fully OK. 

One slight negative side effect might be that cars look a bit funny in sharp turns, when rotating around geometric center instead of rear axle. But that's just cosmetics. Also it might be an issue if ground-truth from your simulation is communicated, e.g. via OSI, to an external process, like a sensor model. Other than that I think it's fine.

**Comment by zzhuolun** [comment]
Thanks for the reply!

So in order to place the bounding box at the geometric center of the car, I would have to define the center to be something similar to `<Center x="1.4" y="0.0" z="0.75"/>`. My previous definition of `<Center x="0" y="0.0" z="0.75"/>` will put the bounding box center on the mid rear axis, not the geometric center of the car. 

Is this understanding correct?

**Comment by eknabevcc** [comment]
Actually I think it's the other way around. For bounding box center you should set x="0.0" (like you already had). 
Only if you want to align with the standard (rear axle center) you should change x to something like 1.4.
You can toggle bounding box view mode on ',' (comma) key. And then see where the small ball/sphere is located - it represent the reference point.
Try x=0.0, and see if ball is in center. Please report back, I'm a bit curios of the result.

**Comment by eknabevcc** [comment]
Exactly, you got it all right! Good summary.
