### ISSUE TITLE
How to speed up emulation of esmini with some commands?

### ISSUE THREAD

**Issue by Liuzy0908** [esmini/esmini#485]
Hi everyone,

My question is how to speed up emulation of esmini with some commands?

Yours, sincerely!

**Comment by eknabevcc** [comment]
See https://github.com/esmini/esmini/issues/481

Further, you can run simulation headless and then replay it with some more view control. Try:

`./bin/esmini --headless --osc ./resources/xosc/cut-in.xosc --fixed_timestep 0.05 --record sim.dat`
`./bin/replayer --window 60 60 800 400 --file sim.dat --res_path ./resources`

or in one step:
`./bin/esmini --headless --osc ./resources/xosc/cut-in.xosc --fixed_timestep 0.05 --record sim.dat; ./bin/replayer --window 60 60 800 400 --file sim.dat --res_path ./resources`

In replayer you can then pause, step and move fast forward or backward. See more info in [User guide - Replay scenario](https://esmini.github.io/#_replay_scenario) and [User guide - replayer - Key shortcuts](https://esmini.github.io/#_replayer).

**Comment by Liuzy0908** [comment]
> See #481
> 
> Further, you can run simulation headless and then replay it with some more view control. Try:
> 
> `./bin/esmini --headless --osc ./resources/xosc/cut-in.xosc --fixed_timestep 0.05 --record sim.dat` `./bin/replayer --window 60 60 800 400 --file sim.dat --res_path ./resources`
> 
> or in one step: `./bin/esmini --headless --osc ./resources/xosc/cut-in.xosc --fixed_timestep 0.05 --record sim.dat; ./bin/replayer --window 60 60 800 400 --file sim.dat --res_path ./resources`
> 
> In replayer you can then pause, step and move fast forward or backward. See more info in [User guide - Replay scenario](https://esmini.github.io/#_replay_scenario) and [User guide - replayer - Key shortcuts](https://esmini.github.io/#_replayer).

Thanks!
