### ISSUE TITLE
ODRViewer - ObjectRepeat: positional error

### ISSUE THREAD

**Issue by mussandreasMVIS** [esmini/esmini#489]
Hi,
I found an issue with the objectRepeat components in the ODRViewer.
The repeat entries of the object are not correctly displayed in the viewer itself. The positional error can be observed in s- and t-direction.
This is a screenshot of the visualization:
![object_repeat_positional_error](https://github.com/esmini/esmini/assets/150109035/bfb33cf9-0d2b-4d5e-ac8b-bfd8fb81bd70)
and this is a part of the ODR-file that you see above:
```xml
<object height="9.0719936230002407e-02" width="0.5000000000000000e+00" type="barrier" length="8.1154076930060626e-01" subtype="curbstone" dynamic="no" hdg="0.0000000000000000e+00" orientation="none" zOffset="0.0000000000000000e+00" id="4" s="2.1883526437796345e+01" t="5.1537831077442391e+00" validLength="8.1154076930060626e-01" pitch="0.0000000000000000e+00" roll="0.0000000000000000e+00">
	<repeat heightEnd="9.0719936230002407e-02" heightStart="9.0719936230002407e-02" widthEnd="0.0000000000000000e+00" zOffsetEnd="0.0000000000000000e+00" zOffsetStart="0.0000000000000000e+00" widthStart="0.0000000000000000e+00" tEnd="5.9009370339699316e+00" tStart="5.1537831077442391e+00" distance="0.0000000000000000e+00" length="8.1154076930060626e-01" s="2.1883526437796345e+01" />
</object>
<object height="9.2867514415264057e-02" width="0.5000000000000000e+00" type="barrier" length="8.1000304376490462e-01" subtype="curbstone" dynamic="no" hdg="0.0000000000000000e+00" orientation="none" zOffset="0.0000000000000000e+00" id="5" s="2.2695067207096951e+01" t="5.9009370339699316e+00" validLength="8.1000304376490462e-01" pitch="0.0000000000000000e+00" roll="0.0000000000000000e+00">
	<repeat heightEnd="9.2867514415264057e-02" heightStart="9.2867514415264057e-02" widthEnd="0.0000000000000000e+00" zOffsetEnd="0.0000000000000000e+00" zOffsetStart="0.0000000000000000e+00" widthStart="0.0000000000000000e+00" tEnd="6.6590531888638509e+00" tStart="5.9009370339699316e+00" distance="0.0000000000000000e+00" length="8.1000304376490462e-01" s="2.2695067207096951e+01" />
</object>
```

The snippet represents the last two objects which shouldn't be placed that far away from the reference line and should also have a fluent transition from one to another.

Unfortunately I'm not allowed to upload the ODR-file, but I tested it with the _straight_500m.xodr_ and can replicate the results.

**Comment by eknabevcc** [comment]
We've done some improvements for [v2.33.1](https://github.com/esmini/esmini/releases/tag/v2.33.1). 
Please try and report how it works for your odr file.

**Comment by mussandreasMVIS** [comment]
Works like a charm :)
![fixed_OR_positional_error](https://github.com/esmini/esmini/assets/150109035/8e73473c-9162-4c8d-941d-9e714e76119f)

**Comment by eknabevcc** [comment]
Thanks for quick test and confirmation! :)
