### ISSUE TITLE
Remote Call Step Function

### ISSUE THREAD

**Issue by bkrztrk** [esmini/esmini#497]
Hi,

As you know we can control step function with using python.

```
se.SE_Init(b"../resources/xosc/cut-in.xosc", 1, 1, 0, 0, 2)

for i in range (500):
   se.SE_Step()

```

But in my problem I am controlling esmini by using "socket"  in python.
Ex: https://github.com/esmini/esmini/blob/dev/EnvironmentSimulator/code-examples/hello_world/inject_actions.py

```
if __name__ == "__main__":

    parser = optparse.OptionParser()
    parser.add_option('-a', '--address',
        action="store", dest="address",
        help="ip address of destination host", default="127.0.0.1")

    options, args = parser.parse_args()

    root = Tk()
    root.attributes('-topmost',True)
    app = Application(master=root, ip=options.address)

    app.mainloop()
    app.close()
    root.destroy()
```
    
        
 So my question is: Is there any possibilities to control step function with using socket in python?

**Comment by eknabevcc** [comment]
I like the idea of extending the action server concept to include also stepping control.

So we renamed the "action_server" to "player_server" and extended the protocol to include step control.

See updated example [inject_actions.py](https://github.com/esmini/esmini/blob/dev/EnvironmentSimulator/code-examples/hello_world/inject_actions.py) and [video clip](https://youtu.be/FmLtwj518No).

Included in release [v2.36.0](https://github.com/esmini/esmini/releases/tag/v2.36.0)

Let us know whether this matches your need.

**Comment by kancanaraa** [comment]
Hi again,

I'm grateful for your support, it will be very useful for me to control the scenario.
See you in the next issue :)

**Comment by bkrztrk** [comment]
Hi again,

I'm grateful for your support, it will be very useful for me to control the scenario.
See you in the next issue :)

**Comment by eknabevcc** [comment]
By release [v2.37.1](https://github.com/esmini/esmini/releases/tag/v2.37.1), and exposing action injection to the lib API, the example script above (inject_actions.py) was renamed to [inject_actions_udp.py](https://github.com/esmini/esmini/blob/dev/EnvironmentSimulator/code-examples/hello_world/inject_actions_udp.py).

Another script,  [action_injection.py](https://github.com/esmini/esmini/blob/dev/EnvironmentSimulator/code-examples/hello_world/action_injection.py), was added to demonstrate injection by API. See also [User guide - Inject actions](https://esmini.github.io/#_inject_actions).

**Comment by kancanaraa** [comment]
Thanks for the info, I will have a try..
