### ISSUE TITLE
CI for Mac

### ISSUE THREAD

**Issue by davidhesselbomvcc** [esmini/esmini#5]
AppVeyor builds binaries for Ubuntu and Windows. [Travis CI](https://travis-ci.org/) is another (free for open-source projects) build service, like AppVeyor, that can build Mac binaries (and Linux, but you already have AppVeyor for that).

Like AppVeyor, Travis CI uses a .yml file for build instructions, but it looks a little different.

There may be better alternatives to Travis CI, it's just one of many services like it.

**Comment by eknabevcc** [comment]
[Appveyor](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.appveyor.com%2Fblog%2F2019%2F11%2F20%2Fbuild-macos-projects-with-appveyor%2F&data=02%7C01%7Cemil.knabe%40volvocars.com%7C9494546dab2143eea32908d76e7f59a9%7C81fa766ea34948678bf4ab35e250a08f%7C0%7C0%7C637099365545558346&sdata=WBW%2FQ9%2FMBaEyL8%2BVupqJpDilVQ8rNuD%2BUGk%2F0OEdArQ%3D&reserved=0) now appears to support MAC. 
So hopefully we'll be able to add MAC to the list of environments for automatic builds. I someone have access to MAC and would be willing to test and provide a build script to the existing yaml file, please let us know!

**Comment by davidhesselbomvcc** [comment]
> If someone have access to MAC

Well, *we* have acces to a Mac if AppVeyor supports it, right? ;)

**Comment by eknabevcc** [comment]
That's correct :) 
So we just need to prepare the build script for that environment (yaml script). I just imagine it would be smoother to play around on a local Mac first. And then when it works as expected, transfer the build steps to appveyor. At least if we have the ambition to include the OpenSceneGraph 3D viewer I think will require some experimenting.
At least it would be nice to be able to download artefacts and run esmini on a Mac to verify the build process.

**Comment by davidhesselbomvcc** [comment]
True, it's hard to know if the artifacts work as expected without access to a physical machine...

**Comment by eknabevcc** [comment]
Mac target added to CI service AppVeyor: https://ci.appveyor.com/project/esmini/esmini
So far only non-OSG configurations. Only RoadManagerDLL and ScenarioEngineDLL are built and without 3D graphics viewer. Still useful for adding OpenDRIVE and OpenSCENARIO support to Mac applications (including Unity).
OSG and viewer support will be a next stop.
