### ISSUE TITLE
Positioning on a different road relative to ego? 

### ISSUE THREAD

**Issue by pjk19942** [esmini/esmini#502]
Hi, I wanted to modify my existing openscenarios in relative coordinates wrt to ego vehicle. I was able to use RelativeLanePosition for vehicles that are on the current road , but for cases where the non ego actor is on a totally separate road this method fails(say a 2 road intersection with different road ids ) any suggestions on how such scenarios can be created?

**Comment by MandolinMicke** [comment]
I would suggest using RelativeLanePosition but relative to the target itself, then just have a trigger based on when you want it to happen.

**Comment by pjk19942** [comment]
Yeah but for cases where there are say 8 different roads, and 8 different actors, having a relativeLanePosition for each target is as good as using absolute coordinates. The idea here is if one knows the position of one vehicle or one point, all other vehicle positions , if can be found , would help with the workflow. Specially when we are trying to extract the meta data to be used elsewhere. 
Any thoughts?

**Comment by mander76** [comment]
Aha, now I get it, missunderstood that it was for the initialization. For different roads no, then I have no real idea to be honest... It becomes much more difficult.. 
The only way I see (in OpenSCENARIO) to deal with different roads is to have some kind of RoutePosition (have not tried it myself though), eg. so routes are defined between each vehicle, since that can be done in some kind of lane/road coordinates aswell.

**Comment by eknabevcc** [comment]
Very good input. Relative positioning has been limited so far, mainly working for the same road id. But of course it should work also across road connections and even junctions. But as @mander76 pointed out, it becomes a bit tricky wrt routing.

Anyway, we've now made an attempt to improve this handling in esmini. Relative road and lane positions should now work across road connections junctions. Any route of action entity is prioritized over any route of the referenced car. 

See brief info in [User guide - Relative positions and routes](https://esmini.github.io/#_relative_positions_and_routes)

Not sure if the fixes fully addresses your need. Anyway, it's included in release [v2.36.0](https://github.com/esmini/esmini/releases/tag/v2.36.0)
