### ISSUE TITLE
Positioning error?

### ISSUE THREAD

**Issue by victor0777** [esmini/esmini#504]
Hi, 

I tested my scenario with latest esmini SW(2.34.1)

I found that each of initial position of some cars is reverse direction.

I specified "head = 0, pitch = 0, roll = 0, 'relative' position" for all vehicles

 
![20231212 Reverse_Car1](https://github.com/esmini/esmini/assets/111849721/cfa7d3b7-b4cb-47ca-a4b6-d1c7492c6e03)

![20231212 Reverse_dire
[myscenario.zip](https://github.com/esmini/esmini/files/13642083/myscenario.zip)
ction_Cars](https://github.com/esmini/esmini/assets/111849721/0be6f7fd-5220-4174-91bd-fbcf289e91ac)

I think that it is a SW bug.

It would be nice, if you look at my scenario code.

Regards

**Comment by victor0777** [comment]
[myscenario.zip](https://github.com/esmini/esmini/files/13643455/myscenario.zip)

**Comment by eknabevcc** [comment]
Can you specify what version of esmini you run previously where you got different orientations?
I run your scenario in v2.34.1 and v2.31.1 and each car get same heading in both versions.

That said, there has been updates to positioning lately so I don't rule out that there is a problem.

**Comment by victor0777** [comment]
Thank you for your comment. 

In my intended scenario, I expected all vehicles to drive on the right. Therefore, in the picture shown above, I found that the heading direction of all vehicles was not on the right, but some vehicles were on the left. From the perspective of the right-hand traffic rule, it becomes a scenario of driving in reverse.

**Comment by eknabevcc** [comment]
Ah, I see. It's not that the behavior has changed between some esmini versions. It's the behavior as such that is the question here.

Long story short. In esmini we handle road- and lane position differently wrt heading and road direction. RoadPosition will relate to road s-axis while LanePosition will relate to the driving direction of the lane.

see brief info in [User guide - Heading behavior in Road vs Lane Position](https://esmini.github.io/#_heading_behavior_in_road_vs_lane_position)

So, for RoadPosition, any t > 0 and relative h = 0 will point in "wrong" direction, while relative h = 0 will always point in right direction. 

From your provided scenario, one "wrong" example (Car1):
```xml
    <RoadPosition roadId="1" s="98.075" t="2.059">
        <Orientation h="0.0" p="0.0" r="0.0" type="relative"/>
    </RoadPosition>
```
either change heading to pi or switch to LanePosition 

A "correct" example: Car4 is positioned using LanePosition, and it ends up correct

**Comment by victor0777** [comment]
Thanks. 👍
