### ISSUE TITLE
The number of Connection elements in a Junction of an .xodr file is m, but when read into OpenDRIVE (pJunction), the number of Connections becomes 2m.

### ISSUE THREAD

**Issue by csawp** [esmini/esmini#510]
The number of Connection elements in a Junction of an .xodr file is m, but when read into OpenDRIVE (pJunction), the number of Connections becomes 2m.
![image](https://github.com/esmini/esmini/assets/114643211/42a7dfd5-c9ac-4c7d-914f-729cb415b917)
![image](https://github.com/esmini/esmini/assets/114643211/8310eafa-1566-4649-8b9f-7b6564c037da)
[UC_Simple-X.zip](https://github.com/esmini/esmini/files/13737823/UC_Simple-X.zip)

**Comment by eknabevcc** [comment]
That's correct. Back in the days we had an issue with vehicles moving in wrong/opposite direction. As solution esmini creates a mirror/opposite variant of each connecting road. (yes, it could be done in other ways but this was the most feasible at the time)

**Comment by csawp** [comment]
:) thanks
