### ISSUE TITLE
Question) How should I interprete meanings of "Successor" and "Predecessor" of a road ?

### ISSUE THREAD

**Issue by victor0777** [esmini/esmini#511]
Hi ~

I'd like to develop a massive traffic scenario. To reach this goal, I'm developing an xodr scanning program to interpret the data structure of connections between roads and lanes.

I successfully retrieved information about overlapped roads in a specific position using the provided API, RM_GetNumberOfRoadsOverlapping. However, it appears that the information obtained is inaccurate.

As an alternative approach, I accessed the successor and predecessor of a road data structure. However, I'm uncertain about the meaning of successor and predecessor.

My current assumption is that:

Successor refers to the next road connected to the current position of the road.
Predecessor refers to the previous road connected to the current position of the road.
Yet, upon reviewing the pictures below:

![capture1](https://github.com/esmini/esmini/assets/111849721/bbd40268-fcb2-44b7-849d-1a537c0329db)
![capture2](https://github.com/esmini/esmini/assets/111849721/c2e0fb53-956c-4a1e-8f18-5c0f1069c864)

I observed that the information displayed in the spotlight window does not align with my assumptions about successors and predecessors. Further clarification or guidance on the correct interpretation of these terms would be appreciated.

Happy New Year.

**Comment by victor0777** [comment]
Add comment.

I attempted to interpret the information with the right-hand traffic rule in mind. 
Notably, in the provided images, vehicles are considered to move from left to right. 
This directional context is crucial to my understanding.

**Comment by victor0777** [comment]
I am reviewing open drive xml file. and It seems that it parsed as it specified. My question is still unclear but partially resolved.

**Comment by eknabevcc** [comment]
I see that you closed the issue. But I have a question and some input anyway :)

Regarding overlapping roads, the value should reflect the number of overlapping roads in a specific X, Y position. If it fails for your case, please provide a X, Y position for my investigation. (I assume this is the same road, Carla - Town10HD.xodr, that you kindly provided in a previous issue). 

Then regarding successor, predecessor. There are two levels of connections. First between roads, and then between lanes. I just checked connection between road 179 (in junction 532) and road 2. At quick glance it looks ok.  2 is successor to 179, connecting at end point (head to head). Lane linking also looks OK, road 179 lane -1 connecting to successor road 2 lane 2. 

Road and lane connectivity is super tricky. Here's some good info in the ASAM OpenDRIVE User guide:
    https://publications.pages.asam.net/standards/ASAM_OpenDRIVE/ASAM_OpenDRIVE_Specification/latest/specification/12_junctions/12_02_common_junctions.html

And a new dedicated junction guide:
https://publications.pages.asam.net/standards/ASAM_OpenDRIVE/ASAM_OpenDRIVE_Junction_guideline/latest/junction-guidelines/index.html
