### ISSUE TITLE
speed is getting slower 

### ISSUE THREAD

**Issue by victor0777** [esmini/esmini#517]
Hi,

Symptom is speed is getting slower as time goes by.
My expectation is getting faster.

I refered to test-driver.cpp sample code

throttle is positive means it is accelerating. (it is explained in the comment)

```
/**
            Control the speed and steering with floating values in the range [-1, 1], suitable for driver models.
            The function also steps the vehicle model, updating its position according to motion state and timestep.
            @param dt timesStep (s)
            @param throttle Longitudinal control, -1: maximum brake, 0: no acceleration, +1: maximum acceleration
            @param steering Lateral control, -1: max left, 0: straight, 1: max right
    */
    SE_DLL_API void SE_SimpleVehicleControlAnalog(void  *handleSimpleVehicle,
                                                  double dt,
                                                  double throttle,
                                                  double steering);  // throttle and steering [-1, 0 or 1]

```

This is my log.

dt: 0.1000, look ahead distance: 15.42, target_speed: 19.44, throttle: 0.56, steerAngle: 0.00, speed: 13.89, Obj18 speed: 13.89
dt: 0.0170, look ahead distance: 15.42, target_speed: 19.44, throttle: 0.56, steerAngle: 0.00, speed: 13.89, Obj18 speed: 13.89
dt: 0.0440, look ahead distance: 15.42, target_speed: 19.44, throttle: 0.56, steerAngle: 0.00, speed: 13.89, Obj18 speed: 13.89
dt: 0.0470, look ahead distance: 15.42, target_speed: 19.44, throttle: 0.56, steerAngle: 0.00, speed: 13.89, Obj18 speed: 13.89
dt: 0.0360, look ahead distance: 15.42, target_speed: 19.44, throttle: 0.56, steerAngle: 0.00, speed: 13.88, Obj18 speed: 13.89
dt: 0.0400, look ahead distance: 15.41, target_speed: 19.44, throttle: 0.56, steerAngle: 0.00, speed: 13.88, Obj18 speed: 13.89
dt: 0.0370, look ahead distance: 15.41, target_speed: 19.44, throttle: 0.56, steerAngle: 0.00, speed: 13.88, Obj18 speed: 13.89
dt: 0.0390, look ahead distance: 15.41, target_speed: 19.44, throttle: 0.56, steerAngle: 0.00, speed: 13.88, Obj18 speed: 13.89
dt: 0.0340, look ahead distance: 15.41, target_speed: 19.44, throttle: 0.56, steerAngle: 0.00, speed: 13.88, Obj18 speed: 13.89
dt: 0.0380, look ahead distance: 15.41, target_speed: 19.44, throttle: 0.56, steerAngle: 0.00, speed: 13.86, Obj18 speed: 13.89
dt: 0.0370, look ahead distance: 15.40, target_speed: 19.44, throttle: 0.56, steerAngle: 0.00, speed: 13.86, Obj18 speed: 13.89
dt: 0.0360, look ahead distance: 15.40, target_speed: 19.44, throttle: 0.56, steerAngle: 0.00, speed: 13.86, Obj18 speed: 13.89
dt: 0.0370, look ahead distance: 15.40, target_speed: 19.44, throttle: 0.56, steerAngle: 0.00, speed: 13.86, Obj18 speed: 13.89
dt: 0.0320, look ahead distance: 15.40, target_speed: 19.44, throttle: 0.56, steerAngle: 0.00, speed: 13.86, Obj18 speed: 13.89
dt: 0.0380, look ahead distance: 15.40, target_speed: 19.44, throttle: 0.56, steerAngle: 0.00, speed: 13.85, Obj18 speed: 13.89
dt: 0.0380, look ahead distance: 15.39, target_speed: 19.44, throttle: 0.56, steerAngle: 0.00, speed: 13.83, Obj18 speed: 13.89
dt: 0.0360, look ahead distance: 15.38, target_speed: 19.44, throttle: 0.56, steerAngle: -0.67, speed: 13.83, Obj18 speed: 13.89
dt: 0.0340, look ahead distance: 15.38, target_speed: 19.44, throttle: 0.56, steerAngle: -0.67, speed: 13.82, Obj18 speed: 13.89
dt: 0.0400, look ahead distance: 15.36, target_speed: 19.44, throttle: 0.56, steerAngle: -0.73, speed: 13.82, Obj18 speed: 13.89
dt: 0.0450, look ahead distance: 15.36, target_speed: 19.44, throttle: 0.56, steerAngle: -0.73, speed: 13.82, Obj18 speed: 13.89
dt: 0.0370, look ahead distance: 15.36, target_speed: 19.44, throttle: 0.56, steerAngle: -0.73, speed: 13.82, Obj18 speed: 13.89
dt: 0.0300, look ahead distance: 15.36, target_speed: 19.44, throttle: 0.56, steerAngle: -0.73, speed: 13.81, Obj18 speed: 13.89
dt: 0.0510, look ahead distance: 15.35, target_speed: 19.44, throttle: 0.56, steerAngle: -0.74, speed: 13.81, Obj18 speed: 13.89
dt: 0.0470, look ahead distance: 15.35, target_speed: 19.44, throttle: 0.56, steerAngle: -0.74, speed: 13.79, Obj18 speed: 13.89
dt: 0.0390, look ahead distance: 15.34, target_speed: 19.44, throttle: 0.57, steerAngle: -0.75, speed: 13.79, Obj18 speed: 13.89

**Comment by victor0777** [comment]
Today I tried in c++ environment, and it works well. 
But it does not work in Python environment.
Needs to be investigated deeply. I'll add when I find more.

**Comment by victor0777** [comment]
It seems that it is my mistake. I close this issue. sorry to bother you.

**Comment by eknabevcc** [comment]
No problem, I didn't have time to look into it yet. Thanks for quick investigating on your side! Glad you solved it.
