### ISSUE TITLE
Command execution error

### ISSUE THREAD

**Issue by yumianhuli2** [esmini/esmini#52]
Hello!
I used this command 
../../bin/esmini --window 50 50 1024 576 --osc ../../resources/xosc/controller_test.xosc
but got:
esmini GIT REV: 29aa37c
esmini GIT TAG: 
esmini GIT BRANCH: master
esmini BUILD VERSION: N/A - client build
ScenarioEngine.cpp / 35 / InitScenario(): Init ../../resources/xosc/controller_test.xosc
ScenarioReader.cpp / 52 / loadOSCFile(): Loading ../../resources/xosc/controller_test.xosc
Parameters.cpp / 108 / parseParameterDeclarations(): Parsing ParameterDeclarations
ScenarioReader.cpp / 173 / parseRoadNetwork(): Parsing RoadNetwork
ScenarioReader.cpp / 204 / parseRoadNetwork(): Roadnetwork ODR: ../xodr/curve_r100.xodr
ScenarioReader.cpp / 205 / parseRoadNetwork(): Scenegraph: ../models/curve_r100.osgb
RoadManager.cpp / 4274 / SetRoadOSI(): Generating OSI lanes
RoadManager.cpp / 4276 / SetRoadOSI(): Generating OSI road marks
RoadManager.cpp / 5574 / SetRoadMarkPos(): Truncate road mark s pos (760.00) to road length (757.08)
RoadManager.cpp / 4278 / SetRoadOSI(): Generating OSI lane boundaries
RoadManager.cpp / 4280 / SetRoadOSI(): OSI road features done
ScenarioReader.cpp / 549 / parseCatalogs(): Parsing Catalogs
ScenarioReader.cpp / 699 / parseEntities(): Parsing Entities
Parameters.cpp / 53 / getParameter(): Resolve parameter $EgoVehicle
Parameters.cpp / 61 / getParameter(): $EgoVehicle replaced with car_white
ScenarioReader.cpp / 140 / LoadCatalog(): Loading catalog VehicleCatalog
ScenarioReader.cpp / 302 / parseOSCVehicle(): Parsing Vehicle car_white
ScenarioReader.cpp / 220 / ParseOSCProperties(): Properties/File = ../models/car_white.osgb registered
ScenarioReader.cpp / 229 / ParseOSCProperties(): Property model_id = 0 registered
ScenarioReader.cpp / 1785 / parseInit(): Parsing init
Parameters.cpp / 99 / ReadAttribute(): Warning: missing required attribute: dynamicsDimension
ScenarioReader.cpp / 1146 / ParseDynamicsDimension(): Dynamics dimension  not supported - fall back to TIME
Parameters.cpp / 99 / ReadAttribute(): Warning: missing required attribute: value
ScenarioReader.cpp / 2414 / parseStoryBoard(): Parsing Story
Story.cpp / 21 / Story(): Story: New Story Story created
ScenarioReader.cpp / 2310 / parseOSCManeuver(): Parsing OSCManeuver ControllerManuever
ScenarioReader.cpp / 2325 / parseOSCManeuver(): Parsing Event SloppyDriverEvent
ScenarioReader.cpp / 2371 / parseOSCManeuver(): Parsing private action AssignSloppyDriverControllerAction
ScenarioReader.cpp / 140 / LoadCatalog(): Loading catalog ControllerCatalog
ScenarioReader.cpp / 1696 / parseOSCPrivateAction(): Parsing controller from reference: Controller
Parameters.cpp / 108 / parseParameterDeclarations(): Parsing ParameterDeclarations
ScenarioReader.cpp / 229 / ParseOSCProperties(): Property esminiController = SloppyDriverController registered
Parameters.cpp / 53 / getParameter(): Resolve parameter $Sloppiness
Parameters.cpp / 61 / getParameter(): $Sloppiness replaced with 0.5
ScenarioReader.cpp / 229 / ParseOSCProperties(): Property sloppiness = 0.5 registered
Parameters.cpp / 53 / getParameter(): Resolve parameter $Mode
Parameters.cpp / 61 / getParameter(): $Mode replaced with additive
ScenarioReader.cpp / 229 / ParseOSCProperties(): Property mode = additive registered
ScenarioReader.cpp / 442 / parseOSCObjectController(): Parsing Controller sloppyDriver
ScenarioReader.cpp / 2371 / parseOSCManeuver(): Parsing private action ActivateSloppyDriverControllerAction
ScenarioReader.cpp / 1667 / parseOSCPrivateAction(): ActivateControllerAction: Longitudinal: false Lateral: true
ScenarioReader.cpp / 2288 / parseTrigger(): Parsing Trigger
ScenarioReader.cpp / 1971 / parseOSCCondition(): Parsing OSCCondition 
ScenarioReader.cpp / 2325 / parseOSCManeuver(): Parsing Event LateralnteractiveEvent
ScenarioReader.cpp / 2371 / parseOSCManeuver(): Parsing private action AssignInteractiveControllerAction
ScenarioReader.cpp / 1696 / parseOSCPrivateAction(): Parsing controller from reference: Controller
ScenarioReader.cpp / 229 / ParseOSCProperties(): Property esminiController = InteractiveController registered
ScenarioReader.cpp / 442 / parseOSCObjectController(): Parsing Controller interactiveDriver
ControllerInteractive.cpp / 37 / ControllerInteractive(): 
ScenarioReader.cpp / 2371 / parseOSCManeuver(): Parsing private action ActivateLateralInteractiveControllerAction
ScenarioReader.cpp / 1667 / parseOSCPrivateAction(): ActivateControllerAction: Longitudinal: false Lateral: true
ScenarioReader.cpp / 2288 / parseTrigger(): Parsing Trigger
ScenarioReader.cpp / 1971 / parseOSCCondition(): Parsing OSCCondition 
ScenarioReader.cpp / 2325 / parseOSCManeuver(): Parsing Event LongitudinalInteractiveInteractiveEvent
ScenarioReader.cpp / 2371 / parseOSCManeuver(): Parsing private action AssignLongitudinalInteractiveControllerAction
ScenarioReader.cpp / 1696 / parseOSCPrivateAction(): Parsing controller from reference: Controller
ScenarioReader.cpp / 229 / ParseOSCProperties(): Property esminiController = InteractiveController registered
ScenarioReader.cpp / 442 / parseOSCObjectController(): Parsing Controller interactiveDriver
ControllerInteractive.cpp / 37 / ControllerInteractive(): 
ScenarioReader.cpp / 2371 / parseOSCManeuver(): Parsing private action ActivateInteractiveControllerAction
ScenarioReader.cpp / 1667 / parseOSCPrivateAction(): ActivateControllerAction: Longitudinal: true Lateral: false
ScenarioReader.cpp / 2288 / parseTrigger(): Parsing Trigger
ScenarioReader.cpp / 1971 / parseOSCCondition(): Parsing OSCCondition 
ScenarioReader.cpp / 2325 / parseOSCManeuver(): Parsing Event BetterSloppyDriverEvent
ScenarioReader.cpp / 2371 / parseOSCManeuver(): Parsing private action AssignBetterSloppyDriverControllerAction
ScenarioReader.cpp / 674 / ResolveCatalogReference(): Assigned 1 parameters for catalog ControllerCatalog entry sloppyDriver
ScenarioReader.cpp / 1696 / parseOSCPrivateAction(): Parsing controller from reference: Controller
Parameters.cpp / 108 / parseParameterDeclarations(): Parsing ParameterDeclarations
ScenarioReader.cpp / 229 / ParseOSCProperties(): Property esminiController = SloppyDriverController registered
Parameters.cpp / 53 / getParameter(): Resolve parameter $Sloppiness
Parameters.cpp / 61 / getParameter(): $Sloppiness replaced with 0.9
ScenarioReader.cpp / 229 / ParseOSCProperties(): Property sloppiness = 0.9 registered
Parameters.cpp / 53 / getParameter(): Resolve parameter $Mode
Parameters.cpp / 61 / getParameter(): $Mode replaced with additive
ScenarioReader.cpp / 229 / ParseOSCProperties(): Property mode = additive registered
ScenarioReader.cpp / 442 / parseOSCObjectController(): Parsing Controller sloppyDriver
ScenarioReader.cpp / 2371 / parseOSCManeuver(): Parsing private action ActivateBetterSloppyDriverControllerAction
ScenarioReader.cpp / 1667 / parseOSCPrivateAction(): ActivateControllerAction: Longitudinal: true Lateral: false
ScenarioReader.cpp / 2288 / parseTrigger(): Parsing Trigger
ScenarioReader.cpp / 1971 / parseOSCCondition(): Parsing OSCCondition 
ScenarioReader.cpp / 2325 / parseOSCManeuver(): Parsing Event DefaultControllerEvent
ScenarioReader.cpp / 2371 / parseOSCManeuver(): Parsing private action AssignDefaultControllerAction
ScenarioReader.cpp / 229 / ParseOSCProperties(): Property esminiController = DefaultController registered
ScenarioReader.cpp / 442 / parseOSCObjectController(): Parsing Controller defaultController
ScenarioReader.cpp / 2371 / parseOSCManeuver(): Parsing private action ActivateDefaultControllerAction
ScenarioReader.cpp / 1667 / parseOSCPrivateAction(): ActivateControllerAction: Longitudinal: true Lateral: true
ScenarioReader.cpp / 2288 / parseTrigger(): Parsing Trigger
ScenarioReader.cpp / 1971 / parseOSCCondition(): Parsing OSCCondition 
ScenarioReader.cpp / 2288 / parseTrigger(): Parsing Trigger
ScenarioReader.cpp / 1971 / parseOSCCondition(): Parsing OSCCondition ActStart
ScenarioReader.cpp / 2288 / parseTrigger(): Parsing Trigger
ScenarioReader.cpp / 1971 / parseOSCCondition(): Parsing OSCCondition EgoLaneChangeCondition
Entities.hpp / 389 / Print(): 
Story.cpp / 135 / Print(): Storyboard:
Story.cpp / 88 / Print(): Story: 
0.000 OSCPrivateAction.cpp / 684 / Start(): Ego pos: 
0.000 RoadManager.cpp / 5829 / Print(): Position:
0.000 RoadManager.cpp / 5814 / PrintTrackPos(): 	Track pos: (road_id 0, s 20.00, t -1.53, h 0.00)
0.000 RoadManager.cpp / 5819 / PrintLanePos(): 	Lane pos: (road_id 0, lane_id -1, s 20.00, offset 0.00, h 0.00)
0.000 RoadManager.cpp / 5824 / PrintInertialPos(): 	Inertial pos: (x 20.00, y -1.53, z 0.00, h 0.00, p 0.00, r 0.00)
0.000 OSCAction.cpp / 96 / SetState(): Init Ego TeleportAction standbyState -> startTransition -> runningState
0.000 OSCAction.hpp / 129 / End(): Init Ego LongitudinalAction complete after 1 execution
0.000 OSCAction.cpp / 96 / SetState(): Init Ego LongitudinalAction standbyState -> endTransition -> completeState
0.000 OSCAction.cpp / 96 / SetState(): Init Ego TeleportAction runningState -> stopTransition -> completeState
0.000 ScenarioGateway.cpp / 207 / reportObject(): Creating new object "Ego" (id 0, timestamp 0.00)
0.000 viewer.cpp / 688 / Viewer(): Scenario file directory, ../../resources/xosc, is used as pivot for model relative file paths
0.000 viewer.cpp / 714 / Viewer(): Anti-Aliasing number of subsamples: 4
Segmentation fault (core dumped)

**Comment by eknabevcc** [comment]
Thanks for the report! Of course the examples should work, so I want to find out the root cause.

I tried to reproduce the problem with latest esmini version (29aa37c) in Kubuntu 18.04. But it runs normally. So it is probably a tricky bug not always showing up. I hope you can answer a few questions:
1. What Linux distribution and version do you run? You can check with: "cat /etc/os-release"
2. Did this error pop up now suddenly, with the latest version? What was the last working version? Don't have to be exact, but it could be useful to know if it was days, weeks or months ago you run esmini without errors.
3. Do you run esmini in a docker container or in a remote desktop setup? 
The last question because these cases have caused an issue before with multisampling but we tried to fix it. Please try to add "--samples 0" just to see if the problem seems to be related to that.

**Comment by yumianhuli2** [comment]
> Thanks for the report! Of course the examples should work, so I want to find out the root cause.
> 
> I tried to reproduce the problem with latest esmini version ([29aa37c](https://github.com/esmini/esmini/commit/29aa37c1054a62715e8afabe6a7bf35ea38cdf9c)) in Kubuntu 18.04. But it runs normally. So it is probably a tricky bug not always showing up. I hope you can answer a few questions:
> 
>     1. What Linux distribution and version do you run? You can check with: "cat /etc/os-release"
> 
>     2. Did this error pop up now suddenly, with the latest version? What was the last working version? Don't have to be exact, but it could be useful to know if it was days, weeks or months ago you run esmini without errors.
> 
>     3. Do you run esmini in a docker container or in a remote desktop setup?
>        The last question because these cases have caused an issue before with multisampling but we tried to fix it. Please try to add "--samples 0" just to see if the problem seems to be related to that.

Yes,I ran this in ubuntu 16.04.I will try 18.04 and report it!

**Comment by eknabevcc** [comment]
Great. Please let me know if 18.04 behaves differently. And if possible, please try the `--samples 0` option in 16.04 (if you have it still available...)

**Comment by yumianhuli2** [comment]
> Great. Please let me know if 18.04 behaves differently. And if possible, please try the `--samples 0` option in 16.04 (if you have it still available...)

Yes,I tried --samples 0 option in 16.04 , This error is still prompted.
And, cmake --build . --config Release --target install is not worked for Error: could not load cache.
So I just run mkdir build,cd build && cmake ..

**Comment by eknabevcc** [comment]
Ok. I understand, thanks for clarification! 
And good that you run the cmake from scratch. A shortcut can be to remove just the file CMakeCache.txt in order to have a clean `cmake ..` and then the `cmake --build . --config Release --target install` should work again.

**Comment by yumianhuli2** [comment]
> Ok. I understand, thanks for clarification!
> And good that you run the cmake from scratch. A shortcut can be to remove just the file CMakeCache.txt in order to have a clean `cmake ..` and then the `cmake --build . --config Release --target install` should work again.

Thank you! ubuntu18.04 worked!
But why not 16.04 and how to support 16.04？
Thanks！

**Comment by yumianhuli2** [comment]
> Ok. I understand, thanks for clarification!
> And good that you run the cmake from scratch. A shortcut can be to remove just the file CMakeCache.txt in order to have a clean `cmake ..` and then the `cmake --build . --config Release --target install` should work again.
Thanks! Worked for both 16.04 and 18.04!

**Comment by eknabevcc** [comment]
Thanks a lot for testing - very good to know!! 👍

Good question, why not 16.04? 

By the way, could you try to run without graphics, i.e. using arguments `--headless --fixed_timestep 0.01`. Then check the log file - does it seem to run further?

If that works, perhaps the OpenSceneGraph (OSG) library has to be rebuilt for 16.04? (the supplied libs are built on 18.04).
There are some instructions here: 
https://github.com/esmini/esmini/blob/master/docs/BuildOSG.md.

However, it's probably not a very easy task. 
I will unfortunately not be able to look into this for the next two weeks or so. Let's leave the issue open and hopefully you or someone else can look into it meanwhile.

**Comment by eknabevcc** [comment]
Ah, do I understand correct that it now works for both 16.04 and 18.04? With graphics?
That would be almost too good news this Monday.

**Comment by yumianhuli2** [comment]
> Ah, do I understand correct that it now works for both 16.04 and 18.04? With graphics?
> That would be almost too good news this Monday.

Yes, OSG works both on 16.04 and 18.04!

But When I ran odrplot and loaded the e6min.xodr map, I found that the starting point in track.csv was -11.6999,0.0392664.
But when I opened opendrive's official OdrViewer64_1.9.1, I noticed that the starting point was -13.7,0. How do you think this error is caused?

Thanks!

**Comment by eknabevcc** [comment]
First great to hear about Ubuntu versions 👍
Now, odrplot - good question! I'll try to sort it out below.

odrplot plots only:
- reference line (red)
- center of drivable lanes (blue)

I must admit that I don't remember why we choose to plot only lane center... I agree it would make more sense to plot 1. All lanes (non drivable in grey) and 2. lane boundaries instead of center. That will perhaps be fixed later.

Now, given that odrplot shows lane center of drivable lanes:
The header you see on line 1: "lane 0 0 4" means here comes a lane with reference position x=0, y=0 and ID=4
Then follows coordinates and heading for that lane
To check whether -11.6999 is correct at center: According to e6mini.xodr width of lane 1=2.6 m, lane 2=3.65, lane 3=3.5, lane 4=3.9. Sum up 1+2+3+4/2 (remember center of lane 4) = 11.7.
Considering that heading is almost PI/2 (1.556 rad ~ 90 degrees) then left side lanes, with positive indices, will start on negative X-axis, explaining the -11.7. 
So it seems correct - but confusing I must admit.

You can search for other lanes in the same file. E.g. lane, 0, 0, -2 starts on line 5865.

If you just want to look at OpenDRIVE files I recommend using odrviewer instead. But I understand that you wanted more to investigate in this case.

**Comment by yumianhuli2** [comment]
> First great to hear about Ubuntu versions +1
> Now, odrplot - good question! I'll try to sort it out below.
> 
> odrplot plots only:
> 
>     * reference line (red)
> 
>     * center of drivable lanes (blue)
> 
> 
> I must admit that I don't remember why we choose to plot only lane center... I agree it would make more sense to plot 1. All lanes (non drivable in grey) and 2. lane boundaries instead of center. That will perhaps be fixed later.
> 
> Now, given that odrplot shows lane center of drivable lanes:
> The header you see on line 1: "lane 0 0 4" means here comes a lane with reference position x=0, y=0 and ID=4
> Then follows coordinates and heading for that lane
> To check whether -11.6999 is correct at center: According to e6mini.xodr width of lane 1=2.6 m, lane 2=3.65, lane 3=3.5, lane 4=3.9. Sum up 1+2+3+4/2 (remember center of lane 4) = 11.7.
> Considering that heading is almost PI/2 (1.556 rad ~ 90 degrees) then left side lanes, with positive indices, will start on negative X-axis, explaining the -11.7.
> So it seems correct - but confusing I must admit.
> 
> You can search for other lanes in the same file. E.g. lane, 0, 0, -2 starts on line 5865.
> 
> If you just want to look at OpenDRIVE files I recommend using odrviewer instead. But I understand that you wanted more to investigate in this case.

This tool would be very useful if it could increase the laneWidth and get the line lane points in the local coordinates. Expect it to be updated soon!Thanks！

**Comment by eknabevcc** [comment]
I'm glad that this old tool, odrplot, is found useful! I have now made a few quick improvements [(commit 842dce0)](https://github.com/esmini/esmini/commit/842dce08fba8b94a0a67362bba97f7b372d8d041):
 - plot lane boundary instead of lane center
 - plot non drivable lanes in gray
 - maximize axis to simplify panning and zooming

I hope these changes makes it more useful.

Regarding the YouTube example. It's simply the cut-in example. You should be able to run it:
1. go to esmini/run/esmini
1. make all scripts executable: `chmod +x *`
1. try for example: `./run_cut-in.bat`

A clarification: The visual model that you see is NOT generated by esmini, it's a pre-created 3D model (this one created in the commercial tool VIRES RoadDesigner).  It's is referred to in the .xosc file, under element <RoadNetwork>

**Comment by yumianhuli2** [comment]
> I'm glad that this old tool, odrplot, is found useful! I have now made a few quick improvements [(commit 842dce0)](https://github.com/esmini/esmini/commit/842dce08fba8b94a0a67362bba97f7b372d8d041):
> 
>     * plot lane boundary instead of lane center
> 
>     * plot non drivable lanes in gray
> 
>     * maximize axis to simplify panning and zooming
> 
> 
> I hope these changes makes it more useful.
> 
> Regarding the YouTube example. It's simply the cut-in example. You should be able to run it:
> 
>     1. go to esmini/run/esmini
> 
>     2. make all scripts executable: `chmod +x *`
> 
>     3. try for example: `./run_cut-in.bat`
> 
> 
> A clarification: The visual model that you see is NOT generated by esmini, it's a pre-created 3D model (this one created in the commercial tool VIRES RoadDesigner). It's is referred to in the .xosc file, under element `<RoadNetwork>`

Thank you very much for your work！I will try (commit 842dce0),and Compare it again with the odrViewer：）！

**Comment by eknabevcc** [comment]
Ok. hopefully something we can fix easily. 
But just so I understand, what's is wrong and what would the expected value be? Remember that now all lanes are included, so lane 7 is the outermost border area. And the values are in order: X, Y, Z, heading (radians).
