### ISSUE TITLE
Save generated model in headless mode?

### ISSUE THREAD

**Issue by TilmanBuente** [esmini/esmini#520]
Hi, thanks for providing and maintaining the valuable esmini environment.
Is there a way to run one of the applications "odrviewer" or "esmini" in headless mode w/o a scenegraph and w/o a window, nevertheless making it save the generated model? I'd like to call it non-interactively by a shell script in a container.

**Comment by eknabevcc** [comment]
It depends. If esmini was built as "slim" (see [here](https://esmini.github.io/#_slim_esmini_customize_configration)) without support for OpenSceneGraph (OSG), then it's not possible.

But in the default case, yes. Just specify any (invisible) window and it should work. For example:

`./bin/esmini --headless --window 60 60 800 400 --osc ./resources/xosc/lane_change_crest.xosc --save_generated_model`

By specifying a window, the viewer will be instantiated and model generated. 

BTW: Also the `--capture_screen` command will work in this mode. 
Example: 
`./bin/esmini --headless --window 60 60 800 400 --osc ./resources/xosc/lane_change_crest.xosc --save_generated_model --capture_screen`

**Comment by TillyIdol** [comment]
Thanks for your quick response! 

I found out that even if there is no visible window in headless mode the X display needs to be working. This has not been the case in the context of my container. Since proper configuration it works fine.

**Comment by TilmanBuente** [comment]
Thanks for your quick response!

I found out that even if there is no visible window in headless mode the X display needs to be working. This has not been the case in the context of my container. Since proper configuration it works fine.

**Comment by TilmanBuente** [comment]
Thanks for your quick response!

I found out that even if there is no visible window in headless mode the X display needs to be working. This has not been the case in the context of my container. Since proper configuration it works fine.
