### ISSUE TITLE
OSI wheel data only set for one wheel

### ISSUE THREAD

**Issue by ClemensLinnhoff** [esmini/esmini#527]
In the [OSIReporter](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Modules/ScenarioEngine/SourceFiles/OSIReporter.cpp#L867) a wheel data field is added and the wheel angle is set. However, this is set for only one wheel and it is not specified which one. [osi3::MovingObject::VehicleAttributes::wheel_data](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/gen/structosi3_1_1MovingObject_1_1VehicleAttributes.html#a27d7ffb7cfe89c54fc94532b4e6869cd) should be set for every individual wheel. The wheels are identified by the [axle](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/gen/structosi3_1_1MovingObject_1_1VehicleAttributes_1_1WheelData.html#a094de989f5a2aab080f9a65f0feb3867) and the [index](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/gen/structosi3_1_1MovingObject_1_1VehicleAttributes_1_1WheelData.html#a2095585cdc9eb8968fe576af7c43d5a3) parameters. 
The wheel angle is obtained from the [ObjectInfoStruct](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Modules/ScenarioEngine/SourceFiles/ScenarioGateway.hpp#L26) which does not contain the information about the number of axles and the number of wheels per axle.

What would be the easiest way to get the wheel information in there? Then the wheel_data in OSI could be correctly set. Also the wheel rotation might be set. Although it is unclear, whether [wheel_rot](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Modules/ScenarioEngine/SourceFiles/ScenarioGateway.hpp#L39) is the rotation speed or the rotation angle. Is a displacement of the wheels in the z-direction due to the suspension also simulated? Then this could also be added to the wheel data.

**Comment by eknabevcc** [comment]
True. We have friction (odr/lane_section/material) support high in backlog. For that one we'll implement separate wheel info anyway. Probably within two weeks.

So, individual wheel info will be implemented. Let us know if this is an immediate show-stopper, in which case we could potentially implement wheel info as a first separate step.

BTW: Thanks for additional info on OSI wheel/axle structure.

**Comment by ClemensLinnhoff** [comment]
Very cool that you have this on the agenda. No, it is not an immediate show-stopper. It is just something I noticed, so it can wait a couple of weeks.

**Comment by ClemensLinnhoff** [comment]
Thank you very much for the implementation @eknabevcc! I tested it with our simulation and the wheel rotation works.
From my side there is only one aspect of this issue still open: the wheel displacement in z-direction. Is this planned to be simulated by esmini? If not, we can close this issue, as it was just about including available wheel parameters in the  OSI output and not about enhancing the wheel simulation in general.

**Comment by eknabevcc** [comment]
Sounds good that rotation works. Both steering (heading) and revolution (pitch)?

Correct observation, the wheel z-displacement is not set. Currently it's not considered in esmini, not even API for setting it. But his would be quite easy to add when needed.

**Comment by ClemensLinnhoff** [comment]
Both steering and revolution are moving. Weather they are moving as intended, I am not fully sure. I attached a video, where the esmini OSI output is used to construct a 3D environment.

You can see the revolving wheels. Due to the aliasing (frame rate of 10 Hz) it is hard to say, if they are moving correctly.
You can also see the steering rotation during the lane change. There is a jerk (sudden movement) in the rotation when the lane change is initiated and another one, when it is completed. 

https://github.com/esmini/esmini/assets/27010086/c3c6c5f4-7099-437c-adbd-7f771e67ab54

**Comment by eknabevcc** [comment]
Great! Thanks for update. From the video I agree it can be concluded that least values are set correctly (e.g. pitch and yaw is not mixed up). Revolution and steering angle can be reported through API, in which case those values are applied. Otherwise they are approximately calculated, so far purpose has been to just illustrate motion for scenario preview. 

We have some planned work ahead that might, as a side effect, involve updating the calculation of wheel pitch and yaw angles.
