### ISSUE TITLE
Is there a key or any method to display driving direction in esmini?

### ISSUE THREAD

**Issue by pjk19942** [esmini/esmini#533]
I am currently using RelativeLanePosition to place few actors and in some scenes i have noticed that once i convert a standard xosc to a relativized version xosc (non ego actors are initialized wrt to ego) , in some cases the non ego vehicle's orientation changes. According to the documentation if heading isnt specified the car assumes the driving direction of the road. So why didnt my ego vehicle change orientation too? I want to check if my ego is facing the driving direction or the non ego actor, how do i check this? Is there a way to visuazie the driving direction from an xodr used in the xosc file?

**Comment by eknabevcc** [comment]
Ah, when revisiting some issues I now realize I missed one of your questions, whether you can visualize road direction.

The only way I see for now is the lines outlining the reference line and lanes of roads (press 'o' to enable/toggle). Road starting points are indicated by a yellowish point, endpoints by a red smaller point.

For example, below command will show a road network with two straight roads pointing head-to-head. Run from esmini root:

 ./bin/odrviewer --window 60 60 800 400 --odr ./EnvironmentSimulator/Unittest/xodr/straight_2x100m_opposite.xodr
 
![image](https://github.com/esmini/esmini/assets/29146839/6aeda2dc-98db-46cb-9c99-1e83425c81ae)

**Comment by pjk19942** [comment]
Thanks Emil! That really helps. The orientation issue was also arising with the direction of the road but this helps a lot. Thanks!
