### ISSUE TITLE
expose ObjectInfoStruct visibilityMask via esmini lib 

### ISSUE THREAD

**Issue by cipibad** [esmini/esmini#535]
Hello,

In order to glue esmini lib as scenario runner to a carla simulation based visualization I would need to expose ObjectInfoStruct visibilityMask via esmini lib.

I have bits of code prepared, not sure if it's enough (https://github.com/esmini/esmini/compare/master...cipibad:esmini:expose-visibilityMask-on-esmini-lib?expand=1), is it something that might be found useful and eventually merged?

Regards,
C

**Comment by eknabevcc** [comment]
Great, yes of course. We can do that. But to keep things in synch, it should also be added to: [esminiLib/ESMiniWrapper.cs](https://github.com/esmini/esmini/blob/dev/EnvironmentSimulator/Libraries/esminiLib/ESMiniWrapper.cs)

Please add there as well and you can create a pull request.

**Comment by eknabevcc** [comment]
Great. Thanks for contribution! PR merged. Feature included in [v2.37.0](https://github.com/esmini/esmini/releases/tag/v2.37.0). Closing issue.
