### ISSUE TITLE
Is it possible to simulate (and especially camera perspective) of a) Bike tipping over b) Vehicle losing control? 

### ISSUE THREAD

**Issue by pjk19942** [esmini/esmini#543]
Hi ,

Is there possible to simulate a bicycle / bike tipping over or falling to its side while travelling? Also, if a vehicle loses control (say because of low friction/ weather) , can such an effect be demonstrated? 

Thanks.
P

**Comment by eknabevcc** [comment]
esmini is basically a player for OpenSCENARIO files. Whatever is described will be executed. 

I guess not your initial idea, but if you can describe the drifting vehicle or falling bicker in terms of a trajectory (adding orientation to the control points) - it can be possible. 

Other than that there is, as of today, no physics engine involved that could handle such events as you describe.

Regarding camera, you can define custom camera locations. See [User guide - Camera control](https://esmini.github.io/#_camera_control).

Regarding friction, from v2.37.0 road friction is supported (see [User guide - Friction](https://esmini.github.io/#_friction)). But only for visualizing and report as part of ground-truth. To actually react to friction is, in typical use case, up to the external system under test. E.g. friction could be considered by a tire model part of a vehicle dynamics model in the vehicle under test. That way it could be tested how an automatic brake system performs with various road conditions.

**Comment by pjk19942** [comment]
Thanks, I can change the orientation of a vehicle and change its roll to a value to make it appear like its tipping over but only  when the vehicle is at rest. As soon as a speed is provided, the vehicle snaps back into the lane. From here on, providing futher lane positions with different orientations doesnt change the orientation or changes it for a small fraction of a second before the vehicle snaps back.


https://github.com/esmini/esmini/assets/125699572/cb251ba4-f99a-43df-a6ad-6b04f3f85b67

**Comment by eknabevcc** [comment]
We need more info to understand and reproduce the issue you encounter.

A quick test with attached simple scenario works fine, a bike tilting to the right after 4 seconds, and maintaining that roll angle as it moves forward.

[bike_tilt.zip](https://github.com/esmini/esmini/files/14646555/bike_tilt.zip)

![screen_shot_00000](https://github.com/esmini/esmini/assets/29146839/1e77e3be-df80-4cad-a57e-08a88f84bdc0)
![screen_shot_00001](https://github.com/esmini/esmini/assets/29146839/3c3a3272-1c40-4ff6-855c-f386aa5e7e57)

**Comment by pjk19942** [comment]
Hello,

Thank you for your reply! Interesting, I see you used the RelativeWorldPosition to teleport the actor to the particular orientation. I am attaching 4 examples.

For first Comparison (Orientation_1 and Orientation_2), the only change is that in Orientation_1 , I have '<Orientation r="0.5"/>', where as in Orientation_2 '<Orientation h="0.0" p="0.0" r="0.5"/>'. Notice that the first one runs without any issue but the second immediately snaps back to the road. 
Note : I am not using RelativeWorldPosition here.

For second Comparison (Orientation_3 and Orientation_4), I repeated the above experiment but with relative world position and noticed that ' <Orientation p="0.5"/>' (in Orientation_3) doesnt do anything but supplying it with '<Orientation p="0.5" r="0.0"/>' (in Orientation_4), i.e. another Euler angle works. 

Looking forward to your reply.

Thanks

[Orientation_Issue.zip](https://github.com/esmini/esmini/files/14651189/Orientation_Issue.zip)

**Comment by eknabevcc** [comment]
First 1 & 2: I don't see the snap-back. For me the tilt remains. Could it be we run different version? I run with esmini v2.37.3 (also tried with v2.37.2). What version do you run (find version in top of the log file/console window)? 

Then 3 & 4: You're right. I also found that issue with pitch and roll mixed-up, thanks to this issue! 👍 The bug has been fixed by commit 9ce1b2c38ff8d885ffa34ac5a38b0b2a6670c9ac. Included in release [v2.37.3](https://github.com/esmini/esmini/releases/tag/v2.37.3). 

So please try your 1 & 2, and modified versions of your 3 & 4 attached below with esmini v2.37.3. Hopefully it works for you as well.

[Orientation_Issue.zip](https://github.com/esmini/esmini/files/14654999/Orientation_Issue.zip)

**Comment by pjk19942** [comment]
I haven't had a chance to test it in latest release yet but would like to ask another query, can the orientation only be changed by a teleport action? Is there a way to specify a gradual orientation change say from r = 0 - pi/2, over say 5 seconds?

**Comment by eknabevcc** [comment]
Special case possible by fix in release [v2.37.5](https://github.com/esmini/esmini/releases/tag/v2.37.5)
See release notes for example and video clip

**Comment by pjk19942** [comment]
This is awesome! Thanks!
