### ISSUE TITLE
info_text too small

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#548]
Hi,

is there an option to make the info text larger? I can nothing read, zoom doesn't help here due to vector graphics.
![grafik](https://github.com/esmini/esmini/assets/78544110/cfa0a2f8-dc96-4f27-a55d-4eccce8607a2)

 --window 60 60 3840 2400 --info_text 3

BR,

Thaddaeus

P.S.: You see the high resolution and that on a small 16"laptop, so I have a high ppi

**Comment by eknabevcc** [comment]
I'm jealous of your screen size/resolution.
Unfortunately there is no way to scale the text. But I agree it would be a good feature. It's noted. Let's keep this issue open for a while.

**Comment by eknabevcc** [comment]
Fixed in release [v2.37.5](https://github.com/esmini/esmini/releases/tag/v2.37.5)
