### ISSUE TITLE
problem with rounding or with precision

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#549]
![grafik](https://github.com/esmini/esmini/assets/78544110/752211b4-1fea-409e-9878-49da8dad57df)

From mathematical point of view this statement from esmini is wrong.

`<SimulationTimeCondition value="8.836236855916514" rule="greaterOrEqual"/>`

So, the condition is true from file. The problem is simply related to the print format, which should have the same precision as the timestep

**Comment by eknabevcc** [comment]
Good find. Fixed on dev branch. Will be included in next release.

**Comment by eknabevcc** [comment]
Fixed in release [v2.37.5](https://github.com/esmini/esmini/releases/tag/v2.37.5)
