### ISSUE TITLE
docu about sensors and esmini-dyn very limited

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#553]
Could you polease add some content to:

docs/user_guide.adoc

First I would wish to have some content of current sensor implementation, what are the lines I see in esmini-dyn examples. How many sensors are there and so on, at least wanted to find more results in search for "sensor" and not just one result. Unclear where the sensors were defined, since I just see the xosc in bat file referenced.

Second, I find no result searching for esmini-dyn. Would be great to find an explanation what exactly is the difference between esmini and esmini-dyn?

BR,

tmIdiada

**Comment by eknabevcc** [comment]
Top of main esmini page https://github.com/esmini/esmini, it says:

esmini: A scenario player application linking esmini modules statically.
esmini-dyn: A minimalistic example using the esminiLib to play OpenSCENARIO files.

esmini-dyn is simply a code example showcasing some of the esminiLib API. You find it here:
https://github.com/esmini/esmini/blob/dev/EnvironmentSimulator/Applications/esmini-dyn

The sensors are simply something you add from the user code, see the esmini-dyn code example. API [here](https://github.com/esmini/esmini/blob/dev/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L1082-L1095).

As can be seen in the esmini-dyn example, the sensors are very basic. Only checking for reference point inside frustum or not.

For sensor model related use cases where more precision is needed, OSI can/should be used.

**Comment by tmIdiada** [comment]
Hi,

thanks a lot for the explanation. Just one question remains, what is rangeNear vs rangeFar? RangeFar means until this distance from sensor to bbox reference point the object is detected and rangeNear that below this range the sensor can't see anything?

BR,

tmIdiada

**Comment by eknabevcc** [comment]
You're perfectly correct. The range represents those constraints, within what distance range the sensor can "see". The check is basically: 
if (rangeNear < dist < rangeFar) -> a hit
where dist = linear/Euclidean distance between object's reference points

We have no public examples of the sensor model integrations, which is outside esmini. I'm don't have full insight in the OSMP module, but it's a way to integrate esmini in a FMI co-simulation environment. But the [openmcx](https://github.com/eclipse/openmcx) project might be a good starting place for more info.

Also, as a starter, you could look into the [osi-groundtruth.cpp](https://github.com/esmini/esmini/blob/dev/EnvironmentSimulator/code-examples/osi-groundtruth/osi-groundtruth.cpp) code example. It fetches some OSI groundthruth, and picks some content from it. 

A sensor model would, I guess, check bounding boxes from ground-truth against its own view frustum, potentially applying occlusion culling from other stationary and moving objects. But this is outside my zone. 

There is a sensor view defined in OSI, but esmini is only populating global ground-truth. The ideal sensors is not connected in any way with the OSI output.

**Comment by eknabevcc** [comment]
Added with release [v2.37.5](https://github.com/esmini/esmini/releases/tag/v2.37.5)
