### ISSUE TITLE
scale graphics to bounding box sizes maybe scales the height not right or the placement of vehicles in z is wrong

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#561]
Hi,

if I scale bounding boxes, the vehicles seems not to be placed right on the road, maybe the height with wheel sizes is not sclaed to bounding box right?

![grafik](https://github.com/esmini/esmini/assets/78544110/0194f6ba-1b3b-456b-9b42-52a2c47e4118)

BR

**Comment by eknabevcc** [comment]
True. The scaling is applied from reference point (defined [here](https://github.com/esmini/esmini/blob/949b84c0852347c436f831174594b68957dbc597/resources/xosc/Catalogs/Vehicles/VehicleCatalog.xosc#L24)).

So, if Z coordinate of the reference points is not at bottom of bounding box, and Z scaling is applied, it will grow or shrink the vehicle upward and downward with respect to the reference point. 
If the reference point is defined at bottom level of the bounding box, it should result in only upward scaling. 

Regarding the wheels of the simple 3D models. Yes they are unfortunately bundled with the rest of the vehicle in terms of this scaling. So, maybe the easiest solution is to try ignore the graphic flaw. 

Potentially we'll make a better separation of the wheel models, but it has not been prioritized yet.

**Comment by tmIdiada** [comment]
thanks for the explanation
