### ISSUE TITLE
Segmentation fault in odrviewer with no drivable lanes

### ISSUE THREAD

**Issue by wk39** [esmini/esmini#562]
Hello,

First of all, thank you for the great project and management!

When opening an xodr file with ODRViewer, if any road within the xodr without drivable lanes, a segmentation fault occurs.
Running with "--density 0" does not produce an error, which suggests there might be an issue during the vehicle spawning process. The viewer fails to run if there is even one road consisting only of bicycle lanes, pedestrian paths, or borders.

This is the test file for segmentation fault. (modified from straight_500m.xodr in the resource folder)
```
<?xml version="1.0" standalone="yes"?>
<OpenDRIVE>
    <header revMajor="1" revMinor="4" name="" version="1.00" date="Tue Jun 30 14:55:47 2020" north="0.0e+00" south="0.0e+00" east="0.0e+00" west="0.0e+00">
        <geoReference> <![CDATA[+proj=utm +lat_0=37.35429341239328 +lon_0=-122.0859797650754 +k_0=1 +x_0=0 +y_0=0 +datum=WGS84 +geoidgrids=egm96_15.gtx +vunits=m +zone=32 +ellps=GRS80 +units=m +no_defs]]>
        </geoReference>
    </header>
    <road name="" length="5.0e+02" id="1" junction="-1">
        <planView>
            <geometry s="0.0+00" x="0.0+00" y="0.0+00" hdg="0.0+00" length="5.0e+02">
                <line/>
            </geometry>
        </planView>
        <lanes>
            <laneSection s="0.0e+00">
                <left>
                    <lane id="1" type="border" level= "false">
                        <width sOffset="0.0e+00" a="4.0+00" b="0.0e+00" c="0.0e+00" d="0.0e+00"/>
                    </lane>
                </left>
                <center>
                  <lane id="0" type="none" level= "false" />
                </center>
                <right>
                    <lane id="-1" type="biking" level= "false">
                        <width sOffset="0.0e+00" a="4.0e+00" b="0.0e+00" c="0.0e+00" d="0.0e+00"/>
                    </lane>
                </right>
            </laneSection>
        </lanes>
    </road>
</OpenDRIVE>
```

Thank you.

**Comment by eknabevcc** [comment]
You definitely found a bug. Thanks a lot for reporting it.

Should be fixed on dev branch by commit b026393820602189cf4da4d98084cd7ef55b2a43. Will be included in next release.

**Comment by eknabevcc** [comment]
Included in release [v2.37.9](https://github.com/esmini/esmini/releases/tag/v2.37.9)

**Comment by wk39** [comment]
You are really fast. 
I will test with a few files early next week and close the issue.
Thank you for your quick response.

**Comment by wk39** [comment]
After testing several cases, it has been confirmed that all issues have been resolved! Thank you.
