### ISSUE TITLE
odrviewer crashes if LHT road contains no right lanes

### ISSUE THREAD

**Issue by FelixBorgelt** [esmini/esmini#563]
The odrviewer crashes as soon as a car reaches the end of a LHT road that contains no right lanes.
To reproduce the error, delete all right lanes in the e6mini-lht.xodr example.

**Comment by eknabevcc** [comment]
Great find! Thanks for reporting it with easy reproduction.

Fix included in release [v2.37.9](https://github.com/esmini/esmini/releases/tag/v2.37.9)
