### ISSUE TITLE
relative speed is always positive in TTC condition 

### ISSUE THREAD

**Issue by wubinwab** [esmini/esmini#569]
![image](https://github.com/esmini/esmini/assets/161703216/41609568-74e1-478b-a86a-58cf99fd9300)
Hi, as shown in the image, the relative speed in TTC condition is always greater than or equal to 0, which may cause a issue like: the folllow car's speed is slower than the leader car's, but we got a critical TTC which may  false trigger  AEB in the simulation. Please check it's by design or just an issue

**Comment by eknabevcc** [comment]
Thanks for report! It looks like a bug. Can you share a simple scenario for reproducing the issue and showing how you setup the condition.

**Comment by wubinwab** [comment]
The scenario is shown as below. We expect that when the speed of the following vehicle is higher than that of the leading vehicle, the following vehicle should change lanes. Here we use TTC (Time-to-Collision) to judge it, but because relative speed is a non-negative number, it also triggers lane changing when the speed of the following vehicle is lower than that of the leading vehicle, which is not the result we expect to see.

<OpenSCENARIO xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="OpenScenario.xsd">
    <FileHeader author="author" date="2024-05-14T11:07:41.987543" description="scenario_description" revMajor="1" revMinor="2"/>
    <ParameterDeclarations>
        <ParameterDeclaration name="ego_lateral_state" parameterType="int" value="0"/>
        <ParameterDeclaration name="ego_urgency_level" parameterType="int" value="0"/>
    </ParameterDeclarations>
    <CatalogLocations>
        <VehicleCatalog>
            <Directory path="../xosc/Catalogs/Vehicles"/>
        </VehicleCatalog>
    </CatalogLocations>
    <RoadNetwork>
        <LogicFile filepath="/home/binwu/ws/third_party/esmini/test/OSC-ALKS-scenarios/Scenarios/ALKS_Road_straight.xodr"/>
    </RoadNetwork>
    <Entities>
        <ScenarioObject name="ego">
            <CatalogReference catalogName="VehicleCatalog" entryName="semi_truck"/>
        </ScenarioObject>
        <ScenarioObject name="new_actor_1">
            <CatalogReference catalogName="VehicleCatalog" entryName="car_red"/>
        </ScenarioObject>
    </Entities>
    <Storyboard>
        <Init>
            <Actions>
                <Private entityRef="ego">
                    <PrivateAction>
                        <TeleportAction>
                            <Position>
                                <LanePosition laneId="-4" offset="-0.047062546079757794" roadId="0" s="5029.243777717605"/>
                            </Position>
                        </TeleportAction>
                    </PrivateAction>
                    <PrivateAction>
                        <LongitudinalAction>
                            <SpeedAction>
                                <SpeedActionDynamics dynamicsDimension="time" dynamicsShape="step" value="0.0"/>
                                <SpeedActionTarget>
                                    <AbsoluteTargetSpeed value="19.444444444444443"/>
                                </SpeedActionTarget>
                            </SpeedAction>
                        </LongitudinalAction>
                    </PrivateAction>
                </Private>
                <Private entityRef="new_actor_1">
                    <PrivateAction>
                        <TeleportAction>
                            <Position>
                                <LanePosition laneId="-4" offset="-0.04356106615181332" roadId="0" s="5055.183582452167"/>
                            </Position>
                        </TeleportAction>
                    </PrivateAction>
                    <PrivateAction>
                        <LongitudinalAction>
                            <SpeedAction>
                                <SpeedActionDynamics dynamicsDimension="time" dynamicsShape="step" value="0.0"/>
                                <SpeedActionTarget>
                                    <AbsoluteTargetSpeed value="22.22222222222222"/>
                                </SpeedActionTarget>
                            </SpeedAction>
                        </LongitudinalAction>
                    </PrivateAction>
                </Private>
            </Actions>
        </Init>
        <Story name="story1">
            <Act name="act9">
                <ManeuverGroup maximumExecutionCount="1" name="maneuver_group7">
                    <Actors selectTriggeringEntities="false">
                        <EntityRef entityRef="ego"/>
                    </Actors>
                    <Maneuver name="maneuver6">
                        <Event maximumExecutionCount="1" name="event4" priority="parallel">
                            <Action name="action5_lane_change">
                                <PrivateAction>
                                    <LateralAction>
                                        <LaneChangeAction>
                                            <LaneChangeActionDynamics dynamicsDimension="time" dynamicsShape="sinusoidal" value="3.0"/>
                                            <LaneChangeTarget>
                                                <RelativeTargetLane entityRef="ego" value="1"/>
                                            </LaneChangeTarget>
                                        </LaneChangeAction>
                                    </LateralAction>
                                </PrivateAction>
                            </Action>
                            <StartTrigger>
                                <ConditionGroup>
                                    <Condition conditionEdge="none" delay="2.0" name="trigger2_ttc">
                                        <ByEntityCondition>
                                            <TriggeringEntities triggeringEntitiesRule="any">
                                                <EntityRef entityRef="ego"/>
                                            </TriggeringEntities>
                                            <EntityCondition>
                                                <TimeToCollisionCondition coordinateSystem="road" freespace="true" relativeDistanceType="longitudinal" rule="lessThan" value="10.0">
                                                    <TimeToCollisionConditionTarget>
                                                        <EntityRef entityRef="new_actor_1"/>
                                                    </TimeToCollisionConditionTarget>
                                                </TimeToCollisionCondition>
                                            </EntityCondition>
                                        </ByEntityCondition>
                                    </Condition>
                                </ConditionGroup>
                            </StartTrigger>
                        </Event>
                    </Maneuver>
                </ManeuverGroup>
                <StartTrigger>
                    <ConditionGroup>
                        <Condition conditionEdge="rising" delay="0.0" name="start_trigger8">
                            <ByValueCondition>
                                <SimulationTimeCondition rule="greaterThan" value="0.0"/>
                            </ByValueCondition>
                        </Condition>
                    </ConditionGroup>
                </StartTrigger>
                <StopTrigger/>
            </Act>
        </Story>
        <StopTrigger>
            <ConditionGroup>
                <Condition conditionEdge="rising" delay="0.0" name="stop_simulation">
                    <ByValueCondition>
                        <SimulationTimeCondition rule="greaterThan" value="60.0"/>
                    </ByValueCondition>
                </Condition>
            </ConditionGroup>
        </StopTrigger>
    </Storyboard>
    <VariableDeclarations/>
</OpenSCENARIO>

**Comment by eknabevcc** [comment]
Thanks for sharing the scenario, it clearly highlights the issue.

 We have updated calculations in release [v2.37.11](https://github.com/esmini/esmini/releases/tag/v2.37.11).

Please try and let us know how it works.

**Comment by wubinwab** [comment]
Thanks for the fix, I have tested it and it's work.
The issue can be closed.
