### ISSUE TITLE
Is there support for left-hand traffic on esmini?

### ISSUE THREAD

**Issue by aqvia** [esmini/esmini#57]
In my scenario, in order to specify the direction of the vehicles running on the road as intended, I specified the `rule` attribute of `road` element in the OpenDrive file as follows, but there was no change.

```xml
<road name="..." length="2.0000000000000000e+03" id="1" junction="-1" rule="LHT">...
```

**Comment by eknabevcc** [comment]
The road rule attribute (introduced in OpenDRIVE 1.5) is not supported in esmini yet. 
However it is possible to run left-hand traffic in esmini. The trick is to set Orientation relative heading = PI (3.14). 
See [https://github.com/esmini/esmini/blob/master/resources/xosc/left-hand-traffic_internal.xosc](https://github.com/esmini/esmini/blob/master/resources/xosc/left-hand-traffic_internal.xosc) for an example
I hope this is OK short term solution. But of course, the rule attribute is a very good addition to OpenDRIVE and of course esmini should support it. I've put in the backlog - but I don't dare to promise a release date.

**Comment by aqvia** [comment]
@eknabevcc 
Thanks for your reply. I'll consider how to deal with it referring to this. Probably I'll take the way to set Orientation element.

**Comment by bleach31** [comment]
Has this issue been solved by 21c7d76d9cc14684111f1bc7f87d0c7b1d575694 ?

**Comment by eknabevcc** [comment]
Yes, thanks @bleach31 for reminding me. 
It should be noted in this thread that from release [2.9.0](https://github.com/esmini/esmini/blob/master/release_notes.md#2021-06-04-version-290) OpenDRIVE road rule (specifying right or left hand traffic) is supported. 
So, vehicles should be aligned accordingly (as long as absolute heading is not specified).

**Comment by eknabevcc** [comment]
Requested feature added. Closing issue.
