### ISSUE TITLE
How to check if one vehicle is out of road?

### ISSUE THREAD

**Issue by GilgameshD** [esmini/esmini#571]
Hi, 

I am studying the API functions in esminilib and I wonder if it is possible to check if one vehicle (with object id) is out of the road? It would be better if there is a python version of such a function. Thanks.

**Comment by eknabevcc** [comment]
There is currently not a direct way to find out, other than checking lane id and offset as part of [SE_ScenarioObjectState](https://github.com/esmini/esmini/blob/b8a64a5602e4f514cb87bbb5fcaa081270c94f75/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L23C1-L53C26). Which can be retrieved with `SE_GetObjectState()` function.

I can see usefulness of a function like `GetObjectOffRoad()`. How would you define our of the road? Outside any driving lane, or outside road altogether. As first or second image below?

![off_lane](https://github.com/esmini/esmini/assets/29146839/8ba086fd-0e30-4a7c-ae69-dbce87cd94e3)

![off_road](https://github.com/esmini/esmini/assets/29146839/a3c9071b-2791-4efa-a85f-c62ebced80e9)

**Comment by GilgameshD** [comment]
Thanks for your response! I think out of the driving lane is more reasonable.

**Comment by eknabevcc** [comment]
Yes, I agree. But when thinking more about it I realize there might be various needs. So the most generic solution I think is to simply ask for the actual lane type (disregarding lane snapping settings). Then the user/programmer can check against various masks for different needs. For example, is the lane a drivable one? Is it on road? Is it at all within defined lanes or outside?

A function for this has been added: [`SE_GetObjectInLaneType()`](https://github.com/esmini/esmini/blob/90fe97b2c6c0c7354490172f1d1f8261321ff1e4/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L974C1-L984C58). On dev branch.

See use example in example Python script [drive.py](https://github.com/esmini/esmini/blob/dev/EnvironmentSimulator/code-examples/hello_world/drive.py). It has been extended with checking the type of lane the car is currently in.

Will be included in next release.
