### ISSUE TITLE
How to fetch image using python API

### ISSUE THREAD

**Issue by GilgameshD** [esmini/esmini#572]
Hi,

I am trying to convert the example of image capture to python. I use the following code to fetch image but it seems the return value is -1:
```python
import ctypes as ct
import os
import sys


class SE_Image(ct.Structure):
    _fields_ = [
        ("width", ct.c_int),
        ("height", ct.c_int),
        ("pixelSize", ct.c_int),
        ("pixelFormat", ct.c_int),
        ("data", ct.POINTER(ct.c_ubyte)),
    ]


xosc_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "resources/xosc/cut-in.xosc")
lib_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "esmini")
lib_paths = {
    "linux": os.path.join(lib_path, "bin/libesminiLib.so"),
    "linux2": os.path.join(lib_path, "bin/libesminiLib.so"),
    "darwin": os.path.join(lib_path, "bin/libesminiLib.dylib"),
    "win32": os.path.join(lib_path, "esminiLib.dll"),
}
se = ct.CDLL(lib_paths[sys.platform])

se.SE_FetchImage.argtypes = [ct.c_void_p]
se.SE_StepDT.argtypes = [ct.c_float]
se.SE_LogToConsole.argtypes = [ct.c_bool]
se.SE_SetWindowPosAndSize.argtypes = [ct.c_int, ct.c_int, ct.c_int, ct.c_int]
img = SE_Image()

disable_ctrls = 0
threads = 0
use_viewer = 2
record = 0
se.SE_LogToConsole(False)
se.SE_SetWindowPosAndSize(60, 60, 1000, 400)
se.SE_Init(xosc_path.encode(), disable_ctrls, use_viewer, threads, record)

flag = se.SE_FetchImage(ct.byref(img))
print(flag)
```

Are there any misunderstandings of the functions in esminilib?

**Comment by eknabevcc** [comment]
I think the issue is in the viewer argument bitmask. 

For viewer you need bit 1 set. For offscreen (no window on display) bit 2 should be set. So 1 + 2 = 3 will instantiate viewer in display-less mode, which I think is what you want. See [here](https://github.com/esmini/esmini/blob/b8a64a5602e4f514cb87bbb5fcaa081270c94f75/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L422) for brief explanation. 

I modified your code slightly to have it run from folder above esmini, see below. It outputs '0'.

I also recommend to either check `SE_Init()` return value (as in my modified code), or enable console output - to see any errors.

```Python
import ctypes as ct
import os
import sys


class SE_Image(ct.Structure):
    _fields_ = [
        ("width", ct.c_int),
        ("height", ct.c_int),
        ("pixelSize", ct.c_int),
        ("pixelFormat", ct.c_int),
        ("data", ct.POINTER(ct.c_ubyte)),
    ]


xosc_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "esmini/resources/xosc/cut-in.xosc")
lib_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "esmini")
lib_paths = {
    "linux": os.path.join(lib_path, "bin/libesminiLib.so"),
    "linux2": os.path.join(lib_path, "bin/libesminiLib.so"),
    "darwin": os.path.join(lib_path, "bin/libesminiLib.dylib"),
    "win32": os.path.join(lib_path, "bin/esminiLib.dll"),
}
se = ct.CDLL(lib_paths[sys.platform])

se.SE_FetchImage.argtypes = [ct.c_void_p]
se.SE_StepDT.argtypes = [ct.c_float]
se.SE_LogToConsole.argtypes = [ct.c_bool]
se.SE_SetWindowPosAndSize.argtypes = [ct.c_int, ct.c_int, ct.c_int, ct.c_int]
img = SE_Image()

disable_ctrls = 0
threads = 0
use_viewer = 3
record = 0
se.SE_LogToConsole(False)
se.SE_SetWindowPosAndSize(60, 60, 1000, 400)
se.SE_SaveImagesToRAM(True)
if se.SE_Init(xosc_path.encode(), disable_ctrls, use_viewer, threads, record) != 0:
    print('Failed init esmini')
    exit -1

flag = se.SE_FetchImage(ct.byref(img))
print(flag)
```

**Comment by GilgameshD** [comment]
Thanks! It works after I change use_viewer to 3. A follow-up question is about the image data. How can I convert the fetched data to an array with shape [H, W, 3]?

**Comment by GilgameshD** [comment]
An update on this thread. I find the way to convert the pointer to an numy array but it seems that the use_viewer flag influences the results. My current code looks like this:

```python
import ctypes as ct
import os
import sys
import numpy as np
import cv2


class SE_Image(ct.Structure):
    _fields_ = [
        ("width", ct.c_int),
        ("height", ct.c_int),
        ("pixelSize", ct.c_int),
        ("pixelFormat", ct.c_int), 
        ("data", ct.POINTER(ct.c_ubyte)),
    ]


xosc_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "esmini/resources/xosc/cut-in.xosc")
lib_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "esmini")

lib_paths = {
    "linux": os.path.join(lib_path, "bin/libesminiLib.so"),
    "linux2": os.path.join(lib_path, "bin/libesminiLib.so"),
    "darwin": os.path.join(lib_path, "bin/libesminiLib.dylib"),
    "win32": os.path.join(lib_path, "esminiLib.dll"),
}
se = ct.CDLL(lib_paths[sys.platform])

se.SE_FetchImage.argtypes = [ct.c_void_p]
se.SE_FetchImage.restype = ct.c_int
se.SE_StepDT.argtypes = [ct.c_float]
se.SE_LogToConsole.argtypes = [ct.c_bool]
se.SE_SetWindowPosAndSize.argtypes = [ct.c_int, ct.c_int, ct.c_int, ct.c_int]
se.SE_SaveImagesToRAM.argtypes = [ct.c_bool]

img = SE_Image()

disable_ctrls = 0
threads = 0
use_viewer = 1
record = 0

se.SE_LogToConsole(False)
se.SE_SetWindowPosAndSize(60, 60, 1000, 400)
se.SE_SaveImagesToRAM(True)

se.SE_Init(xosc_path.encode(), disable_ctrls, use_viewer, threads, record)

for i in range(10):
    flag = se.SE_FetchImage(ct.byref(img))
    se.SE_StepDT(0.1)

    total_bytes = img.pixelSize * img.width * img.height
    img_data = np.ctypeslib.as_array(img.data, shape=(total_bytes,))
    img_array = img_data.reshape((img.height, img.width, img.pixelSize, ))

    img_array = np.flip(img_array, 0) # flip y axis
    img_array = cv2.cvtColor(img_array, cv2.COLOR_BGR2RGB) # change BGR to RGB
    cv2.imwrite("output.png", img_array)
```

It gave me the image I want like this:
![output1](https://github.com/esmini/esmini/assets/13979878/5697c856-8975-4431-a20c-d6b6d99b09aa)

But when I change use_viewer to 3, I got this:
![output](https://github.com/esmini/esmini/assets/13979878/075540ac-74a1-4701-9b7d-342c8fdfe4c1)

**Comment by eknabevcc** [comment]
Nice solution and using cv to handle image!

I get a valid image with use_viewer = 3, although I had to comment out line below to get correct colors.
```Python
# img_array = cv2.cvtColor(img_array, cv2.COLOR_BGR2RGB) # change BGR to RGB
```

Saving as jpg, I get this image:
![output](https://github.com/esmini/esmini/assets/29146839/27e4bc16-7ba0-4ba5-a0fa-047edbcee418)

Unfortunately the image is not anti-aliased. What happens is, I think, off-screen rendering is using Mesa lib instead of GPU, applying simpler rendering pipeline. This is good for Linux systems lacking GPU. But I'm not sure how to make use of any existing GPU for offscreen rendering. 

It would be interesting to find out why you get a black image. Can you check graphics system with command glxinfo -B. See output on my virtual Ubuntu below. See [User guide - Software rendering (no gfx hw)](https://esmini.github.io/#_software_rendering_no_gfx_hw) for some brief info.

```
esmini@esmini-VirtualBox:~/tmp$ glxinfo -B
name of display: :1
display: :1  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Mesa/X.org (0xffffffff)
    Device: llvmpipe (LLVM 12.0.0, 128 bits) (0xffffffff)
    Version: 21.2.6
    Accelerated: no
    Video memory: 7938MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 12.0.0, 128 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 21.2.6
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.1 Mesa 21.2.6
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by GilgameshD** [comment]
The problem might be about the GPU. I am using an Apple M3 chip so the info about my graphical system is like this:
```
Chipset Model: Apple M3 Pro
      Type: GPU
      Bus: Built-In
      Total Number of Cores: 14
      Vendor: Apple (0x106b)
      Metal Support: Metal 3
```
I will try the code on a Ubuntu system and update my find out.

**Comment by eknabevcc** [comment]
First, regarding mac: I'll might be able to try on Mac myself in a few days. 

Then regarding ssh: Did you try this (from the User guide, see link above):
`Xvfb :99 -screen 0 1920x1080x24+32 & export DISPLAY=:99`

With that it should be possible to run on display-less Linux. But there might be pitfalls I'm not aware of.

**Comment by GilgameshD** [comment]
Thanks. This `Xvfb ` command works. I think all of my requirements are satisfied now. One small problem is that there is always a message printed out `saveImagesToFile_ = 0` during the fetch of the image. I cannot find where it is in the source code.

**Comment by eknabevcc** [comment]
That's a true mystery. Can you check the esmini version, and paste it here?

Change: 
```se.SE_LogToConsole(False)```
into:
```se.SE_LogToConsole(True)```

And run again. Copy the four topmost rows, like:
```
esmini GIT REV: v2.37.10-0-59851732
esmini GIT TAG: v2.37.10
esmini GIT BRANCH: tags/v2.37.10^0
esmini BUILD VERSION: N/A - client build
```

I'd like to solve the mystery. But a quick fix might be to run like:
```python3 img.py &> /dev/null```

That should skip all output intended for stdout and stderr.

**Comment by GilgameshD** [comment]
The first four lines of the log are:
```
esmini GIT REV: v2.37.11-0-b8a64a56-dirty
esmini GIT TAG: v2.37.11
esmini GIT BRANCH: tags/v2.37.11^0
esmini BUILD VERSION: N/A - client build
```

**Comment by eknabevcc** [comment]
Ah, I see. Thanks for solving the mystery!
