### ISSUE TITLE
IsSuccessor and IsPredecessor Api 

### ISSUE THREAD

**Issue by neo896** [esmini/esmini#573]
Hi,
I want to know how to use RoadManager Api to call  IsSuccessor and IsPredecessor ,  i want to use python to call the lib, but  it seems they were not exposed?

**Comment by eknabevcc** [comment]
That's correct. Currently they are not exposed in neither esmini.lib nor esminiRM.lib. 

The internal IsSuccessor/Predeceessor are methods of Position class. They will take a road reference and check whether there is a path connecting that road as a successor/predecessor to the road of current position. 

I guess it would be possible to expose this method, slightly changing so that argument is a roadId instead of road reference. Potentially the argument could be an object (in case of esmini) or position handle (for esminiRM). But roadId seems more generic and can work for both libs.

What lib are you using?

Would you like to draft an implementation (to speed up), or wait for us to do it (probably slower)? Hopefully it's a fairly straight forward implementation, using the internal existing methods to do the dirty work.

**Comment by neo896** [comment]
> That's correct. Currently they are not exposed in neither esmini.lib nor esminiRM.lib.没错。目前，它们既没有在 esmini.lib 中公开，也没有在 esminiRM.lib 中公开。
> 
> The internal IsSuccessor/Predeceessor are methods of Position class. They will take a road reference and check whether there is a path connecting that road as a successor/predecessor to the road of current position.内部 IsSuccessor/Predeceessor 是 Position 类的方法。他们将参考道路，并检查是否有一条连接该道路的路径，作为当前位置道路的继任者/前任。
> 
> I guess it would be possible to expose this method, slightly changing so that argument is a roadId instead of road reference. Potentially the argument could be an object (in case of esmini) or position handle (for esminiRM). But roadId seems more generic and can work for both libs.我想可以公开此方法，稍作更改，以便参数是 roadId 而不是 road reference。参数可能是对象（如果是 esmini）或位置句柄（对于 esminiRM）。但是 roadId 似乎更通用，可以同时适用于这两个库。
> 
> What lib are you using?你用的是什么库？
> 
> Would you like to draft an implementation (to speed up), or wait for us to do it (probably slower)? Hopefully it's a fairly straight forward implementation, using the internal existing methods to do the dirty work.您是想起草一个实现（以加快速度），还是等待我们完成（可能更慢）？希望这是一个相当直接的实现，使用内部现有方法来完成肮脏的工作。

I have a possibly strange need:
There is a target vehicle in front of an ego vehicle, and I want to determine if the target object is in the same lane as ego based on world coordinates.
Normally this is obvious if the ego and the target vehicle are under the same roadID and laneID. But if a straight line road is very long, it may be segmented when drawing the opendrive, at this time, the ego vehicle and the target vehicle may not be in the same roadID, but theoretically they can also determine whether they are in the same lane if I can know the road link relationship.
So that's why I need this API, by the way I'm using libesminiRMLib.so in python, I'm not very familiar with c++.
Also correct me if my idea is wrong or doesn't make much sense

**Comment by neo896** [comment]
> Maybe you can make use of the [`RM_SubtractAFromB()`](https://github.com/esmini/esmini/blob/dev/EnvironmentSimulator/Libraries/esminiRMLib/esminiRMLib.hpp#L466C1-L473C91) function. 
> 
> It's a bit tricky, but the idea is to measure the difference between position B and position A. Distance will be positive if B is in front of A (based on driving direction at A), else negative. You also get any delta in lane IDs. 
> 
> You can see how to use in this new test case: [`SubtractPositionsHW()`](https://github.com/esmini/esmini/blob/dev/EnvironmentSimulator/Unittest/RoadManagerDll_test.cpp#L170C1-L246C1)
> 
> In the [`RM_PositionDiff`](https://github.com/esmini/esmini/blob/dev/EnvironmentSimulator/Libraries/esminiRMLib/esminiRMLib.hpp#L68C1-L73C19) struct the `ds` field holds the the signed longitudinal distance, `dt` the lateral distance and `dLaneId` the delta of lane IDs.
> 
> You'd have to define this struct on the Python side before using the mentioned function. Let us know if you succeed or need some further assistance.

It works, thanks!

**Comment by eknabevcc** [comment]
Closing issue
