### ISSUE TITLE
Get listed on the FMI Tools page

### ISSUE THREAD

**Issue by chrbertsch** [esmini/esmini#578]
I would like to encourage you get listed on the FMI tools page https://fmi-standard.org/tools/, see https://github.com/modelica/fmi-standard.org/blob/main/CONTRIBUTING.md#updating-the-tools-list.

**Comment by eknabevcc** [comment]
We would have nothing against it. But to be honest I have not much clue about FMI, so I don't even know the answer to some of the form fields, e.g. fmiVersions, fmuExport... 

Maybe someone could assist. This is as far as I get:

```
{
    "name": "esmini",
    "license": "osi",
    "url": "https://github.com/esmini/esmini",
    "logo": "https://avatars.githubusercontent.com/u/49203938?v=4",
    "vendor": "esmini team",
    "vendorURL": "https://github.com/esmini",
    "description": "Basic OpenSCENARIO player",
    "features": [],
    "platforms": [
        "Linux",
        "Windows",
        "macOS"
    ],
    "interfaces": [
        "GUI",
        "CLI"
    ],
    "fmiVersions": [
        ?
    ],
    "fmuExport": [
        ?
    ],
    "fmuImport": [
        ?
    ]
}
```

@ClemensLinnhoff, maybe you can provide answers (just replay in this thread) to:

- fmiVersions:
- fmuExport:
- fmuImport:

then I can arrange the pull request.

**Comment by chrbertsch** [comment]
To my understanding the entry for esmini in the tools.json should be as follows: 


```
{
    "name": "esmini",
    "license": "osi",
    "url": "https://github.com/esmini/esmini",
    "logo": "esmini.png",
    "vendor": "esmini team",
    "vendorURL": "https://github.com/esmini",
    "description": "Basic OpenSCENARIO player",
    "features": [],
    "platforms": [
        "Linux",
        "Windows",
        "macOS"
    ],
    "interfaces": [
        "CLI"
    ],
    "fmiVersions": [
         "2.0"
    ],
    "fmuExport": [
         "CS"
    ],
    "fmuImport": [ ]
}
```

where you would upload your logo https://avatars.githubusercontent.com/u/49203938?v=4 as "esmini.png" to https://github.com/modelica/fmi-standard.org/tree/main/static/assets/images/esmini.png in your Pull Request

It would be great if you could also provide the optional "examplesURL" with with information on how you tested your generated esmini FMUs and examples, see the tools with the "golden star" and the "examples and compatibility" link listed top on https://fmi-standard.org/tools/.

Thanks!

**Comment by eknabevcc** [comment]
Unfortunately I (or anyone in core esmini team) can't provide any information on how to use esmini with FMU. So we'd rely on someone to provide such info. To avoid wrong info being added, my proposal is to wait with the pull request. We can keep this issue open and see if someone can provide the info asked for.  (I'm not sure about the maturity level of using esmini in the context of FMU, that's why I'm a bit careful here)

**Comment by ClemensLinnhoff** [comment]
The fmiVersion is 2.0 as @chrbertsch stated. I don't know about fmuExport and fmuImport. I never needed to state these parameters and could not find anything in the FMI specification.

As for the platforms: I have only tested the esmini FMU with Linux. I cannot guarantee, that it will work out-of-the-box for Windows or macOS.

For Linux however it works very well. Examples demonstrating this can be found on [OpenMSL](https://github.com/openMSL) in the test pipelines of the individual models, e.g. [here](https://github.com/openMSL/sl-1-0-sensor-model-repository-template/actions/runs/8554572907/job/23440542878) for a sensor model and [here](https://github.com/openMSL/sl-2-0-traffic-participant-model-repository-template/actions/runs/9497779359/job/26175436827) for a traffic participant model.

**Comment by ClemensLinnhoff** [comment]
Should we add OSI as an interface?

**Comment by eknabevcc** [comment]
Ok, thanks for all info. @chrbertsch: What about the "Interfaces", what does GUI mean here (which I see you omitted for esmini)?

**Comment by chrbertsch** [comment]
Here we think of typical model&simulation tools and how the support FMI Import/Export. 
"GUI" would be FMI supoort in something like Matlab/simulink.
"CLI" would semthink like fmpy, where you can simulate from Python, "library" something FMI support in "C", "Julia".
This is not exactly defined, I just recommended "CLI", because you create your FMU from the command line using the build instructions as described https://github.com/esmini/esmini/tree/master/OSMP_FMU

**Comment by eknabevcc** [comment]
> Should we add OSI as an interface?

First seems a good idea, but I see the field is limited to two options in this context:

```
    "interfaces": [
        "GUI",
        "CLI"
    ],
```

So, I think we stick with "CLI", also considering Christians replay above.

My conclusion is that I will deal with pull request end of next week. For now I will skip the "examplesURL" part, since I'd rather keep:
```
    "platforms": [
        "Linux",
        "Windows",
        "macOS"
    ],
```
to encourage trying to use on various platforms. Instead of only the verified:
```
    "platforms": [
        "Linux"
    ],
```
My thinking is: I'm not comfortable with the combination a "star" tool with claimed support for platforms not being tested on. So better with a wanna-be tool for multiple platforms :) than verified tool for single platform, for now. We can change later.

**Comment by eknabevcc** [comment]
https://github.com/modelica/fmi-standard.org/pull/625

**Comment by eknabevcc** [comment]
esmini added to https://fmi-standard.org/tools/
Closing issue.
