### ISSUE TITLE
Does esmini support OpenSCENARIO FollowTrajectoryAction when followMode=follow

### ISSUE THREAD

**Issue by wubinwab** [esmini/esmini#579]
Hello, 
I would like to know about Esmini's support for FollowTrajectoryAction. Because I found that, If followMode is set to follow, and the vehicle has not yet reached the starting point of the trajectory, the vehicle will teleport directly to the starting point, which is not quite consistent with the standard as below:
![image](https://github.com/esmini/esmini/assets/161703216/b38a65e4-495b-4af0-8917-65864864fc7d)

**Comment by eknabevcc** [comment]
Yes, this is a limitation of esmini. 

It has not yet been prioritized to be implemented. So far most use cases is either to follow trajectory from start and throughout the scenario or to trig a trajectory laid out from current position (using relative position types in control points).
