### ISSUE TITLE
Where are the dependencies downloaded and linked?

### ISSUE THREAD

**Issue by xuanyuxin** [esmini/esmini#580]
When trying to build esminiJS, the following error occurs even if I set all of the followings to false (so that the dependencies will not be linked or compiled?):
USE_OSG
USE_OSI
USE_SUMO
USE_GTEST
USE_IMPLOT

```
EnvironmentSimulator/Modules/PlayerBase\Plot.hpp:13:10: fatal error: 'imgui.h' file not found
```
The following headers are not found either:
```
#include "osi_sensordata.pb.h"
#include "osi_object.pb.h"
#include "osi_groundtruth.pb.h"
#include "osi_sensorview.pb.h"
#include "osi_version.pb.h"
#include "osi_common.pb.h"
#include "osi_trafficcommand.pb.h"
#include "osi_trafficupdate.pb.h"
```

I am wondering whether these missing headers are needed, and if so how could I acquire these?  I tried reinstalling by running [scripts/generate_osi_sumo_osg_libs.sh](https://github.com/esmini/esmini/blob/master/scripts/generate_osi_sumo_osg_libs.sh) but it seems to cause many errors on my computer.

**Comment by eknabevcc** [comment]
Quick answer: If you do a clean clone of esmini repo, then run the cmake for creating build files, all dependencies (prebuilt libs and headers) should be downloaded as part of the cmake process. See [User guide - Build esmini - quick guide](https://esmini.github.io/#_build_esmini_quick_guide) for the basic steps.

See #540 for some related info on the topic.

**Comment by xuanyuxin** [comment]
For anyone having the same problem, I was able to solve by adding the following lines in esminiJS's CMakeLists:

```
set(OSI_INCLUDE_DIR
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../externals/osi/v10/*")
set(OSG_INCLUDE_DIR
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../externals/osg/v10/*")
set(SUMO_INCLUDE_DIR
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../externals/sumo/v10/*")
set(IMPLOT_INCLUDE_DIR
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../externals/implot/v10/*")

include_directories("${CMAKE_CURRENT_SOURCE_DIR}/../../../externals/implot/v10/include/implot" 
					"${CMAKE_CURRENT_SOURCE_DIR}/../../../externals/implot/v10/include/imgui" 
					"${CMAKE_CURRENT_SOURCE_DIR}/../../../externals/implot/v10/include/imgui/backends" 
                                        "${CMAKE_CURRENT_SOURCE_DIR}/../../../externals/osi/v10/include"
					"${CMAKE_CURRENT_SOURCE_DIR}/../../../externals/osg/v10/include"
```
I think the author of esminiJS tried to turn off OSI/OSG/PLOT related links but for some reason my compiler still tries to find the headers.
I don't really use C++ so I am only able to solve the header not found issues by adding directories one-by-one.

**Comment by eknabevcc** [comment]
Thanks for sharing your solution!
