### ISSUE TITLE
Trailer vehicles are always mapped onto the road 

### ISSUE THREAD

**Issue by lrstttl** [esmini/esmini#585]
I briefly mentioned the following in https://github.com/esmini/esmini/pull/583 already:

When using a vehicle with a trailer, the trailers position is implicitly set behind the towing vehicle based on the vehicle definition.

I noticed that when setting an absolute position for the towing vehicle, which is not perfectly set on the road (for whatever reason), the trailer is still mapped onto the road and there is no option to reuse the towing vehicle's z position (flying yellow box is towing vehicle, yellow box on the road is trailer):  
![image](https://github.com/esmini/esmini/assets/28296759/33076ecc-736d-47f6-9994-8a316e9df09e)

I don't know if this is an actual use case. It just came up when I used imperfect OpenScenario files, where my vehicles were flying around..

**Comment by eknabevcc** [comment]
Yes, I checked and you're right. The trailer position is set internally by x, y and heading alone. The rest is aligned to the road surface. 

I think this is the desired behavior in most cases. But yes, it looks strange if the towing vehicle is flying :)

Let us know if you have a use case where the current behavior becomes a problem.
