### ISSUE TITLE
Scenario editor for openScenario

### ISSUE THREAD

**Issue by yumianhuli2** [esmini/esmini#59]
Is there an open source Scenario editor for openScenario that generates openScenario xosc files？Thanks a lot！

**Comment by eknabevcc** [comment]
Unfortunately, as far as I now, there is no such graphical editor available, yet. 
That would be a very welcomed project I believe. As soon as we find out of such project we'll refer it under Related Work.

**Comment by yumianhuli2** [comment]
> Unfortunately, as far as I now, there is no such graphical editor available, yet.
> That would be a very welcomed project I believe. As soon as we find out of such project we'll refer it under Related Work.

Got it！Thanks!
