### ISSUE TITLE
Use different position modes (Center, Front, Rear) when interpreting WorldPositions

### ISSUE THREAD

**Issue by lrstttl** [esmini/esmini#590]
Hi,

I have come across the following use case: in an input OpenScenario file, I define a trajectory as follows (simplified here of course):
```xml
<Trajectory name="trajectory" closed="false">
    <Shape>
        <Polyline>
            <Vertex time="0">
                <Position>
                    <WorldPosition x="400.0" y="12.0" z="100.0" h="-1.5" p="0.0" r="0.0"/>
                </Position>
            </Vertex>
            <Vertex time="1">
                <Position>
                    <WorldPosition x="397.0" y="10.0" z="100.0" h="-2.0" p="0.0" r="0.0"/>
                </Position>
            </Vertex>
             ...
        </Polyline>
    </Shape>
</Trajectory>
```

When running the scenario with esmini, all `WorldPosition`s are interpreted as the center point of the object.

Is there an option to not interpret them as the object's center, but rather move the rear end or the front end of the vehicle to that position? Meaning in the vehicle's coordinate system, its `x` position should increased or decreased by `length / 2`? 

I've seen that there is an enum class `PositionType` in RoadManager (https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Modules/RoadManager/RoadManager.hpp#L2982-L2990). Can this be used after reading world positions from the OpenScenario?

**Comment by eknabevcc** [comment]
esmini is strictly applying the [OpenSCENARIO vehicle coordinate system](https://publications.pages.asam.net/standards/ASAM_OpenSCENARIO/ASAM_OpenSCENARIO_XML/latest/06_general_concepts/06_03_coordinate_systems.html#_vehicle_coordinate_system_xv_yv_zv), which puts the reference point at ground level mid rear axle.

For OSI, the reference point is transformed to bounding box center (even z). This is probably what you observed.

There is currently no way of changing only the reported reference point. 

However, by modifying the definition of a vehicle you can altogether move the reference point, in terms of bounding box position. But that will also affect the kinematics of the entity.

See [this video clip](https://youtu.be/otsou0_stME) which shows a few different settings.

The scenario files are available here:
https://github.com/esmini/esmini/blob/dev/EnvironmentSimulator/Unittest/xosc/ref_point.xosc
https://github.com/esmini/esmini/blob/dev/EnvironmentSimulator/Unittest/xodr/ref_point.xodr

That said, you're not the first asking for another reference point. It has been suggested for OpenSCENARIO 1.4 (next iteration of the standard) to include support for custom reference point setting. We're also already thinking about it internally, but a few details need to be sorted out first, e.g. how to handle the heading for other reference points than rear axle...
