### ISSUE TITLE
Does esmini support ConstraintValue for Parameters Declaration?

### ISSUE THREAD

**Issue by Quidzilla** [esmini/esmini#591]
Hello all,

First and foremost, thank you for the excellent work you’re doing.

I am curious whether esmini supports the **ValueConstraint** feature for parameter declarations, see documentation:

- [ConstraintValueGroups](https://publications.pages.asam.net/standards/ASAM_OpenSCENARIO/ASAM_OpenSCENARIO_XML/latest/generated/content/ValueConstraintGroup.html)
- [ConstraintValue](https://publications.pages.asam.net/standards/ASAM_OpenSCENARIO/ASAM_OpenSCENARIO_XML/latest/generated/content/ValueConstraint.html)

I couldn't find any relevant information on [this page](https://github.com/esmini/esmini/blob/master/osc_coverage.txt). Could someone clarify this for me?

**Comment by eknabevcc** [comment]
No, esmini is currently not supporting parameter constraints. 

It has been discussed previously. The question then was whether a broken constraint should result in adjusted (truncated) value or an error. 

It's not in immediate plans to implement, but for our understanding which handling would fit your use case?

**Comment by eknabevcc** [comment]
I see. Then we already have two different expectations :) 

We will investigate further before implementing. Maybe on option to choose between the two behaviors would be a solution...
