### ISSUE TITLE
Ignore Letter Case

### ISSUE THREAD

**Issue by Vinka01** [esmini/esmini#60]
I use a program to generate OpenScenario Files. The program generates the root element `<OpenScenario/>`. This causes esmini to not be able to run the scenario, because it seems to require the explicit `<OpenSCENARIO/>` tag. Otherwise the program closes with the message 
`Failed to load OpenDRIVE file
main.cpp / 253 / main(): Failed to initialize scenario player
`.

I think it would be a great increase in user experience, if tag letter case would be ignored (I literally searched a half week for the error in my files).

**Comment by eknabevcc** [comment]
Thanks for reporting this issue. It could be argued if OpenScenario is OK or not. But I like to be pragmatic so it's supported now (from commit ca5aa18). 

Anyway esmini could at least output a better error message in the case of missing OpenSCENARIO/OpenScenario top element. Which is also implemented now.

Sorry to hear about the headache it caused (I know how it feels). I hope you will give esmini some more chance.

Thanks again for the report and contribution to a better esmini!
