### ISSUE TITLE
Conversion of ESMINI replay to XOSC

### ISSUE THREAD

**Issue by kancanaraa** [esmini/esmini#608]
Hi,

I know this topic is a bit interesting and maybe not exactly in your scope. 
But I'm wondering if it's possible to create scenarios from esmini replay? 
It might just be using the trajectory as a reference without needing to define a specific maneuver.

Best regards

**Comment by eknabevcc** [comment]
Please check if this script could meet your needs: [dat2xosc.py](https://github.com/esmini/esmini/blob/master/scripts/dat2xosc.py)

It will basically take a dat file and, based on the original OpenSCENARIO file, generate a new OpenSCENARIO with FollowTrajectory actions for all (or selected) entities.

**Comment by kancanaraa** [comment]
Thank you for your quick response. 
I appreciate it, and I will try the script you suggested and keep you informed. 
Thanks a lot!
