### ISSUE TITLE
Open Sceanrio 2.0: Implementers Group

### ISSUE THREAD

**Issue by jdsika** [esmini/esmini#61]
I was wondering what I could do to support you to be the spearhead of the OSC2.0 implementation? At BMW we will aim for an example implementation in OpenPass. This effort is also supported by the German research project SET Level. Are there any reseach projects that are financing the development of esmini and can you imagine contributing developer time to this task. I am spamming your issue section with a new idea every week but your tool kind of grew to me :D

**Comment by eknabevcc** [comment]
This is another very good question, and please keep them coming :) We haven't thought about it yet. But I realize that eventually we also will look towards OSC2.0. And hopefully we can launch, join or contribute to an Open Source project. 
During today's meeting I'm thinking about OpenPass. What is the basic terms for that project? I know it's hosted by EclipseFoundation. Is the result Open Source in any way? In that case, for members only, or for anyone? Maybe as ASAM OpenX: Anyone can download and use the standards but only (active) members can take part of the development?

**Comment by jdsika** [comment]
@ArunDas1 is a good partner to discuss this with. I think you would have to make a quick compatibility check on MPL-2.0 and EPL-2.0 which is the open source license from Eclipse projects. In my opinion those two licenses are very similar from its properties. I think it would in theory be possible to reuse for esmini and also contribute to a library for the parsing of OSC2.0 from the OpenPass project.

**Comment by eknabevcc** [comment]
The license compatibility comparison sounds promising. The weak copy-left aspect of MPL2.0 I find excellent, in that it does not affect any proprietary code of a tool developer - only esmini module itself. So if anyone do changes (hopefully improvements :)) to esmini modules being part of distributed SW, these changes (and no other) should be published in some way, e.g. proposed pull request here at esmini github. I think that's fair.
So I see two questions:
1. Can OpenPASS incorporate MPL2.0 code?
2. Can MPL2.0 project, like esmini, incorporate OpenPASS EPL-2.0 code?
If issues we can always think about heading to Eclipse/OpenPASS? for further development of a "new" OSC2.0 based simulation platform.

**Comment by jdsika** [comment]
I chose the MPL-2.0 for the Open Simulation Interface for the same reason! :) The feedback from our license experts states that both licensenses are compatibel with each other. EPL-2.0 is even more "permissive" - I suggest you just read it quickly (takes 10min).
The suggested way here would be:
There is a single repository on a Gitlab from Eclipse in which the Eclipse OpenPass working group does do their implementation. You fork the library to Github, inklude it in esmini and you are able to provide feedback in PRs [see here](https://www.eclipse.org/legal/termsofuse.php) but cannot attend regular online meetings the group conducts due to the extended compliance that comes with an Eclipse membership.
If you like we can make a quick call in January in which I explain the idea? Maybe we can then even already show first results?

**Comment by mikgerds** [comment]
Going back to OSC2 Implementers Forum topic ;) It would be great to have you on board for this! ASAM already contacted the Eclipse Foundation and they are also interested in collaboration, possibly use OpenPASS for simulation. Actual Kick-Off for this group will be in calendar week 5 or 6.

**Comment by eknabevcc** [comment]
Thanks for pushing :)
This is of course highly interesting. But, typically when you're under heavy workload, topics involving license questions and memberships (Eclipse) tends to be pushed since it's hard to find clear answers... 

First, I will now try to find out whether VCC is member in Eclipse (wasn't last time checking, but that's a few years ago). 

When it comes to license, maybe it's not that complicated. I agree, after reading (and understanding maybe 40% :) ) it seems to harmonize with MPL 2.0. Further checking would be needed but discussions shouldn't be put on-hold.

As of today, there are no actual plans for OSC 2.0 implementation on our side. But, obviously, if we can see a win-win collaboration situation, that would help internal discussions. 

Maybe a next step would be to roughly draft major components of an open source OSC 2.0 simulation platform. What is the proposed scope for OSC 2.0 Implementers Group and what pieces would be missing? 

So a quick online-meeting to sync sounds like a good next step. I'll contact you for that.

**Comment by ArunDas1** [comment]
Hi all,

Sorry for my late reply! 

Some comments from my side concerning the mentioned topics:
- EPL-2.0 and MPL-2.0 work together well. In openPASS (EPL-2.0) we use e.g. open-simulation-interface (MPL-2.0). The license compatibility has been checked also by the Eclipse Foundation and has been approved. EPL-2.0 also has a weak copyleft. 
- openPASS is fully open source, meaning anybody can download, use and contribute. 
- For contributing you don't need to be a member of the Eclipse Foundation. However, you need to sign a contributor agreement (no membership required; free of charge). 
- We regularly have steering and architecture committees in the openPASS working group (meeting minutes are publicly available: https://wiki.eclipse.org/OpenPASS-WG). If you are planing on contributing or want to discuss potential collaborations with openPASS, there is always the possibility to be invited to our committees as a guest member. 

I like the idea of collaborating among our open source projects and especially when it comes to scenario interpretation. We are currently in the discussion of how to implement an abstract scenario API which allows for the abstraction of the scenario description language from the simulation core. This could also be an interesting starting point for mutual code modules.

**Comment by eknabevcc** [comment]
Thanks a lot for extremely clear answers. And multiple good news which means there are at least no bureaucratic stoppers for potential collaborations.

**Comment by eknabevcc** [comment]
We're still focusing on OSC 1.X but if and when need arise we might look for integration and collaboration opportunities. 
I close the issue since we have kind of regular follow ups with YASE team and will join an OpenPASS meeting focusing on OSC1 frontend and YASE engine.
