### ISSUE TITLE
Doubts about RoadID

### ISSUE THREAD

**Issue by csawp** [esmini/esmini#612]
https://publications.pages.asam.net/standards/ASAM_OpenDRIVE/ASAM_OpenDRIVE_Specification/latest/specification/10_roads/10_01_introduction.html 
The officially defined data type is string. If it is int, it is recommended to use uint. However, I have a file with a large number of RoadIDs exceeding 4.2 billion, all of which are letters
![image](https://github.com/user-attachments/assets/de40f880-5b3c-46f9-9155-5a89acf60065)
![image](https://github.com/user-attachments/assets/da21e677-d4fb-4335-bf24-5e02600bcd2f)

At present, ESMINI cannot run normally, but some websites that can browse xodr format can be browsed

**Comment by csawp** [comment]
At present, special processing is required for all RoadIDs to ensure the normal operation of ESMINI

**Comment by eknabevcc** [comment]
Please share a road (OpenDRIVE) causing the issue for our investigation and verifying any fix.

**Comment by csawp** [comment]
int connecting_road_id = -1;
                if (junction_type == Junction::JunctionType::DIRECT)
                {
                    connecting_road_id = atoi(connection_node.attribute("linkedRoad").value());
                }
                else
                {
                    connecting_road_id = atoi(connection_node.attribute("connectingRoad").value());
                }
                Road* connecting_road = GetRoadById(connecting_road_id);

                if (connecting_road == nullptr)
                {
                    LOG("Missing connecting road with id %d", connecting_road_id);
                    return false;
                }

connecting_road_id = atoi("C6000000000"); OR connecting_road_id = atoi("6000000000"); Unable to find the correct path if (connecting_road == nullptr)return false;
I was thinking that you probably won't be able to change the data type of RoadID smoothly now. There are too many data types being migrated out, such as int, int64, or int, string. The best solution at the moment is to find a way to remove the ID with letters. As for the issue of atoi (6000000000) being out of bounds and unable to find the road, if you don't want to return false, at least it can be loaded
The xodr case is indeed difficult to put out, and a simple junction case can be used to test it

**Comment by csawp** [comment]
OK

**Comment by eknabevcc** [comment]
Forgot got mention that the fix was included in [v2.39.0](https://github.com/esmini/esmini/releases/tag/v2.39.0)
