### ISSUE TITLE
Cannot resolve parameter value when running scenario file from repo vectorgrp/OSC-NCAP-scenarios

### ISSUE THREAD

**Issue by Thomas2e** [esmini/esmini#613]
From repository [https://github.com/vectorgrp/OSC-NCAP-scenarios] I tried to play file NCAP_AEB_C2C_CCR_2023.xosc  (./NCAP/AEB_C2C_2023/NCAP_AEB_C2C_CCR_2023.xosc) with esmini version 2.38.3 (build 4109). 

Log info
_Loading OSC-NCAP-scenarios\OpenSCENARIO\NCAP\AEB_C2C_2023\NCAP_AEB_C2C_CCR_2023.xosc (v1.3)
Expr ${$Ego_speed_kph/3.6} = 20/3.6 = 5.5555555556
Expr ${$GVT_init_speed_kph/3.6} = 0/3.6 = 0.0000000000
Expr ${$GVT_final_speed_kph/3.6} = 0/3.6 = 0.0000000000
Expr ${sign($Overlap)*min(1.0,100.0-$Overlap)*($GVT_width/2-$Ego_width*((abs($Overlap)-50.0)/100.0))} = sign(100)*min(1.0,100.0-100)*(1.712/2-1.815*((abs(100)-50.0)/100.0)) = -0.0000000000
2 variables:
   egoSpeedReached = 0.0
   collisionDetected = false
Loaded OpenDRIVE: \OSC-NCAP-scenarios\OpenSCENARIO\NCAP\AEB_C2C_2023/../../../OpenDRIVE/NCAP/StraightRoad_NCAP_noRoadmarks.xodr
Expr ${$Ego_initTimeHeadway * $_Ego_speed} = 5 * 5.555556 = 27.7777800000
Failed to resolve parameter $_Ego_speed
Exception: Failed to resolve parameter

Issue occurs in referenced input file "ManeuverCatalog.xosc" (./NCAP/Catalogs/Maneuver/ManeuverCatalog.xosc) in line 39
"SetAction"

![image](https://github.com/user-attachments/assets/fe708b60-6f5a-46a5-a42d-76839c24bc80)

I locally applied a workaround for test purposes in OSCGlobalAction *ScenarioReader::parseOSCGlobalAction(pugi::xml_node actionNode, Event *parent) module ./EnvironmentSimulator/Modules/ScenarioEngine/SourceFiles/ScenarioReader.cpp
//varSetAction->value_     = variables.ReadAttribute(varChild, "value");
varSetAction->value_     = parameters.ReadAttribute(varChild, "value");

to pass the declared parameters instead of variables. With that change the scenario is playing.

Change request: Additionally resolve parameter (on top of variable) values used in variable action.

**Comment by eknabevcc** [comment]
Good find, thanks for reporting it! I noticed it as well when running the Vector NCAP scenarios.

This bug, and a few other limitations, has been fixed in release [v2.38.4](https://github.com/esmini/esmini/releases/tag/v2.38.4).
