### ISSUE TITLE
OpenGL version test failed, requires valid graphics context

### ISSUE THREAD

**Issue by ar4development** [esmini/esmini#627]
Hi,

I'm trying run odrviewer but I encounter

```
esmini GIT REV: N/A
esmini GIT TAG: N/A
esmini GIT BRANCH: N/A
esmini BUILD VERSION: 4248
Generated seed 4275473928
density: 1.00
global speed factor: 1.00
Window created at 89,147 with size 6560,2560
No scenegraph 3D model loaded. Generating a simplistic one...
osi_features: lines off points off
Error: OpenGL version test failed, requires valid graphics context.
7 cars added
Segmentation fault (core dumped)
```

I have Ubuntu 24.04 with X environment. Nvidia card:

```
---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060        Off | 00000000:01:00.0  On |                  N/A |
|  0%   51C    P5              26W / 170W |   2100MiB / 12288MiB |     15%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

And `glxinfo | grep "OpenGL version"` returns:

```
OpenGL version string: 4.6.0 NVIDIA 535.183.01
```

and `glxgears` and `glxdemo` run smoothly

Could you advice some tricks

**Comment by eknabevcc** [comment]
I have no clue. But I also would like to find root cause. Have you tried smaller window? 

Can you try, from esmini root:
`./bin/odrviewer --window 60 60 800 400 --odr ./resources/xodr/straight_500m.xodr`

If that doesn't work, also try:
`./bin/odrviewer --window 60 60 800 400 --odr ./resources/xodr/straight_500m.xodr --aa_mode 0`
which will switch off any multi-sampling (anti-aliasing).

**Comment by ar4development** [comment]
> Can you try, from esmini root: `./bin/odrviewer --window 60 60 800 400 --odr ./resources/xodr/straight_500m.xodr`
> 
> If that doesn't work, also try: `./bin/odrviewer --window 60 60 800 400 --odr ./resources/xodr/straight_500m.xodr --aa_mode 0` which will switch off any multi-sampling (anti-aliasing).

Both methods work!

Thank you very much!
