### ISSUE TITLE
Conversion of 3D models from other formats to .osgb

### ISSUE THREAD

**Issue by jaY-S-99** [esmini/esmini#63]
I wanted to convert and import 3d models from other simulators which use formats like .fbx,.3ds etc. into .osgb. How to convert those formats from those formats to .osgb? Is it also possible to color and texture them separately and how to control the wheel node movements?

Thanks a lot!

**Comment by eknabevcc** [comment]
Thanks for good questions!
1. Convert 3D models. 
Yes, I think the OSG tool [osgconv](http://www.openscenegraph.org/index.php/documentation/user-guides/55-osgconv) is a great tool for converting 3D models. It's command line, so no GUI. However, combined with [osgviewer](http://www.openscenegraph.org/index.php/documentation/user-guides/54-osgviewer) you can preview the result easily.
OSG supports quite a few formats, [see here](http://www.openscenegraph.org/index.php/documentation/user-guides/61-osgplugins) (maybe not up to date, but should give an idea). 
My experience is that translating (forth and back) between .osgb, .obj, .dae (collada) and .fbx works great, while others e.g. 3ds sometimes does not give perfect results. But it was quite long time ago I tried the 3ds, so you should give it a try.
See [here ](https://github.com/esmini/esmini/blob/master/docs/BuildInstructions.md#osgconv) for some info on downloading pre-built OSG (with tools) or how to build yourself.
The syntax for converting is simple:
```osgconv input.fbx output.osgb``` 
Some useful options:
```osgconv input.fbx output.osgb --compressed```  will compress and embed textures
```osgconv input.fbx output.osgb --t 1,5,7```  will translate the model (x=1, y=5, z=7)
```osgconv input.fbx output.osgb --o -90-1,0,0```  will rotate the model (rotate -90 deg around X-axis) 
```osgconv input.fbx output.osgb --o -90-1,0,0 --use-world-frame```  as above but pivot point world origin
2. Color and texture
Unfortunately there is no straight forward way of re-color or re-texture objects using osgconv. However, a trick I use sometimes is to convert in to .obj or .dae (which are ASCII resp. XML) and then manually or by script editing the color information. That's how I could easily create color variants of a single car model for example. Then convert the result into .osgb. 
I haven't tried it, but similar trick should work great with textures. For example, if you have a traffic sign with speedlimit 70 you could convert it into .osgb embedding the texture, and then just replace the image with e.g. 50 and convert it into a different .osgb embedding texture again. And they will end up as two different models containing different textures. Thanks for question, I haven't thought about this trick before :)
3. Wheel movements
This is easy: Make sure your vehicle model has four separate wheel nodes with names: "wheel_fl", "wheel_fr", "wheel_rr", "wheel_rl" (front left, front right, rear right, rear left). For this you might need a 3D editor, e.g. [Blender](https://www.blender.org/) which btw is free and great. This is how it looks in one of our models:

![image](https://user-images.githubusercontent.com/29146839/101729942-6d2da200-3ab9-11eb-809e-de1b565d0b06.png)

Then esmini should identify those nodes and handle the rest. Please get back if this does not work.

**Comment by johschmitz** [comment]
Can this (at least step 1.) or at least a link to this information (containing the keyword "osgconv") be added to the main README.md. Right now this issue seems to be the only place to find this information.

**Comment by eknabevcc** [comment]
Thanks Johannes, that was a good suggestion. 
I added a small [section in main readme](https://github.com/esmini/esmini/blob/master/README.md#3d-model-support) on the topic and a link back to this issue.

**Comment by johschmitz** [comment]
@eknabevcc I am coming back to this after a long time and wonder if it could be added to this section now:

https://esmini.github.io/#_openscenegraph_and_3d_models

I am especially missing the part with the moving wheels.

**Comment by eknabevcc** [comment]
Yes, we might do that, I agree it would be good. 
However, until then, the reference is still there, under [Colors, textures and wheel rotations](https://esmini.github.io/#_colors_textures_and_wheel_rotations).

**Comment by johschmitz** [comment]
Ah, I missed that because I searched for "wheels" instead of "wheel".

**Comment by johschmitz** [comment]
Created a mini PR #657 to improve this.

**Comment by eknabevcc** [comment]
Excellent, thanks. 
It's merged on dev, and hence will be included in next release.

**Comment by johschmitz** [comment]
A very old issue but I'm reopening this to ask whether this information could be added to the user guide?
