### ISSUE TITLE
Control scenario via external commands

### ISSUE THREAD

**Issue by wubinwab** [esmini/esmini#646]
Hello, I’m curious to know if esmini is capable of operating in a mode where vehicles within the scenario are dynamically introduced and managed by an external application. This would include the ability to control vehicle behaviors such as changing lanes, accelerating, or decelerating, etc. All of which would be controlled through external commands rather than being predefined within an OpenSCENARIO file.
I would be glad if you could give me some advice!

**Comment by eknabevcc** [comment]
**Adding and deleting entities during simulation** 

Yes, it's possible, utilizing [AddEntityAction](https://publications.pages.asam.net/standards/ASAM_OpenSCENARIO/ASAM_OpenSCENARIO_XML/latest/generated/content/AddEntityAction.html) and [DeleteEntityAction](https://publications.pages.asam.net/standards/ASAM_OpenSCENARIO/ASAM_OpenSCENARIO_XML/latest/generated/content/DeleteEntityAction.html). Here's a scenario example (a bit silly, it's for test purposes):
https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Unittest/xosc/add_delete_entity.xosc

It's also possible to add and delete entities via the esminiLib API. Here's a code example: [ad_hoc_traffic](https://github.com/esmini/esmini/tree/master/EnvironmentSimulator/code-examples/ad_hoc_traffic).

**Injection of actions**

Yes, it's possible, utilizing the esminiLib action injection feature, see [User guide - Inject actions](https://esmini.github.io/#_inject_actions).

Examples, run from `esmini/bin`:

Python:
`python ../EnvironmentSimulator/code-examples/hello_world/action_injection.py ../resources/xosc/cut-in.xosc`

C++ ([action_injection.cpp](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/code-examples/hello_world/action_injection.cpp)):
`../code-examples-bin/action_injection ../resources/xosc/cut-in.xosc`

Note that only a few actions are currently supported. But it's fairly simple to extend if needed. 

I hope this information can get you going with your use case!

**Comment by wubinwab** [comment]
Thank for your quick reply! 
I tested the demo and it works well, which is of great help to my subsequent work.
Additionally, I’d like to ask if the existing framework supports injecting triggers and actions, so that the trigger can activate the execution of the action?

**Comment by eknabevcc** [comment]
Only actions can be injected via API, as described above. They will be performed immediately. Trigger can't be injected in similar way.

May I ask what is you use case, briefly?

**Comment by wubinwab** [comment]
What I’m looking to implement is a feature that allows for the injection of Events, which could either be actions that executed immediately or actions that are executed once a certain condition is met. It’s similar to the SCP functionality in VTD, if you’re familiar with VTD, you might understand what I mean.

**Comment by eknabevcc** [comment]
Ok, I see. Yes, I know about VTD and the SCP protocol. It's a nice feature. 

Unfortunately nothing similar is implemented for esmini, yet.

**Comment by wubinwab** [comment]
Okay, I understand the current situation now. Thank you for your information. I will close this issue.
