### ISSUE TITLE
Fixed timestep and more detailed output / debug mode?

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#75]
Hi,
is there any possibility to get the positions of all objects in STDOUT, logs file or separated file for a fixed time step? I've found a batch file with the option "fixed_timestep", but this seems also not to be used.

Kind regards,

Thaddäus

**Comment by eknabevcc** [comment]
Try this, from esmini root folder:
`.\bin\esmini --window 60 60 800 400 --fixed_timestep 0.02 --osc .\resources\xosc\cut-in.xosc --record sim.dat`

You can then view the file in replayer: 
`.\bin\replayer.exe --window 60 60 800 400 --res_path .\resources --file .\sim.dat`
  please try the key shortcut commands to pause and step (also backwards) the scenario (see [replayer/readme.txt](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Applications/replayer/readme.txt)

But more importantly, for you question:
`.\bin\dat2csv.exe .\sim.dat`
Then you can print the resulting sim.csv:
`cat sim.csv ` (from PowerShell, if you're in cmd use type sim.csv)

And you can open the .csv in Excel as well.

And you can plot stuff from it with esmini/scripts/plot_csv, e.g:
`.\scripts\plot_csv.py .\sim.csv --param speed`

**Comment by tmIdiada** [comment]
Hi,
thanks a lot for the information. Yes, that is exactly the information I've searched for.

Kind regards,

Thaddäus

**Comment by eknabevcc** [comment]
> 
Update for v2.18.2:
plot_dat.py replaces the two-step sequence with dat2csv and plot_csv.py.

So if you just want to plot the data, run:
`./scripts/plot_dat.py sim.dat --param speed`

And there's a Python version of the dat2csv: scripts/dat2csv.py
