### ISSUE TITLE
OSG version problem

### ISSUE THREAD

**Issue by rongguodong** [esmini/esmini#8]
In Linux build instruction, there is the following line for OSG:
"git checkout OpenSceneGraph-3.6.3"
However, this branch does not exist.

I tried to checkout OpenSceneGraph-3.6 instead, but got lots of errors later when build esmini, all related to OSG 3.6.3. Can you fix this problem?

**Comment by eknabevcc** [comment]
To my understanding: "OpenSceneGraph-3.6.3" is a tag, not a branch. So it should be OK to just checkout according to the instruction. 
Unfortunatelly I can't verify on Linux, but I just tried it on Windows and it works. However, there is not much feedback of the checkout command - so you might have got the wrong impression that no files where changed.
Here you can see valid OSG tags: https://github.com/openscenegraph/OpenSceneGraph/tags
Hope this helps!

**Comment by rongguodong** [comment]
I found out that I can use "git checkout OpenSceneGraph-3.6.3 -b OpenSceneGraph-3.6.3" to create a local branch named "OpenSceneGraph-3.6.3". Now, I can successfully build esmini as instructed. :)

**Comment by eknabevcc** [comment]
Excellent!
