### ISSUE TITLE
Path to esmini-Log

### ISSUE THREAD

**Issue by cfschaller** [esmini/esmini#81]
Dear Emil,

while working with esmini (or, more concretely, esminiLib - which we still enjoy greatly!), we came across another possible opportunity for improvement. From what we understand, esmini's log is always written to the file "log.txt" in the execution directory. In terms of code, this is specified by a preprocessor constant (#define LOG_FILENAME "log.txt") in CommonMini.cpp. 

This is problematic for us, as in some of our use cases, the attempt to write to the execution directory will cause an exception. Our current workaround is to manually build esmini with /DSUPPRESS_LOG, which will avoid the problem at the cost of having no log at all. However, what we would like to do is having the opportunity to specify the logPath when working with esminiLib, e.g. as an extra parameter in SE_Init.

What are your thoughts on this? Are we missing something? 

Thanks in advance,
Christoph

**Comment by eknabevcc** [comment]
Actually, since yesterday's release [v2.4.3](https://github.com/esmini/esmini/releases/tag/v2.4.3) there is a check if log file could be created. If not, it will try with a system provided temp filename (which is printed in the console). Last resort is to skip logfile altogether. Please check if this approach is good enough for your use case. 

We try to avoid growing the SE_Init argument list. But one alternative could be to have a separate function call to set the logfile path - that in that case should be called prior to SE_Init.

**Comment by eknabevcc** [comment]
Actually when thinking about it, this was a really good suggestion that will be useful.
An option set custom name (and complete path) for logfile, and option to disable it altogether is now implemented (commit [4d23792](https://github.com/esmini/esmini/commit/4d2379272c6d28424a92e9909d0197400c484f6f)) from [v2.4.4](https://github.com/esmini/esmini/releases/tag/v2.4.4).

I've added an example how to use it via API in [Applications/esmini-dyn/main.cpp lines 103-104](https://github.com/esmini/esmini/blob/7c9b62bf46660bc06a75102b24b05fa35c005777/EnvironmentSimulator/Applications/esmini-dyn/main.cpp#L103). If you change the name after SE_Init() it will close the current logfile and open a new one. This could be useful between multiple runs within same session (between each call to SE_Init()).

Thanks for suggestion 👍

**Comment by cfschaller** [comment]
Amazing! :heart_eyes:
I spent the last few hours experimenting with v2.4.3 and a rather tricky workaround (along the lines of redirecting the dll console output to determine the temporary filename and then working with the temporary file and its content), which wasn't really satisfying.
However, the new functionality seems to be just what we needed - I will have a closer look now!

Thanks for the great effort!

**Comment by cfschaller** [comment]
Works like a charm - thanks again! :)

**Comment by eknabevcc** [comment]
Thanks for feedback, glad that it works for you as well!
