### ISSUE TITLE
New signals for dat and csv file

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#82]
Hi,

is it possible to define new signals (for ALKS scenarios it would be great to have collision, collision-front-back, collision-side, backward interrupt signals).

How one could define such signals? Other people are asking for more options regarding the SE-Init and logs output, maybe it would be a good idea to define a config file for esmini and control its options and features by this config file?

Kind regards,

Thaddäus

**Comment by eknabevcc** [comment]
Currently users can can control most stuff by command line arguments (typically scripted in most use cases). But I agree that the options are limited when using the library. We provided a few functions for controlling logfile handling and search paths. The strategy so far has been to add stuff based on need. A config file sounds like a good idea 👍, but it's probably some work which I personally can't prioritize that now - there's other hanging fruits I'd like to pick first :) 

Then signals. Actually collision detection has been discussed, like extending the bounding box based collision detection (used for OpenSCENARIO CollisionCondition) to always check and report - as you propose. But sometimes users need more detailed collision detection (than BoundingBox). So to cover all case, the user in that case concluded to do the analysis externally based on OSI output. 

It's an interesting idea to allow for config the content of .dat-files. Users could then store what they need, and not having to store the superset for all possible use cases. However, I think it would require some work, which would be hard for me to prioritize before we see internal need.

But, all this said, for this kind of features that does not currently fit in our own backlog, we really encourage users to try implement a solution and propose as pull request. I can also imagine some collaborative process, where we are involved early discussing the solution to avoid a situation where it doesn't fit in the end for some reason.

And thanks for good suggestions! We'll keep them in mind.

**Comment by eknabevcc** [comment]
I close this issue now since there is no immediate action planned. It will still be available for re-opening if and when anyone is ready to implement this functionality.

**Comment by tmIdiada** [comment]
Closing is ok to me. Hope the idea will be implemented one day. Unfortunatly, I have not the invests and not own expertise in C++ coding to do it by myself.

**Comment by eknabevcc** [comment]
Understand. Thanks for valuable input.
