### ISSUE TITLE
Rendering artifacts on road with poly param 3 geometry

### ISSUE THREAD

**Issue by radarsat1** [esmini/esmini#83]
Hello,

I have been generating OpenDRIVE files using polyparam3 geometry elements, and trying to use esmini's odrviewer to visualize.  I am getting some rendering artifacts with the road marks.

Can you verify if this is a bug, or if there is something wrong with the OpenDRIVE file?  I do not get similar artifacts with other software.

Screenshot 1:
![screen_shot_0_0](https://user-images.githubusercontent.com/66805/110304262-a95e9900-7ffb-11eb-96ba-f5d1c733716d.jpg)

Screenshot 2:
![screen_shot_0_1](https://user-images.githubusercontent.com/66805/110304245-a4014e80-7ffb-11eb-92b3-1b0b591f772e.jpg)

I noticed that the problem effectively goes away if I comment out the following else-if clause: https://github.com/esmini/esmini/blob/bcbdbecf57309ba95c03510ebba25521ab42426b/EnvironmentSimulator/Modules/ViewerBase/roadgeom.cpp#L163

But it doesn't seem correct to me to just remove this statement, and some roadmarks I think are just missing when I do that.  However, maybe it is a hint.

[test_poly3.xodr.txt](https://github.com/esmini/esmini/files/6100372/test_poly3.xodr.txt)

Thanks for any help.

**Comment by eknabevcc** [comment]
Excellent! I can confirm you found a bug. The creation of road marks did not work well with multiple lane sections. It should now be fixed from commit [9c9ab00](https://github.com/esmini/esmini/commit/9c9ab0081e8bbf3c38b03d22e0ab722d1fe2a056). Please test. It will be part of next upcoming release. Let me know if you need one urgent.

![image](https://user-images.githubusercontent.com/29146839/110345862-4be43f80-802f-11eb-8471-35dc30a6b4d9.png)

BWT: I found one issue in the OpenDRIVE, although not related to the road mark bug. The length attribute of the road didn't match the total length of geometries. The reason why I checked was that the randomized traffic in odrviewer got stuck at end of road... I attach my updated version.

[test_poly3-edit.xodr.txt](https://github.com/esmini/esmini/files/6102499/test_poly3-edit.xodr.txt)

Thanks for reporting the issue!

**Comment by radarsat1** [comment]
Thanks for the quick fix! Confirmed, it does seem to work properly now.

**Comment by eknabevcc** [comment]
Good to hear that it seems to work, thanks for feedback.
Regarding the road length, yes I suspected it was from a trim "operation" because I recognized the issue from similar operations on my own :)
