### ISSUE TITLE
need help with accessing ground truth

### ISSUE THREAD

**Issue by sterres** [esmini/esmini#88]
Hi,

first thanks for providing such a cool tool.

Unfortunately, I'm stuck with accessing the ground truth via the C++ API (Windows).

My current code looks sth like this:

```
SE_Init(".../esmini-demo_win/esmini-demo/resources/xosc/cut-in.xosc", 0, 1, 0, 0);
SE_EnableOSIFile("C:/temp/test.osi");

osi3::GroundTruth esminiGT;

SE_StepDT(0.01);
SE_StepDT(0.01);
SE_StepDT(0.01);
SE_StepDT(0.01);
SE_StepDT(0.01);
SE_StepDT(0.01);

SE_ClearOSIGroundTruth();
SE_UpdateOSIGroundTruth();
SE_UpdateOSIDynamicGroundTruth();

esminiGT.ParseFromString(SE_GetOSIGroundTruthRaw()); 

printf("moving objects in GT %d\n", esminiGT.moving_object_size());
printf("road markings in GT %d\n", esminiGT.road_marking_size());

```

I was expecting 2 moving objects (which I can also see in the OSI trace file and the scenario player). But it always gives output "0". Same for the road markings.

There is no build error.

Thanks for your help
Simon

**Comment by eknabevcc** [comment]
My guess is that the SE_ClearOSIGroundTruth() actually clears the data. And since there is no step in between, the Update calls have no effect, cause there is no new data since the clear. 

Please try the following:

```
osi3::GroundTruth* gt;

// Initial update of complete Ground Truth, including static things
SE_UpdateOSIGroundTruth();

for (int i = 0; i < 10; i++)
{
	SE_StepDT(0.01);
		
	// Update only dynamic OSI stuff
	SE_UpdateOSIDynamicGroundTruth();

	// Fetch OSI struct
	gt = (osi3::GroundTruth*)SE_GetOSIGroundTruthRaw();

	// Print timestamp
	printf("Frame %d timestamp: %.2f\n", i, gt->mutable_timestamp()->seconds() +
		1E-9 * gt->mutable_timestamp()->nanos());

	// Print object id, position, orientation and velocity
	for (int j = 0; j < gt->mutable_moving_object()->size(); j++)
	{
		printf(" obj id %lld pos (%.2f, %.2f, %.2f) orientation (%.2f, %.2f, %.2f) velocity (%.2f, %.2f, %.2f) \n",
			gt->mutable_moving_object(j)->mutable_id()->value(),
			gt->mutable_moving_object(j)->mutable_base()->mutable_position()->x(),
			gt->mutable_moving_object(j)->mutable_base()->mutable_position()->y(),
			gt->mutable_moving_object(j)->mutable_base()->mutable_position()->z(),
			gt->mutable_moving_object(j)->mutable_base()->mutable_orientation()->yaw(),
			gt->mutable_moving_object(j)->mutable_base()->mutable_orientation()->pitch(),
			gt->mutable_moving_object(j)->mutable_base()->mutable_orientation()->roll(),
			gt->mutable_moving_object(j)->mutable_base()->mutable_velocity()->x(),
			gt->mutable_moving_object(j)->mutable_base()->mutable_velocity()->y(),
			gt->mutable_moving_object(j)->mutable_base()->mutable_velocity()->z()
		);
	}

	printf("moving objects in GT %d\n", gt->moving_object_size());
	printf("road markings in GT %d\n", gt->road_marking_size());
}
```

**Comment by sterres** [comment]
Thanks for trying to help. With your code I get different values, but they still don't make sense.
![image](https://user-images.githubusercontent.com/30345042/111122834-e0d6c380-856e-11eb-878b-7e4cd57edb16.png)

Is this a memory address?

I had a look into the source code (OSIReporter.cpp - line 279) and it looks like the _obj_osi_internal.gt_ is sometimes serialized as a string too. But I also tried with disabled OSI trace file and still get the same results.

**Comment by eknabevcc** [comment]
Interesting that you get different result. If you run the latest esmini (at least from latest release), we should get the same.
I attach my exact main.cpp. 
Actually when looking at the console output (attached console_output1.txt), I see that the same objects are re-created each update. And that should not be the case. I suspect there is a bug. I created a branch to test a solution: https://github.com/esmini/esmini/tree/osi_fix

Please try with my main.cpp. It should give the same result. 
And also, if possible, please try the branch and see if you get better result, (like attached console_output2.txt).
[main.cpp.txt](https://github.com/esmini/esmini/files/6140447/main.cpp.txt)
[console_out1.txt](https://github.com/esmini/esmini/files/6140526/console_out1.txt)
[console_out2.txt](https://github.com/esmini/esmini/files/6140527/console_out2.txt)

**Comment by sterres** [comment]
I tried to run your example with ESmini 2.5.0 DLL - with this I get an access violation error.

Are there special version requirements for OSI/protobuf to be compatible with ESmini DLL?
Do I have to compile esminiLib myself to make it work with OSI?

I also downloaded the osi-fix branch, but with this I get CMake errors and can't compile:
> Error		CMake Error at EnvironmentSimulator/CMakeLists.txt:364 (download_and_extract):
>   download_and_extract Function invoked with incorrect arguments for function

**Comment by sterres** [comment]
Update: the access violation might be caused by some old processes not being killed.
Now your main.cpp gives this output on my machine:
![image](https://user-images.githubusercontent.com/30345042/111147236-8ba8ab00-858a-11eb-8812-bfd5bba4910e.png)

**Comment by sterres** [comment]
Update: I got the build working by setting the platform manually
`set(CMAKE_VS_PLATFORM_NAME "x64")`

Then, I linked the main.cpp against the same OSI lib that is downloaded by the esmini build script.

Now it is working and I get the same results like you.

Can we make this more transparent by giving version numbers that are required for compatibility?

**Comment by eknabevcc** [comment]
That was good news 👍 
I definitely agree that we should somehow clarify or at least provide means to check the version. At least making a note in the relevant esmini code - how to find out the version. 
What I understand it's both Protobuf version and OSI version that is relevant.

Protobuf version I think can be found out from here: externals/OSI/v10/include/google/protobuf/port_def.inc

But OSI version is worse. I think we should add the [VERSION](https://github.com/OpenSimulationInterface/open-simulation-interface/blob/master/VERSION) file to the Include folder.

Do you think that would make sense?
(Because I would avoid hardcoding the version number somewhere in esmini code or documents, that would at some point be out of synch).

**Comment by eknabevcc** [comment]
Forget my branch "osi_fix". It was me that got things wrong on how to use the OSI API.

Please check updated code example, now added to the Hello World tutorial [here](https://github.com/esmini/esmini/tree/master/Hello-World_coding-example#osi-groundtruth).

And I also didn't find a simple way to include the VERSION file. So I added manual info after all in the README, [here](https://github.com/esmini/esmini#osi-support).

If possible, please try the code and tell how it works.

**Comment by sterres** [comment]
Thanks....adding OSI how-to to the Hello World tutorial is a very good idea. That's also where I started.

Maybe add a notification there, that OSI & protobuf versions have to be consistent (where you explain, how to use esmini OSI libs).

Concerning the osi_fix: I can confirm that it works with your Hello World code.

Thanks a lot for your help!

**Comment by eknabevcc** [comment]
Good to hear that it works 👍
Yes, good idea to mention the version dependency. I added [a note about that](https://github.com/esmini/esmini/tree/master/Hello-World_coding-example#osi-groundtruth).
Thanks for reporting. I close this for now.
