### ISSUE TITLE
How to run a bunch of scenarios in a loop in python?

### ISSUE THREAD

**Issue by Qianyu-Liu** [esmini/esmini#89]
Hi,
I am running esmini in python. And I got many scenarios, so I made a loop so that I don't need to run them one by one every time when I did some changes in the code.
Here are the structure of my code:

import libraries
se = ctypes.CDLL("./libesminiLib.so")

class SEScenarioObjectState(ctypes.Structure):
    ....

def callback(state_ptr):
    ...

for EventID in Eventlist:
    casepath = 'xxx.xosc'  #chose casepath during looping
    callback_type = ctypes.CFUNCTYPE(None, ctypes.POINTER(SEScenarioObjectState))
    callback_func = callback_type(callback)
    se.SE_Init(casepath.encode('utf-8'), 0, 0, 0, 1)
    se.SE_RegisterObjectCallback(0, callback_func, 0)
    numTimeSteps = 2000
    timeStep = 0.01

    for i in range (numTimeSteps):
        se.SE_StepDT(ctypes.c_float(timeStep))
        obj_state = SEScenarioObjectState()
        ...
        ...
        ...
        ...

But I got an error "Segmentation fault (core dumped)" in second interation in line "se.SE_StepDT(ctypes.c_float(timeStep))"

I would really appreciate if you could give me some suggestions on how to solve this error or sharing a helloworld example for looping the esmini simulation.

Thanks in advance.

**Comment by eknabevcc** [comment]
Interesting use case! Let's try to solve the problem. To narrow down, please try the attached script. It works for me, at least on Windows. 
If it doesn't work for you, then: 
1. What platform? (I can test on Linux, but not on Mac) and 
2. What esmini version? 
3. Are there any significant differences between our scripts?

[esmini-player.py.txt](https://github.com/esmini/esmini/files/6163028/esmini-player.py.txt)

**Comment by Qianyu-Liu** [comment]
Thanks so much for your code !
I moved these 2 lines outside the loop, then everything is ok now.

- callback_type = ctypes.CFUNCTYPE(None, ctypes.POINTER(SEScenarioObjectState))
- callback_func = callback_type(callback)

**Comment by eknabevcc** [comment]
Ah, I see. I tried the same and also get a crash with those two lines inside the loop. I don't understand why. But since we only need to declare the callback function once - I think we found a good solution. 👍
Thanks for report. I close the issue for now.
