### ISSUE TITLE
dat2csv without system call?

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#90]
Hi,

there are several questions and answers how esmini can be integrated into python (also included in Hello world example esmini_player.py). But is there also a possibility to do similar python commands to replace dat2csv and to get the final csv files out of the dat files or directly the dat file content into python?

I've already tried something like this
dt = np.dtype([('info', [('id', 'int32'), ('model_id', 'int32'), ('obj_type', 'int32'), ('obj_category', 'int32'), ('ctrl_type', 'int32'), ('timeStamp', 'float32'), ('name', 'a32'), ('speed', 'float32'), ('wheel_angle', 'float32'), ('wheel_rot', 'float32'),
                       ('boundingbox', [('center', [('x', 'float32'), ('y', 'float32'), ('z', 'float32')]), ('dimensions', [('width', 'float32'), ('length', 'float32'), ('height', 'float32')])])]),
                       ('pos', [('x', 'float32'), ('y', 'float32'), ('z', 'float32'), ('h', 'float32'), ('p', 'float32'), ('r', 'float32'), ('roadId', 'int32'), ('laneId', 'int32'), ('offset', 'float32'), ('t', 'float32'), ('s', 'float32')])])

np.fromfile("esminiResult.dat", dtype=dt)

But it seems to be not correct, I think the structure and data types are very close to the used ones by dat2csv or replayer, but not completely correct. Or is it possible to bind directly the compiled dat2csv by using ctypes?

**Comment by eknabevcc** [comment]
That's a good idea, to enable reading .dat directly from Python. 
Actually recent modifications of the .dat file format makes it more possible. And a last [minor change](https://github.com/esmini/esmini/commit/28ab08ea9b64311eb7b442fa65828d72218e0c1a) (converting OSCBoundingBox type from class to struct) also makes the format only including basic C types. Also compatible between Linux/Windows.

I added a [simple Python-script](https://github.com/esmini/esmini/blob/master/scripts/dat2csv.py) that behaves just like the dat2csv application.

Please test and see if works for you.

**Comment by tmIdiada** [comment]
Thank you a lot Mr. Knabe,

I can test it on Thursday, hope you are patient ;)

Kind regards,

Thaddäus

**Comment by eknabevcc** [comment]
Usually I'm not that patient, but let's go for this time :)

**Comment by tmIdiada** [comment]
Hi it works fine.

Thank you a lot for the support here.

**Comment by tmIdiada** [comment]
It seems I'm not allowed to create branches with following pull requests. Thus, I'm sending my code proposal for scripts/dat2csv.py here, becasue I think your script name (and finally the basis of the script) is not completely suitable for the result and doing of the current script, or in other words now really a csv file is written by python and not only STDOUT prints generated.

import argparse
import ctypes
import os


REPLAY_FILENAME_SIZE = 128
NAME_LEN = 32


class ObjectStateStructDat(ctypes.Structure):
    _fields_ = [

        # ObjectInfoStruct
        ("id", ctypes.c_int),
        ("model_id", ctypes.c_int),
        ("obj_type", ctypes.c_int),
        ("obj_category", ctypes.c_int),
        ("ctrl_type", ctypes.c_int),
        ("timestamp", ctypes.c_float),
        ('name', ctypes.c_char * NAME_LEN),
        ("speed", ctypes.c_float),
        ("wheel_angle", ctypes.c_float),
        ("wheel_rot", ctypes.c_float),
        ("centerOffsetX", ctypes.c_float),
        ("centerOffsetY", ctypes.c_float),
        ("centerOffsetZ", ctypes.c_float),
        ("width", ctypes.c_float),
        ("length", ctypes.c_float),
        ("height", ctypes.c_float),

        # ObjectPositionStruct
        ("x", ctypes.c_float),
        ("y", ctypes.c_float),
        ("z", ctypes.c_float),
        ("h", ctypes.c_float),
        ("p", ctypes.c_float),
        ("r", ctypes.c_float),
        ("roadId", ctypes.c_int),
        ("laneId", ctypes.c_int),
        ("offset", ctypes.c_float),
        ("t", ctypes.c_float),
        ("s", ctypes.c_float),
    ]


class DATHeader(ctypes.Structure):
    _fields_ = [
        ('odr_filename', ctypes.c_char * REPLAY_FILENAME_SIZE),
        ('model_filename', ctypes.c_char * REPLAY_FILENAME_SIZE),
    ]


def dat2csv(datfile):
    if not os.path.isfile(datfile):
        print('ERROR: dat-file not found: {}'.format(datfile))
        return
    try:
        fdat = open(datfile, 'rb')
    except OSError:
        print('ERROR: Could not open file {} for reading'.format(datfile)
        raise
    buffer = fdat.read(2 * REPLAY_FILENAME_SIZE)

    csvfile = os.path.splitext(datfile)[0] + 'csv'
    try:
        fcsv = open(csvfile, 'w')
    except OSError:
        print('ERROR: Could not open file {} for writing'.format(csvfile)
        raise

    h = DATHeader.from_buffer_copy(buffer)
    fcsv.write('OpenDRIVE: {}, 3DModel: {}\n'.format(
        h.odr_filename.decode('utf-8'), h.model_filename.decode('utf-8'))
    )

    # Print column headings / value types
    fcsv.write('time, id, name, x, y, z, h, p, r, speed, wheel_angle, wheel_rot\n')

    # Read and print all rows of data
    while (True):

        buffer = fdat.read(ctypes.sizeof(ObjectStateStructDat))
        if len(buffer) < ctypes.sizeof(ObjectStateStructDat):
            break

        data = ObjectStateStructDat.from_buffer_copy(buffer)
        for fs in data._fields_:
            fcsv.write('{:.3f}, {}, {}, {:.2f}, {:.2f}, {:.2f}, {:.2f}, {:.2f}, {:.2f}, {:.2f}, {:.2f}, {:.2f}\n'.format(
                data.timestamp,
                data.id,
                data.name.decode('utf-8'),
                data.x,
                data.y,
                data.z,
                data.h,
                data.p,
                data.r,
                data.speed,
                data.wheel_angle,
                data.wheel_rot)
            )

    fcsv.close()
    fdat.close()
    return


if __name__ == "__main__":
    # Create the parser
    parser = argparse.ArgumentParser(description='Convert esmini .dat file to .csv')

    # Add the arguments
    parser.add_argument('filename', help='dat filename')

    # Execute the parse_args() method
    args = parser.parse_args()

    dat2csv(args.filename)

**Comment by eknabevcc** [comment]
Excellent! Thanks for contribution. I made just a few minor adjustments and it outputs identical result as dat2csv.cpp (at least on Win).
Commit link; https://github.com/esmini/esmini/tree/8247243b0309e7d3dfd8d97ef9b20d34117d798c
