### ISSUE TITLE
OSI SensorData vs. SensorView

### ISSUE THREAD

**Issue by sterres** [esmini/esmini#91]
Hi,

I had a look into the OSI SensorData output.
SE_GetOSISensorDataRaw();

The code in OSIReporter.cpp looks like the SensorData only contains the GroundTruth information for a list of SensorViews (for each ESmini sensor)

mobj = obj_osi_internal.sd->mutable_sensor_view(i)->mutable_global_ground_truth()->add_moving_object();

From my understanding, OSI SensorData should contain the detected object lists (of the ESmini ideal sensor).
https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/structosi3_1_1SensorData.html#exhale-struct-structosi3-1-1sensordata

Can you help me understand the ESmini concept of this?

Best regards
Simon

**Comment by eknabevcc** [comment]
I must admit I'm a noob at OSI. Most OSI code was written others. But until digging deeper, I created a branch where I added GetSensorData method to lib and modified the esmini-dyn to read it and print basic info to console.
https://github.com/esmini/esmini/tree/sensor_data
Please check if it makes sense. Otherwise it would be valuable if you could elaborate how you expect it to be structured/populated.

**Comment by eknabevcc** [comment]
BTW: You can run the updated esmini-dyn with synchronize.xosc or cut-in.xosc. It should give some immediate hits.

**Comment by sterres** [comment]
I'm also a beginner with OSI and find it not very straight forward.

The function SE_GetOSISensorDataRaw() was already in the lib in master branch. Like I said, it seems to hold only the SensorView but not the DetectedMovingObject messages and so on.

In the OSI repository is an example sensor model - here is a link to the corresponding lines
https://github.com/OpenSimulationInterface/osi-sensor-model-packaging/blob/40ed0fce1a367882ca0fd1bd20eecefb33a2ec8a/examples/OSMPDummySensor/OSMPDummySensor.cpp#L306

However, I can't tell the best way of implementing it in ESmini which supports multiple sensors. Maybe sth like SE_GetOSISensorDataRaw( int sensor_id );

Also, you should think if you really want to make this implementation effort.

Another way would be to only output SensorView out of ESmini and use another tool (e.g. the OSI ideal dummy sensor linked above) to calculate the SensorData. This would also comply to the OSI graphic that expects a SensorView from the environment simulation (esmini in this case)

![grafik](https://user-images.githubusercontent.com/30345042/111814421-ba9c8500-88da-11eb-891d-9a2d4c33a6bd.png)

**Comment by eknabevcc** [comment]
I think you can get hits per sensor via the existing API, like the way I added showed in the updated esmini-dyn (in the branch https://github.com/esmini/esmini/tree/sensor_data). 

The basic relevant code is:

```
for (int k = 0; k < sd->mutable_sensor_view()->size(); k++)
{
	for (int l = 0; l < sd->mutable_sensor_view(k)->mutable_global_ground_truth()->mutable_moving_object()->size(); l++)
	{
		printf(" sview %d movingobj %d \n", k, (int)sd->mutable_sensor_view(k)->mutable_global_ground_truth()->mutable_moving_object(l)->mutable_id()->value());
	}
}
```
Each hit (sensor see an object) will be printed in terms of sensorView index (which sensor) and objectID (that was seen by the sensor). You can try by setting `#define DEMONSTRATE_OSI 1` in [esmini-dyn/main.cpp](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Applications/esmini-dyn/main.cpp) and re-compile esmini-dyn.

Maybe this is not the most elegant or correct way, but perhaps good enough. And as you suggests, the typical use case - also as we do - is to analyze the OSI to create more detailed sensor information, taking object geometry, at least bounding box, into account. The esmini provided sensors are very simple (so far): Reference point within sensor view frustum -> hit.

So for now I think we have a good enough solution. Until someone needs more or in another way...

By the way, I merged the example code into master. I think it was missing and it's thanks to you reporting this issue that we now have it. 👍

**Comment by sterres** [comment]
Ok, yeah I think that makes sense to me.

I'm integrating esmini with OSI sensor FMUs. Therefore, I'll generate an empty SensorView and add the esmini GroundTruth to it.
This SensorView is then the input to an object-based OSI Sensor which outputs the detected objects as SensorData. Now I just need to find the time to code all that :)

I really like that esmini is so lightweight.

And thanks for your help again :)

**Comment by eknabevcc** [comment]
Sounds good. During your implementation mission, let us know if you see any showstoppers in esmini OSI handling. Maybe we can sort out how to fix it with joined forces. 👍
I close this for now.
