### ISSUE TITLE
fatal error: GL/gl.h: No such file or directory - Ubuntu 18.04

### ISSUE THREAD

**Issue by leanderpeter** [esmini/esmini#94]
Hi guys, first of all i have to say what a great project this is. I'm looking into custom and ASAM scenarios. I have the following problem while building the project on Ubuntu. I hope you can help me and the description of the problem fits.

Error message short (full message below)

> fatal error: GL/gl.h: No such file or directory

System details:

> NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

esmini commit:

> c07a249

full process:

<pre>(base) <font color="#8AE234"><b>l@deepl</b></font>:<font color="#729FCF"><b>~/esmini</b></font>$ mkdir build
(base) <font color="#8AE234"><b>l@deepl</b></font>:<font color="#729FCF"><b>~/esmini</b></font>$ cd build
(base) <font color="#8AE234"><b>l@deepl</b></font>:<font color="#729FCF"><b>~/esmini/build</b></font>$ cmake ..
-- CMake version: 3.15.2
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- downloading osg.7z ...
-- extracting osg.7z ... 
-- downloading osi.7z ...
-- extracting osi.7z ... 
-- downloading sumo.7z ...
-- extracting sumo.7z ... 
-- downloading googletest.7z ...
-- extracting googletest.7z ... 
-- downloading models.7z ...
-- extracting models.7z ... 
Submodule &apos;test/OSC-ALKS-scenarios&apos; (https://github.com/arauschert/OSC-ALKS-scenarios.git) registered for path &apos;../test/OSC-ALKS-scenarios&apos;
Cloning into &apos;/home/l/esmini/test/OSC-ALKS-scenarios&apos;...
Submodule path &apos;../test/OSC-ALKS-scenarios&apos;: checked out &apos;0ce2c9e23131dc90266fc0298060143f06040b88&apos;
-- Configuring done
-- Generating done
-- Build files have been written to: /home/l/esmini/build
(base) <font color="#8AE234"><b>l@deepl</b></font>:<font color="#729FCF"><b>~/esmini/build</b></font>$ cmake --build . --config Release --target install[  1%] <font color="#729FCF"><b>Generating ../../../../EnvironmentSimulator/Modules/CommonMini/_version.cpp, ../../../../EnvironmentSimulator/Modules/CommonMini/version.cpp</b></font>
<font color="#AD7FA8"><b>Scanning dependencies of target CommonMini</b></font>
[  2%] <font color="#4E9A06">Building CXX object EnvironmentSimulator/Modules/CommonMini/CMakeFiles/CommonMini.dir/CommonMini.cpp.o</font>
<b>/home/l/esmini/EnvironmentSimulator/Modules/CommonMini/CommonMini.cpp:</b> In constructor ‘<b>CSV_Logger::CSV_Logger(std::__cxx11::string, int, std::__cxx11::string)</b>’:
<b>/home/l/esmini/EnvironmentSimulator/Modules/CommonMini/CommonMini.cpp:722:35:</b> <font color="#AD7FA8"><b>warning: </b></font>format not a string literal and no format arguments [<font color="#AD7FA8"><b>-Wformat-security</b></font>]
  snprintf(message, 1024, egoHeader<font color="#AD7FA8"><b>)</b></font>;
                                   <font color="#AD7FA8"><b>^</b></font>
[  2%] <font color="#729FCF"><b>Generating ../../../../EnvironmentSimulator/Modules/CommonMini/_version.cpp, ../../../../EnvironmentSimulator/Modules/CommonMini/version.cpp</b></font>
[  4%] <font color="#4E9A06">Building CXX object EnvironmentSimulator/Modules/CommonMini/CMakeFiles/CommonMini.dir/version.cpp.o</font>
[  5%] <font color="#4E9A06">Building CXX object EnvironmentSimulator/Modules/CommonMini/CMakeFiles/CommonMini.dir/buildnr.cpp.o</font>
[  7%] <font color="#8AE234"><b>Linking CXX static library libCommonMini.a</b></font>
/usr/bin/ar qc libCommonMini.a  CMakeFiles/CommonMini.dir/CommonMini.cpp.o CMakeFiles/CommonMini.dir/version.cpp.o CMakeFiles/CommonMini.dir/buildnr.cpp.o
/usr/bin/ranlib libCommonMini.a
[  7%] Built target CommonMini
<font color="#AD7FA8"><b>Scanning dependencies of target Controllers</b></font>
[  8%] <font color="#4E9A06">Building CXX object EnvironmentSimulator/Modules/Controllers/CMakeFiles/Controllers.dir/Controller.cpp.o</font>
[ 10%] <font color="#4E9A06">Building CXX object EnvironmentSimulator/Modules/Controllers/CMakeFiles/Controllers.dir/ControllerExternal.cpp.o</font>
[ 11%] <font color="#4E9A06">Building CXX object EnvironmentSimulator/Modules/Controllers/CMakeFiles/Controllers.dir/ControllerFollowGhost.cpp.o</font>
[ 12%] <font color="#4E9A06">Building CXX object EnvironmentSimulator/Modules/Controllers/CMakeFiles/Controllers.dir/ControllerInteractive.cpp.o</font>
[ 14%] <font color="#4E9A06">Building CXX object EnvironmentSimulator/Modules/Controllers/CMakeFiles/Controllers.dir/ControllerSloppyDriver.cpp.o</font>
[ 15%] <font color="#4E9A06">Building CXX object EnvironmentSimulator/Modules/Controllers/CMakeFiles/Controllers.dir/ControllerSumo.cpp.o</font>
[ 17%] <font color="#4E9A06">Building CXX object EnvironmentSimulator/Modules/Controllers/CMakeFiles/Controllers.dir/vehicle.cpp.o</font>
[ 18%] <font color="#8AE234"><b>Linking CXX static library libControllers.a</b></font>
/usr/bin/ar qc libControllers.a  CMakeFiles/Controllers.dir/Controller.cpp.o CMakeFiles/Controllers.dir/ControllerExternal.cpp.o CMakeFiles/Controllers.dir/ControllerFollowGhost.cpp.o CMakeFiles/Controllers.dir/ControllerInteractive.cpp.o CMakeFiles/Controllers.dir/ControllerSloppyDriver.cpp.o CMakeFiles/Controllers.dir/ControllerSumo.cpp.o CMakeFiles/Controllers.dir/vehicle.cpp.o
/usr/bin/ranlib libControllers.a
[ 18%] Built target Controllers
<font color="#AD7FA8"><b>Scanning dependencies of target PlayerBase</b></font>
[ 20%] <font color="#4E9A06">Building CXX object EnvironmentSimulator/Modules/PlayerBase/CMakeFiles/PlayerBase.dir/playerbase.cpp.o</font>
In file included from <b>/home/l/esmini/EnvironmentSimulator/../externals/OpenSceneGraph/linux/include/osg/GLDefines:25:0</b>,
                 from <b>/home/l/esmini/EnvironmentSimulator/../externals/OpenSceneGraph/linux/include/osg/GLExtensions:18</b>,
                 from <b>/home/l/esmini/EnvironmentSimulator/../externals/OpenSceneGraph/linux/include/osg/Shader:25</b>,
                 from <b>/home/l/esmini/EnvironmentSimulator/../externals/OpenSceneGraph/linux/include/osg/StateAttribute:20</b>,
                 from <b>/home/l/esmini/EnvironmentSimulator/../externals/OpenSceneGraph/linux/include/osg/StateSet:18</b>,
                 from <b>/home/l/esmini/EnvironmentSimulator/../externals/OpenSceneGraph/linux/include/osg/Node:19</b>,
                 from <b>/home/l/esmini/EnvironmentSimulator/../externals/OpenSceneGraph/linux/include/osg/Group:17</b>,
                 from <b>/home/l/esmini/EnvironmentSimulator/../externals/OpenSceneGraph/linux/include/osg/PositionAttitudeTransform:17</b>,
                 from <b>/home/l/esmini/EnvironmentSimulator/Modules/ViewerBase/viewer.hpp:16</b>,
                 from <b>/home/l/esmini/EnvironmentSimulator/Modules/PlayerBase/playerbase.hpp:25</b>,
                 from <b>/home/l/esmini/EnvironmentSimulator/Modules/PlayerBase/playerbase.cpp:21</b>:
<b>/home/l/esmini/EnvironmentSimulator/../externals/OpenSceneGraph/linux/build/include/osg/GL:114:10:</b> <font color="#EF2929"><b>fatal error: </b></font>GL/gl.h: No such file or directory
 #include <font color="#EF2929"><b>&lt;GL/gl.h&gt;</b></font>
          <font color="#EF2929"><b>^~~~~~~~~</b></font>
compilation terminated.
EnvironmentSimulator/Modules/PlayerBase/CMakeFiles/PlayerBase.dir/build.make:65: recipe for target &apos;EnvironmentSimulator/Modules/PlayerBase/CMakeFiles/PlayerBase.dir/playerbase.cpp.o&apos; failed
make[2]: *** [EnvironmentSimulator/Modules/PlayerBase/CMakeFiles/PlayerBase.dir/playerbase.cpp.o] Error 1
CMakeFiles/Makefile2:240: recipe for target &apos;EnvironmentSimulator/Modules/PlayerBase/CMakeFiles/PlayerBase.dir/all&apos; failed
make[1]: *** [EnvironmentSimulator/Modules/PlayerBase/CMakeFiles/PlayerBase.dir/all] Error 2
Makefile:129: recipe for target &apos;all&apos; failed
make: *** [all] Error 2
</pre>

**Comment by eknabevcc** [comment]
First step would be to make sure you have the dependencies installed. It's not obvious, but please look here:
https://github.com/esmini/esmini/blob/master/docs/BuildInstructions.md#additional-platform-dependencies

The command is:

`sudo apt install build-essential git pkg-config libgl1-mesa-dev libpthread-stubs0-dev libjpeg-dev libxml2-dev libpng-dev libtiff5-dev libgdal-dev libpoppler-dev libdcmtk-dev libgstreamer1.0-dev libgtk2.0-dev libcairo2-dev libpoppler-glib-dev libxrandr-dev libxinerama-dev curl cmake`

Try that as a first step, and get back if it doesn't help and we take it from there.

**Comment by leanderpeter** [comment]
Thank you very much. I installed the dependencies before but due to the scale of messages i didn't saw an error. Works fine now!
