### ISSUE TITLE
Add Sensor Model

### ISSUE THREAD

**Issue by aktasalifurkan** [esmini/esmini#97]
Is there a way to implement a new sensor model or make changes to the sensor model which we can see in esmini-dyn.exe?

**Comment by eknabevcc** [comment]
What is easy is to create any number of sensors, and configure them with given parameters, e.g. range and field-of-view. However, to change the modelling is not easy. The first think to fix would be to have a true checking if bounding box is within view frustum. Currently only reference point is checked for being inside or not. 

And further modeling, like lens distortion, noise, is simply not handled. esmini currently only providing ideal sensor. 

Sensor modeling can be done outside esmini, based on the ground truth delivered by esmini either through esminiLib API (like shoed in esmini-dyn) or via OSI.

I hope this clarifies somewhat, although maybe not the answer you wished for...

**Comment by aktasalifurkan** [comment]
Yes, that is not the answer I was looking for but I understand what you mean. Thank you anyway, continue to good work :)
