### ISSUE TITLE
dumping out global xyz position of signals like odrplot

### ISSUE THREAD

**Issue by cy-goh** [esmini/esmini#99]
Hi!

I wish to dump out the global xyz coordinates of the traffic lights and traffic signs to a csv file, just as you did with the lanes in the odrplot main.cpp file. 

I took a look at the RoadManager.hpp class and is aware that I probably need the `Position` class, but the class is huge and not sure where to start. Would you kindly point me to the correct methods/steps?

Also, since the Signal objects have the height and width attributes, is it that I should interpret them with the position as the centrepoint, of a box?

Thank you in advance.

**Comment by eknabevcc** [comment]
Depends a little bit. If you're just interested in dumping once, then you could look at code-example [rm-basic](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/code-examples/rm-basic/rm-basic.cpp) using esminiRMlib. I just extended the API and example code to include some more sign attributes, e.g. height and z_offset. 
```
PS C:\eknabe1\GIT\esmini\code-examples-bin> .\rm-basic.exe
nrOfRoads: 1
Road[0] ID: 1
Road[0] nrOf(drivable)Lanes (at s=0): 2
Road[0] sign[0] id 0 name Swe_Round_600_c31-5 x 0.00 y 3.57 z 0.00 heading 0.00 orientation 1 z_offset 1.70 height: 0.61 width 0.00
Road[0] sign[1] id 1 name Swe_Round_600_c31-5 x -0.00 y -3.57 z 0.00 heading 0.00 orientation 1 z_offset 1.70 height: 0.61 width 0.00
Road[0] sign[2] id 2 name Swe_Round_600_c31-3 x 100.00 y 3.57 z 0.00 heading 0.00 orientation 1 z_offset 1.70 height: 0.61 width 0.00
Road[0] sign[3] id 3 name Swe_Round_600_c31-3 x 100.00 y -3.57 z 0.00 heading 0.00 orientation 1 z_offset 1.70 height: 0.61 width 0.00
Road[0] sign[4] id 4 name Swe_Round_600_c31-5 x 100.00 y 3.57 z 0.00 heading 0.00 orientation -1 z_offset 1.70 height: 0.61 width 0.00
Road[0] sign[5] id 5 name Swe_Round_600_c31-5 x 100.00 y -3.57 z 0.00 heading 0.00 orientation -1 z_offset 1.70 height: 0.61 width 0.00
Road[0] sign[6] id 6 name Swe_Round_600_c31-5 x 200.00 y 3.57 z 0.00 heading 0.00 orientation 1 z_offset 1.70 height: 0.61 width 0.00
Road[0] sign[7] id 7 name Swe_Round_600_c31-5 x 200.00 y -3.57 z 0.00 heading 0.00 orientation 1 z_offset 1.70 height: 0.61 width 0.00
Road[0] sign[8] id 8 name Swe_Round_600_c31-3 x 200.00 y 3.57 z 0.00 heading 0.00 orientation -1 z_offset 1.70 height: 0.61 width 0.00
Road[0] sign[9] id 9 name Swe_Round_600_c31-3 x 200.00 y -3.57 z 0.00 heading 0.00 orientation -1 z_offset 1.70 height: 0.61 width 0.00
Road[0] sign[10] id 10 name Swe_Round_600_c31-5 x 500.00 y 3.57 z 0.00 heading 0.00 orientation -1 z_offset 1.70 height: 0.61 width 0.00
Road[0] sign[11] id 11 name Swe_Round_600_c31-5 x 500.00 y -3.57 z 0.00 heading 0.00 orientation -1 z_offset 1.70 height: 0.61 width 0.00

Position manipulation:
current pos: s 9.00 laneId 1 offset 58.47 x 9.00 y 60.00 z 0.00
current pos: s 200.00 laneId 2 offset 0.00 x 200.00 y 3.91 z 0.00
current pos: s 0.00 laneId 2 offset 0.00 x 0.00 y 3.91 z 0.00
```
Maybe this could be a starting point for your case?

Otherwise, if you want/need to go for the internal API (not via shared library), then I think the RoadManager methods relevant for you are:
```
int GetNumberOfSignals();
Signal* GetSignal(int idx);
int GetNumberOfObjects() { return (int)object_.size(); }
RMObject* GetObject(int idx);
```
You find them [here](https://github.com/esmini/esmini/blob/9e71e72db7b9dc670b78ebee802c1182977da90a/EnvironmentSimulator/Modules/RoadManager/RoadManager.hpp#L974)

**Comment by cy-goh** [comment]
Oh great, thank you for the prompt response! 

I didn't realize there is an easier interface to use than RoadManager.hpp directly.

**Comment by eknabevcc** [comment]
Hopefully the simpler interface (esminiRMLib) provides enough of information. It is typically a subset of all internal attributes and features. But of course, it can always be extended to include some additional attributes, like I did this morning adding height for example.
